ALTER TABLE NOTIB.NOT_NOTIFICACIO_ENV RENAME COLUMN NOTIFICA_ERROR_EVENT_ID TO ULTIM_EVENT;
ALTER TABLE NOTIB.NOT_NOTIFICACIO_ENV DROP CONSTRAINT NOT_NOTENV_NOTEVENT_ERROR_FK;
ALTER TABLE NOTIB.NOT_NOTIFICACIO_ENV ADD CONSTRAINT NOT_NOTEVENT_ULTIM_EVENT_FK FOREIGN KEY (ULTIM_EVENT) REFERENCES NOTIB.NOT_NOTIFICACIO_EVENT(ID);
UPDATE NOT_NOTIFICACIO_ENV env SET env.ULTIM_EVENT = (
    SELECT nne2.id FROM NOT_NOTIFICACIO_EVENT nne2 WHERE env.id = nne2.NOTIFICACIO_ENV_ID  AND nne2.DATA =
                                                                                               (SELECT max(nne.DATA) FROM NOT_NOTIFICACIO_EVENT nne WHERE nne.NOTIFICACIO_ENV_ID = env.id AND nne.TIPUS != 8 and nne.TIPUS != 9))
WHERE env.CREATEDDATE > TO_DATE('25/03/2024', 'dd/MM/yyyy');