ALTER TABLE NOTIB.NOT_NOTIFICACIO_ENV RENAME COLUMN NOTIFICA_ERROR_EVENT_ID TO ULTIM_EVENT;
ALTER TABLE NOTIB.NOT_NOTIFICACIO_ENV DROP CONSTRAINT NOT_NOTENV_NOTEVENT_ERROR_FK;
ALTER TABLE NOTIB.NOT_NOTIFICACIO_ENV ADD CONSTRAINT NOT_NOTEVENT_ULTIM_EVENT_FK FOREIGN KEY (ULTIM_EVENT) REFERENCES NOTIB.NOT_NOTIFICACIO_EVENT(ID);

