-- Refactoritzacio callbacks
CREATE TABLE NOT_CALLBACK (
    ID NUMBER(19, 0) NOT NULL,
    USUARI_CODI VARCHAR2(64 CHAR) NOT NULL,
    NOTIFICACIO_ID NUMBER(19, 0) NOT NULL,
    ENVIAMENT_ID NUMBER(19, 0) NOT NULL,
    DATA TIMESTAMP(6),
    ERROR NUMBER(1) DEFAULT 0 NOT NULL,
    ERROR_DESC VARCHAR2(2048 CHAR),
    ESTAT VARCHAR2(10 CHAR),
    INTENTS INTEGER DEFAULT 0 NOT NULL,
    CONSTRAINT NOT_CALLBACK_PK PRIMARY KEY (ID),
    UNIQUE (ENVIAMENT_ID));

ALTER TABLE not_notificacio_env ADD callback_error NUMBER(1) DEFAULT 0 NOT NULL;
ALTER TABLE not_notificacio_env_table ADD callback_error NUMBER(1) DEFAULT 0 NOT NULL;

-- Refactoritzacio events
ALTER TABLE not_notificacio_event ADD intents NUMBER(10, 0) DEFAULT '1' NOT NULL;
ALTER TABLE not_notificacio_event ADD fi_reintents NUMBER(1, 0) DEFAULT '0';
