-- Refactoritzacio callbacks
INSERT INTO NOT_CALLBACK c (c.id, c."DATA", c.ERROR_DESC, c.ESTAT, c.INTENTS, c.NOTIFICACIO_ID, c.ENVIAMENT_ID, c.USUARI_CODI)
    SELECT id, CALLBACK_DATA, CALLBACK_ERROR_DESC, CALLBACK_ESTAT, CALLBACK_INTENTS, NOTIFICACIO_ID, NOTIFICACIO_ENV_ID, CREATEDBY_CODI
    FROM ( select row_number() over (PARTITION BY nne.NOTIFICACIO_ENV_ID  order by CALLBACK_DATA ) as rnum , nne.id, nne.CALLBACK_DATA, nne.CALLBACK_ERROR_DESC, nne.CALLBACK_ESTAT, nne.CALLBACK_INTENTS, nne.NOTIFICACIO_ID, nne.NOTIFICACIO_ENV_ID, e.CREATEDBY_CODI from NOT_NOTIFICACIO_EVENT nne JOIN NOT_NOTIFICACIO_ENV e ON nne.NOTIFICACIO_ENV_ID  = e.id WHERE CALLBACK_ESTAT = 'PENDENT' ) WHERE rnum = 1;

-- Refactoritzacio events
UPDATE NOT_NOTIFICACIO_EVENT SET tipus = '4' WHERE tipus = 3;
UPDATE NOT_NOTIFICACIO_EVENT SET tipus = '4' WHERE tipus = 5;
UPDATE NOT_NOTIFICACIO_EVENT SET tipus = '4' WHERE tipus = 6;
UPDATE NOT_NOTIFICACIO_EVENT SET tipus = '4' WHERE tipus = 12;
UPDATE NOT_NOTIFICACIO_EVENT SET tipus = '3' WHERE tipus = 0;
UPDATE NOT_NOTIFICACIO_EVENT SET tipus = '6' WHERE tipus = 1;
UPDATE NOT_NOTIFICACIO_EVENT SET tipus = '5' WHERE tipus = 2;
UPDATE NOT_NOTIFICACIO_EVENT SET tipus = '0' WHERE tipus = 7;
UPDATE NOT_NOTIFICACIO_EVENT SET tipus = '2' WHERE tipus = 10;
UPDATE NOT_NOTIFICACIO_EVENT SET tipus = '2' WHERE tipus = 11;
UPDATE NOT_NOTIFICACIO_EVENT SET tipus = '2' WHERE tipus = 13;
UPDATE NOT_NOTIFICACIO_EVENT SET tipus = '7' WHERE tipus = 15;
UPDATE NOT_NOTIFICACIO_EVENT SET tipus = '8' WHERE tipus = 9;
UPDATE NOT_NOTIFICACIO_EVENT SET tipus = '8' WHERE tipus = 14;

-- Eliminar organigrama json
DELETE FROM NOT_CONFIG c WHERE c."KEY" like '%unitats.fitxer%';
