package es.caib.notib.logic.intf.dto.accioMassiva;

public enum AccioMassivaTipus {

    MARCAR_PROCESSADES,
    ACTUALITZAR_ESTAT,
    TORNA_ENVIAR_AMB_ERROR,
    ESBORRAR,
    EXPORTAR_FULL_CALCUL,
    DESCARREGA_JUSTIFICANT_ENVIAMENT,
    DESCARREGA_CERTIFICAT_RECEPCIO,
    AMPLIAR_TERMINI,
    TORNA_ACTIVAR_CONSULTES_CANVI_ESTAT,
    TORNA_ACTIVAR_CALLBACK,
    ENVIAR_NOT_MOVIL;
}
