package es.caib.notib.logic.intf.dto.accioMassiva;

public enum AccioMassivaTipus {

    ACTUALITZAR_ESTAT,
    TORNA_ENVIAR_AMB_ERROR,
    ESBORRAR,
    RECUPERAR_ESBORRADES,
    EXPORTAR_FULL_CALCUL,
    DESCARREGA_JUSTIFICANT_ENVIAMENT,
    DESCARREGA_CERTIFICAT_RECEPCIO,
    TORNA_ACTIVAR_CONSULTES_CANVI_ESTAT,
    TORNA_ACTIVAR_CALLBACK,
    REACTIVAR_SIR,
    REACTIVAR_REGISTRE,
    ENVIAR_CALLBACK,
    MARCAR_PROCESSADES,
    AMPLIAR_TERMINI,
    ENVIAR_NOT_MOVIL,
    ANULAR;
}
