ALTER TABLE not_usuari ADD entitat_defecte NUMBER;
ALTER TABLE not_usuari ADD organ_defecte NUMBER;
ALTER TABLE not_usuari ADD procediment_defecte NUMBER;
ALTER TABLE not_avis MODIFY data_final NULL;
ALTER TABLE not_aplicacio ADD horari_laboral_inici DATE DEFAULT TO_DATE('07:00:00', 'HH24:MI:SS') NOT NULL;
ALTER TABLE not_aplicacio ADD horari_laboral_fi DATE DEFAULT TO_DATE('16:00:00', 'HH24:MI:SS') NOT NULL;
ALTER TABLE not_aplicacio ADD max_env_min_laboral INTEGER DEFAULT '4' NOT NULL;
ALTER TABLE not_aplicacio ADD max_env_min_no_laboral INTEGER DEFAULT '8' NOT NULL;
ALTER TABLE not_aplicacio ADD max_env_dia_laboral INTEGER DEFAULT '8000' NOT NULL;
ALTER TABLE not_aplicacio ADD max_env_dia_no_laboral INTEGER DEFAULT '100000' NOT NULL;
ALTER TABLE not_notificacio_table ADD anulable NUMBER(1) DEFAULT '0';
ALTER TABLE not_notificacio_table ADD last_event_fi_reintents NUMBER(1) DEFAULT '0';
ALTER TABLE not_notificacio_env_table ADD anulable NUMBER(1);
ALTER TABLE not_notificacio_env_table ADD organ_nom VARCHAR2(1000 CHAR);
ALTER TABLE not_notificacio_env_table ADD procediment_nom VARCHAR2(1000 CHAR);
ALTER TABLE not_notificacio_env_table ADD referencia_notificacio VARCHAR2(36 CHAR);
ALTER TABLE not_notificacio_env_table ADD not_id NUMBER(19, 0);
ALTER TABLE not_notificacio_env_table ADD ultim_event_data date;
CREATE INDEX NOT_NOT_ENV_TABLE_USR_CODI_IDX ON NOTIB.NOT_NOTIFICACIO_ENV_TABLE (USUARI_CODI);
CREATE INDEX NOT_ENV_TABLE_CREATEDDATE_IDX ON NOTIB.NOT_NOTIFICACIO_ENV_TABLE (CREATEDDATE);
CREATE INDEX NOT_ENV_TABLE_ORGAN_CODI_IDX ON NOTIB.NOT_NOTIFICACIO_ENV_TABLE (NOT_ORGAN_CODI);
CREATE INDEX NOT_NOT_TABLE_PROCORGAN_ID_IDX ON NOTIB.NOT_NOTIFICACIO_TABLE (PROCEDIMENT_ORGAN_ID);
CREATE INDEX NOT_NOT_TABLE_USUARI_CODI_IDX ON NOTIB.NOT_NOTIFICACIO_TABLE (USUARI_CODI);
ALTER TABLE not_notificacio_env ADD anulat NUMBER(1) DEFAULT '0';
ALTER TABLE not_notificacio_env ADD motiu_anulacio VARCHAR2(250 CHAR);
ALTER TABLE not_notificacio_env_table ADD anulat NUMBER(1) DEFAULT '0';
ALTER TABLE not_notificacio_env_table ADD motiu_anulacio VARCHAR2(250 CHAR);

UPDATE not_notificacio_table SET per_actualitzar = 1;
UPDATE not_notificacio_table t SET t.LAST_EVENT_FI_REINTENTS = 1 WHERE t.id IN (SELECT DISTINCT e.NOTIFICACIO_ID  FROM not_notificacio_event e WHERE e.FI_REINTENTS = 1 AND e.tipus IN (0, 3));
INSERT INTO NOT_CONFIG (KEY, VALUE, DESCRIPTION, GROUP_CODE, POSITION, JBOSS_PROPERTY, TYPE_CODE, CONFIGURABLE) VALUES ('es.caib.notib.log.tipus.DIGITALITZACIO', 'false', 'Mostrar logs de la digitalitzacio', 'LOGS', 24, 0, 'BOOL', 0);
INSERT INTO NOT_CONFIG_GROUP (CODE, PARENT_CODE, POSITION, DESCRIPTION) VALUES ('DIGITALITZACIO', 'PLUGINS', 13, 'Plugin de Digitalitzacio');
INSERT INTO NOT_CONFIG (KEY, VALUE, DESCRIPTION, GROUP_CODE, POSITION, JBOSS_PROPERTY, TYPE_CODE, CONFIGURABLE) VALUES ('es.caib.notib.plugin.digitalitzacio.encription.key', null, 'Clau per encriptar i desencriptar els documents digitalitzats.', 'DIGITALITZACIO', 0, 1, 'PASSWORD', 0);
INSERT INTO NOT_CONFIG_TYPE (CODE, VALUE) VALUES ('DIGITALITZACIO_CLASS', 'es.caib.notib.plugin.digitalitzacio.DigitalitzacioPluginDigitalIB');
INSERT INTO NOT_CONFIG (KEY, VALUE, DESCRIPTION, GROUP_CODE, POSITION, JBOSS_PROPERTY, TYPE_CODE, CONFIGURABLE) VALUES ('es.caib.notib.plugin.digitalitzacio.class', 'es.caib.notib.plugin.digitalitzacio.DigitalitzacioPluginDigitalIB','Classe del plugin', 'DIGITALITZACIO', 0, 0, 'DIGITALITZACIO_CLASS', 0);
INSERT INTO NOT_CONFIG (KEY, VALUE, DESCRIPTION, GROUP_CODE, POSITION, JBOSS_PROPERTY, TYPE_CODE, CONFIGURABLE) VALUES ('es.caib.notib.plugin.digitalitzacio.digitalib.username', null,'Nom d’’usuari de DigitalIB','DIGITALITZACIO', 1, 1, 'TEXT', 0);
INSERT INTO NOT_CONFIG (KEY, VALUE, DESCRIPTION, GROUP_CODE, POSITION, JBOSS_PROPERTY, TYPE_CODE, CONFIGURABLE) VALUES ('es.caib.notib.plugin.digitalitzacio.digitalib.password', null,'Contrasenya de DigitalIB','DIGITALITZACIO', 2, 1, 'PASSWORD', 0);
INSERT INTO NOT_CONFIG (KEY, VALUE, DESCRIPTION, GROUP_CODE, POSITION, JBOSS_PROPERTY, TYPE_CODE, CONFIGURABLE) VALUES ('es.caib.notib.plugin.digitalitzacio.digitalib.perfil', null,'Perfil de DigitalIB','DIGITALITZACIO', 3, 0, 'TEXT', 0);
INSERT INTO NOT_CONFIG (KEY, VALUE, DESCRIPTION, GROUP_CODE, POSITION, JBOSS_PROPERTY, TYPE_CODE, CONFIGURABLE) VALUES ('es.caib.notib.plugin.digitalitzacio.endpointName', null,'Nom del endpoint del plugin de digitalitzacio','DIGITALITZACIO', 4, 0, 'TEXT', 0);
INSERT INTO NOT_CONFIG (KEY, VALUE, DESCRIPTION, GROUP_CODE, POSITION, JBOSS_PROPERTY, TYPE_CODE, CONFIGURABLE) VALUES ('es.caib.notib.plugin.digitalitzacio.scanner.mock', 0,'Resultat de l''escanneig fictici','DIGITALITZACIO', 5, 0, 'BOOL', 0);
INSERT INTO NOT_CONFIG (KEY, VALUE, DESCRIPTION, GROUP_CODE, POSITION, JBOSS_PROPERTY, TYPE_CODE, CONFIGURABLE) VALUES ('es.caib.notib.plugin.fitxer.logs.path', null,'Ruta on es guarden el fitxers de logs del servidor','LOGS', 0, 1, 'TEXT', 0);

DELETE FROM not_config WHERE key = 'es.caib.notib.tasques.actives';