package es.caib.notib.client.domini;

public enum CieEstat {

    ENVIADO_CI,
    ENTREGADO_OP,
    CANCELADO,
    ERROR,
    EXTRAVIADA,
    SIN_INFORMACION,
    REHUSADA,
    AUSENTE,
    NOTIFICADA,
    DESCONOCIDO,
    DIRECCION_INCORRECTA,
    FALLECIDO,
    DEVUELTO;
}
// TODO SEGUIR DEMA AMB LES TRADUCCIONS DE L'ESTAT I L'USUARI D'APLICACIO AL DETALL DE L'ENVAIMETN SURT UNDEFINED
