
package es.caib.notib.plugin.cie.nexea;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NotificaWsV2Service", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/", wsdlLocation = "https://nexea.es/serviciosweb_pre/NotificaWsV2Service?wsdl")
public class NotificaWsV2Service
    extends Service
{

    private final static URL NOTIFICAWSV2SERVICE_WSDL_LOCATION;
    private final static WebServiceException NOTIFICAWSV2SERVICE_EXCEPTION;
    private final static QName NOTIFICAWSV2SERVICE_QNAME = new QName("https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/", "NotificaWsV2Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://nexea.es/serviciosweb_pre/NotificaWsV2Service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NOTIFICAWSV2SERVICE_WSDL_LOCATION = url;
        NOTIFICAWSV2SERVICE_EXCEPTION = e;
    }

    public NotificaWsV2Service() {
        super(__getWsdlLocation(), NOTIFICAWSV2SERVICE_QNAME);
    }

    public NotificaWsV2Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), NOTIFICAWSV2SERVICE_QNAME, features);
    }

    public NotificaWsV2Service(URL wsdlLocation) {
        super(wsdlLocation, NOTIFICAWSV2SERVICE_QNAME);
    }

    public NotificaWsV2Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NOTIFICAWSV2SERVICE_QNAME, features);
    }

    public NotificaWsV2Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotificaWsV2Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NotificaWsV2PortType
     */
    @WebEndpoint(name = "NotificaWsV2Port")
    public NotificaWsV2PortType getNotificaWsV2Port() {
        return super.getPort(new QName("https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/", "NotificaWsV2Port"), NotificaWsV2PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotificaWsV2PortType
     */
    @WebEndpoint(name = "NotificaWsV2Port")
    public NotificaWsV2PortType getNotificaWsV2Port(WebServiceFeature... features) {
        return super.getPort(new QName("https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/", "NotificaWsV2Port"), NotificaWsV2PortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NOTIFICAWSV2SERVICE_EXCEPTION!= null) {
            throw NOTIFICAWSV2SERVICE_EXCEPTION;
        }
        return NOTIFICAWSV2SERVICE_WSDL_LOCATION;
    }

}
