
package es.caib.notib.plugin.cie.nexea;


import es.caib.notib.plugin.cie.nexea.altaremesaenvios.AltaRemesaEnvios;
import es.caib.notib.plugin.cie.nexea.altaremesaenvios.ResultadoAltaRemesaEnvios;
import es.caib.notib.plugin.cie.nexea.cancelarenvio.CancelarEnvio;
import es.caib.notib.plugin.cie.nexea.cancelarenvio.ResultadocancelarEnvio;
import es.caib.notib.plugin.cie.nexea.infoenvioligero.InfoEnvioLigero;
import es.caib.notib.plugin.cie.nexea.infoenvioligero.ResultadoinfoEnvioLigero;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NotificaWsV2PortType", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/altaRemesaEnvios")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    es.caib.notib.plugin.cie.nexea.altaremesaenvios.ObjectFactory.class,
    es.caib.notib.plugin.cie.nexea.cancelarenvio.ObjectFactory.class,
    es.caib.notib.plugin.cie.nexea.infoenvioligero.ObjectFactory.class
})
public interface NotificaWsV2PortType {


    /**
     * 
     * @param cancelarEnvio
     * @return
     *     returns https.administracionelectronica_gob_es.notifica.ws.notificaws_v2._1_0.cancelarenvio.ResultadocancelarEnvio
     * @throws Exception
     */
    @WebMethod(action = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/cancelarEnvio")
    @WebResult(name = "resultadocancelarEnvio", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/cancelarEnvio", partName = "parameters")
    public ResultadocancelarEnvio cancelarEnvio(
        @WebParam(name = "cancelarEnvio", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/altaRemesaEnvios", partName = "cancelarEnvio")
        CancelarEnvio cancelarEnvio)
        throws Exception
    ;

    /**
     * 
     * @param altaRemesaEnvios
     * @return
     *     returns https.administracionelectronica_gob_es.notifica.ws.notificaws_v2._1_0.altaremesaenvios.ResultadoAltaRemesaEnvios
     * @throws Exception
     */
    @WebMethod(action = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/altaRemesaEnvios")
    @WebResult(name = "resultadoAltaRemesaEnvios", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/altaRemesaEnvios", partName = "parameters")
    public ResultadoAltaRemesaEnvios altaRemesaEnvios(
        @WebParam(name = "altaRemesaEnvios", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/altaRemesaEnvios", partName = "altaRemesaEnvios")
        AltaRemesaEnvios altaRemesaEnvios)
        throws Exception
    ;

    /**
     * 
     * @param infoEnvioLigero
     * @return
     *     returns https.administracionelectronica_gob_es.notifica.ws.notificaws_v2._1_0.infoenvioligero.ResultadoinfoEnvioLigero
     * @throws Exception
     */
    @WebMethod(action = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/infoEnvioLigero")
    @WebResult(name = "resultadoinfoEnvioLigero", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/infoEnvioLigero", partName = "parameters")
    public ResultadoinfoEnvioLigero infoEnvioLigero(
        @WebParam(name = "infoEnvioLigero", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/altaRemesaEnvios", partName = "infoEnvioLigero")
        InfoEnvioLigero infoEnvioLigero)
        throws Exception
    ;

}
