
package es.caib.notib.ws.notificacio;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Notificacio", targetNamespace = "http://www.caib.es/notib/ws/notificacio")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Notificacio {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "alta", targetNamespace = "http://www.caib.es/notib/ws/notificacio", className = "es.caib.notib.ws.notificacio.Alta")
    @ResponseWrapper(localName = "altaResponse", targetNamespace = "http://www.caib.es/notib/ws/notificacio", className = "es.caib.notib.ws.notificacio.AltaResponse")
    public List<String> alta(
        @WebParam(name = "arg0", targetNamespace = "")
        Notificacio_Type arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns es.caib.notib.ws.notificacio.Notificacio_Type
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consulta", targetNamespace = "http://www.caib.es/notib/ws/notificacio", className = "es.caib.notib.ws.notificacio.Consulta")
    @ResponseWrapper(localName = "consultaResponse", targetNamespace = "http://www.caib.es/notib/ws/notificacio", className = "es.caib.notib.ws.notificacio.ConsultaResponse")
    public Notificacio_Type consulta(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns es.caib.notib.ws.notificacio.NotificacioCertificacio
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaCertificacio", targetNamespace = "http://www.caib.es/notib/ws/notificacio", className = "es.caib.notib.ws.notificacio.ConsultaCertificacio")
    @ResponseWrapper(localName = "consultaCertificacioResponse", targetNamespace = "http://www.caib.es/notib/ws/notificacio", className = "es.caib.notib.ws.notificacio.ConsultaCertificacioResponse")
    public NotificacioCertificacio consultaCertificacio(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns es.caib.notib.ws.notificacio.NotificacioEstat
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaEstat", targetNamespace = "http://www.caib.es/notib/ws/notificacio", className = "es.caib.notib.ws.notificacio.ConsultaEstat")
    @ResponseWrapper(localName = "consultaEstatResponse", targetNamespace = "http://www.caib.es/notib/ws/notificacio", className = "es.caib.notib.ws.notificacio.ConsultaEstatResponse")
    public NotificacioEstat consultaEstat(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
