CREATE TABLE NOT_OFICINA (codi VARCHAR(64) NOT NULL, nom VARCHAR(1024), sir BOOLEAN NOT NULL, actiu BOOLEAN NOT NULL, organ_codi VARCHAR(16), entitat_id BIGINT, CONSTRAINT NOT_OFI_PK PRIMARY KEY (codi));

ALTER TABLE NOT_OFICINA ADD CONSTRAINT NOT_OFI_ORGAN_FK FOREIGN KEY (organ_codi) REFERENCES NOT_ORGAN_GESTOR(CODI);

ALTER TABLE NOT_OFICINA ADD CONSTRAINT NOT_OFI_ENTITAT_FK FOREIGN KEY (entitat_id) REFERENCES NOT_ENTITAT(ID);

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_OFICINA TO WWW_NOTIB;

ALTER TABLE not_notificacio_table ADD titular VARCHAR(1024);

ALTER TABLE not_notificacio_table ADD notifica_ids VARCHAR(1024);

ALTER TABLE not_notificacio_table ADD estat_mask INTEGER;

CREATE INDEX NOT_TABLE_ENTITAT_INDEX ON not_notificacio_table(ENTITAT_ID);
CREATE INDEX NOT_TABLE_ENV_ENTITAT_INDEX ON not_notificacio_env_table(ENTITAT_ID);