-- Update for version (1.0.1 -> 1.0.2)
-- #109
ALTER TABLE ONLY NOT_PERSONA ADD INCAPACITAT BIGSERIAL(1,0);

-- #115
ALTER TABLE ONLY NOT_NOTIFICACIO DROP (
    SEU_EXP_SERDOC, 
    SEU_EXP_UNIORG, 
    SEU_EXP_IDENI, 
    SEU_EXP_TITOL, 
    SEU_REG_OFICINA, 
    SEU_REG_LLIBRE,
    SEU_REG_ORGAN,
    SEU_IDIOMA,
    SEU_AVIS_TITOL,
    SEU_AVIS_TEXT,
    SEU_AVIS_MOBIL,
    SEU_OFICI_TITOL,
    SEU_OFICI_TEXT,
    SEU_PROC_CODI);

ALTER TABLE ONLY NOT_NOTIFICACIO_ENV DROP (
    SEU_REG_NUMERO, 
    SEU_REG_DATA, 
    SEU_DATA_FI, 
    SEU_ESTAT, 
    SEU_ERROR, 
    SEU_ERROR_EVENT_ID,
    SEU_DATA_ESTAT,
    SEU_DATA_NOTINF,
    SEU_DATA_NOTIDP,
    SEU_INTENT_DATA,
    SEU_FITXER_CODI,
    SEU_FITXER_CLAU);
    
-- #130
ALTER TABLE NOT_NOTIFICACIO MODIFY CONCEPTE character varying(50);

-- #131
ALTER TABLE NOT_PERSONA MODIFY NOM character varying(255);
ALTER TABLE NOT_PERSONA MODIFY LLINATGE1 character varying(40);
ALTER TABLE NOT_PERSONA MODIFY LLINATGE2 character varying(40);
ALTER TABLE NOT_PERSONA MODIFY EMAIL character varying(255);

ALTER TABLE NOT_NOTIFICACIO MODIFY DESCRIPCIO character varying(1000);

ALTER TABLE NOT_NOTIFICACIO_ENV MODIFY DOM_VIA_NOM character varying(50);
ALTER TABLE NOT_NOTIFICACIO_ENV MODIFY DOM_NUM_NUM character varying(5);
ALTER TABLE NOT_NOTIFICACIO_ENV MODIFY DOM_LINEA1 character varying(50);
ALTER TABLE NOT_NOTIFICACIO_ENV MODIFY DOM_LINEA2 character varying(50);