-- Update for version (0.1 -> 1.0)
-- #54
CREATE TABLE NOT_PROCEDIMENT 
(
  ID						BIGSERIAL(19)	    	NOT NULL,
  CODI          			character varying(64)		NOT NULL,
  NOM						character varying(100),
  CODISIA					character varying(64),
  ENTITAT					BIGSERIAL(19),
  PAGADORPOSTAL				BIGSERIAL(19),
  PAGADORCIE				BIGSERIAL(19),
  AGRUPAR					BIGSERIAL(1) 			NOT NULL,
  DATA_PROGRAMADA			timestamp without time zone,
  RETARD					BIGSERIAL(19),
  CREATEDBY_CODI       		character varying(64),
  CREATEDDATE          		timestamp without time zone,
  LASTMODIFIEDBY_CODI  		character varying(64),
  LASTMODIFIEDDATE     		timestamp without time zone
);

CREATE TABLE NOT_GRUP 
(
  ID						BIGSERIAL(19)	    	NOT NULL,
  CODI						character varying(64)		NOT NULL,
  NOM						character varying(100),
  CREATEDBY_CODI       		character varying(64),
  CREATEDDATE          		timestamp without time zone,
  LASTMODIFIEDBY_CODI  		character varying(64),
  LASTMODIFIEDDATE     		timestamp without time zone,
  ENTITAT				BIGSERIAL(19)
);

CREATE TABLE NOT_PAGADOR_POSTAL
(
  ID						BIGSERIAL(19)	    	NOT NULL,
  DIR3_CODI            		character varying(9)  		NOT NULL,
  CONTRACTE_NUM		       	character varying(20),
  CONTRACTE_DATA_VIG      	DATE,
  FACTURACIO_CODI_CLIENT   	character varying(20),
  CREATEDBY_CODI       		character varying(64),
  CREATEDDATE          		timestamp without time zone,
  LASTMODIFIEDBY_CODI  		character varying(64),
  LASTMODIFIEDDATE     		timestamp without time zone
);

CREATE TABLE NOT_PAGADOR_CIE
(
  ID						BIGSERIAL(19)	    	NOT NULL,
  DIR3_CODI            		character varying(9)  		NOT NULL,
  CONTRACTE_DATA_VIG      	DATE,
  CREATEDBY_CODI       		character varying(64),
  CREATEDDATE          		timestamp without time zone,
  LASTMODIFIEDBY_CODI  		character varying(64),
  LASTMODIFIEDDATE     		timestamp without time zone
);

CREATE TABLE NOT_PRO_GRUP 
(
  ID						BIGSERIAL(19)	    	NOT NULL,
  GRUP						BIGSERIAL(19),			
  PROCEDIMENT				BIGSERIAL(19),
  CREATEDBY_CODI       		character varying(64),
  CREATEDDATE          		timestamp without time zone,
  LASTMODIFIEDBY_CODI  		character varying(64),
  LASTMODIFIEDDATE     		timestamp without time zone
);

ALTER TABLE ONLY NOT_PROCEDIMENT ADD (
  CONSTRAINT NOT_PROCEDIMENT_PK PRIMARY KEY (ID));
  
ALTER TABLE ONLY NOT_GRUP ADD (
  CONSTRAINT NOT_GRUP_PK PRIMARY KEY (ID));
  
ALTER TABLE ONLY NOT_PAGADOR_POSTAL ADD (
  CONSTRAINT NOT_PAGADOR_POSTAL_PK PRIMARY KEY (ID));
  
ALTER TABLE ONLY NOT_PAGADOR_CIE ADD (
  CONSTRAINT NOT_PAGADOR_CIE_PK PRIMARY KEY (ID));
  
ALTER TABLE ONLY NOT_PROCEDIMENT ADD (
  CONSTRAINT NOT_PAGADOR_POSTAL_FK FOREIGN KEY (PAGADORPOSTAL)
    REFERENCES NOT_PAGADOR_POSTAL (ID));
  
ALTER TABLE ONLY NOT_PROCEDIMENT ADD (
  CONSTRAINT NOT_PAGADOR_CIE_FK FOREIGN KEY (PAGADORCIE)
    REFERENCES NOT_PAGADOR_CIE (ID));
    
ALTER TABLE ONLY NOT_PROCEDIMENT ADD (
  CONSTRAINT NOT_ENTITAT_FK FOREIGN KEY (ENTITAT)
    REFERENCES NOT_ENTITAT (ID));

-- #55

ALTER TABLE ONLY NOT_NOTIFICACIO ADD REGISTRE_ORGAN character varying(10);
ALTER TABLE ONLY NOT_NOTIFICACIO ADD REGISTRE_OFICINA character varying(10);
ALTER TABLE ONLY NOT_NOTIFICACIO ADD REGISTRE_LLIBRE character varying(10);

-- #59
CREATE TABLE NOT_COLUMNES
(
  ID                   		BIGSERIAL(19),
  CREATED_DATE      		BIGSERIAL(1),
  DATA_PROGRAMADA           BIGSERIAL(1),
  NOT_IDENTIFICADOR         BIGSERIAL(1),
  PRO_CODI             		BIGSERIAL(1),
  GRUP_CODI           		BIGSERIAL(1),
  DIR3_CODI					BIGSERIAL(1),
  USUARI					BIGSERIAL(1),
  ENVIAMENT_TIPUS          	BIGSERIAL(1),
  CONCEPTE       			BIGSERIAL(1),
  DESCRIPCIO   				BIGSERIAL(1),
  TITULAR_NIF      			BIGSERIAL(1),
  TITULAR_NOM_LLINATGE      BIGSERIAL(1),
  TITULAR_EMAIL      		BIGSERIAL(1),
  DESTINATARIS        	    BIGSERIAL(1),
  LLIBRE_REGISTRE        	BIGSERIAL(1),
  NUMERO_REGISTRE           BIGSERIAL(1),
  DATA_REGISTRE        		BIGSERIAL(1),
  DATA_CADUCITAT         	BIGSERIAL(1),
  CODI_NOTIB_ENV            BIGSERIAL(1),
  NUM_CERTIFICACIO      	BIGSERIAL(1),
  CSV_UUID          		BIGSERIAL(1),
  ESTAT                		BIGSERIAL(1),
  ENTITAT_ID				BIGSERIAL(19),
  USUARI_CODI				character varying(64),
  CREATEDBY_CODI       		character varying(64),
  CREATEDDATE          		timestamp without time zone,
  LASTMODIFIEDBY_CODI  		character varying(64),
  LASTMODIFIEDDATE     		timestamp without time zone
);


ALTER TABLE ONLY NOT_COLUMNES ADD (
  CONSTRAINT NOT_COLUMNES_ENTITAT_FK FOREIGN KEY (ENTITAT_ID)
    REFERENCES NOT_ENTITAT (ID));

ALTER TABLE ONLY NOT_COLUMNES ADD (
  CONSTRAINT NOT_COLUMNES_USUARI_FK FOREIGN KEY (USUARI_CODI)
    REFERENCES NOT_USUARI (CODI));

-- #67
ALTER TABLE ONLY NOT_PROCEDIMENT ADD LLIBRE character varying(64);
ALTER TABLE ONLY NOT_PROCEDIMENT ADD OFICINA character varying(64);
ALTER TABLE ONLY NOT_PROCEDIMENT ADD TIPUSASSUMPTE BIGSERIAL(1);

CREATE TABLE NOT_PERSONA
(
  ID					BIGSERIAL(19)			NOT NULL,
  EMAIL					character varying(100),
  LLINATGE1				character varying(100)		NOT NULL,
  LLINATGE2				character varying(100),
  NIF					character varying(9)			NOT NULL,
  NOM					character varying(100),
  TELEFON				character varying(16),
  RAO_SOCIAL			character varying(100),
  COD_ENTITAT_DESTI		character varying(9),
  NOTIFICACIO_ENV_ID	BIGSERIAL(19),
  CREATEDBY_CODI       	character varying(64),
  CREATEDDATE          	timestamp without time zone,
  LASTMODIFIEDBY_CODI  	character varying(64),
  LASTMODIFIEDDATE     	timestamp without time zone
);

ALTER TABLE ONLY NOT_PERSONA ADD (
  CONSTRAINT NOT_PERSONA_NOT_FK FOREIGN KEY (NOTIFICACIO_ENV_ID)
    REFERENCES NOT_NOTIFICACIO_ENV(ID));

CREATE TABLE NOT_DOCUMENT
(
  ID					BIGSERIAL(19)			NOT NULL,
  ARXIU_ID				character varying(64),
  ARXIU_GEST_DOC_ID		character varying(64),
  ARXIU_NOM				character varying(100),
  HASH					character varying(2048),
  URL					character varying(256),
  TELEFON				character varying(16),
  METADADES				character varying(256),
  NORMALITZAT			BOOLEAN,
  GENERAR_CSV			BOOLEAN,
  UUID					character varying(64),
  CSV					character varying(256),
  CREATEDBY_CODI       	character varying(64),
  CREATEDDATE          	timestamp without time zone,
  LASTMODIFIEDBY_CODI  	character varying(64),
  LASTMODIFIEDDATE     	timestamp without time zone
);

ALTER TABLE ONLY NOT_NOTIFICACIO ADD REGISTRE_EXTRACTE character varying(64);
ALTER TABLE ONLY NOT_NOTIFICACIO ADD REGISTRE_DOC_FISICA character varying(64);
ALTER TABLE ONLY NOT_NOTIFICACIO ADD REGISTRE_IDIOMA character varying(2);
ALTER TABLE ONLY NOT_NOTIFICACIO ADD REGISTRE_TIPUS_ASSUMPTE BIGSERIAL(1);
ALTER TABLE ONLY NOT_NOTIFICACIO ADD REGISTRE_NUM_EXPEDIENT character varying(20);
ALTER TABLE ONLY NOT_NOTIFICACIO ADD REGISTRE_REF_EXTERNA character varying(64);
ALTER TABLE ONLY NOT_NOTIFICACIO ADD REGISTRE_CODI_ASSUMPTE character varying(20);
ALTER TABLE ONLY NOT_NOTIFICACIO ADD REGISTRE_OBSERVACIONS character varying(256);
ALTER TABLE ONLY NOT_NOTIFICACIO ADD GRUP_CODI character varying(64);
ALTER TABLE ONLY NOT_NOTIFICACIO MODIFY DOC_ARXIU_NOM character varying(256);
ALTER TABLE ONLY NOT_NOTIFICACIO ADD DOCUMENT_ID	BIGSERIAL(19) NOT NULL;
ALTER TABLE ONLY NOT_NOTIFICACIO ADD USUARI_CODI	character varying(64);
ALTER TABLE ONLY NOT_NOTIFICACIO ADD PROCEDIMENT_ID BIGSERIAL(19);
ALTER TABLE ONLY NOT_NOTIFICACIO ADD PAGADOR_POSTAL_ID BIGSERIAL(19);
ALTER TABLE ONLY NOT_NOTIFICACIO ADD PAGADOR_CIE_ID BIGSERIAL(19);
ALTER TABLE ONLY NOT_NOTIFICACIO ADD TITULAR_ID BIGSERIAL(19);
ALTER TABLE ONLY NOT_NOTIFICACIO ADD PROC_CODI_NOTIB	character varying(6);
ALTER TABLE ONLY NOT_NOTIFICACIO MODIFY PROC_CODI_SIA character varying(6);
ALTER TABLE ONLY NOT_NOTIFICACIO ADD CSV_UUID character varying(64);

ALTER TABLE ONLY NOT_NOTIFICACIO_ENV ADD TITULAR_ID BIGSERIAL(19);

ALTER TABLE ONLY NOT_DOCUMENT ADD (
  CONSTRAINT NOT_DOCUMENT_PK PRIMARY KEY (ID));
  
ALTER TABLE ONLY NOT_PERSONA ADD (
  CONSTRAINT NOT_PERSONA_PK PRIMARY KEY (ID));

ALTER TABLE ONLY NOT_NOTIFICACIO_ENV ADD (
  CONSTRAINT NOT_PERSONA_NOTIFICACIO_ENV_FK FOREIGN KEY (TITULAR_ID)
    REFERENCES NOT_PERSONA (ID));

ALTER TABLE ONLY NOT_NOTIFICACIO ADD (
  CONSTRAINT NOT_DOCUMENT_NOTIFICACIO_FK FOREIGN KEY (DOCUMENT_ID)
    REFERENCES NOT_DOCUMENT (ID));
    
ALTER TABLE ONLY NOT_NOTIFICACIO ADD (
  CONSTRAINT NOT_PROCEDIMENT_NOT_FK FOREIGN KEY (PROCEDIMENT_ID)
    REFERENCES NOT_PROCEDIMENT (ID));    
    
ALTER TABLE ONLY NOT_NOTIFICACIO ADD (
  CONSTRAINT NOT_PAGADOR_POSTAL_NOT_FK FOREIGN KEY (PAGADOR_POSTAL_ID)
    REFERENCES NOT_PAGADOR_POSTAL (ID));
    
ALTER TABLE ONLY NOT_NOTIFICACIO ADD (
  CONSTRAINT NOT_PAGADOR_CIE_NOTIFICACIO_FK FOREIGN KEY (PAGADOR_CIE_ID)
    REFERENCES NOT_PAGADOR_CIE (ID));
      
ALTER TABLE ONLY NOT_PRO_GRUP ADD (
  CONSTRAINT NOT_GRUP_PRO_FK FOREIGN KEY (GRUP)
      REFERENCES NOT_GRUP (ID),
  CONSTRAINT NOT_PRO_GRUP_FK FOREIGN KEY (PROCEDIMENT)
      REFERENCES NOT_PROCEDIMENT (ID));

CREATE INDEX NOT_PAGADOR_POSTAL_FK_I ON NOT_PROCEDIMENT(PAGADORPOSTAL);
CREATE INDEX NOT_PAGADOR_CIE_FK_I ON NOT_PROCEDIMENT(PAGADORCIE);
CREATE INDEX NOT_ENTITAT_FK_I ON NOT_PROCEDIMENT(entitat);

ALTER TABLE ONLY NOT_NOTIFICACIO DROP COLUMN DOC_ARXIU_NOM;
ALTER TABLE ONLY NOT_NOTIFICACIO DROP COLUMN DOC_ARXIU_ID;
ALTER TABLE ONLY NOT_NOTIFICACIO DROP COLUMN DOC_GEN_CSV;
ALTER TABLE ONLY NOT_NOTIFICACIO DROP COLUMN DOC_HASH;
ALTER TABLE ONLY NOT_NOTIFICACIO DROP COLUMN DOC_NORMALITZAT;
ALTER TABLE ONLY NOT_NOTIFICACIO DROP COLUMN PROC_CODI_SIA;
ALTER TABLE ONLY NOT_NOTIFICACIO ADD PROC_CODI_SIA VARCHAR(6);
ALTER TABLE ONLY NOT_NOTIFICACIO DROP COLUMN SEU_EXP_UNIORG;
ALTER TABLE ONLY NOT_NOTIFICACIO ADD SEU_EXP_UNIORG VARCHAR(10);
ALTER TABLE ONLY NOT_NOTIFICACIO DROP COLUMN SEU_EXP_IDENI;
ALTER TABLE ONLY NOT_NOTIFICACIO ADD SEU_EXP_IDENI VARCHAR(52);
ALTER TABLE ONLY NOT_NOTIFICACIO DROP COLUMN SEU_EXP_TITOL;
ALTER TABLE ONLY NOT_NOTIFICACIO ADD SEU_EXP_TITOL VARCHAR(256);
ALTER TABLE ONLY NOT_NOTIFICACIO DROP COLUMN SEU_EXP_TITOL;
ALTER TABLE ONLY NOT_NOTIFICACIO ADD SEU_EXP_TITOL VARCHAR(256);
ALTER TABLE ONLY NOT_NOTIFICACIO DROP COLUMN SEU_REG_OFICINA;
ALTER TABLE ONLY NOT_NOTIFICACIO ADD SEU_REG_OFICINA VARCHAR(256);
ALTER TABLE ONLY NOT_NOTIFICACIO DROP COLUMN SEU_REG_LLIBRE;
ALTER TABLE ONLY NOT_NOTIFICACIO ADD SEU_REG_LLIBRE VARCHAR(256);
ALTER TABLE ONLY NOT_NOTIFICACIO DROP COLUMN SEU_IDIOMA;
ALTER TABLE ONLY NOT_NOTIFICACIO ADD SEU_IDIOMA VARCHAR(256);
ALTER TABLE ONLY NOT_NOTIFICACIO DROP COLUMN SEU_AVIS_TITOL;
ALTER TABLE ONLY NOT_NOTIFICACIO ADD SEU_AVIS_TITOL VARCHAR(256);
ALTER TABLE ONLY NOT_NOTIFICACIO DROP COLUMN SEU_AVIS_TEXT;
ALTER TABLE ONLY NOT_NOTIFICACIO ADD SEU_AVIS_TEXT VARCHAR(256);
ALTER TABLE ONLY NOT_NOTIFICACIO DROP COLUMN SEU_OFICI_TITOL;
ALTER TABLE ONLY NOT_NOTIFICACIO ADD SEU_OFICI_TITOL VARCHAR(256);
ALTER TABLE ONLY NOT_NOTIFICACIO DROP COLUMN SEU_OFICI_TEXT;
ALTER TABLE ONLY NOT_NOTIFICACIO ADD SEU_OFICI_TEXT VARCHAR(256);
ALTER TABLE ONLY NOT_NOTIFICACIO ADD REGISTRE_NUMERO VARCHAR(256);
ALTER TABLE ONLY NOT_NOTIFICACIO ADD REGISTRE_DATA DATE;

ALTER TABLE ONLY NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_NIF;
ALTER TABLE ONLY NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_NOM;
ALTER TABLE ONLY NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_LLINATGE1;
ALTER TABLE ONLY NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_LLINATGE2;
ALTER TABLE ONLY NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_RAOSOC;
ALTER TABLE ONLY NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_CODDES;
ALTER TABLE ONLY NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_TELEFON;
ALTER TABLE ONLY NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_EMAIL;

ALTER TABLE ONLY NOT_NOTIFICACIO_ENV DROP COLUMN SEU_ESTAT;
ALTER TABLE ONLY NOT_NOTIFICACIO_ENV DROP COLUMN SEU_ERROR;
ALTER TABLE ONLY NOT_NOTIFICACIO_ENV ADD SEU_ESTAT BIGSERIAL(19);
ALTER TABLE ONLY NOT_NOTIFICACIO_ENV ADD SEU_ERROR BIGSERIAL(19);

-- #72
ALTER TABLE ONLY NOT_NOTIFICACIO MODIFY REGISTRE_TIPUS_ASSUMPTE character varying(255);
ALTER TABLE ONLY NOT_NOTIFICACIO MODIFY REGISTRE_CODI_ASSUMPTE character varying(255);
ALTER TABLE ONLY NOT_NOTIFICACIO DROP COLUMN PROC_CODI_SIA;

ALTER TABLE ONLY NOT_PROCEDIMENT MODIFY TIPUSASSUMPTE character varying(255);
ALTER TABLE ONLY NOT_PROCEDIMENT ADD CODIASSUMPTE character varying(255);

ALTER TABLE ONLY NOT_NOTIFICACIO MODIFY DOCUMENT_ID BIGSERIAL(19) NULL;

ALTER TABLE ONLY NOT_DOCUMENT MODIFY METADADES character varying(3000);

ALTER TABLE ONLY NOT_PERSONA ADD INTERESSATTIPUS character varying(30);
ALTER TABLE ONLY NOT_PERSONA MODIFY LLINATGE1 character varying(100) NULL;

ALTER TABLE ONLY NOT_NOTIFICACIO DROP COLUMN REGISTRE_DOC_FISICA;
ALTER TABLE ONLY NOT_NOTIFICACIO ADD REGISTRE_DOC_FISICA BIGSERIAL(2);
ALTER TABLE ONLY NOT_NOTIFICACIO MODIFY REGISTRE_IDIOMA character varying(10);

ALTER TABLE ONLY NOT_NOTIFICACIO MODIFY REGISTRE_NUMERO BIGSERIAL(19);
ALTER TABLE ONLY NOT_NOTIFICACIO ADD REGISTRE_NUMERO_FORMATAT character varying(50);

ALTER TABLE ONLY NOT_NOTIFICACIO_ENV ADD REGISTRE_NUMERO_FORMATAT character varying(50);
ALTER TABLE ONLY NOT_NOTIFICACIO_ENV ADD REGISTRE_DATA DATE;
ALTER TABLE ONLY NOT_NOTIFICACIO_ENV ADD ESTAT_REGISTRE BIGSERIAL(19);

-- #77
ALTER TABLE ONLY NOT_NOTIFICACIO ADD MOTIU character varying(255);
ALTER TABLE ONLY NOT_USUARI ADD REBRE_EMAILS BIGSERIAL(1,0);
UPDATE NOT_USUARI SET REBRE_EMAILS = 1;

-- #83
ALTER TABLE ONLY NOT_ENTITAT ADD API_KEY character varying(64);

-- #84
ALTER TABLE ONLY NOT_PROCEDIMENT ADD ORGAN_GESTOR character varying(19);
ALTER TABLE ONLY NOT_PROCEDIMENT ADD ORGAN_GESTOR_NOM character varying(64);
ALTER TABLE ONLY NOT_PROCEDIMENT ADD TIPUSASSUMPTE_NOM character varying(64);
ALTER TABLE ONLY NOT_PROCEDIMENT ADD CODIASSUMPTE_NOM character varying(64);
ALTER TABLE ONLY NOT_NOTIFICACIO ADD ORGAN_GESTOR character varying(19);



