-- Update for version (1.0 -> 1.0.1)
-- #92
ALTER TABLE ONLY NOT_PROCEDIMENT ADD CADUCITAT BIGSERIAL(19);

-- #94
ALTER TABLE ONLY NOT_ENTITAT ADD LOGO_CAP BLOB;
ALTER TABLE ONLY NOT_ENTITAT ADD LOGO_PEU BLOB;
ALTER TABLE ONLY NOT_ENTITAT ADD COLOR_FONS character varying(32);
ALTER TABLE ONLY NOT_ENTITAT ADD COLOR_LLETRA character varying(32);
ALTER TABLE ONLY NOT_ENTITAT ADD TIPUS_DOC_DEFAULT BIGSERIAL(32);

CREATE TABLE NOT_ENTITAT_TIPUS_DOC
(
  ID            			BIGSERIAL(19),
  ENTITAT_ID				BIGSERIAL(19),
  TIPUS_DOC					BIGSERIAL(32),
  CREATEDBY_CODI       		character varying(64),
  CREATEDDATE          		timestamp without time zone,
  LASTMODIFIEDBY_CODI  		character varying(64),
  LASTMODIFIEDDATE     		timestamp without time zone
);

ALTER TABLE ONLY NOT_ENTITAT_TIPUS_DOC ADD (
  CONSTRAINT NOT_ENTITAT_TIPUS_DOC_PK PRIMARY KEY (ID));

ALTER TABLE ONLY NOT_ENTITAT_TIPUS_DOC ADD (
  CONSTRAINT NOT_ENTITAT_TIPUS_DOC_FK FOREIGN KEY (ENTITAT_ID)
    REFERENCES NOT_ENTITAT (ID));
	
CREATE INDEX NOT_ENTITAT_TIPUS_DOC_FK_I ON NOT_ENTITAT_TIPUS_DOC(ENTITAT_ID);

-- #96
ALTER TABLE ONLY NOT_NOTIFICACIO ADD TIPUS_USUARI BIGSERIAL(1);

-- #98
ALTER TABLE ONLY NOT_APLICACIO DROP COLUMN TIPUS_AUTENTICACIO;

-- #99
CREATE TABLE NOT_FORMATS_FULLA
(
  ID            			BIGSERIAL(19),
  PAGADOR_CIE_ID			BIGSERIAL(19),
  CODI						character varying(64),
  CREATEDBY_CODI       		character varying(64),
  CREATEDDATE          		timestamp without time zone,
  LASTMODIFIEDBY_CODI  		character varying(64),
  LASTMODIFIEDDATE     		timestamp without time zone
);

CREATE TABLE NOT_FORMATS_SOBRE
(
  ID            			BIGSERIAL(19),
  PAGADOR_CIE_ID			BIGSERIAL(19),
  CODI						character varying(64),
  CREATEDBY_CODI       		character varying(64),
  CREATEDDATE          		timestamp without time zone,
  LASTMODIFIEDBY_CODI  		character varying(64),
  LASTMODIFIEDDATE     		timestamp without time zone
);

ALTER TABLE ONLY NOT_FORMATS_FULLA ADD (
  CONSTRAINT NOT_FORMATS_FULLA_PK PRIMARY KEY (ID));

ALTER TABLE ONLY NOT_FORMATS_SOBRE ADD (
  CONSTRAINT NOT_FORMATS_SOBRE_PK PRIMARY KEY (ID));
  
ALTER TABLE ONLY NOT_FORMATS_FULLA ADD (
  CONSTRAINT NOT_FORMATS_FULLA_FK FOREIGN KEY (PAGADOR_CIE_ID)
    REFERENCES NOT_PAGADOR_CIE (ID));
    
ALTER TABLE ONLY NOT_FORMATS_SOBRE ADD (
  CONSTRAINT NOT_FORMATS_SOBRE_FK FOREIGN KEY (PAGADOR_CIE_ID)
    REFERENCES NOT_PAGADOR_CIE (ID));
    
-- #104
ALTER TABLE ONLY NOT_PAGADOR_POSTAL ADD ENTITAT BIGSERIAL(19);
ALTER TABLE ONLY NOT_PAGADOR_CIE ADD ENTITAT BIGSERIAL(19);

UPDATE NOT_PAGADOR_POSTAL SET ENTITAT = 1;
UPDATE NOT_PAGADOR_CIE SET ENTITAT = 1;

ALTER TABLE ONLY NOT_PAGADOR_POSTAL ADD (
  CONSTRAINT NOT_PAGADOR_POSTAL_ENTITAT_FK FOREIGN KEY (ENTITAT)
    REFERENCES NOT_ENTITAT (ID));

ALTER TABLE ONLY NOT_PAGADOR_CIE ADD (
  CONSTRAINT NOT_PAGADOR_CIE_ENTITAT_FK FOREIGN KEY (ENTITAT)
    REFERENCES NOT_ENTITAT (ID));
    
-- #105
ALTER TABLE ONLY NOT_NOTIFICACIO ADD ESTAT_DATE timestamp without time zone;

-- #107
ALTER TABLE ONLY NOT_ENTITAT ADD AMB_ENTREGA_DEH BIGSERIAL(1) DEFAULT 0;