CREATE TABLE NOT_COLUMNES
(
  ID                   		NUMBER(19),
  CREATED_DATE      		NUMBER(1),
  DATA_PROGRAMADA           NUMBER(1),
  NOT_IDENTIFICADOR         NUMBER(1),
  PRO_CODI             		NUMBER(1),
  GRUP_CODI           		NUMBER(1),
  DIR3_CODI					NUMBER(1),
  USUARI					NUMBER(1),
  ENVIAMENT_TIPUS          	NUMBER(1),
  CONCEPTE       			NUMBER(1),
  DESCRIPCIO   				NUMBER(1),
  TITULAR_NIF      			NUMBER(1),
  TITULAR_NOM_LLINATGE      NUMBER(1),
  TITULAR_EMAIL      		NUMBER(1),
  DESTINATARIS        	    NUMBER(1),
  LLIBRE_REGISTRE        	NUMBER(1),
  NUMERO_REGISTRE           NUMBER(1),
  DATA_REGISTRE        		NUMBER(1),
  DATA_CADUCITAT         	NUMBER(1),
  CODI_NOTIB_ENV            NUMBER(1),
  NUM_CERTIFICACIO      	NUMBER(1),
  CSV_UUID          		NUMBER(1),
  ESTAT                		NUMBER(1),
  ENTITAT_ID				NUMBER(19),
  USUARI_CODI				VARCHAR2(64),
  CREATEDBY_CODI       		VARCHAR2(64),
  CREATEDDATE          		TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  		VARCHAR2(64),
  LASTMODIFIEDDATE     		TIMESTAMP(6)
)

ALTER TABLE NOT_COLUMNES ADD (
  CONSTRAINT NOT_COLUMNES_ENTITAT_FK FOREIGN KEY (ENTITAT_ID)
    REFERENCES NOT_ENTITAT (ID));

ALTER TABLE NOT_COLUMNES ADD (
  CONSTRAINT NOT_COLUMNES_USUARI_FK FOREIGN KEY (USUARI_CODI)
    REFERENCES NOT_USUARI (CODI));
    

ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_OFICINA VARCHAR2(64);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_LLIBRE VARCHAR2(64);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_EXTRACTE VARCHAR2(64);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_DOC_FISICA VARCHAR2(64);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_IDIOMA VARCHAR2(2);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_TIPUS_ASSUMPTE NUMBER(1);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_NUM_EXPEDIENT VARCHAR2(20);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_REF_EXTERNA VARCHAR2(64);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_CODI_ASSUMPTE VARCHAR2(20);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_OBSERVACIONS VARCHAR2(256);

ALTER TABLE NOT_NOTIFICACIO ADD GRUP_CODI VARCHAR2(64);
ALTER TABLE NOT_PROCEDIMENT ADD DATA_PROGRAMADA TIMESTAMP(6);
ALTER TABLE NOT_PROCEDIMENT ADD RETARD NUMBER(19);
ALTER TABLE NOT_PROCEDIMENT ADD LLIBRE VARCHAR2(64);
ALTER TABLE NOT_PROCEDIMENT ADD OFICINA VARCHAR2(64);
ALTER TABLE NOT_PROCEDIMENT ADD TIPUSASSUMPTE NUMBER(1);

ALTER TABLE NOT_NOTIFICACIO MODIFY DOC_ARXIU_NOM VARCHAR2(256);






--
--
--************NOTIFICACIO***** 
-- DOCUMENT_ID				NUMBER(19)			NOT NULL,
--  USUARI_CODI          		VARCHAR2(64),
--  PROCEDIMENT_ID			NUMBER(19),
-- PAGADOR_POSTAL_ID			NUMBER(19),
--  PAGADOR_CIE_ID			NUMBER(19),
-- TITULAR_ID				NUMBER(19),
--RETARD_POSTAL				NUMBER(19),
--PAGADOR_POSTAL_ID			NUMBER(19),
--  PAGADOR_CIE_ID			NUMBER(19),
--  PROC_CODI_NOTIB			VARCHAR2(6)			NOT NULL,
--  CSV_UUID					VARCHAR2(64),
--**************NOTIFICACIO*****
--
--**********ENVIAMENT*******
--
--  TITULAR_ID				NUMBER(19),
--  DESTINATARI				NUMBER(19),
--  NOTIFICA_EMI_DIR3DESC 	VARCHAR2(50),
--
--
--**********ENVIAMENT*******
--
--
--
--CREATE TABLE NOT_PERSONA
--(
--  ID					NUMBER(19)			NOT NULL,
--  EMAIL					VARCHAR2(100),
--  LLINATGE1				VARCHAR2(100)		NOT NULL,
--  LLINATGE2				VARCHAR2(100),
--  NIF					VARCHAR2(9)			NOT NULL,
--  NOM					VARCHAR2(100),
--  TELEFON				VARCHAR2(16),
--  RAO_SOCIAL			VARCHAR2(100),
--  COD_ENTITAT_DESTI		VARCHAR2(9),
--  NOTIFICACIO_ENV_ID	NUMBER(19),
--  CREATEDBY_CODI       	VARCHAR2(64),
--  CREATEDDATE          	TIMESTAMP(6),
--  LASTMODIFIEDBY_CODI  	VARCHAR2(64),
--  LASTMODIFIEDDATE     	TIMESTAMP(6)
--);
--
--CREATE TABLE NOT_DOCUMENT
--(
--  ID					NUMBER(19)			NOT NULL,
--  ARXIU_ID				VARCHAR2(64),
--  ARXIU_GEST_DOC_ID		VARCHAR2(64),
--  ARXIU_NOM				VARCHAR2(100)		NOT NULL,
--  CONTINGUT_BASE_64		CLOB,
--  HASH					VARCHAR2(2048),
--  URL					VARCHAR2(256),
--  TELEFON				VARCHAR2(16),
--  METADADES				VARCHAR2(256),
--  NORMALITZAT			NUMBER(1, 0),
--  GENERAR_CSV			NUMBER(1, 0),
--  UUID					VARCHAR2(64),
--  CSV					VARCHAR2(256),
--  CREATEDBY_CODI       	VARCHAR2(64),
--  CREATEDDATE          	TIMESTAMP(6),
--  LASTMODIFIEDBY_CODI  	VARCHAR2(64),
--  LASTMODIFIEDDATE     	TIMESTAMP(6)
--);
--
--    
--
--ALTER TABLE NOT_PROCEDIMENT ADD (
--  CONSTRAINT NOT_PROCEDIMENT_PK PRIMARY KEY (ID));
--  
--ALTER TABLE NOT_GRUP ADD (
--  CONSTRAINT NOT_GRUP_PK PRIMARY KEY (ID));
--  
--ALTER TABLE NOT_PAGADOR_POSTAL ADD (
--  CONSTRAINT NOT_PAGADOR_POSTAL_PK PRIMARY KEY (ID));
--  
--ALTER TABLE NOT_PAGADOR_CIE ADD (
--  CONSTRAINT NOT_PAGADOR_CIE_PK PRIMARY KEY (ID));
--
--ALTER TABLE NOT_DOCUMENT ADD (
--  CONSTRAINT NOT_DOCUMENT_PK PRIMARY KEY (ID));
--  
--ALTER TABLE NOT_PERSONA ADD (
--  CONSTRAINT NOT_PERSONA_PK PRIMARY KEY (ID));
--
--ALTER TABLE NOT_PROCEDIMENT ADD (
--  CONSTRAINT NOT_GRUP_FK FOREIGN KEY (GRUP)
--    REFERENCES NOT_GRUP (ID));
--  
--ALTER TABLE NOT_PROCEDIMENT ADD (
--  CONSTRAINT NOT_PAGADOR_POSTAL_FK FOREIGN KEY (PAGADORPOSTAL)
--    REFERENCES NOT_PAGADOR_POSTAL (ID));
--  
--ALTER TABLE NOT_PROCEDIMENT ADD (
--  CONSTRAINT NOT_PAGADOR_CIE_FK FOREIGN KEY (PAGADORCIE)
--    REFERENCES NOT_PAGADOR_CIE (ID));
--    
--ALTER TABLE NOT_PROCEDIMENT ADD (
--  CONSTRAINT NOT_ENTITAT_FK FOREIGN KEY (ENTITAT)
--    REFERENCES NOT_ENTITAT (ID));
--      
--ALTER TABLE NOT_GRUP ADD (
--  CONSTRAINT NOT_ENTITAT_GRUP_FK FOREIGN KEY (ENTITAT)
--    REFERENCES NOT_ENTITAT (ID));
--    
--ALTER TABLE NOT_COLUMNES ADD (
--  CONSTRAINT NOT_COLUMNES_ENTITAT_FK FOREIGN KEY (ENTITAT_ID)
--    REFERENCES NOT_ENTITAT (ID));
--
--ALTER TABLE NOT_COLUMNES ADD (
--  CONSTRAINT NOT_COLUMNES_USUARI_FK FOREIGN KEY (USUARI_CODI)
--    REFERENCES NOT_USUARI (CODI));
--    
--ALTER TABLE NOT_PERSONA ADD (
--  CONSTRAINT NOT_PERSONA_NOT_FK FOREIGN KEY (NOTIFICACIO_ENV_ID)
--    REFERENCES NOT_NOTIFICACIO_ENV (ID));
--    
--ALTER TABLE NOT_NOTIFICACIO_ENV ADD (
--  CONSTRAINT NOT_PERSONA_NOTIFICACIO_ENV_FK FOREIGN KEY (TITULAR_ID)
--    REFERENCES NOT_PERSONA (ID));
--
--
--ALTER TABLE NOT_NOTIFICACIO ADD (
--  CONSTRAINT NOT_DOCUMENT_NOTIFICACIO_FK FOREIGN KEY (DOCUMENT_ID)
--    REFERENCES NOT_DOCUMENT (ID));
--    
--ALTER TABLE NOT_NOTIFICACIO ADD (
--  CONSTRAINT NOT_PROCEDIMENT_NOT_FK FOREIGN KEY (PROCEDIMENT_ID)
--    REFERENCES NOT_PROCEDIMENT (ID));
--    
--ALTER TABLE NOT_NOTIFICACIO ADD (
--  CONSTRAINT NOT_PAGADOR_POSTAL_NOTIFICACIO_FK FOREIGN KEY (PAGADOR_POSTAL_ID)
--    REFERENCES NOT_PAGADOR_POSTAL (ID));
--    
--ALTER TABLE NOT_NOTIFICACIO ADD (
--  CONSTRAINT NOT_PAGADOR_CIE_NOTIFICACIO_FK FOREIGN KEY (PAGADOR_CIE_ID)
--    REFERENCES NOT_PAGADOR_CIE (ID));
--    
--  
--ALTER TABLE NOT_PRO_GRUP ADD (
--  CONSTRAINT NOT_GRUP_PRO_FK FOREIGN KEY (GRUP)
--      REFERENCES NOT_GRUP (ID),
--  CONSTRAINT NOT_PRO_GRUP_FK FOREIGN KEY (PROCEDIMENT)
--      REFERENCES NOT_PROCEDIMENT (ID));
--
--
--CREATE INDEX NOT_GRUP_FK_I ON NOT_PROCEDIMENT(GRUP);
--CREATE INDEX NOT_PAGADOR_POSTAL_FK_I ON NOT_PROCEDIMENT(PAGADORPOSTAL);
--CREATE INDEX NOT_PAGADOR_CIE_FK_I ON NOT_PROCEDIMENT(PAGADORCIE);
--CREATE INDEX NOT_ENTITAT_FK_I ON NOT_PROCEDIMENT(entitat);
--
--
--
--
--







