-- #415  Canvis a les dades de l’assentament registral 
ALTER TABLE NOT_NOTIFICACIO ADD IDIOMA BIGSERIAL(10);

-- #416  Canvis a les metadades dels documents annexos
ALTER TABLE NOT_NOTIFICACIO ADD DOCUMENT2_ID BIGSERIAL(19);
ALTER TABLE NOT_NOTIFICACIO ADD DOCUMENT3_ID BIGSERIAL(19);
ALTER TABLE NOT_NOTIFICACIO ADD DOCUMENT4_ID BIGSERIAL(19);
ALTER TABLE NOT_NOTIFICACIO ADD DOCUMENT5_ID BIGSERIAL(19);

ALTER TABLE NOT_DOCUMENT ADD ORIGEN character varying(20 );
ALTER TABLE NOT_DOCUMENT ADD VALIDESA character varying(20 );
ALTER TABLE NOT_DOCUMENT ADD TIPUS_DOCUMENTAL character varying(30 );
ALTER TABLE NOT_DOCUMENT ADD FIRMAT BOOLEAN DEFAULT FALSE NOT NULL;

-- #424 Permetre definir l'oficina de registre a nivell d'entitat o a nivell d'òrgan gestor
ALTER TABLE NOT_ORGAN_GESTOR ADD OFICINA character varying(255 );
ALTER TABLE NOT_ORGAN_GESTOR ADD OFICINA_NOM character varying(255 );
ALTER TABLE NOT_ENTITAT ADD OFICINA_ENTITAT BIGSERIAL(1) DEFAULT

-- #448 Millorar el rendiment de la consulta de remeses
CREATE INDEX "NOT_NOTIF_ORGAN_FK_I" ON "NOT_NOTIFICACIO" ("ORGAN_GESTOR");
CREATE INDEX "NOT_NOTIF_PROORGAN_FK_I" ON "NOT_NOTIFICACIO" ("PROCEDIMENT_ORGAN_ID");
CREATE INDEX "NOT_NOTIF_PROCEDIMENT_FK_I" ON "NOT_NOTIFICACIO" ("PROCEDIMENT_ID");
CREATE INDEX "NOT_NOTIF_ESTAT_I" ON "NOT_NOTIFICACIO" ("ESTAT");
CREATE INDEX "NOT_NOTIF_USUARI_I" ON "NOT_NOTIFICACIO" ("USUARI_CODI");
CREATE INDEX "NOT_NOTIF_PROCOD_I" ON "NOT_NOTIFICACIO" ("PROC_CODI_NOTIB");

-- #455 java.lang.NullPointerException en el procés d'actualització de procediments
ALTER TABLE NOT_PROCEDIMENT_AUDIT MODIFY NOM character varying(256 );