-- #416  Canvis a les metadades dels documents annexos
ALTER TABLE NOT_NOTIFICACIO ADD DOCUMENT2_ID BIGSERIAL(19);
ALTER TABLE NOT_NOTIFICACIO ADD DOCUMENT3_ID BIGSERIAL(19);
ALTER TABLE NOT_NOTIFICACIO ADD DOCUMENT4_ID BIGSERIAL(19);
ALTER TABLE NOT_NOTIFICACIO ADD DOCUMENT5_ID BIGSERIAL(19);

ALTER TABLE NOT_DOCUMENT ADD ORIGEN character varying(20 );
ALTER TABLE NOT_DOCUMENT ADD VALIDESA character varying(20 );
ALTER TABLE NOT_DOCUMENT ADD TIPUS_DOCUMENTAL character varying(30 );
ALTER TABLE NOT_DOCUMENT ADD FIRMAT BOOLEAN DEFAULT FALSE NOT NULL;