-- #424
ALTER TABLE NOT_ORGAN_GESTOR ADD OFICINA character varying(256);
ALTER TABLE NOT_ORGAN_GESTOR ADD OFICINA_NOM character varying(256);
ALTER TABLE NOT_ENTITAT ADD OFICINA_ENTITAT BIGSERIAL(1) DEFAULT 1;