-- #448 Millorar el rendiment de la consulta de remeses
CREATE INDEX "NOT_NOTIF_ORGAN_FK_I" ON "NOT_NOTIFICACIO" ("ORGAN_GESTOR");
CREATE INDEX "NOT_NOTIF_PROORGAN_FK_I" ON "NOT_NOTIFICACIO" ("PROCEDIMENT_ORGAN_ID");
CREATE INDEX "NOT_NOTIF_PROCEDIMENT_FK_I" ON "NOT_NOTIFICACIO" ("PROCEDIMENT_ID");
CREATE INDEX "NOT_NOTIF_ESTAT_I" ON "NOT_NOTIFICACIO" ("ESTAT");
CREATE INDEX "NOT_NOTIF_USUARI_I" ON "NOT_NOTIFICACIO" ("USUARI_CODI");
CREATE INDEX "NOT_NOTIF_PROCOD_I" ON "NOT_NOTIFICACIO" ("PROC_CODI_NOTIB");