-- HERENCIA JOINED https://thorben-janssen.com/complete-guide-inheritance-strategies-jpa-hibernate/
CREATE TABLE NOT_HIST_NOTIF
(
	ID						NUMBER(19)	    NOT NULL,
    ENTITAT_ID              NUMBER(19)     NOT NULL,
    ORGAN_ID                NUMBER(19),
    TIPUS                   NUMBER(10)     NOT NULL,
    DATA                    TIMESTAMP(6)   NOT NULL,
    
	PROCEDIMENT_ID			NUMBER(19),
	COMU					NUMBER(1, 0),
	
	GRUP_CODI				NUMBER(19),
	USUARI_CODI				VARCHAR2(64)	NOT NULL,
	ESTAT					NUMBER(10, 0)	NOT NULL,
	   	
	N_NOT_TOTAL				NUMBER(19)	    NOT NULL,
	N_NOT_CORRECTES     	NUMBER(19)	    NOT NULL,
	N_NOT_AMB_ERROR     	NUMBER(19)      NOT NULL,
	N_NOT_ORIGEN_API        NUMBER(19)		NOT NULL,
	N_NOT_ORIGEN_WEB    	NUMBER(19)		NOT NULL,
	N_NOT_DESTI_ADM    	    NUMBER(19)	    NOT NULL,
	N_NOT_DESTI_CIUTADA     NUMBER(19)	    NOT NULL,

	N_COM_TOTAL				NUMBER(19)	    NOT NULL,
	N_COM_CORRECTES     	NUMBER(19)	    NOT NULL,
	N_COM_AMB_ERROR     	NUMBER(19)      NOT NULL,
	N_COM_ORIGEN_API        NUMBER(19)		NOT NULL,
	N_COM_ORIGEN_WEB    	NUMBER(19)		NOT NULL,
	N_COM_DESTI_ADM    	    NUMBER(19)	    NOT NULL,
	N_COM_DESTI_CIUTADA     NUMBER(19)	    NOT NULL,
	
    CREATEDBY_CODI          VARCHAR2(64),
    CREATEDDATE             TIMESTAMP(6),
    LASTMODIFIEDBY_CODI     VARCHAR2(64),
    LASTMODIFIEDDATE        TIMESTAMP(6),
    VERSION                 NUMBER(19)      NOT NULL
);

ALTER TABLE NOT_HIST_NOTIF ADD (
  CONSTRAINT NOT_HIST_NOTIF_OID_PK PRIMARY KEY (ID),
  CONSTRAINT NOT_HIST_NOTIF_PROCEDIMENT_FK FOREIGN KEY (PROCEDIMENT_ID) REFERENCES NOT_PROCEDIMENT (ID),
  CONSTRAINT NOT_HIST_NOTIF_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID),
  CONSTRAINT NOT_HIST_NOTIF_ORGAN_FK FOREIGN KEY (ORGAN_ID) REFERENCES NOT_ORGAN_GESTOR (ID)
);

CREATE TABLE NOT_HIST_ENVIAMENTS
(
	ID						NUMBER(19)	    NOT NULL,
    ENTITAT_ID              NUMBER(19)     NOT NULL,
    ORGAN_ID                NUMBER(19),
    TIPUS                   NUMBER(10)     NOT NULL,
    DATA                    TIMESTAMP(6)   NOT NULL,
    
	PROCEDIMENT_ID			NUMBER(19),
	COMU					NUMBER(1, 0),
	
	GRUP_CODI				NUMBER(19),
	USUARI_CODI				VARCHAR2(64)	NOT NULL,
	ESTAT					NUMBER(10, 0)	NOT NULL,
	ESTAT_NOT				NUMBER(10, 0)	NOT NULL,
	ENV_TIPUS				NUMBER(10, 0)	NOT NULL,
	
	N_TOTAL				NUMBER(19)	    NOT NULL,
	N_CORRECTES     	NUMBER(19)	    NOT NULL,
	N_AMB_ERROR     	NUMBER(19)      NOT NULL,
	N_ORIGEN_API        NUMBER(19)		NOT NULL,
	N_ORIGEN_WEB    	NUMBER(19)		NOT NULL,
	N_DESTI_ADM    	    NUMBER(19)	    NOT NULL,
	N_DESTI_CIUTADA     NUMBER(19)	    NOT NULL,
	
    CREATEDBY_CODI          VARCHAR2(64),
    CREATEDDATE             TIMESTAMP(6),
    LASTMODIFIEDBY_CODI     VARCHAR2(64),
    LASTMODIFIEDDATE        TIMESTAMP(6),
    VERSION                 NUMBER(19)      NOT NULL
);

ALTER TABLE NOT_HIST_ENVIAMENTS ADD (
  CONSTRAINT NOT_HIST_ENVI_OID_PK PRIMARY KEY (ID),
  CONSTRAINT NOT_HIST_ENVI_PROCEDIMENT_FK FOREIGN KEY (PROCEDIMENT_ID) REFERENCES NOT_PROCEDIMENT (ID),
  CONSTRAINT NOT_HIST_ENVI_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID),
  CONSTRAINT NOT_HIST_ENVI_ORGAN_FK FOREIGN KEY (ORGAN_ID) REFERENCES NOT_ORGAN_GESTOR (ID)
);

CREATE TABLE NOT_HIST_PROCEDIMENT
(
	ID						NUMBER(19)	    NOT NULL,
    ENTITAT_ID              NUMBER(19)      NOT NULL,
    ORGAN_ID                NUMBER(19),
    TIPUS                   NUMBER(10)     NOT NULL,
    DATA                    TIMESTAMP(6)   NOT NULL,
	
	PROCEDIMENT_ID			NUMBER(19)	    NOT NULL,
	COMU					NUMBER(1, 0)	NOT NULL,
  	CODI_SIA				VARCHAR2(64)	NOT NULL,
	NOM				     	VARCHAR2(64)	NOT NULL,
	
	N_GRUPS				   	NUMBER(19)	    NOT NULL,
	N_PERM_CONSULTA		   	NUMBER(19)	    NOT NULL,
	N_PERM_NOTIFICACIO	   	NUMBER(19)	    NOT NULL,
	N_PERM_GESTIO		   	NUMBER(19)	    NOT NULL,
	N_PERM_PROCESSAR	   	NUMBER(19)	    NOT NULL,
	
    CREATEDBY_CODI          VARCHAR2(64),
    CREATEDDATE             TIMESTAMP(6),
    LASTMODIFIEDBY_CODI     VARCHAR2(64),
    LASTMODIFIEDDATE        TIMESTAMP(6),
    VERSION                 NUMBER(19)      NOT NULL
);

ALTER TABLE NOT_HIST_PROCEDIMENT ADD (
  CONSTRAINT NOT_HIST_PROC_OID_PK PRIMARY KEY (ID),
  CONSTRAINT NOT_HIST_PROC_PROCEDIMENT_FK FOREIGN KEY (PROCEDIMENT_ID) REFERENCES NOT_PROCEDIMENT (ID),
  CONSTRAINT NOT_HIST_PROC_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID),
  CONSTRAINT NOT_HIST_PROC_ORGAN_FK FOREIGN KEY (ORGAN_ID) REFERENCES NOT_ORGAN_GESTOR (ID)
);

CREATE TABLE NOT_HIST_ORGAN
(
	ID						NUMBER(19)	    NOT NULL,
    ENTITAT_ID              NUMBER(19)      NOT NULL,
    ORGAN_ID                NUMBER(19),
    TIPUS                   NUMBER(10)     NOT NULL,
    DATA                    TIMESTAMP(6)   NOT NULL,
    
  	CODI_DIR3				VARCHAR2(64)	NOT NULL,
	NOM				     	VARCHAR2(64)	NOT NULL,
	
	N_PROCEDIMENTS		   	NUMBER(19)	    NOT NULL,
	N_GRUPS				   	NUMBER(19)	    NOT NULL,
	N_PERM_CONSULTA		   	NUMBER(19)	    NOT NULL,
	N_PERM_NOTIFICACIO	   	NUMBER(19)	    NOT NULL,
	N_PERM_GESTIO		   	NUMBER(19)	    NOT NULL,
	N_PERM_PROCESSAR	   	NUMBER(19)	    NOT NULL,
	N_PERM_ADMINISTRAR	   	NUMBER(19)	    NOT NULL,
	
    CREATEDBY_CODI          VARCHAR2(64),
    CREATEDDATE             TIMESTAMP(6),
    LASTMODIFIEDBY_CODI     VARCHAR2(64),
    LASTMODIFIEDDATE        TIMESTAMP(6),
    VERSION                 NUMBER(19)      NOT NULL
);

ALTER TABLE NOT_HIST_ORGAN ADD (
  CONSTRAINT NOT_HIST_ORGAN_OID_PK PRIMARY KEY (ID),
  CONSTRAINT NOT_HIST_ORGANENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID),
  CONSTRAINT NOT_HIST_ORGAN_ORGAN_FK FOREIGN KEY (ORGAN_ID) REFERENCES NOT_ORGAN_GESTOR (ID)
);

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_HIST_NOTIF TO WWW_NOTIB;
GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_HIST_ENVIAMENTS TO WWW_NOTIB;
GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_HIST_PROCEDIMENT TO WWW_NOTIB;
GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_HIST_ORGAN TO WWW_NOTIB;

