-- #393
-- Relació entre procediment i òrgan (permís ACL sobre aquesta taula)
CREATE TABLE "NOT_PRO_ORGAN" (
    "ID" NUMBER(19,0), 
	"PROCEDIMENT_ID" NUMBER(19,0),
	"ORGANGESTOR_ID" NUMBER(19,0), 
	"CREATEDDATE" TIMESTAMP (6), 
	"LASTMODIFIEDDATE" TIMESTAMP (6), 
	"CREATEDBY_CODI" VARCHAR2(64 CHAR), 
	"LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR)
) ;

-- Primary keys
ALTER TABLE "NOT_PRO_ORGAN" ADD CONSTRAINT "NOT_PRO_ORGAN_PK" PRIMARY KEY (ID);

-- Indexos
CREATE INDEX "NOT_ORGAN_EK" ON "NOT_PRO_ORGAN" ("ORGANGESTOR_ID");
CREATE INDEX "NOT_PROCEDIMENT_EK" ON "NOT_PRO_ORGAN" ("PROCEDIMENT_ID");

-- Foreign keys
ALTER TABLE "NOT_PRO_ORGAN" ADD CONSTRAINT "NOT_PRO_ORGAN_FK" FOREIGN KEY ("ORGANGESTOR_ID") REFERENCES "NOT_ORGAN_GESTOR" ("ID");
ALTER TABLE "NOT_PRO_ORGAN" ADD CONSTRAINT "NOT_ORGAN_PRO_FK" FOREIGN KEY ("PROCEDIMENT_ID") REFERENCES "NOT_PROCEDIMENT" ("ID");

-- Grants
GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_PRO_ORGAN TO WWW_NOTIB;


ALTER TABLE NOT_NOTIFICACIO ADD PROCEDIMENT_ORGAN_ID NUMBER(19,0);
ALTER TABLE NOT_NOTIFICACIO ADD ( CONSTRAINT NOT_PROCORGAN_NOT_FK FOREIGN KEY (PROCEDIMENT_ORGAN_ID) REFERENCES NOT_PRO_ORGAN (ID));