ALTER TABLE NOT_ACL_CLASS ALTER COLUMN id bigint generated by default as identity(start with 100);
ALTER TABLE NOT_ACL_OBJECT_IDENTITY ALTER COLUMN id bigint generated by default as identity(start with 100);
ALTER TABLE NOT_ACL_SID ALTER COLUMN id bigint generated by default as identity(start with 100);
ALTER TABLE NOT_ACL_ENTRY ALTER COLUMN id bigint generated by default as identity(start with 100);