package com.example.statemachine.enums;

public enum EstatsComSIR {

    INICI,
    INICIAT,
    REGISTRAR,
    ERROR_REGISTRE,
    REINTENTAR_REGISTRE,
    ENVIAT_SIR,
    CONSULTA_ESTAT_SIR,
    CONSULTA_ESTAT_SIR_OK,
    CONSULTA_ESTAT_SIR_ERROR,
    ERROR_ACTUALITZAR,
    REINTENTAR_CONSULTA_ESTAT_SIR,
    CHECK_ESTAT_SIR,
    OFICI_ACCEPTAT,
    REBUTJAT,
    OFICI_SIR,
    REENVIAR_CONSULTA_ESTAT_SIR,
    FI;
}
