package com.example.statemachine.enums;

public enum EstatsNot {

    INICI,
    PENDENT,
    REGISTRAR,
    ERROR_REGISTRE,
    REGISTRAT,
    REINTENTAR_REGISTRE,
    ENVIAR,
    ENVIAR_EMAIL,
    CHECK_ENVIAT_EMAIL,
    ENVIAR_NOTIFICA,
    ENVIAT_EMAIL,
    ERROR_ENVIAR_EMAIL,
    CHECK_ENVIAT_NOTIFICA,
    PENDENT_COMPAREIXENCA,
    ERROR_ENVIAR_NOTIFICA,
    REINTENTAR_ENVIAR_NOTIFICA,
    OBTENIR_ESTAT_NOTIFICA,
    CHECK_ESTAT_FINAL,
    ERROR_ACTUALITZAR_ESTAT_NOTIFICA,
    CHECK_ADVISER,
    REINTENTAR_OBTENIR_ESTAT_NOTIFICA,
    LLEGIDA,
    NOTIFICADA,
    REBUTJADA,
    EXPIRADA,
    ABSENT,
    DESCONEGUT,
    ADRECA_INCORRETA,
    DIFUNT,
    EXTRAVIADA,
    SENSE_INFORMACIO,
    ERROR_AGENT,
    FI
    ;
}
