package com.example.statemachine.enums;

public enum EstatsUpdateComSir {

    INICI,
    PENDENT,
    CHECK_REGISTRAT,
    ERROR_REGISTRE,
    PARCIAL_ENVIADA_SIR,
    ENVIADA_SIR,
    CHECK_TOTS_ACTUALITZATS,
    ERROR_SIR,
    CHECK_TOTS_ERROR,
    CHECK_ENV_PARCIALS,
    TOTS_ACT_CHECK_ENV_PARCIAL,
    ENV_PARCIAL_CHECK_ESTAT_ENV,
    TOTS_ENVIATS_CHECK_ESTAT_ENV,
    FINALITZADA_ACCEPTADA,
    FINALITZADA_REBUTJADA,
    FINALITZADA_PARCIALMENT_ACCPETADA,
    FINALITZADA_AMB_ERRORS_ACCEPTADA,
    FINALITZADA_AMB_ERRORS_REBUTJADA,
    FINALITZADA_AMB_ERRORS_PARCIALMENT_ACCPETADA,
    NO_TOTS_ACT_CHECK_ENV_PARCIAL,
    NO_TOTS_ACT_ENV_PARCIAL_CHECK_ESTAT_ENV,
    NO_TOTS_ACT_TOTS_ENVIATS_CHECK_ESTAT_ENV,
    ENVIADA_SIR_AMB_ERRORS_ACCEPTADA,
    ENVIADA_SIR_AMB_ERRORS_REBUTJADA,
    ENVIADA_SIR_AMB_ERRORS_PARCIALMENT_ACCPETADA,
    ENVIADA_SIR_ACCEPTADA,
    ENVIADA_SIR_REBUTJADA,
    ENVIADA_SIR_PARCIALMENT_ACCPETADA,
    FI;

}
