package com.example.statemachine.enums;

public enum EventsUpdateNot {

    ALTA,
    REGISTRAR_ENVIAMENTS,
    CHECK_NIF_DESTINATARIS,
    ENVIAR_TOTS_EMAIL,
    TOTS_EMAIL_CHECK_TOTS_ENVIATS,
    ENVIAR_MIXTE,
    MIXTE_CHECK_TOTS_ENVIATS,
    MIXTA_ACTUALITZAR_ESTAT_NOTIFICA,
    MIXTE_CHECK_TOTS_ACTUALITZATS,
    ENVIAR_NOTIFICA,
    NOTIFICA_CHECK_REINTENTS,
    NOTIFICA_CHECK_ENVIAT,
    ENVIAR_NOTIFICAR_REINTENTAR,
    NOTIFICA_ACTUALITZAR_ESTAT_NOTIFICA,
    FINALITZAR;
}
