//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.01 at 01:39:07 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://nexea.es/ws/adviserwsv2/1.0/sincronizarEnvio", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package es.caib.notib.logic.intf.ws.adviser.nexea.sincronizarenvio;
