
package es.caib.notib.logic.wsdl.seu;


import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SedeWsPortType", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SedeWsPortType {


    /**
     * 
     * @param getEnvios
     * @return
     *     returns es.caib.notib.logic.wsdl.seu.ResultadoGetEnvios
     */
    @WebMethod(action = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/getEnvios")
    @WebResult(partName = "return")
    public ResultadoGetEnvios getEnvios(
        @WebParam(name = "get_envios", partName = "get_envios")
        GetEnvios getEnvios);

    /**
     * 
     * @param getEnvios2
     * @return
     *     returns es.caib.notib.logic.wsdl.seu.ResultadoGetEnvios2
     */
    @WebMethod(action = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/getEnvios2")
    @WebResult(partName = "return")
    public ResultadoGetEnvios2 getEnvios2(
        @WebParam(name = "get_envios2", partName = "get_envios2")
        GetEnvios2 getEnvios2);

    /**
     * 
     * @param infoEnvio
     * @return
     *     returns es.caib.notib.logic.wsdl.seu.ResultadoInfoEnvio
     */
    @WebMethod(action = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/infoEnvio")
    @WebResult(partName = "return")
    public ResultadoInfoEnvio infoEnvio(
        @WebParam(name = "info_envio", partName = "info_envio")
        InfoEnvio infoEnvio);

    /**
     * 
     * @param infoEnvio2
     * @return
     *     returns es.caib.notib.logic.wsdl.seu.ResultadoInfoEnvio2
     */
    @WebMethod(action = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/infoEnvio2")
    @WebResult(partName = "return")
    public ResultadoInfoEnvio2 infoEnvio2(
        @WebParam(name = "info_envio2", partName = "info_envio2")
        InfoEnvio infoEnvio2);

    /**
     * 
     * @param certificacionSede
     * @return
     *     returns es.caib.notib.logic.wsdl.seu.ResultadoCertificacionSede
     */
    @WebMethod(action = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/certificacionSede")
    @WebResult(partName = "return")
    public ResultadoCertificacionSede certificacionSede(
        @WebParam(name = "certificacion_sede", partName = "certificacion_sede")
        CertificacionSede certificacionSede);

    /**
     * 
     * @param comunicacionSede
     * @return
     *     returns es.caib.notib.logic.wsdl.seu.ResultadoComunicacionSede
     */
    @WebMethod(action = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/comunicacionSede")
    @WebResult(partName = "return")
    public ResultadoComunicacionSede comunicacionSede(
        @WebParam(name = "comunicacion_sede", partName = "comunicacion_sede")
        ComunicacionSede comunicacionSede);

    /**
     * 
     * @param getEnviosAgrupados
     * @return
     *     returns es.caib.notib.logic.wsdl.seu.ResultadoGetEnviosAgrupados
     */
    @WebMethod(action = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/getEnviosAgrupados")
    @WebResult(partName = "return")
    public ResultadoGetEnviosAgrupados getEnviosAgrupados(
        @WebParam(name = "get_envios_agrupados", partName = "get_envios_agrupados")
        GetEnviosAgrupados getEnviosAgrupados);

    /**
     * 
     * @param getEnviosAgrupados2
     * @return
     *     returns es.caib.notib.logic.wsdl.seu.ResultadoGetEnviosAgrupados2
     */
    @WebMethod(action = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/getEnviosAgrupados2")
    @WebResult(partName = "return")
    public ResultadoGetEnviosAgrupados2 getEnviosAgrupados2(
        @WebParam(name = "get_envios_agrupados2", partName = "get_envios_agrupados2")
        GetEnviosAgrupados2 getEnviosAgrupados2);

    /**
     * 
     * @param getCertificacion
     * @return
     *     returns es.caib.notib.logic.wsdl.seu.ResultadoGetCertificacion
     */
    @WebMethod(action = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/getCertificacion")
    @WebResult(partName = "return")
    public ResultadoGetCertificacion getCertificacion(
        @WebParam(name = "get_certificacion", partName = "get_certificacion")
        GetCertificacion getCertificacion);

    /**
     * 
     * @return
     *     returns es.caib.notib.logic.wsdl.seu.ResultadoOrganismosActivos
     */
    @WebMethod(action = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/consultaOrganismosActivos")
    @WebResult(partName = "return")
    public ResultadoOrganismosActivos consultaOrganismosActivos();

}
