
package es.caib.notib.logic.wsdl.seu;

import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SedeWsService", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/", wsdlLocation = "file:/home/siona/git/notib/notib-core/src/main/resources/es/caib/notib/core/wsdl/SedeWs.wsdl")
public class SedeWsService
    extends Service
{

    private final static URL SEDEWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SEDEWSSERVICE_EXCEPTION;
    private final static QName SEDEWSSERVICE_QNAME = new QName("https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/", "SedeWsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/siona/git/notib/notib-core/src/main/resources/es/caib/notib/core/wsdl/SedeWs.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SEDEWSSERVICE_WSDL_LOCATION = url;
        SEDEWSSERVICE_EXCEPTION = e;
    }

    public SedeWsService() {
        super(__getWsdlLocation(), SEDEWSSERVICE_QNAME);
    }

    public SedeWsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SEDEWSSERVICE_QNAME, features);
    }

    public SedeWsService(URL wsdlLocation) {
        super(wsdlLocation, SEDEWSSERVICE_QNAME);
    }

    public SedeWsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SEDEWSSERVICE_QNAME, features);
    }

    public SedeWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SedeWsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SedeWsPortType
     */
    @WebEndpoint(name = "SedeWsPort")
    public SedeWsPortType getSedeWsPort() {
        return super.getPort(new QName("https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/", "SedeWsPort"), SedeWsPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SedeWsPortType
     */
    @WebEndpoint(name = "SedeWsPort")
    public SedeWsPortType getSedeWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/", "SedeWsPort"), SedeWsPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SEDEWSSERVICE_EXCEPTION!= null) {
            throw SEDEWSSERVICE_EXCEPTION;
        }
        return SEDEWSSERVICE_WSDL_LOCATION;
    }

}
