<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>es.caib.notib</groupId>
		<artifactId>notib</artifactId>
		<version>2.1.1</version>
	</parent>
	<artifactId>notib-ear</artifactId>
	<packaging>ear</packaging>
	<properties>
		<docker.image.name>${project.parent.artifactId}</docker.image.name>
<!--		<docker.auth.username>${env.DOCKER_USER}</docker.auth.username>-->
<!--		<docker.auth.password>${env.DOCKER_PASSWORD}</docker.auth.password>-->
		<docker.jboss.userhome>/home/jboss</docker.jboss.userhome>
	</properties>
	<dependencies>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>notib-back</artifactId>
			<version>${project.version}</version>
			<type>war</type>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>notib-api-interna</artifactId>
			<version>${project.version}</version>
			<type>war</type>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>notib-api-externa</artifactId>
			<version>${project.version}</version>
			<type>war</type>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>notib-ejb</artifactId>
			<version>${project.version}</version>
			<type>ejb</type>
		</dependency>
		<!-- Dependències dels mòduls war pels skinny wars -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-oauth2-client</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-websocket</artifactId>
		</dependency>
		<dependency>
			<groupId>dev.akkinoc.spring.boot</groupId>
			<artifactId>orika-spring-boot-starter</artifactId>
			<version>${orika.starter.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-jms</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-messaging</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-web</artifactId>
		</dependency>
		<dependency>
			<groupId>opensymphony</groupId>
			<artifactId>sitemesh</artifactId>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>jstl</artifactId>
		</dependency>
		<dependency>
			<groupId>commons-beanutils</groupId>
			<artifactId>commons-beanutils</artifactId>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
		</dependency>
		<dependency>
			<groupId>commons-fileupload</groupId>
			<artifactId>commons-fileupload</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.activemq</groupId>
			<artifactId>activemq-client</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.activemq</groupId>
			<artifactId>activemq-pool</artifactId>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>notib-service-intf</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>notib-backend</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>notib-client-intf</artifactId>
			<version>${project.version}</version>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-ear-plugin</artifactId>
				<version>3.2.0</version>
				<configuration>
					<generateApplicationXml>true</generateApplicationXml>
					<defaultLibBundleDir>/lib</defaultLibBundleDir>
					<includeLibInApplicationXml>false</includeLibInApplicationXml>
					<packagingExcludes>lib/org.apache.tomcat.embed-tomcat*.jar</packagingExcludes>
					<version>6</version>
					<initializeInOrder>true</initializeInOrder>
					<skinnyWars>true</skinnyWars>
					<archive>
						<manifestEntries>
							<Build-Timestamp>${maven.build.timestamp}</Build-Timestamp>
							<Implementation-Vendor>${implementation.vendor}</Implementation-Vendor>
							<Implementation-Version>${project.version}</Implementation-Version>
							<Implementation-SCM-Branch>${scmBranch}</Implementation-SCM-Branch>
							<Implementation-SCM-Revision>${buildNumber}</Implementation-SCM-Revision>
						</manifestEntries>
					</archive>
					<modules>
						<ejbModule>
							<groupId>${project.groupId}</groupId>
							<artifactId>notib-ejb</artifactId>
							<bundleFileName>notib-ejb.jar</bundleFileName>
						</ejbModule>
						<webModule>
							<groupId>${project.groupId}</groupId>
							<artifactId>notib-back</artifactId>
							<contextRoot>/${notib.context}back</contextRoot>
							<bundleFileName>notib-back.war</bundleFileName>
						</webModule>
						<webModule>
							<groupId>${project.groupId}</groupId>
							<artifactId>notib-api-interna</artifactId>
							<contextRoot>/${notib.context}api/interna</contextRoot>
							<bundleFileName>notib-api-interna.war</bundleFileName>
						</webModule>
						<webModule>
							<groupId>${project.groupId}</groupId>
							<artifactId>notib-api-externa</artifactId>
							<contextRoot>/${notib.context}api/externa</contextRoot>
							<bundleFileName>notib-api-externa.war</bundleFileName>
						</webModule>
					</modules>
				</configuration>
			</plugin>
		</plugins>
		<finalName>notib</finalName>
	</build>
	<profiles>
		<!-- Profile per generar la imatge de docker amb la imatge de JBoss EAP 7.2 per openshift -->
		<!-- Per configurar aquesta imatge s'utilitza el fitxer docker/jboss_caib/standalone-openshift amb variables d'entorn -->
		<!-- Abans de copiar aquest fitxer dins la imatge es substitueixen els valors [app] i [App] per tal de configurar: -->
		<!--  - Datasource: -->
		<!--      - jdi-name per defecte: jboss/datasources/notibDS -->
		<!--      - pool-name per defecte: notibDS -->
		<!--  - Correu: -->
		<!--      - Nom del mail session: notib-mail -->
		<!--      - Nom del jndi-name: java:jboss/mail/NotibSession -->
		<!--      - Nom del outbound-socket-binding: notib-smtp -->
		<!--  - Noms dels secure-deployment del subsistema de keycloak: -->
		<!--      - notib-back.war -->
		<!--      - notib-api-interna.war -->
		<!--      - notib-api-externa.war -->
		<profile>
			<id>docker-eap72-caib-openshift</id>
			<properties>
				<docker.image.from>docker.io/goib/jboss-eap72-openshift-base</docker.image.from>
				<app.name>notib</app.name>
				<app.name.cap>Notib</app.name.cap>
			</properties>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-antrun-plugin</artifactId>
						<version>3.1.0</version>
						<executions>
							<execution>
								<id>filter-standalone-openshift</id>
								<phase>generate-resources</phase>
								<goals>
									<goal>run</goal>
								</goals>
								<configuration>
									<target>
										<mkdir dir="${project.build.directory}/generated-resources/docker/jboss"/>
										<copy file="${basedir}/docker/jboss_caib/standalone-openshift.xml" tofile="${project.build.directory}/generated-resources/docker/jboss/standalone-openshift.xml" encoding="${project.build.sourceEncoding}" overwrite="true">
											<filterset begintoken="[" endtoken="]">
												<filter token="app" value="${app.name}"/>
												<filter token="App" value="${app.name.cap}"/>
											</filterset>
										</copy>
									</target>
								</configuration>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>io.fabric8</groupId>
						<artifactId>docker-maven-plugin</artifactId>
						<version>0.42.1</version>
						<configuration>
							<verbose>true</verbose>
							<images>
								<image>
									<name>${docker.image.name}</name>
									<alias>${project.parent.artifactId}</alias>
									<build>
										<from>${docker.image.from}</from>
										<buildOptions>
											<platform>linux/amd64</platform>
										</buildOptions>
										<maintainer>limit@limit.es</maintainer>
										<args>
											<VITE_APP_VERSION>${project.version}</VITE_APP_VERSION>
										</args>
										<ports>
											<port>8080</port>
											<port>8787</port>
										</ports>
										<assemblies>
											<assembly>
												<name>copy_standalone_openshift</name>
												<inline>
														<files>
															<file>
																<source>${project.build.directory}/generated-resources/docker/jboss/standalone-openshift.xml</source>
																<outputDirectory>.</outputDirectory>
															</file>
														</files>
												</inline>
												<targetDir>$JBOSS_HOME/standalone/configuration</targetDir>
												<user>jboss:root</user>
											</assembly>
											<assembly>
												<name>copy_properties</name>
												<inline>
													<fileSets>
														<fileSet>
															<directory>${basedir}/docker/properties</directory>
															<outputDirectory>${project.parent.artifactId}</outputDirectory>
														</fileSet>
													</fileSets>
												</inline>
												<targetDir>${docker.jboss.userhome}/apps</targetDir>
												<user>jboss:root</user>
											</assembly>
											<assembly>
												<name>copy_keystores</name>
												<inline>
													<fileSets>
														<fileSet>
															<directory>${basedir}/docker/keystores</directory>
															<outputDirectory>keystores</outputDirectory>
														</fileSet>
													</fileSets>
												</inline>
												<targetDir>${docker.jboss.userhome}</targetDir>
												<user>jboss:root</user>
											</assembly>
											<assembly>
												<descriptorRef>artifact</descriptorRef>
												<targetDir>$JBOSS_HOME/standalone/deployments</targetDir>
												<user>jboss:root</user>
											</assembly>
										</assemblies>
										<runCmds>
											<run>chmod -R g=u ${docker.jboss.userhome}/apps ${docker.jboss.userhome}/keystores</run>
										</runCmds>
										<tags>
											<tag>latest</tag>
											<tag>${project.version}</tag>
										</tags>
									</build>
								</image>
							</images>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
		<!-- Profile per poder generar la imatge de docker amb la imatge de JBoss EAP 7.2 amb adaptador keycloak v.12 -->
		<!-- Per configurar aquesta imatge s'utilitzen els fitxers dins docker/jboss, i l'script jboss_config.sh -->
		<profile>
			<id>docker-legacy</id>
			<properties>
				<docker.image.from>280421/jboss-eap-caib-7.2</docker.image.from>
			</properties>
			<build>
				<plugins>
					<plugin>
						<groupId>io.fabric8</groupId>
						<artifactId>docker-maven-plugin</artifactId>
						<version>0.42.1</version>
						<configuration>
							<verbose>true</verbose>
							<images>
								<image>
									<name>${docker.image.name}</name>
									<alias>${project.parent.artifactId}</alias>
									<build>
										<from>${docker.image.from}</from>
										<maintainer>limit@limit.es</maintainer>
										<args>
											<VITE_APP_VERSION>${project.version}</VITE_APP_VERSION>
										</args>
										<ports>
											<port>8080</port>
											<port>8787</port>
										</ports>
										<assemblies>
											<assembly>
												<name>copy_jboss_config</name>
												<inline>
													<fileSets>
														<fileSet>
															<directory>${basedir}/docker/jboss</directory>
															<outputDirectory>config</outputDirectory>
														</fileSet>
													</fileSets>
												</inline>
												<targetDir>${docker.jboss.userhome}</targetDir>
												<user>jboss:root</user>
											</assembly>
											<assembly>
												<name>copy_properties</name>
												<inline>
													<fileSets>
														<fileSet>
															<directory>${basedir}/docker/properties</directory>
															<outputDirectory>${project.parent.artifactId}</outputDirectory>
														</fileSet>
													</fileSets>
												</inline>
												<targetDir>${docker.jboss.userhome}/apps</targetDir>
												<user>jboss:root</user>
											</assembly>
											<assembly>
												<name>copy_keystores</name>
												<inline>
													<fileSets>
														<fileSet>
															<directory>${basedir}/docker/keystores</directory>
															<outputDirectory>keystores</outputDirectory>
														</fileSet>
													</fileSets>
												</inline>
												<targetDir>${docker.jboss.userhome}</targetDir>
												<user>jboss:root</user>
											</assembly>
											<assembly>
												<descriptorRef>artifact</descriptorRef>
												<targetDir>$JBOSS_HOME/standalone/deployments</targetDir>
												<user>jboss:root</user>
											</assembly>
										</assemblies>
										<runCmds>
											<run>chmod a+x ${docker.jboss.userhome}/config/jboss_config.sh</run>
											<run>chmod -R g=u ${docker.jboss.userhome}/config ${docker.jboss.userhome}/apps ${docker.jboss.userhome}/keystores</run>
											<run>sed -i '1a ${docker.jboss.userhome}/config/jboss_config.sh' $JBOSS_HOME/bin/standalone.sh</run>
										</runCmds>
										<tags>
											<tag>latest</tag>
											<tag>${project.version}</tag>
										</tags>
									</build>
								</image>
							</images>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
