ALTER TABLE not_usuari ADD rebre_emails_agrupats NUMBER(1) DEFAULT '0';
CREATE TABLE NOT_CORREUS_AGRUPATS (id NUMBER(19, 0) NOT NULL, enviament_id NUMBER(38, 0) NOT NULL, createdby_codi VARCHAR2(64 CHAR), LASTMODIFIEDBY_CODI VARCHAR2(64 CHAR), LASTMODIFIEDDATE TIMESTAMP(6), createddate TIMESTAMP(6), CONSTRAINT NOT_CORREUS_AGRUPATS_PK PRIMARY KEY (id));
ALTER TABLE NOT_CORREUS_AGRUPATS ADD CONSTRAINT CORREUS_AGRUPATS_ENV_ID_FK FOREIGN KEY (enviament_id) REFERENCES NOT_NOTIFICACIO_ENV (id);
ALTER TABLE NOT_PERSONA MODIFY RAO_SOCIAL VARCHAR2(255 CHAR);