-- #99
CREATE TABLE NOT_FORMATS_FULLA
(
  ID            			BIGSERIAL(19),
  PAGADOR_CIE_ID			BIGSERIAL(19),
  CODI						character varying(64),
  CREATEDBY_CODI       		character varying(64),
  CREATEDDATE          		timestamp without time zone,
  LASTMODIFIEDBY_CODI  		character varying(64),
  LASTMODIFIEDDATE     		timestamp without time zone
);

CREATE TABLE NOT_FORMATS_SOBRE
(
  ID            			BIGSERIAL(19),
  PAGADOR_CIE_ID			BIGSERIAL(19),
  CODI						character varying(64),
  CREATEDBY_CODI       		character varying(64),
  CREATEDDATE          		timestamp without time zone,
  LASTMODIFIEDBY_CODI  		character varying(64),
  LASTMODIFIEDDATE     		timestamp without time zone
);

ALTER TABLE ONLY NOT_FORMATS_FULLA ADD (
  CONSTRAINT NOT_FORMATS_FULLA_PK PRIMARY KEY (ID));

ALTER TABLE ONLY NOT_FORMATS_SOBRE ADD (
  CONSTRAINT NOT_FORMATS_SOBRE_PK PRIMARY KEY (ID));
  
ALTER TABLE ONLY NOT_FORMATS_FULLA ADD (
  CONSTRAINT NOT_FORMATS_FULLA_FK FOREIGN KEY (PAGADOR_CIE_ID)
    REFERENCES NOT_PAGADOR_CIE (ID));
    
ALTER TABLE ONLY NOT_FORMATS_SOBRE ADD (
  CONSTRAINT NOT_FORMATS_SOBRE_FK FOREIGN KEY (PAGADOR_CIE_ID)
    REFERENCES NOT_PAGADOR_CIE (ID));