-- # 198
ALTER TABLE NOT_DOCUMENT ADD MEDIA character varying(256);
ALTER TABLE NOT_DOCUMENT ADD MIDA BIGSERIAL(19);

-- #350
ALTER TABLE NOT_USUARI ADD REBRE_EMAILS_CREATS BOOLEAN DEFAULT FALSE NOT NULL;

-- #361
ALTER TABLE NOT_USUARI ADD ULTIM_ROL character varying(40);
ALTER TABLE NOT_USUARI ADD ULTIMA_ENTITAT BIGSERIAL(19);