CREATE TABLE NOT_ACCIO_MASSIVA (ID NUMBER(19, 0) NOT NULL, tipus VARCHAR2(50 CHAR), data_inici TIMESTAMP(6), data_fi TIMESTAMP(6), createdby_codi VARCHAR2(64 CHAR), LASTMODIFIEDBY_CODI VARCHAR2(64 CHAR), LASTMODIFIEDDATE TIMESTAMP(6), createddate TIMESTAMP(6), entitat_id NUMBER(38, 0), error NUMBER(1), num_errors INTEGER, error_descripcio VARCHAR2(1024 CHAR), excepcio_stacktrace VARCHAR2(2048 CHAR), CONSTRAINT NOT_ACC_MASS_PK PRIMARY KEY (ID));

CREATE TABLE NOT_ACCIO_MASSIVA_ELEMENT (ID NUMBER(19, 0) NOT NULL, ACCIO_MASSIVA_ID NUMBER(19, 0), seleccio_tipus VARCHAR2(20 CHAR), element_id NUMBER(19, 0), data_execucio TIMESTAMP(6), error_descripcio VARCHAR2(1024 CHAR), excepcio_stacktrace VARCHAR2(2048 CHAR), CONSTRAINT NOT_ACC_MASS_ELEM_PK PRIMARY KEY (ID));

ALTER TABLE NOT_ACCIO_MASSIVA_ELEMENT ADD CONSTRAINT FK_ACCIOMASSIVA_ELEMENT FOREIGN KEY (ACCIO_MASSIVA_ID) REFERENCES NOT_ACCIO_MASSIVA (ID);
