server:
  servlet:
    context-path: /notibapi/interna

spring:
  mvc:
    view:
      prefix: /WEB_INF/jsp/
      suffix: .jsp

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/liquibase-changelog.xml
    default-schema: public

springdoc:
  packages-to-scan: es.caib.notib.api.interna.controller
  api-docs.path: /api-docs
  swagger-ui:
#    configUrl: /notibapi/interna/api-docs
    path: /rest
    operationsSorter: method
#    url: /notibapi/interna/
    use-root-path: true