ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_OFICINA_NOM VARCHAR2(255 CHAR);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_LLIBRE_NOM VARCHAR2(255 CHAR);

CREATE INDEX NOT_NOTIF_DOCUMENT_ID_INDEX
    ON NOT_NOTIFICACIO(DOCUMENT_ID);

CREATE INDEX NOT_NOTENV_TITULAR_ID_INDEX
    ON NOT_NOTIFICACIO_ENV(TITULAR_ID);

CREATE INDEX NOT_PERSONA_NOTENV_ID_INDEX
    ON NOT_PERSONA(NOTIFICACIO_ENV_ID);

ALTER TABLE NOT_NOTIFICACIO
    ADD IS_ERROR_LAST_EVENT number(1, 0) default 0;

UPDATE
    NOT_NOTIFICACIO
SET IS_ERROR_LAST_EVENT = (
    (SELECT errorev
     FROM (
              SELECT CASE WHEN ev.error = 1 AND ev.TIPUS in (8, 1, 2, 7, 0, 11, 12, 13) THEN 1 ELSE 0 END as errorev
              FROM NOT_NOTIFICACIO_EVENT ev
              WHERE ev.NOTIFICACIO_ID = ID
              ORDER BY ev.DATA DESC
          )
     WHERE ROWNUM = 1
    )
);
