ALTER TABLE NOT_NOTIFICACIO_ENV
    DROP CONSTRAINT NOT_NOTEVE_NOTERR_NOTDEST_FK;


ALTER TABLE NOT_NOTIFICACIO_ENV ADD CONSTRAINT NOT_NOTEVE_NOTERR_NOTDEST_FK FOREIGN KEY (NOTIFICA_ERROR_EVENT_ID)
    REFERENCES NOT_NOTIFICACIO_EVENT (ID) ON DELETE SET NULL ;