ALTER TABLE NOT_PERSONA MODIFY NIF VARCHAR(50);

ALTER TABLE NOT_NOTIFICACIO_ENV_TABLE  MODIFY TITULAR_NIF  VARCHAR(50);

ALTER TABLE not_aplicacio ADD header_csrf NUMBER(1) DEFAULT '1';

ALTER TABLE not_columnes DROP COLUMN llibre_registre;

ALTER TABLE not_columnes DROP COLUMN titular_email;

ALTER TABLE not_columnes DROP COLUMN data_registre;

ALTER TABLE not_columnes DROP COLUMN num_certificacio;

ALTER TABLE not_mon_int ADD notificacio_id NUMBER(19, 0);

ALTER TABLE not_organ_gestor ADD entrega_cie_desactivada NUMBER(1) DEFAULT '0' NOT NULL;

ALTER TABLE not_organ_gestor ADD sobrescriure_cie_organ_emisor NUMBER(1) DEFAULT '0' NOT NULL;

ALTER TABLE NOT_OFICINA DROP CONSTRAINT NOT_OFI_ORGAN_FK;
ALTER TABLE NOT_OFICINA ADD ORGAN_GESTOR NUMBER(19,0);
ALTER TABLE NOT_OFICINA DROP COLUMN ORGAN_CODI;
ALTER TABLE NOT_OFICINA ADD CONSTRAINT NOT_OFI_ORGAN_GESTOR_FK FOREIGN KEY (ORGAN_GESTOR) REFERENCES NOT_ORGAN_GESTOR(ID);

ALTER TABLE NOT_NOTIFICACIO DROP CONSTRAINT NOT_NOT_ORGAN_FK;
ALTER TABLE NOT_NOTIFICACIO ADD ORGAN_GESTOR_AUX NUMBER(19,0);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN ORGAN_GESTOR;
ALTER TABLE NOT_NOTIFICACIO ADD CONSTRAINT NOT_ORGAN_GESTOR_FK FOREIGN KEY (ORGAN_GESTOR_AUX) REFERENCES NOT_ORGAN_GESTOR(ID);
ALTER TABLE NOT_NOTIFICACIO RENAME COLUMN ORGAN_GESTOR_AUX TO ORGAN_GESTOR;

ALTER TABLE NOT_ORGAN_GESTOR DROP CONSTRAINT NOT_ORGAN_GESTOR_UK;
DROP INDEX NOT_ORGAN_GESTOR_UK;
ALTER TABLE NOT_ORGAN_GESTOR ADD CONSTRAINT NOT_ORGAN_ENTITAT_UNIQUE UNIQUE (CODI,ENTITAT) ENABLE;


ALTER TABLE NOT_PROCEDIMENT ADD ORGAN_GESTOR_AUX NUMBER(19,0);
ALTER TABLE NOT_PROCEDIMENT DROP COLUMN ORGAN_GESTOR;
ALTER TABLE NOT_PROCEDIMENT ADD CONSTRAINT NOT_PROCSER_ORGAN_FK FOREIGN KEY (ORGAN_GESTOR_AUX) REFERENCES NOT_ORGAN_GESTOR(ID);
ALTER TABLE NOT_PROCEDIMENT RENAME COLUMN ORGAN_GESTOR_AUX TO ORGAN_GESTOR;
ALTER TABLE NOT_PROCEDIMENT ADD ORGAN_GESTOR_AUX VARCHAR2(64);
ALTER TABLE NOT_PROCEDIMENT RENAME COLUMN ORGAN_GESTOR_AUX TO ORGAN_CODI;
