--------------------------------------------------------
--  DDL for Table NOT_ACL_CLASS
--------------------------------------------------------

  CREATE TABLE "NOT_ACL_CLASS" 
   (	"ID" NUMBER(19,0), 
	"CLASS" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table NOT_ACL_ENTRY
--------------------------------------------------------

  CREATE TABLE "NOT_ACL_ENTRY" 
   (	"ID" NUMBER(19,0), 
	"ACL_OBJECT_IDENTITY" NUMBER(19,0), 
	"ACE_ORDER" NUMBER(19,0), 
	"SID" NUMBER(19,0), 
	"MASK" NUMBER(19,0), 
	"GRANTING" NUMBER(1,0), 
	"AUDIT_SUCCESS" NUMBER(1,0), 
	"AUDIT_FAILURE" NUMBER(1,0)
   ) ;
--------------------------------------------------------
--  DDL for Table NOT_ACL_OBJECT_IDENTITY
--------------------------------------------------------

  CREATE TABLE "NOT_ACL_OBJECT_IDENTITY" 
   (	"ID" NUMBER(19,0), 
	"OBJECT_ID_CLASS" NUMBER(19,0), 
	"OBJECT_ID_IDENTITY" NUMBER(19,0), 
	"PARENT_OBJECT" NUMBER(19,0), 
	"OWNER_SID" NUMBER(19,0), 
	"ENTRIES_INHERITING" NUMBER(1,0)
   ) ;
--------------------------------------------------------
--  DDL for Table NOT_ACL_SID
--------------------------------------------------------

  CREATE TABLE "NOT_ACL_SID" 
   (	"ID" NUMBER(19,0), 
	"PRINCIPAL" NUMBER(1,0), 
	"SID" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table NOT_APLICACIO
--------------------------------------------------------

  CREATE TABLE "NOT_APLICACIO" 
   (	"ID" NUMBER(19,0), 
	"CREATEDDATE" TIMESTAMP (6), 
	"LASTMODIFIEDDATE" TIMESTAMP (6), 
	"CALLBACK_URL" VARCHAR2(256 CHAR), 
	"USUARI_CODI" VARCHAR2(64 CHAR), 
	"CREATEDBY_CODI" VARCHAR2(64 CHAR), 
	"LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR), 
	"ENTITAT_ID" NUMBER(19,0)
   ) ;
--------------------------------------------------------
--  DDL for Table NOT_COLUMNES
--------------------------------------------------------

  CREATE TABLE "NOT_COLUMNES" 
   (	"ID" NUMBER(19,0), 
	"CREATEDDATE" TIMESTAMP (6), 
	"LASTMODIFIEDDATE" TIMESTAMP (6), 
	"CODI_NOTIB_ENV" NUMBER(1,0), 
	"CONCEPTE" NUMBER(1,0), 
	"CSV_UUID" NUMBER(1,0), 
	"DATA_CADUCITAT" NUMBER(1,0), 
	"CREATED_DATE" NUMBER(1,0), 
	"DATA_PROGRAMADA" NUMBER(1,0), 
	"DATA_REGISTRE" NUMBER(1,0), 
	"DESCRIPCIO" NUMBER(1,0), 
	"DESTINATARIS" NUMBER(1,0), 
	"DIR3_CODI" NUMBER(1,0), 
	"ENVIAMENT_TIPUS" NUMBER(1,0), 
	"ESTAT" NUMBER(1,0), 
	"GRUP_CODI" NUMBER(1,0), 
	"LLIBRE_REGISTRE" NUMBER(1,0), 
	"NOT_IDENTIFICADOR" NUMBER(1,0), 
	"NUM_CERTIFICACIO" NUMBER(1,0), 
	"NUMERO_REGISTRE" NUMBER(1,0), 
	"PRO_CODI" NUMBER(1,0), 
	"TITULAR_EMAIL" NUMBER(1,0), 
	"TITULAR_NIF" NUMBER(1,0), 
	"TITULAR_NOM_LLINATGE" NUMBER(1,0), 
	"USUARI" NUMBER(1,0), 
	"CREATEDBY_CODI" VARCHAR2(64 CHAR), 
	"LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR), 
	"ENTITAT_ID" NUMBER(19,0), 
	"USUARI_CODI" VARCHAR2(64 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Table NOT_DOCUMENT
--------------------------------------------------------

  CREATE TABLE "NOT_DOCUMENT" 
   (	"ID" NUMBER(19,0), 
	"CREATEDDATE" TIMESTAMP (6), 
	"LASTMODIFIEDDATE" TIMESTAMP (6), 
	"ARXIU_GEST_DOC_ID" VARCHAR2(64 CHAR), 
	"ARXIU_NOM" VARCHAR2(256 CHAR), 
	"CSV" VARCHAR2(256 CHAR), 
	"HASH" VARCHAR2(256 CHAR), 
	"NORMALITZAT" NUMBER(1,0), 
	"URL" VARCHAR2(256 CHAR), 
	"UUID" VARCHAR2(256 CHAR), 
	"CREATEDBY_CODI" VARCHAR2(64 CHAR), 
	"LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Table NOT_ENTITAT
--------------------------------------------------------

  CREATE TABLE "NOT_ENTITAT" 
   (	"ID" NUMBER(19,0), 
	"CREATEDDATE" TIMESTAMP (6), 
	"LASTMODIFIEDDATE" TIMESTAMP (6), 
	"ACTIVA" NUMBER(1,0), 
	"AMB_ENTREGA_CIE" NUMBER(1,0), 
	"AMB_ENTREGA_DEH" NUMBER(1,0), 
	"API_KEY" VARCHAR2(64 CHAR), 
	"CODI" VARCHAR2(64 CHAR), 
	"COLOR_FONS" VARCHAR2(1024 CHAR), 
	"COLOR_LLETRA" VARCHAR2(1024 CHAR), 
	"DESCRIPCIO" VARCHAR2(1024 CHAR), 
	"DIR3_CODI" VARCHAR2(9 CHAR), 
	"DIR3_CODI_REG" VARCHAR2(9 CHAR), 
	"LOGO_CAP" RAW(1024), 
	"LOGO_PEU" RAW(1024), 
	"NOM" VARCHAR2(256 CHAR), 
	"TIPUS" VARCHAR2(32 CHAR), 
	"TIPUS_DOC_DEFAULT" NUMBER(10,0), 
	"VERSION" NUMBER(19,0), 
	"CREATEDBY_CODI" VARCHAR2(64 CHAR), 
	"LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Table NOT_ENTITAT_TIPUS_DOC
--------------------------------------------------------

  CREATE TABLE "NOT_ENTITAT_TIPUS_DOC" 
   (	"ID" NUMBER(19,0), 
	"CREATEDDATE" TIMESTAMP (6), 
	"LASTMODIFIEDDATE" TIMESTAMP (6), 
	"TIPUS_DOC" NUMBER(10,0), 
	"CREATEDBY_CODI" VARCHAR2(64 CHAR), 
	"LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR), 
	"ENTITAT_ID" NUMBER(19,0)
   ) ;
--------------------------------------------------------
--  DDL for Table NOT_FORMATS_FULLA
--------------------------------------------------------

  CREATE TABLE "NOT_FORMATS_FULLA" 
   (	"ID" NUMBER(19,0), 
	"CREATEDDATE" TIMESTAMP (6), 
	"LASTMODIFIEDDATE" TIMESTAMP (6), 
	"CODI" VARCHAR2(64 CHAR), 
	"CREATEDBY_CODI" VARCHAR2(64 CHAR), 
	"LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR), 
	"PAGADOR_CIE_ID" NUMBER(19,0)
   ) ;
--------------------------------------------------------
--  DDL for Table NOT_FORMATS_SOBRE
--------------------------------------------------------

  CREATE TABLE "NOT_FORMATS_SOBRE" 
   (	"ID" NUMBER(19,0), 
	"CREATEDDATE" TIMESTAMP (6), 
	"LASTMODIFIEDDATE" TIMESTAMP (6), 
	"CODI" VARCHAR2(64 CHAR), 
	"CREATEDBY_CODI" VARCHAR2(64 CHAR), 
	"LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR), 
	"PAGADOR_CIE_ID" NUMBER(19,0)
   ) ;
--------------------------------------------------------
--  DDL for Table NOT_GRUP
--------------------------------------------------------

  CREATE TABLE "NOT_GRUP" 
   (	"ID" NUMBER(19,0), 
	"CREATEDDATE" TIMESTAMP (6), 
	"LASTMODIFIEDDATE" TIMESTAMP (6), 
	"CODI" VARCHAR2(64 CHAR), 
	"NOM" VARCHAR2(100 CHAR), 
	"CREATEDBY_CODI" VARCHAR2(64 CHAR), 
	"LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR), 
	"ENTITAT" NUMBER(19,0)
   ) ;
--------------------------------------------------------
--  DDL for Table NOT_NOTIFICACIO
--------------------------------------------------------

  CREATE TABLE "NOT_NOTIFICACIO" 
   (	"ID" NUMBER(19,0), 
	"CREATEDDATE" TIMESTAMP (6), 
	"LASTMODIFIEDDATE" TIMESTAMP (6), 
	"CADUCITAT" DATE, 
	"COM_TIPUS" NUMBER(10,0), 
	"CONCEPTE" VARCHAR2(255 CHAR), 
	"DESCRIPCIO" VARCHAR2(1000 CHAR), 
	"EMISOR_DIR3CODI" VARCHAR2(9 CHAR), 
	"ENV_DATA_PROG" DATE, 
	"ENV_TIPUS" NUMBER(10,0), 
	"CALLBACK_ERROR" NUMBER(1,0), 
	"ESTAT" NUMBER(10,0), 
	"ESTAT_DATE" TIMESTAMP (6), 
	"GRUP_CODI" VARCHAR2(64 CHAR), 
	"MOTIU" VARCHAR2(255 CHAR), 
	"NOT_ENV_DATA" TIMESTAMP (6), 
	"NOT_ENV_INTENT" NUMBER(10,0), 
	"NOT_ERROR_TIPUS" NUMBER(10,0), 
	"REGISTRE_NUM_EXPEDIENT" VARCHAR2(80 CHAR), 
	"PROC_CODI_NOTIB" VARCHAR2(9 CHAR), 
	"REGISTRE_DATA" DATE, 
	"REGISTRE_ENV_INTENT" NUMBER(10,0), 
	"REGISTRE_NUMERO" NUMBER(10,0), 
	"REGISTRE_NUMERO_FORMATAT" VARCHAR2(200 CHAR), 
	"RETARD_POSTAL" NUMBER(10,0), 
	"TIPUS_USUARI" NUMBER(10,0), 
	"USUARI_CODI" VARCHAR2(64 CHAR), 
	"CREATEDBY_CODI" VARCHAR2(64 CHAR), 
	"LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR), 
	"DOCUMENT_ID" NUMBER(19,0), 
	"ENTITAT_ID" NUMBER(19,0), 
	"NOT_ERROR_EVENT_ID" NUMBER(19,0), 
	"PAGADOR_CIE_ID" NUMBER(19,0), 
	"PAGADOR_POSTAL_ID" NUMBER(19,0), 
	"PROCEDIMENT_ID" NUMBER(19,0)
   ) ;
--------------------------------------------------------
--  DDL for Table NOT_NOTIFICACIO_ENV
--------------------------------------------------------

  CREATE TABLE "NOT_NOTIFICACIO_ENV" 
   (	"ID" NUMBER(19,0), 
	"CREATEDDATE" TIMESTAMP (6), 
	"LASTMODIFIEDDATE" TIMESTAMP (6), 
	"DEH_NIF" VARCHAR2(9 CHAR), 
	"DEH_OBLIGAT" NUMBER(1,0), 
	"DEH_PROC_CODI" VARCHAR2(64 CHAR), 
	"DOM_APARTAT" VARCHAR2(10 CHAR), 
	"DOM_BLOC" VARCHAR2(50 CHAR), 
	"DOM_CIE" NUMBER(10,0), 
	"DOM_CODI_POSTAL" VARCHAR2(10 CHAR), 
	"DOM_COMPLEM" VARCHAR2(250 CHAR), 
	"DOM_CON_TIPUS" NUMBER(10,0), 
	"DOM_ESCALA" VARCHAR2(50 CHAR), 
	"DOM_LINEA1" VARCHAR2(50 CHAR), 
	"DOM_LINEA2" VARCHAR2(50 CHAR), 
	"DOM_MUN_CODINE" VARCHAR2(6 CHAR), 
	"DOM_MUN_NOM" VARCHAR2(64 CHAR), 
	"DOM_NUM_NUM" VARCHAR2(5 CHAR), 
	"DOM_NUM_PUNTKM" VARCHAR2(10 CHAR), 
	"DOM_NUM_QUALIF" VARCHAR2(3 CHAR), 
	"DOM_NUM_TIPUS" NUMBER(10,0), 
	"DOM_PAI_CODISO" VARCHAR2(3 CHAR), 
	"DOM_PAI_NOM" VARCHAR2(64 CHAR), 
	"DOM_PLANTA" VARCHAR2(50 CHAR), 
	"DOM_POBLACIO" VARCHAR2(255 CHAR), 
	"DOM_PORTA" VARCHAR2(50 CHAR), 
	"DOM_PORTAL" VARCHAR2(50 CHAR), 
	"DOM_PRV_CODI" VARCHAR2(2 CHAR), 
	"DOM_PRV_NOM" VARCHAR2(64 CHAR), 
	"DOM_TIPUS" NUMBER(10,0), 
	"DOM_VIA_NOM" VARCHAR2(50 CHAR), 
	"DOM_VIA_TIPUS" NUMBER(10,0), 
	"FORMAT_FULLA" VARCHAR2(10 CHAR), 
	"FORMAT_SOBRE" VARCHAR2(10 CHAR), 
	"NOTIFICA_ARR_DIR3DESC" VARCHAR2(100 CHAR), 
	"NOTIFICA_ARR_DIR3CODI" VARCHAR2(9 CHAR), 
	"NOTIFICA_ARR_DIR3NIF" VARCHAR2(9 CHAR), 
	"NOTIFICA_CER_ARXIUID" VARCHAR2(50 CHAR), 
	"NOTIFICA_CER_ARXTIP" NUMBER(10,0), 
	"NOTIFICA_CER_CSV" VARCHAR2(50 CHAR), 
	"NOTIFICA_CER_DATA" TIMESTAMP (6), 
	"NOTIFICA_CER_HASH" VARCHAR2(50 CHAR), 
	"NOTIFICA_CER_METAS" VARCHAR2(255 CHAR), 
	"NOTIFICA_CER_MIME" VARCHAR2(20 CHAR), 
	"NOTIFICA_CER_NUMSEG" VARCHAR2(50 CHAR), 
	"NOTIFICA_CER_ORIGEN" VARCHAR2(20 CHAR), 
	"NOTIFICA_CER_TAMANY" NUMBER(10,0), 
	"NOTIFICA_CER_TIPUS" NUMBER(10,0), 
	"NOTIFICA_DATCAD" TIMESTAMP (6), 
	"NOTIFICA_DATCRE" TIMESTAMP (6), 
	"NOTIFICA_DATDISP" TIMESTAMP (6), 
	"NOTIFICA_DATAT_ERRDES" VARCHAR2(255 CHAR), 
	"NOTIFICA_DATAT_NUMSEG" VARCHAR2(50 CHAR), 
	"NOTIFICA_DATAT_ORIGEN" VARCHAR2(20 CHAR), 
	"NOTIFICA_DATAT_RECNIF" VARCHAR2(9 CHAR), 
	"NOTIFICA_DATAT_RECNOM" VARCHAR2(100 CHAR), 
	"NOTIFICA_EMI_DIR3DESC" VARCHAR2(100 CHAR), 
	"NOTIFICA_EMI_DIR3CODI" VARCHAR2(9 CHAR), 
	"NOTIFICA_EMI_DIR3NIF" VARCHAR2(9 CHAR), 
	"NOTIFICA_ERROR" NUMBER(1,0), 
	"NOTIFICA_ESTAT" NUMBER(10,0), 
	"NOTIFICA_ESTAT_DATA" TIMESTAMP (6), 
	"NOTIFICA_ESTAT_DATAACT" TIMESTAMP (6), 
	"NOTIFICA_ESTAT_DESC" VARCHAR2(255 CHAR), 
	"NOTIFICA_ESTAT_FINAL" NUMBER(1,0), 
	"NOTIFICA_ID" VARCHAR2(20 CHAR), 
	"NOTIFICA_INTENT_DATA" TIMESTAMP (6), 
	"NOTIFICA_INTENT_NUM" NUMBER(10,0), 
	"NOTIFICA_REF" VARCHAR2(20 CHAR), 
	"NOTIFICACIO_ID" NUMBER(19,0), 
	"REGISTRE_DATA" TIMESTAMP (6), 
	"ESTAT_REGISTRE" NUMBER(10,0), 
	"REGISTRE_ESTAT_FINAL" NUMBER(1,0), 
	"REGISTRE_NUMERO_FORMATAT" VARCHAR2(50 CHAR), 
	"SERVEI_TIPUS" NUMBER(10,0), 
	"SIR_CON_DATA" TIMESTAMP (6), 
	"SIR_CON_INTENT" NUMBER(10,0), 
	"SIR_REC_DATA" TIMESTAMP (6), 
	"SIR_REG_DESTI_DATA" TIMESTAMP (6), 
	"CREATEDBY_CODI" VARCHAR2(64 CHAR), 
	"LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR), 
	"NOTIFICA_ERROR_EVENT_ID" NUMBER(19,0), 
	"TITULAR_ID" NUMBER(19,0)
   ) ;
--------------------------------------------------------
--  DDL for Table NOT_NOTIFICACIO_EVENT
--------------------------------------------------------

  CREATE TABLE "NOT_NOTIFICACIO_EVENT" 
   (	"ID" NUMBER(19,0), 
	"CREATEDDATE" TIMESTAMP (6), 
	"LASTMODIFIEDDATE" TIMESTAMP (6), 
	"CALLBACK_DATA" TIMESTAMP (6), 
	"CALLBACK_ERROR_DESC" VARCHAR2(2048 CHAR), 
	"CALLBACK_ESTAT" VARCHAR2(10 CHAR), 
	"CALLBACK_INTENTS" NUMBER(10,0), 
	"DATA" TIMESTAMP (6), 
	"DESCRIPCIO" VARCHAR2(256 CHAR), 
	"ERROR" NUMBER(1,0), 
	"ERROR_DESC" VARCHAR2(2048 CHAR), 
	"NOTIFICACIO_ID" NUMBER(19,0), 
	"TIPUS" NUMBER(10,0), 
	"CREATEDBY_CODI" VARCHAR2(64 CHAR), 
	"LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR), 
	"NOTIFICACIO_ENV_ID" NUMBER(19,0)
   ) ;
--------------------------------------------------------
--  DDL for Table NOT_PAGADOR_CIE
--------------------------------------------------------

  CREATE TABLE "NOT_PAGADOR_CIE" 
   (	"ID" NUMBER(19,0), 
	"CREATEDDATE" TIMESTAMP (6), 
	"LASTMODIFIEDDATE" TIMESTAMP (6), 
	"CONTRACTE_DATA_VIG" DATE, 
	"DIR3_CODI" VARCHAR2(9 CHAR), 
	"CREATEDBY_CODI" VARCHAR2(64 CHAR), 
	"LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR), 
	"ENTITAT" NUMBER(19,0)
   ) ;
--------------------------------------------------------
--  DDL for Table NOT_PAGADOR_POSTAL
--------------------------------------------------------

  CREATE TABLE "NOT_PAGADOR_POSTAL" 
   (	"ID" NUMBER(19,0), 
	"CREATEDDATE" TIMESTAMP (6), 
	"LASTMODIFIEDDATE" TIMESTAMP (6), 
	"CONTRACTE_DATA_VIG" DATE, 
	"CONTRACTE_NUM" VARCHAR2(20 CHAR), 
	"DIR3_CODI" VARCHAR2(9 CHAR), 
	"FACTURACIO_CODI_CLIENT" VARCHAR2(20 CHAR), 
	"CREATEDBY_CODI" VARCHAR2(64 CHAR), 
	"LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR), 
	"ENTITAT" NUMBER(19,0)
   ) ;
--------------------------------------------------------
--  DDL for Table NOT_PERSONA
--------------------------------------------------------

  CREATE TABLE "NOT_PERSONA" 
   (	"ID" NUMBER(19,0), 
	"CREATEDDATE" TIMESTAMP (6), 
	"LASTMODIFIEDDATE" TIMESTAMP (6), 
	"COD_ENTITAT_DESTI" VARCHAR2(9 CHAR), 
	"EMAIL" VARCHAR2(255 CHAR), 
	"INCAPACITAT" NUMBER(1,0), 
	"INTERESSATTIPUS" VARCHAR2(255 CHAR), 
	"LLINATGE1" VARCHAR2(40 CHAR), 
	"LLINATGE2" VARCHAR2(40 CHAR), 
	"NIF" VARCHAR2(9 CHAR), 
	"NOM" VARCHAR2(255 CHAR), 
	"RAO_SOCIAL" VARCHAR2(100 CHAR), 
	"TELEFON" VARCHAR2(16 CHAR), 
	"CREATEDBY_CODI" VARCHAR2(64 CHAR), 
	"LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR), 
	"NOTIFICACIO_ENV_ID" NUMBER(19,0)
   ) ;
--------------------------------------------------------
--  DDL for Table NOT_PROCEDIMENT
--------------------------------------------------------

  CREATE TABLE "NOT_PROCEDIMENT" 
   (	"ID" NUMBER(19,0), 
	"CREATEDDATE" TIMESTAMP (6), 
	"LASTMODIFIEDDATE" TIMESTAMP (6), 
	"AGRUPAR" NUMBER(1,0), 
	"CADUCITAT" NUMBER(10,0), 
	"CODI" VARCHAR2(64 CHAR), 
	"CODIASSUMPTE" VARCHAR2(255 CHAR), 
	"CODIASSUMPTE_NOM" VARCHAR2(255 CHAR), 
	"LLIBRE" VARCHAR2(255 CHAR), 
	"NOM" VARCHAR2(100 CHAR), 
	"OFICINA" VARCHAR2(255 CHAR), 
	"RETARD" NUMBER(10,0), 
	"TIPUSASSUMPTE" VARCHAR2(255 CHAR), 
	"TIPUSASSUMPTE_NOM" VARCHAR2(255 CHAR), 
	"CREATEDBY_CODI" VARCHAR2(64 CHAR), 
	"LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR), 
	"ENTITAT" NUMBER(19,0), 
	"ORGAN_GESTOR" VARCHAR2(64 CHAR), 
	"PAGADORCIE" NUMBER(19,0), 
	"PAGADORPOSTAL" NUMBER(19,0)
   ) ;
--------------------------------------------------------
--  DDL for Table NOT_PRO_GRUP
--------------------------------------------------------

  CREATE TABLE "NOT_PRO_GRUP" 
   (	"ID" NUMBER(19,0), 
	"CREATEDDATE" TIMESTAMP (6), 
	"LASTMODIFIEDDATE" TIMESTAMP (6), 
	"CREATEDBY_CODI" VARCHAR2(64 CHAR), 
	"LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR), 
	"GRUP" NUMBER(19,0), 
	"PROCEDIMENT" NUMBER(19,0)
   ) ;
--------------------------------------------------------
--  DDL for Table NOT_USUARI
--------------------------------------------------------

  CREATE TABLE "NOT_USUARI" 
   (	"CODI" VARCHAR2(64 CHAR), 
	"EMAIL" VARCHAR2(200 CHAR), 
	"IDIOMA" VARCHAR2(2 CHAR), 
	"LLINATGES" VARCHAR2(100 CHAR), 
	"NOM" VARCHAR2(100 CHAR), 
	"NOM_SENCER" VARCHAR2(200 CHAR), 
	"REBRE_EMAILS" NUMBER(1,0), 
	"VERSION" NUMBER(19,0)
   ) ;
   
--------------------------------------------------------
--  DDL for Table NOT_ORGAN_GESTOR
--------------------------------------------------------

  CREATE TABLE "NOT_ORGAN_GESTOR" 
   (	"ID" NUMBER(19,0), 
	"CODI" VARCHAR2(64), 
	"ENTITAT" NUMBER(19,0), 
	"NOM" VARCHAR2(1000)
   ) ;
