--------------------------------------------------------
--  Ref Constraints for Table NOT_APLICACIO
--------------------------------------------------------

  ALTER TABLE "NOT_APLICACIO" ADD CONSTRAINT "NOT_APLICACIO_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
 
  ALTER TABLE "NOT_APLICACIO" ADD CONSTRAINT "NOT_APLICACIO_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
 
  ALTER TABLE "NOT_APLICACIO" ADD CONSTRAINT "NOT_APLICACIO_ENTITAT_FK" FOREIGN KEY ("ENTITAT_ID")
	  REFERENCES "NOT_ENTITAT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOT_COLUMNES
--------------------------------------------------------

  ALTER TABLE "NOT_COLUMNES" ADD CONSTRAINT "NOT_COLUMNES_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
 
  ALTER TABLE "NOT_COLUMNES" ADD CONSTRAINT "NOT_COLUMNES_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
 
  ALTER TABLE "NOT_COLUMNES" ADD CONSTRAINT "NOT_COLUMNES_ENTITAT_FK" FOREIGN KEY ("ENTITAT_ID")
	  REFERENCES "NOT_ENTITAT" ("ID") ENABLE;
 
  ALTER TABLE "NOT_COLUMNES" ADD CONSTRAINT "NOT_COLUMNES_USUARI_FK" FOREIGN KEY ("USUARI_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOT_DOCUMENT
--------------------------------------------------------

  ALTER TABLE "NOT_DOCUMENT" ADD CONSTRAINT "NOT_DOCUMENT_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
 
  ALTER TABLE "NOT_DOCUMENT" ADD CONSTRAINT "NOT_DOCUMENT_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOT_ENTITAT
--------------------------------------------------------

  ALTER TABLE "NOT_ENTITAT" ADD CONSTRAINT "NOT_ENTITAT_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
 
  ALTER TABLE "NOT_ENTITAT" ADD CONSTRAINT "NOT_ENTITAT_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOT_ENTITAT_TIPUS_DOC
--------------------------------------------------------

  ALTER TABLE "NOT_ENTITAT_TIPUS_DOC" ADD CONSTRAINT "NOT_ENTTIPDOC_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
 
  ALTER TABLE "NOT_ENTITAT_TIPUS_DOC" ADD CONSTRAINT "NOT_ENTTIPDOC_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
 
  ALTER TABLE "NOT_ENTITAT_TIPUS_DOC" ADD CONSTRAINT "NOT_ENTITAT_TIPUS_DOC_FK" FOREIGN KEY ("ENTITAT_ID")
	  REFERENCES "NOT_ENTITAT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOT_FORMATS_FULLA
--------------------------------------------------------

  ALTER TABLE "NOT_FORMATS_FULLA" ADD CONSTRAINT "NOT_FORMATFULLA_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
 
  ALTER TABLE "NOT_FORMATS_FULLA" ADD CONSTRAINT "NOT_FORMATFULLA_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
 
  ALTER TABLE "NOT_FORMATS_FULLA" ADD CONSTRAINT "NOT_FORMATS_FULLA_FK" FOREIGN KEY ("PAGADOR_CIE_ID")
	  REFERENCES "NOT_PAGADOR_CIE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOT_FORMATS_SOBRE
--------------------------------------------------------

  ALTER TABLE "NOT_FORMATS_SOBRE" ADD CONSTRAINT "NOT_FORMATSOBRE_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
 
  ALTER TABLE "NOT_FORMATS_SOBRE" ADD CONSTRAINT "NOT_FORMATSOBRE_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
 
  ALTER TABLE "NOT_FORMATS_SOBRE" ADD CONSTRAINT "NOT_FORMATS_SOBRE_FK" FOREIGN KEY ("PAGADOR_CIE_ID")
	  REFERENCES "NOT_PAGADOR_CIE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOT_GRUP
--------------------------------------------------------

  ALTER TABLE "NOT_GRUP" ADD CONSTRAINT "NOT_GRUP_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
 
  ALTER TABLE "NOT_GRUP" ADD CONSTRAINT "NOT_GRUP_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
 
  ALTER TABLE "NOT_GRUP" ADD CONSTRAINT "NOT_ENTITAT_GRUP_FK" FOREIGN KEY ("ENTITAT")
	  REFERENCES "NOT_ENTITAT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOT_NOTIFICACIO
--------------------------------------------------------

  ALTER TABLE "NOT_NOTIFICACIO" ADD CONSTRAINT "NOT_NOTIFICACIO_ENV_FK" FOREIGN KEY ("ID")
	  REFERENCES "NOT_NOTIFICACIO_ENV" ("ID") ENABLE;
 
  ALTER TABLE "NOT_NOTIFICACIO" ADD CONSTRAINT "NOT_NOTIFICACIO_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
 
  ALTER TABLE "NOT_NOTIFICACIO" ADD CONSTRAINT "NOT_NOTIFICACIO_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
 
  ALTER TABLE "NOT_NOTIFICACIO" ADD CONSTRAINT "NOT_DOCUMENT_NOTIFICACIO_FK" FOREIGN KEY ("DOCUMENT_ID")
	  REFERENCES "NOT_DOCUMENT" ("ID") ENABLE;
 
  ALTER TABLE "NOT_NOTIFICACIO" ADD CONSTRAINT "NOT_ENTITAT_NOTIFICACIO_FK" FOREIGN KEY ("ENTITAT_ID")
	  REFERENCES "NOT_ENTITAT" ("ID") ENABLE;
 
  ALTER TABLE "NOT_NOTIFICACIO" ADD CONSTRAINT "NOT_NOTERREVENT_NOTIFICACIO_FK" FOREIGN KEY ("NOT_ERROR_EVENT_ID")
	  REFERENCES "NOT_NOTIFICACIO_EVENT" ("ID") ENABLE;
 
  ALTER TABLE "NOT_NOTIFICACIO" ADD CONSTRAINT "NOT_PAGADOR_CIE_NOT_FK" FOREIGN KEY ("PAGADOR_CIE_ID")
	  REFERENCES "NOT_PAGADOR_CIE" ("ID") ENABLE;
 
  ALTER TABLE "NOT_NOTIFICACIO" ADD CONSTRAINT "NOT_PAGADOR_POSTAL_NOT_FK" FOREIGN KEY ("PAGADOR_POSTAL_ID")
	  REFERENCES "NOT_PAGADOR_POSTAL" ("ID") ENABLE;
 
  ALTER TABLE "NOT_NOTIFICACIO" ADD CONSTRAINT "NOT_PROCEDIMENT_NOT_FK" FOREIGN KEY ("PROCEDIMENT_ID")
	  REFERENCES "NOT_PROCEDIMENT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOT_NOTIFICACIO_ENV
--------------------------------------------------------

  ALTER TABLE "NOT_NOTIFICACIO_ENV" ADD CONSTRAINT "NOT_NOTIFENV_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
 
  ALTER TABLE "NOT_NOTIFICACIO_ENV" ADD CONSTRAINT "NOT_NOTIFENV_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
 
  ALTER TABLE "NOT_NOTIFICACIO_ENV" ADD CONSTRAINT "NOT_NOTEVE_NOTERR_NOTDEST_FK" FOREIGN KEY ("NOTIFICA_ERROR_EVENT_ID")
	  REFERENCES "NOT_NOTIFICACIO_EVENT" ("ID") ENABLE;
 
  ALTER TABLE "NOT_NOTIFICACIO_ENV" ADD CONSTRAINT "NOT_NOTIFICACIO_NOTENV_FK" FOREIGN KEY ("NOTIFICACIO_ID")
	  REFERENCES "NOT_NOTIFICACIO" ("ID") ENABLE;
 
  ALTER TABLE "NOT_NOTIFICACIO_ENV" ADD CONSTRAINT "NOT_PERSONA_NOTIFICACIO_ENV_FK" FOREIGN KEY ("TITULAR_ID")
	  REFERENCES "NOT_PERSONA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOT_NOTIFICACIO_EVENT
--------------------------------------------------------

  ALTER TABLE "NOT_NOTIFICACIO_EVENT" ADD CONSTRAINT "NOT_NOTIFEVENT_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
 
  ALTER TABLE "NOT_NOTIFICACIO_EVENT" ADD CONSTRAINT "NOT_NOTIFEVENT_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
 
  ALTER TABLE "NOT_NOTIFICACIO_EVENT" ADD CONSTRAINT "NOT_NOTENV_NOTEVE_FK" FOREIGN KEY ("NOTIFICACIO_ENV_ID")
	  REFERENCES "NOT_NOTIFICACIO_ENV" ("ID") ENABLE;
 
  ALTER TABLE "NOT_NOTIFICACIO_EVENT" ADD CONSTRAINT "NOT_NOTIFI_NOTEVE_FK" FOREIGN KEY ("NOTIFICACIO_ID")
	  REFERENCES "NOT_NOTIFICACIO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOT_PAGADOR_CIE
--------------------------------------------------------

  ALTER TABLE "NOT_PAGADOR_CIE" ADD CONSTRAINT "NOT_PAGADORCIE_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
 
  ALTER TABLE "NOT_PAGADOR_CIE" ADD CONSTRAINT "NOT_PAGADOR_CIE_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
 
  ALTER TABLE "NOT_PAGADOR_CIE" ADD CONSTRAINT "NOT_PAGADOR_CIE_ENTITAT_FK" FOREIGN KEY ("ENTITAT")
	  REFERENCES "NOT_ENTITAT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOT_PAGADOR_POSTAL
--------------------------------------------------------

  ALTER TABLE "NOT_PAGADOR_POSTAL" ADD CONSTRAINT "NOT_PAGPOSTAL_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
 
  ALTER TABLE "NOT_PAGADOR_POSTAL" ADD CONSTRAINT "NOT_PAGPOSTAL_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
 
  ALTER TABLE "NOT_PAGADOR_POSTAL" ADD CONSTRAINT "NOT_PAGADOR_POSTAL_ENTITAT_FK" FOREIGN KEY ("ENTITAT")
	  REFERENCES "NOT_ENTITAT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOT_PERSONA
--------------------------------------------------------

  ALTER TABLE "NOT_PERSONA" ADD CONSTRAINT "NOT_PERSONA_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
 
  ALTER TABLE "NOT_PERSONA" ADD CONSTRAINT "NOT_PERSONA_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
 
  ALTER TABLE "NOT_PERSONA" ADD CONSTRAINT "NOT_PERSONA_NOT_FK" FOREIGN KEY ("NOTIFICACIO_ENV_ID")
	  REFERENCES "NOT_NOTIFICACIO_ENV" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOT_PROCEDIMENT
--------------------------------------------------------

  ALTER TABLE "NOT_PROCEDIMENT" ADD CONSTRAINT "NOT_PROC_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
 
  ALTER TABLE "NOT_PROCEDIMENT" ADD CONSTRAINT "NOT_PROC_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
 
  ALTER TABLE "NOT_PROCEDIMENT" ADD CONSTRAINT "NOT_ENTITAT_FK" FOREIGN KEY ("ENTITAT")
	  REFERENCES "NOT_ENTITAT" ("ID") ENABLE;
 
  ALTER TABLE "NOT_PROCEDIMENT" ADD CONSTRAINT "NOT_PAGADOR_CIE_FK" FOREIGN KEY ("PAGADORCIE")
	  REFERENCES "NOT_PAGADOR_CIE" ("ID") ENABLE;
 
  ALTER TABLE "NOT_PROCEDIMENT" ADD CONSTRAINT "NOT_PAGADOR_POSTAL_FK" FOREIGN KEY ("PAGADORPOSTAL")
	  REFERENCES "NOT_PAGADOR_POSTAL" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOT_PRO_GRUP
--------------------------------------------------------

  ALTER TABLE "NOT_PRO_GRUP" ADD CONSTRAINT "NOT_PROGRUP_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
 
  ALTER TABLE "NOT_PRO_GRUP" ADD CONSTRAINT "NOT_PROGRUP_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
	  REFERENCES "NOT_USUARI" ("CODI") ENABLE;
 
  ALTER TABLE "NOT_PRO_GRUP" ADD CONSTRAINT "NOT_GRUP_PRO_FK" FOREIGN KEY ("GRUP")
	  REFERENCES "NOT_GRUP" ("ID") ENABLE;
 
  ALTER TABLE "NOT_PRO_GRUP" ADD CONSTRAINT "NOT_PRO_GRUP_FK" FOREIGN KEY ("PROCEDIMENT")
	  REFERENCES "NOT_PROCEDIMENT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOT_ORGAN_GESTOR
--------------------------------------------------------

  ALTER TABLE "NOT_ORGAN_GESTOR" ADD CONSTRAINT "NOT_ORGAN_ENTITAT_FK" FOREIGN KEY ("ENTITAT")
	  REFERENCES "NOT_ENTITAT" ("ID") ENABLE;
