ALTER TABLE NOT_ENTITAT ADD LLIBRE VARCHAR2(255 CHAR);
ALTER TABLE NOT_ENTITAT ADD LLIBRE_NOM VARCHAR2(255 CHAR);
ALTER TABLE NOT_ENTITAT ADD LLIBRE_ENTITAT NUMBER(1,0);

UPDATE NOT_ENTITAT SET LLIBRE_ENTITAT = 0;