-- Update for version (0.1 -> 1.0)
-- #54
CREATE TABLE NOT_PROCEDIMENT 
(
  ID						BIGSERIAL(19)	    	NOT NULL,
  CODI          			character varying(64),		NOT NULL,
  NOM						character varying(100),
  CODISIA					character varying(64),
  ENTITAT					BIGSERIAL(19),
  PAGADORPOSTAL				BIGSERIAL(19),
  PAGADORCIE				BIGSERIAL(19),
  AGRUPAR					BOOLEAN,
  RETARD 					BIGSERIAL(19),
  DATA_PROGRAMADA 			timestamp without time zone,
  CREATEDBY_CODI       		character varying(64),
  CREATEDDATE          		timestamp without time zone,
  LASTMODIFIEDBY_CODI  		character varying(64),
  LASTMODIFIEDDATE     		timestamp without time zone
);

CREATE TABLE NOT_GRUP 
(
  ID						BIGSERIAL(19)	    	NOT NULL,
  CODI						character varying(64),		NOT NULL,
  NOM						character varying(100),
  ENTITAT					BIGSERIAL(19),
  CREATEDBY_CODI       		character varying(64),
  CREATEDDATE          		timestamp without time zone,
  LASTMODIFIEDBY_CODI  		character varying(64),
  LASTMODIFIEDDATE     		timestamp without time zone
);

CREATE TABLE NOT_PAGADOR_POSTAL
(
  ID						BIGSERIAL(19)	    	NOT NULL,
  DIR3_CODI            		character varying(9),  		NOT NULL,
  CONTRACTE_NUM		        character varying(20),
  CONTRACTE_DATA_VIG      	DATE,
  FACTURACIO_CODI_CLIENT   	character varying(20),
  CREATEDBY_CODI       		character varying(64),
  CREATEDDATE          		timestamp without time zone,
  LASTMODIFIEDBY_CODI  		character varying(64),
  LASTMODIFIEDDATE     		timestamp without time zone
);

CREATE TABLE NOT_PAGADOR_CIE
(
  ID						BIGSERIAL(19)	   	 	NOT NULL,
  DIR3_CODI            		character varying(9), 		NOT NULL,
  CONTRACTE_DATA_VIG      	DATE,
  CREATEDBY_CODI       		character varying(64),
  CREATEDDATE          		timestamp without time zone,
  LASTMODIFIEDBY_CODI  		character varying(64),
  LASTMODIFIEDDATE     		timestamp without time zone
);

CREATE TABLE NOT_PRO_GRUP 
(
  ID						BIGSERIAL(19)	    	NOT NULL,
  GRUP						BIGSERIAL(19),			
  PROCEDIMENT				BIGSERIAL(19),
  CREATEDBY_CODI       		character varying(64),
  CREATEDDATE          		timestamp without time zone,
  LASTMODIFIEDBY_CODI  		character varying(64),
  LASTMODIFIEDDATE     		timestamp without time zone
);

ALTER TABLE ONLY NOT_PROCEDIMENT ADD (
  CONSTRAINT NOT_PROCEDIMENT_PK PRIMARY KEY (ID));
  
ALTER TABLE ONLY NOT_GRUP ADD (
  CONSTRAINT NOT_GRUP_PK PRIMARY KEY (ID));
  
ALTER TABLE ONLY NOT_PAGADOR_POSTAL ADD COLUMN (
  CONSTRAINT NOT_PAGADOR_POSTAL_PK PRIMARY KEY (ID));
  
ALTER TABLE ONLY NOT_PAGADOR_CIE ADD (
  CONSTRAINT NOT_PAGADOR_CIE_PK PRIMARY KEY (ID));
  
ALTER TABLE ONLY NOT_PROCEDIMENT ADD (
  CONSTRAINT NOT_PAGADOR_POSTAL_FK FOREIGN KEY (PAGADORPOSTAL)
    REFERENCES NOT_PAGADOR_POSTAL (ID));
  
ALTER TABLE NOT_PROCEDIMENT ADD (
  CONSTRAINT NOT_PAGADOR_CIE_FK FOREIGN KEY (PAGADORCIE)
    REFERENCES NOT_PAGADOR_CIE (ID));
    
ALTER TABLE ONLY NOT_PROCEDIMENT ADD (
  CONSTRAINT NOT_ENTITAT_FK FOREIGN KEY (ENTITAT)
    REFERENCES NOT_ENTITAT (ID));
    
-- #55

ALTER TABLE NOT_NOTIFICACIO ADD COLUMN REGISTRE_ORGAN character varying(10);
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN REGISTRE_OFICINA character varying(10);
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN REGISTRE_LLIBRE character varying(10);
    
-- #59
CREATE TABLE NOT_COLUMNES
(
  ID                   		BIGSERIAL(19),
  CREATED_DATE      		BOOLEAN,
  DATA_PROGRAMADA           BOOLEAN,
  NOT_IDENTIFICADOR         BOOLEAN,
  PRO_CODI             		BOOLEAN,
  GRUP_CODI           		BOOLEAN,
  DIR3_CODI					BOOLEAN,
  USUARI					BOOLEAN,
  ENVIAMENT_TIPUS          	BOOLEAN,
  CONCEPTE       			BOOLEAN,
  DESCRIPCIO   				BOOLEAN,
  TITULAR_NIF      			BOOLEAN,
  TITULAR_NOM_LLINATGE      BOOLEAN,
  TITULAR_EMAIL      		BOOLEAN,
  DESTINATARIS        	    BOOLEAN,
  LLIBRE_REGISTRE        	BOOLEAN,
  NUMERO_REGISTRE           BOOLEAN,
  DATA_REGISTRE        		BOOLEAN,
  DATA_CADUCITAT         	BOOLEAN,
  CODI_NOTIB_ENV            BOOLEAN,
  NUM_CERTIFICACIO      	BOOLEAN,
  CSV_UUID          		BOOLEAN,
  ESTAT                		BOOLEAN,
  ENTITAT_ID				BIGSERIAL(19),
  USUARI_CODI				character varying(64),
  CREATEDBY_CODI       		character varying(64),
  CREATEDDATE          		timestamp without time zone,
  LASTMODIFIEDBY_CODI  		character varying(64),
  LASTMODIFIEDDATE     		timestamp without time zone
);

ALTER TABLE ONLY NOT_COLUMNES ADD (
  CONSTRAINT NOT_COLUMNES_ENTITAT_FK FOREIGN KEY (ENTITAT_ID)
    REFERENCES NOT_ENTITAT (ID));

ALTER TABLE ONLY NOT_COLUMNES ADD (
  CONSTRAINT NOT_COLUMNES_USUARI_FK FOREIGN KEY (USUARI_CODI)
    REFERENCES NOT_USUARI (CODI));
  
-- #67
ALTER TABLE NOT_PROCEDIMENT ADD COLUMN LLIBRE character varying(64);
ALTER TABLE NOT_PROCEDIMENT ADD COLUMN OFICINA character varying(64);
ALTER TABLE NOT_PROCEDIMENT ADD COLUMN TIPUSASSUMPTE BIGSERIAL(1);

CREATE TABLE NOT_PERSONA
(
  ID					BIGSERIAL					NOT NULL,
  EMAIL					character varying(100),
  LLINATGE1				character varying(100)		NOT NULL,
  LLINATGE2				character varying(100),
  NIF					character varying(9)		NOT NULL,
  NOM					character varying(100),
  TELEFON				character varying(16),
  RAO_SOCIAL			character varying(100),
  COD_ENTITAT_DESTI		character varying(9),
  NOTIFICACIO_ENV_ID	BIGSERIAL,
  CREATEDBY_CODI       	character varying(64),
  CREATEDDATE          	timestamp without time zone,
  LASTMODIFIEDBY_CODI  	character varying(64),
  LASTMODIFIEDDATE     	timestamp without time zone
);

ALTER TABLE ONLY NOT_PERSONA ADD (
  CONSTRAINT NOT_PERSONA_NOT_FK FOREIGN KEY (NOTIFICACIO_ENV_ID)
    REFERENCES NOT_NOTIFICACIO_ENV(ID));


CREATE TABLE NOT_DOCUMENT
(
  ID					BIGSERIAL(19)			NOT NULL,
  ARXIU_ID				character varying(64),
  ARXIU_GEST_DOC_ID		character varying(64),
  ARXIU_NOM				character varying(100)	NOT NULL,
  HASH					character varying(2048),
  URL					character varying(256),
  TELEFON				character varying(16),
  METADADES				character varying(256),
  NORMALITZAT			BOOLEAN,
  GENERAR_CSV			BOOLEAN,
  UUID					character varying(64),
  CSV					character varying(256),
  CREATEDBY_CODI       	character varying(64),
  CREATEDDATE          	timestamp without time zone,
  LASTMODIFIEDBY_CODI  	character varying(64),
  LASTMODIFIEDDATE     	timestamp without time zone
);

ALTER TABLE NOT_NOTIFICACIO ADD COLUMN REGISTRE_EXTRACTE character varying(64);
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN REGISTRE_DOC_FISICA character varying(64);
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN REGISTRE_IDIOMA character varying(2);
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN REGISTRE_TIPUS_ASSUMPTE BIGSERIAL(1);
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN REGISTRE_NUM_EXPEDIENT character varying(20);
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN REGISTRE_REF_EXTERNA character varying(64);
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN REGISTRE_CODI_ASSUMPTE character varying(20);
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN REGISTRE_OBSERVACIONS character varying(256);
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN GRUP_CODI character varying(64);
ALTER TABLE NOT_NOTIFICACIO MODIFY DOC_ARXIU_NOM character varying(256);
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN DOCUMENT_ID	BIGSERIAL(19) NOT NULL;
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN USUARI_CODI	character varying(64);
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN PROCEDIMENT_ID BIGSERIAL(19);
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN PAGADOR_POSTAL_ID BIGSERIAL(19);
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN PAGADOR_CIE_ID BIGSERIAL(19);
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN TITULAR_ID BIGSERIAL(19);
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN PROC_CODI_NOTIB	character varying(6);
ALTER TABLE NOT_NOTIFICACIO MODIFY PROC_CODI_SIA character varying(6);
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN CSV_UUID character varying(64);

ALTER TABLE NOT_NOTIFICACIO_ENV ADD COLUMN TITULAR_ID BIGSERIAL(19);

ALTER TABLE ONLY NOT_DOCUMENT ADD (
  CONSTRAINT NOT_DOCUMENT_PK PRIMARY KEY (ID));
  
ALTER TABLE ONLY NOT_PERSONA ADD (
  CONSTRAINT NOT_PERSONA_PK PRIMARY KEY (ID));
  
ALTER TABLE ONLY NOT_NOTIFICACIO_ENV ADD (
  CONSTRAINT NOT_PERSONA_NOTIFICACIO_ENV_FK FOREIGN KEY (TITULAR_ID)
    REFERENCES NOT_PERSONA (ID));

ALTER TABLE ONLY NOT_NOTIFICACIO ADD (
  CONSTRAINT NOT_DOCUMENT_NOTIFICACIO_FK FOREIGN KEY (DOCUMENT_ID)
    REFERENCES NOT_DOCUMENT (ID));
    
ALTER TABLE ONLY NOT_NOTIFICACIO ADD (
  CONSTRAINT NOT_PROCEDIMENT_NOT_FK FOREIGN KEY (PROCEDIMENT_ID)
    REFERENCES NOT_PROCEDIMENT (ID));    
    
ALTER TABLE ONLY NOT_NOTIFICACIO ADD (
  CONSTRAINT NOT_PAGADOR_POSTAL_NOT_FK FOREIGN KEY (PAGADOR_POSTAL_ID)
    REFERENCES NOT_PAGADOR_POSTAL (ID));
    
ALTER TABLE ONLY NOT_NOTIFICACIO ADD (
  CONSTRAINT NOT_PAGADOR_CIE_NOTIFICACIO_FK FOREIGN KEY (PAGADOR_CIE_ID)
    REFERENCES NOT_PAGADOR_CIE (ID));
      
ALTER TABLE ONLY NOT_PRO_GRUP ADD (
  CONSTRAINT NOT_GRUP_PRO_FK FOREIGN KEY (GRUP)
      REFERENCES NOT_GRUP (ID),
  CONSTRAINT NOT_PRO_GRUP_FK FOREIGN KEY (PROCEDIMENT)
      REFERENCES NOT_PROCEDIMENT (ID));
      
CREATE INDEX NOT_PAGADOR_POSTAL_FK_I ON NOT_PROCEDIMENT(PAGADORPOSTAL);
CREATE INDEX NOT_PAGADOR_CIE_FK_I ON NOT_PROCEDIMENT(PAGADORCIE);
CREATE INDEX NOT_ENTITAT_FK_I ON NOT_PROCEDIMENT(entitat);   

ALTER TABLE NOT_NOTIFICACIO DROP COLUMN DOC_ARXIU_NOM;
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN DOC_ARXIU_ID;
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN DOC_GEN_CSV;
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN DOC_HASH;
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN DOC_NORMALITZAT;
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN PROC_CODI_SIA;
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN PROC_CODI_SIA VARCHAR(6);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_EXP_UNIORG;
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN SEU_EXP_UNIORG VARCHAR(10);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_EXP_IDENI;
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN SEU_EXP_IDENI VARCHAR(52);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_EXP_TITOL;
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN SEU_EXP_TITOL VARCHAR(256);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_EXP_TITOL;
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN SEU_EXP_TITOL VARCHAR(256);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_REG_OFICINA;
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN SEU_REG_OFICINA VARCHAR(256);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_REG_LLIBRE;
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN SEU_REG_LLIBRE VARCHAR(256);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_IDIOMA;
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN SEU_IDIOMA VARCHAR(256);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_AVIS_TITOL;
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN SEU_AVIS_TITOL VARCHAR(256);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_AVIS_TEXT;
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN SEU_AVIS_TEXT VARCHAR(256);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_OFICI_TITOL;
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN SEU_OFICI_TITOL VARCHAR(256);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_OFICI_TEXT;
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN SEU_OFICI_TEXT VARCHAR(256);
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN REGISTRE_NUMERO VARCHAR(256);
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN REGISTRE_DATA DATE;

ALTER TABLE NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_NIF;
ALTER TABLE NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_NOM;
ALTER TABLE NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_LLINATGE1;
ALTER TABLE NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_LLINATGE2;
ALTER TABLE NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_RAOSOC;
ALTER TABLE NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_CODDES;
ALTER TABLE NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_TELEFON;
ALTER TABLE NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_EMAIL;

ALTER TABLE NOT_NOTIFICACIO_ENV DROP COLUMN SEU_ESTAT;
ALTER TABLE NOT_NOTIFICACIO_ENV DROP COLUMN SEU_ERROR;
ALTER TABLE NOT_NOTIFICACIO_ENV ADD COLUMN SEU_ESTAT BIGSERIAL(19);
ALTER TABLE NOT_NOTIFICACIO_ENV ADD COLUMN SEU_ERROR BIGSERIAL(19);

-- #72
ALTER TABLE NOT_NOTIFICACIO MODIFY REGISTRE_TIPUS_ASSUMPTE character varying(255);
ALTER TABLE NOT_NOTIFICACIO MODIFY REGISTRE_CODI_ASSUMPTE character varying(255);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN PROC_CODI_SIA;

ALTER TABLE NOT_PROCEDIMENT MODIFY TIPUSASSUMPTE character varying(255);
ALTER TABLE NOT_PROCEDIMENT ADD COLUMN CODIASSUMPTE character varying(255);

ALTER TABLE NOT_NOTIFICACIO MODIFY DOCUMENT_ID BIGSERIAL(19) NULL;

ALTER TABLE NOT_DOCUMENT MODIFY METADADES character varying(3000);

ALTER TABLE NOT_PERSONA ADD INTERESSATTIPUS character varying(30);
ALTER TABLE NOT_PERSONA MODIFY LLINATGE1 character varying(100) NULL;

ALTER TABLE NOT_NOTIFICACIO DROP COLUMN REGISTRE_DOC_FISICA;
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_DOC_FISICA BIGSERIAL(2);
ALTER TABLE NOT_NOTIFICACIO MODIFY REGISTRE_IDIOMA character varying(10);

ALTER TABLE NOT_NOTIFICACIO MODIFY REGISTRE_NUMERO BIGSERIAL(19);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_NUMERO_FORMATAT character varying(50);

ALTER TABLE NOT_NOTIFICACIO_ENV ADD REGISTRE_NUMERO_FORMATAT character varying(50);
ALTER TABLE NOT_NOTIFICACIO_ENV ADD REGISTRE_DATA timestamp without time zone;
ALTER TABLE NOT_NOTIFICACIO_ENV ADD ESTAT_REGISTRE BIGSERIAL(19);

-- #77
ALTER TABLE NOT_NOTIFICACIO ADD MOTIU character varying(255);
ALTER TABLE NOT_USUARI ADD REBRE_EMAILS BOOLEAN;
UPDATE NOT_USUARI SET REBRE_EMAILS = 1;

-- #83
ALTER TABLE NOT_ENTITAT ADD API_KEY character varying(64);

-- #84
ALTER TABLE NOT_PROCEDIMENT ADD ORGAN_GESTOR character varying(19);
ALTER TABLE NOT_PROCEDIMENT ADD ORGAN_GESTOR_NOM character varying(64);
ALTER TABLE NOT_PROCEDIMENT ADD OFICINA_NOM character varying(64);
ALTER TABLE NOT_PROCEDIMENT ADD LLIBRE_NOM character varying(64);
ALTER TABLE NOT_PROCEDIMENT ADD TIPUSASSUMPTE_NOM character varying(64);
ALTER TABLE NOT_PROCEDIMENT ADD CODIASSUMPTE_NOM character varying(64);
ALTER TABLE NOT_NOTIFICACIO ADD ORGAN_GESTOR character varying(19);




