ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_ORGAN character varying(10);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_OFICINA character varying(10);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_LLIBRE character varying(10);