ALTER TABLE NOT_NOTIFICACIO ADD COLUMN REGISTRE_ORGAN character varying(10);
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN REGISTRE_OFICINA character varying(10);
ALTER TABLE NOT_NOTIFICACIO ADD COLUMN REGISTRE_LLIBRE character varying(10);
