CREATE TABLE NOT_COLUMNES
(
  ID                   		BIGSERIAL(19),
  CREATED_DATE      		BOOLEAN,
  DATA_PROGRAMADA           BOOLEAN,
  NOT_IDENTIFICADOR         BOOLEAN,
  PRO_CODI             		BOOLEAN,
  GRUP_CODI           		BOOLEAN,
  DIR3_CODI					BOOLEAN,
  USUARI					BOOLEAN,
  ENVIAMENT_TIPUS          	BOOLEAN,
  CONCEPTE       			BOOLEAN,
  DESCRIPCIO   				BOOLEAN,
  TITULAR_NIF      			BOOLEAN,
  TITULAR_NOM_LLINATGE      BOOLEAN,
  TITULAR_EMAIL      		BOOLEAN,
  DESTINATARIS        	    BOOLEAN,
  LLIBRE_REGISTRE        	BOOLEAN,
  NUMERO_REGISTRE           BOOLEAN,
  DATA_REGISTRE        		BOOLEAN,
  DATA_CADUCITAT         	BOOLEAN,
  CODI_NOTIB_ENV            BOOLEAN,
  NUM_CERTIFICACIO      	BOOLEAN,
  CSV_UUID          		BOOLEAN,
  ESTAT                		BOOLEAN,
  ENTITAT_ID				BIGSERIAL(19),
  USUARI_CODI				character varying(64),
  CREATEDBY_CODI       		character varying(64),
  CREATEDDATE          		timestamp without time zone,
  LASTMODIFIEDBY_CODI  		character varying(64),
  LASTMODIFIEDDATE     		timestamp without time zone
)

ALTER TABLE ONLY NOT_COLUMNES ADD (
  CONSTRAINT NOT_COLUMNES_ENTITAT_FK FOREIGN KEY (ENTITAT_ID)
    REFERENCES NOT_ENTITAT (ID));

ALTER TABLE ONLY NOT_COLUMNES ADD (
  CONSTRAINT NOT_COLUMNES_USUARI_FK FOREIGN KEY (USUARI_CODI)
    REFERENCES NOT_USUARI (CODI));





