CREATE TABLE NOT_COLUMNES
(
  ID                   		BIGSERIAL(19),
  CREATED_DATE      		BIGSERIAL(1),
  DATA_PROGRAMADA           BIGSERIAL(1),
  NOT_IDENTIFICADOR         BIGSERIAL(1),
  PRO_CODI             		BIGSERIAL(1),
  GRUP_CODI           		BIGSERIAL(1),
  DIR3_CODI					BIGSERIAL(1),
  USUARI					BIGSERIAL(1),
  ENVIAMENT_TIPUS          	BIGSERIAL(1),
  CONCEPTE       			BIGSERIAL(1),
  DESCRIPCIO   				BIGSERIAL(1),
  TITULAR_NIF      			BIGSERIAL(1),
  TITULAR_NOM_LLINATGE      BIGSERIAL(1),
  TITULAR_EMAIL      		BIGSERIAL(1),
  DESTINATARIS        	    BIGSERIAL(1),
  LLIBRE_REGISTRE        	BIGSERIAL(1),
  NUMERO_REGISTRE           BIGSERIAL(1),
  DATA_REGISTRE        		BIGSERIAL(1),
  DATA_CADUCITAT         	BIGSERIAL(1),
  CODI_NOTIB_ENV            BIGSERIAL(1),
  NUM_CERTIFICACIO      	BIGSERIAL(1),
  CSV_UUID          		BIGSERIAL(1),
  ESTAT                		BIGSERIAL(1),
  ENTITAT_ID				BIGSERIAL(19),
  USUARI_CODI				character varying(64),
  CREATEDBY_CODI       		character varying(64),
  CREATEDDATE          		TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  		character varying(64),
  LASTMODIFIEDDATE     		TIMESTAMP(6)
)

ALTER TABLE NOT_COLUMNES ADD (
  CONSTRAINT NOT_COLUMNES_ENTITAT_FK FOREIGN KEY (ENTITAT_ID)
    REFERENCES NOT_ENTITAT (ID));

ALTER TABLE NOT_COLUMNES ADD (
  CONSTRAINT NOT_COLUMNES_USUARI_FK FOREIGN KEY (USUARI_CODI)
    REFERENCES NOT_USUARI (CODI));








