ALTER TABLE NOT_PROCEDIMENT ADD LLIBRE character varying(64);
ALTER TABLE NOT_PROCEDIMENT ADD OFICINA character varying(64);
ALTER TABLE NOT_PROCEDIMENT ADD TIPUSASSUMPTE BIGSERIAL(1);
      
CREATE TABLE NOT_PERSONA
(
  ID					BIGSERIAL(19)			NOT NULL,
  EMAIL					character varying(100),
  LLINATGE1				character varying(100)		NOT NULL,
  LLINATGE2				character varying(100),
  NIF					character varying(9)			NOT NULL,
  NOM					character varying(100),
  TELEFON				character varying(16),
  RAO_SOCIAL			character varying(100),
  COD_ENTITAT_DESTI		character varying(9),
  NOTIFICACIO_ENV_ID	BIGSERIAL(19),
  CREATEDBY_CODI       	character varying(64),
  CREATEDDATE          	timestamp without time zone,
  LASTMODIFIEDBY_CODI  	character varying(64),
  LASTMODIFIEDDATE     	timestamp without time zone
);

ALTER TABLE NOT_PERSONA ADD (
  CONSTRAINT NOT_PERSONA_NOT_FK FOREIGN KEY (NOTIFICACIO_ENV_ID)
    REFERENCES NOT_NOTIFICACIO_ENV(ID));

CREATE TABLE NOT_DOCUMENT
(
  ID					BIGSERIAL(19)			NOT NULL,
  ARXIU_ID				character varying(64),
  ARXIU_GEST_DOC_ID		character varying(64),
  ARXIU_NOM				character varying(100),
  HASH					character varying(2048),
  URL					character varying(256),
  TELEFON				character varying(16),
  METADADES				character varying(256),
  NORMALITZAT			BOOLEAN,
  GENERAR_CSV			BOOLEAN,
  UUID					character varying(64),
  CSV					character varying(256),
  CREATEDBY_CODI       	character varying(64),
  CREATEDDATE          	timestamp without time zone,
  LASTMODIFIEDBY_CODI  	character varying(64),
  LASTMODIFIEDDATE     	timestamp without time zone
);

ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_EXTRACTE character varying(64);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_DOC_FISICA character varying(64);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_IDIOMA character varying(2);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_TIPUS_ASSUMPTE BIGSERIAL(1);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_NUM_EXPEDIENT character varying(20);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_REF_EXTERNA character varying(64);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_CODI_ASSUMPTE character varying(20);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_OBSERVACIONS character varying(256);
ALTER TABLE NOT_NOTIFICACIO ADD GRUP_CODI character varying(64);
ALTER TABLE NOT_NOTIFICACIO MODIFY DOC_ARXIU_NOM character varying(256);
ALTER TABLE NOT_NOTIFICACIO ADD DOCUMENT_ID	BIGSERIAL(19) NOT NULL;
ALTER TABLE NOT_NOTIFICACIO ADD USUARI_CODI	character varying(64);
ALTER TABLE NOT_NOTIFICACIO ADD PROCEDIMENT_ID BIGSERIAL(19);
ALTER TABLE NOT_NOTIFICACIO ADD PAGADOR_POSTAL_ID BIGSERIAL(19);
ALTER TABLE NOT_NOTIFICACIO ADD PAGADOR_CIE_ID BIGSERIAL(19);
ALTER TABLE NOT_NOTIFICACIO ADD TITULAR_ID BIGSERIAL(19);
ALTER TABLE NOT_NOTIFICACIO ADD PROC_CODI_NOTIB	character varying(6);
ALTER TABLE NOT_NOTIFICACIO MODIFY PROC_CODI_SIA character varying(6);
ALTER TABLE NOT_NOTIFICACIO ADD CSV_UUID character varying(64);

ALTER TABLE NOT_NOTIFICACIO_ENV ADD TITULAR_ID BIGSERIAL(19);

ALTER TABLE NOT_DOCUMENT ADD (
  CONSTRAINT NOT_DOCUMENT_PK PRIMARY KEY (ID));
  
ALTER TABLE NOT_PERSONA ADD (
  CONSTRAINT NOT_PERSONA_PK PRIMARY KEY (ID));

ALTER TABLE NOT_NOTIFICACIO_ENV ADD (
  CONSTRAINT NOT_PERSONA_NOTIFICACIO_ENV_FK FOREIGN KEY (TITULAR_ID)
    REFERENCES NOT_PERSONA (ID));

ALTER TABLE NOT_NOTIFICACIO ADD (
  CONSTRAINT NOT_DOCUMENT_NOTIFICACIO_FK FOREIGN KEY (DOCUMENT_ID)
    REFERENCES NOT_DOCUMENT (ID));
    
ALTER TABLE NOT_NOTIFICACIO ADD (
  CONSTRAINT NOT_PROCEDIMENT_NOT_FK FOREIGN KEY (PROCEDIMENT_ID)
    REFERENCES NOT_PROCEDIMENT (ID));
   
    
    
ALTER TABLE NOT_NOTIFICACIO ADD (
  CONSTRAINT NOT_PAGADOR_POSTAL_NOT_FK FOREIGN KEY (PAGADOR_POSTAL_ID)
    REFERENCES NOT_PAGADOR_POSTAL (ID));
    
ALTER TABLE NOT_NOTIFICACIO ADD (
  CONSTRAINT NOT_PAGADOR_CIE_NOTIFICACIO_FK FOREIGN KEY (PAGADOR_CIE_ID)
    REFERENCES NOT_PAGADOR_CIE (ID));
      
ALTER TABLE NOT_PRO_GRUP ADD (
  CONSTRAINT NOT_GRUP_PRO_FK FOREIGN KEY (GRUP)
      REFERENCES NOT_GRUP (ID),
  CONSTRAINT NOT_PRO_GRUP_FK FOREIGN KEY (PROCEDIMENT)
      REFERENCES NOT_PROCEDIMENT (ID));

CREATE INDEX NOT_PAGADOR_POSTAL_FK_I ON NOT_PROCEDIMENT(PAGADORPOSTAL);
CREATE INDEX NOT_PAGADOR_CIE_FK_I ON NOT_PROCEDIMENT(PAGADORCIE);
CREATE INDEX NOT_ENTITAT_FK_I ON NOT_PROCEDIMENT(entitat);


ALTER TABLE NOT_NOTIFICACIO DROP COLUMN DOC_ARXIU_NOM;
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN DOC_ARXIU_ID;
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN DOC_GEN_CSV;
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN DOC_HASH;
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN DOC_NORMALITZAT;
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN PROC_CODI_SIA;
ALTER TABLE NOT_NOTIFICACIO ADD PROC_CODI_SIA character varying(6);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_EXP_UNIORG;
ALTER TABLE NOT_NOTIFICACIO ADD SEU_EXP_UNIORG character varying(10);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_EXP_IDENI;
ALTER TABLE NOT_NOTIFICACIO ADD SEU_EXP_IDENI character varying(52);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_EXP_TITOL;
ALTER TABLE NOT_NOTIFICACIO ADD SEU_EXP_TITOL character varying(256);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_EXP_TITOL;
ALTER TABLE NOT_NOTIFICACIO ADD SEU_EXP_TITOL character varying(256);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_REG_OFICINA;
ALTER TABLE NOT_NOTIFICACIO ADD SEU_REG_OFICINA character varying(256);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_REG_LLIBRE;
ALTER TABLE NOT_NOTIFICACIO ADD SEU_REG_LLIBRE character varying(256);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_IDIOMA;
ALTER TABLE NOT_NOTIFICACIO ADD SEU_IDIOMA character varying(256);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_AVIS_TITOL;
ALTER TABLE NOT_NOTIFICACIO ADD SEU_AVIS_TITOL character varying(256);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_AVIS_TEXT;
ALTER TABLE NOT_NOTIFICACIO ADD SEU_AVIS_TEXT character varying(256);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_OFICI_TITOL;
ALTER TABLE NOT_NOTIFICACIO ADD SEU_OFICI_TITOL character varying(256);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_OFICI_TEXT;
ALTER TABLE NOT_NOTIFICACIO ADD SEU_OFICI_TEXT character varying(256);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_NUMERO character varying(256);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_DATA DATE;


ALTER TABLE NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_NIF;
ALTER TABLE NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_NOM;
ALTER TABLE NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_LLINATGE1;
ALTER TABLE NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_LLINATGE2;
ALTER TABLE NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_RAOSOC;
ALTER TABLE NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_CODDES;
ALTER TABLE NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_TELEFON;
ALTER TABLE NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_EMAIL;

ALTER TABLE NOT_NOTIFICACIO_ENV DROP COLUMN SEU_ESTAT;
ALTER TABLE NOT_NOTIFICACIO_ENV DROP COLUMN SEU_ERROR;
ALTER TABLE NOT_NOTIFICACIO_ENV ADD SEU_ESTAT BIGSERIAL(19);
ALTER TABLE NOT_NOTIFICACIO_ENV ADD SEU_ERROR BIGSERIAL(19);







