-- #72
ALTER TABLE NOT_NOTIFICACIO MODIFY REGISTRE_TIPUS_ASSUMPTE character varying(255);
ALTER TABLE NOT_NOTIFICACIO MODIFY REGISTRE_CODI_ASSUMPTE character varying(255);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN PROC_CODI_SIA;

ALTER TABLE NOT_PROCEDIMENT MODIFY TIPUSASSUMPTE character varying(255);
ALTER TABLE NOT_PROCEDIMENT ADD CODIASSUMPTE character varying(255);

ALTER TABLE NOT_NOTIFICACIO MODIFY DOCUMENT_ID BIGSERIAL(19) NULL;

ALTER TABLE NOT_DOCUMENT MODIFY METADADES character varying(3000);

ALTER TABLE NOT_PERSONA ADD INTERESSATTIPUS character varying(30);
ALTER TABLE NOT_PERSONA MODIFY LLINATGE1 character varying(100) NULL;

ALTER TABLE NOT_NOTIFICACIO DROP COLUMN REGISTRE_DOC_FISICA;
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_DOC_FISICA BIGSERIAL(2);
ALTER TABLE NOT_NOTIFICACIO MODIFY REGISTRE_IDIOMA character varying(10);

ALTER TABLE NOT_NOTIFICACIO MODIFY REGISTRE_NUMERO BIGSERIAL(19);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_NUMERO_FORMATAT character varying(50);

ALTER TABLE NOT_NOTIFICACIO_ENV ADD REGISTRE_NUMERO_FORMATAT character varying(50);
ALTER TABLE NOT_NOTIFICACIO_ENV ADD REGISTRE_DATA DATE;
ALTER TABLE NOT_NOTIFICACIO_ENV ADD ESTAT_REGISTRE BIGSERIAL(19);