-- #84
ALTER TABLE NOT_PROCEDIMENT ADD ORGAN_GESTOR character varying(19);
ALTER TABLE NOT_PROCEDIMENT ADD ORGAN_GESTOR_NOM character varying(64);
ALTER TABLE NOT_PROCEDIMENT ADD OFICINA_NOM character varying(64);
ALTER TABLE NOT_PROCEDIMENT ADD LLIBRE_NOM character varying(64);
ALTER TABLE NOT_PROCEDIMENT ADD TIPUSASSUMPTE_NOM character varying(64);
ALTER TABLE NOT_PROCEDIMENT ADD CODIASSUMPTE_NOM character varying(64);
ALTER TABLE NOT_NOTIFICACIO ADD ORGAN_GESTOR character varying(19);