-- #94
ALTER TABLE NOT_ENTITAT ADD LOGO_CAP BLOB;
ALTER TABLE NOT_ENTITAT ADD LOGO_PEU BLOB;
ALTER TABLE NOT_ENTITAT ADD COLOR_FONS character varying(32);
ALTER TABLE NOT_ENTITAT ADD COLOR_LLETRA character varying(32);
ALTER TABLE NOT_ENTITAT ADD TIPUS_DOC_DEFAULT BIGSERIAL(32);

CREATE TABLE NOT_ENTITAT_TIPUS_DOC
(
  ID            			BIGSERIAL(19),
  ENTITAT_ID				BIGSERIAL(19),
  TIPUS_DOC					BIGSERIAL(32),
  CREATEDBY_CODI       		character varying(64),
  CREATEDDATE          		timestamp without time zone,
  LASTMODIFIEDBY_CODI  		character varying(64),
  LASTMODIFIEDDATE     		timestamp without time zone
)

ALTER TABLE ONLY NOT_ENTITAT_TIPUS_DOC ADD (
  CONSTRAINT NOT_ENTITAT_TIPUS_DOC_PK PRIMARY KEY (ID));

ALTER TABLE ONLY NOT_ENTITAT_TIPUS_DOC ADD (
  CONSTRAINT NOT_ENTITAT_TIPUS_DOC_FK FOREIGN KEY (ENTITAT_ID)
    REFERENCES NOT_ENTITAT (ID));
	
CREATE INDEX NOT_ENTITAT_TIPUS_DOC_FK_I ON NOT_ENTITAT_TIPUS_DOC(ENTITAT_ID);


