-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: db/changelog/db.changelog-master.yaml
-- Ran at: 22/09/21 12:20
-- Against: null@offline:oracle?changeLogFile=liquibase/databasechangelog.csv
-- Liquibase version: 4.4.3
-- *********************************************************************

-- Changeset db/changelog/initial_schema_table.yaml::init-table-1::limit (generated)
CREATE TABLE NOT_ACL_SID (ID NUMBER(38, 0) NOT NULL, PRINCIPAL NUMBER(1) NOT NULL, SID VARCHAR2(100) NOT NULL, CONSTRAINT NOT_ACL_SID_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-2::limit (generated)
CREATE TABLE NOT_ACL_OBJECT_IDENTITY (ID NUMBER(38, 0) NOT NULL, OBJECT_ID_CLASS NUMBER(38, 0) NOT NULL, OBJECT_ID_IDENTITY NUMBER(38, 0) NOT NULL, PARENT_OBJECT NUMBER(38, 0), OWNER_SID NUMBER(38, 0) NOT NULL, ENTRIES_INHERITING NUMBER(1) NOT NULL, CONSTRAINT NOT_ACL_OBJECT_IDENTITY_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-3::limit (generated)
CREATE TABLE NOT_ACL_ENTRY (ID NUMBER(38, 0) NOT NULL, ACL_OBJECT_IDENTITY NUMBER(38, 0) NOT NULL, ACE_ORDER NUMBER(38, 0) NOT NULL, SID NUMBER(38, 0) NOT NULL, MASK NUMBER(38, 0) NOT NULL, GRANTING NUMBER(1) NOT NULL, AUDIT_SUCCESS NUMBER(1) NOT NULL, AUDIT_FAILURE NUMBER(1) NOT NULL, CONSTRAINT NOT_ACL_ENTRY_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-4::limit (generated)
CREATE TABLE NOT_ACL_CLASS (ID NUMBER(38, 0) NOT NULL, CLASS VARCHAR2(100) NOT NULL, CONSTRAINT NOT_ACL_CLASS_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-5::limit (generated)
CREATE TABLE NOT_APLICACIO (ID NUMBER(38, 0) NOT NULL, CREATEDDATE TIMESTAMP(6), LASTMODIFIEDDATE TIMESTAMP(6), CALLBACK_URL VARCHAR2(256), USUARI_CODI VARCHAR2(64), CREATEDBY_CODI VARCHAR2(64), LASTMODIFIEDBY_CODI VARCHAR2(64), ENTITAT_ID NUMBER(38, 0) NOT NULL, ACTIVA NUMBER(1) DEFAULT 1 NOT NULL, CONSTRAINT NOT_APLICACIO_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-6::limit (generated)
CREATE TABLE NOT_APLICACIO_AUDIT (ID NUMBER(38, 0) NOT NULL, TIPUSOPERACIO VARCHAR2(20) NOT NULL, JOINPOINT VARCHAR2(256), CREATEDBY_CODI VARCHAR2(64), CREATEDDATE TIMESTAMP(6), LASTMODIFIEDBY_CODI VARCHAR2(64), LASTMODIFIEDDATE TIMESTAMP(6), APLICACIO_ID NUMBER(38, 0) NOT NULL, ENTITAT_ID NUMBER(38, 0) NOT NULL, USUARI_CODI VARCHAR2(64), CALLBACK_URL VARCHAR2(256), ACTIVA NUMBER(1), CONSTRAINT NOT_APLICACIO_AUDIT_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-7::limit (generated)
CREATE TABLE NOT_AVIS (ID NUMBER(38, 0) NOT NULL, ASSUMPTE VARCHAR2(256) NOT NULL, MISSATGE VARCHAR2(2048) NOT NULL, DATA_INICI TIMESTAMP(6) NOT NULL, DATA_FINAL TIMESTAMP(6) NOT NULL, ACTIU NUMBER(1) NOT NULL, AVIS_NIVELL VARCHAR2(10) NOT NULL, CREATEDBY_CODI VARCHAR2(64), CREATEDDATE TIMESTAMP(6), LASTMODIFIEDBY_CODI VARCHAR2(64), LASTMODIFIEDDATE TIMESTAMP(6), CONSTRAINT NOT_AVIS_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-8::limit (generated)
CREATE TABLE NOT_COLUMNES (ID NUMBER(38, 0) NOT NULL, CREATEDDATE TIMESTAMP(6), LASTMODIFIEDDATE TIMESTAMP(6), CODI_NOTIB_ENV NUMBER(1), CONCEPTE NUMBER(1), CSV_UUID NUMBER(1), DATA_CADUCITAT NUMBER(1), CREATED_DATE NUMBER(1), DATA_PROGRAMADA NUMBER(1), DATA_REGISTRE NUMBER(1), DESCRIPCIO NUMBER(1), DESTINATARIS NUMBER(1), DIR3_CODI NUMBER(1), ENVIAMENT_TIPUS NUMBER(1), ESTAT NUMBER(1), GRUP_CODI NUMBER(1), LLIBRE_REGISTRE NUMBER(1), NOT_IDENTIFICADOR NUMBER(1), NUM_CERTIFICACIO NUMBER(1), NUMERO_REGISTRE NUMBER(1), PRO_CODI NUMBER(1), TITULAR_EMAIL NUMBER(1), TITULAR_NIF NUMBER(1), TITULAR_NOM_LLINATGE NUMBER(1), USUARI NUMBER(1), CREATEDBY_CODI VARCHAR2(64), LASTMODIFIEDBY_CODI VARCHAR2(64), ENTITAT_ID NUMBER(38, 0), USUARI_CODI VARCHAR2(64), CONSTRAINT NOT_COLUMNES_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-9::limit (generated)
CREATE TABLE NOT_CONFIG (KEY VARCHAR2(256) NOT NULL, VALUE VARCHAR2(2048), DESCRIPTION VARCHAR2(2048), GROUP_CODE VARCHAR2(128) NOT NULL, POSITION NUMBER(3, 0) DEFAULT 0 NOT NULL, JBOSS_PROPERTY NUMBER(1) DEFAULT 0 NOT NULL, TYPE_CODE VARCHAR2(128) DEFAULT 'TEXT', LASTMODIFIEDBY_CODI VARCHAR2(64), LASTMODIFIEDDATE TIMESTAMP(6), CONSTRAINT NOT_CONFIG_PK PRIMARY KEY (KEY));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-10::limit (generated)
CREATE TABLE NOT_CONFIG_GROUP (CODE VARCHAR2(128) NOT NULL, PARENT_CODE VARCHAR2(128), POSITION NUMBER(3, 0) DEFAULT 0 NOT NULL, DESCRIPTION VARCHAR2(512) NOT NULL, CONSTRAINT NOT_CONFIG_GROUP_PK PRIMARY KEY (CODE));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-11::limit (generated)
CREATE TABLE NOT_CONFIG_TYPE (CODE VARCHAR2(128) NOT NULL, VALUE VARCHAR2(2048), CONSTRAINT NOT_CONFIG_TYPE_PK PRIMARY KEY (CODE));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-12::limit (generated)
CREATE TABLE NOT_DOCUMENT (ID NUMBER(38, 0) NOT NULL, CREATEDDATE TIMESTAMP(6), LASTMODIFIEDDATE TIMESTAMP(6), ARXIU_GEST_DOC_ID VARCHAR2(64), ARXIU_NOM VARCHAR2(200), CSV VARCHAR2(256), HASH VARCHAR2(256), NORMALITZAT NUMBER(1), URL VARCHAR2(256), UUID VARCHAR2(256), CREATEDBY_CODI VARCHAR2(64), LASTMODIFIEDBY_CODI VARCHAR2(64), MEDIA VARCHAR2(256), MIDA NUMBER(38, 0), ORIGEN VARCHAR2(20), VALIDESA VARCHAR2(20), TIPUS_DOCUMENTAL VARCHAR2(30), FIRMAT NUMBER(1), CONSTRAINT NOT_DOCUMENT_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-13::limit (generated)
CREATE TABLE NOT_ENTITAT (ID NUMBER(38, 0) NOT NULL, CREATEDDATE TIMESTAMP(6), LASTMODIFIEDDATE TIMESTAMP(6), ACTIVA NUMBER(1) NOT NULL, AMB_ENTREGA_DEH NUMBER(1) NOT NULL, API_KEY VARCHAR2(64) NOT NULL, CODI VARCHAR2(64) NOT NULL, COLOR_FONS VARCHAR2(1024), COLOR_LLETRA VARCHAR2(1024), DESCRIPCIO VARCHAR2(1024), DIR3_CODI VARCHAR2(9) NOT NULL, DIR3_CODI_REG VARCHAR2(9), LOGO_CAP BLOB, LOGO_PEU BLOB, NOM VARCHAR2(256) NOT NULL, TIPUS VARCHAR2(32) NOT NULL, TIPUS_DOC_DEFAULT INTEGER, VERSION NUMBER(38, 0) NOT NULL, CREATEDBY_CODI VARCHAR2(64), LASTMODIFIEDBY_CODI VARCHAR2(64), NOM_OFICINA_VIRTUAL VARCHAR2(255), OFICINA VARCHAR2(255), LLIBRE VARCHAR2(255), LLIBRE_NOM VARCHAR2(255), LLIBRE_ENTITAT NUMBER(1), OFICINA_ENTITAT NUMBER(1) DEFAULT 1, ENTREGA_CIE_ID NUMBER(38, 0), AMB_ENTREGA_CIE NUMBER(1) DEFAULT 0, CONSTRAINT NOT_ENTITAT_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-14::limit (generated)
CREATE TABLE NOT_ENTITAT_AUDIT (ID NUMBER(38, 0) NOT NULL, TIPUSOPERACIO VARCHAR2(20) NOT NULL, JOINPOINT VARCHAR2(256), CREATEDBY_CODI VARCHAR2(64), CREATEDDATE TIMESTAMP(6), LASTMODIFIEDBY_CODI VARCHAR2(64), LASTMODIFIEDDATE TIMESTAMP(6), ENTITAT_ID NUMBER(38, 0) NOT NULL, CODI VARCHAR2(64) NOT NULL, NOM VARCHAR2(256) NOT NULL, TIPUS VARCHAR2(32), DIR3_CODI VARCHAR2(9) NOT NULL, DIR3_CODI_REG VARCHAR2(9), API_KEY VARCHAR2(64), AMB_ENTREGA_DEH NUMBER(1), AMB_ENTREGA_CIE NUMBER(1), DESCRIPCIO VARCHAR2(1024), ACTIVA NUMBER(1), OFICINA VARCHAR2(255), LLIBRE_ENTITAT NUMBER(1), LLIBRE VARCHAR2(255), LLIBRE_NOM VARCHAR2(255), CONSTRAINT NOT_ENTITAT_AUDIT_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-15::limit (generated)
CREATE TABLE NOT_ENTITAT_TIPUS_DOC (ID NUMBER(38, 0) NOT NULL, CREATEDDATE TIMESTAMP(6), LASTMODIFIEDDATE TIMESTAMP(6), TIPUS_DOC INTEGER, CREATEDBY_CODI VARCHAR2(64), LASTMODIFIEDBY_CODI VARCHAR2(64), ENTITAT_ID NUMBER(38, 0), CONSTRAINT NOT_ENTITAT_TIPUS_DOC_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-16::limit (generated)
CREATE TABLE NOT_ENTREGA_CIE (ID NUMBER(38, 0) NOT NULL, OPERADOR_POSTAL_ID NUMBER(38, 0) NOT NULL, CIE_ID NUMBER(38, 0) NOT NULL, CREATEDBY_CODI VARCHAR2(64), CREATEDDATE TIMESTAMP(6), LASTMODIFIEDBY_CODI VARCHAR2(64), LASTMODIFIEDDATE TIMESTAMP(6), CONSTRAINT NOT_ENTREGA_CIE_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-17::limit (generated)
CREATE TABLE NOT_ENTREGA_POSTAL (ID NUMBER(38, 0) NOT NULL, DOM_TIPUS INTEGER, DOM_CON_TIPUS INTEGER, DOM_VIA_TIPUS INTEGER, DOM_VIA_NOM VARCHAR2(50), DOM_NUM_TIPUS INTEGER, DOM_NUM_NUM VARCHAR2(5), DOM_NUM_QUALIF VARCHAR2(3), DOM_NUM_PUNTKM VARCHAR2(10), DOM_APARTAT VARCHAR2(10), DOM_BLOC VARCHAR2(50), DOM_PORTAL VARCHAR2(50), DOM_ESCALA VARCHAR2(50), DOM_PLANTA VARCHAR2(50), DOM_PORTA VARCHAR2(50), DOM_COMPLEM VARCHAR2(250), DOM_POBLACIO VARCHAR2(30), DOM_MUN_CODINE VARCHAR2(6), DOM_MUN_NOM VARCHAR2(64), DOM_CODI_POSTAL VARCHAR2(10), DOM_PRV_CODI VARCHAR2(2), DOM_PRV_NOM VARCHAR2(64), DOM_PAI_CODISO VARCHAR2(3), DOM_PAI_NOM VARCHAR2(64), DOM_LINEA1 VARCHAR2(50), DOM_LINEA2 VARCHAR2(50), DOM_CIE INTEGER, CREATEDBY_CODI VARCHAR2(64), CREATEDDATE TIMESTAMP(6), LASTMODIFIEDBY_CODI VARCHAR2(64), LASTMODIFIEDDATE TIMESTAMP(6), FORMAT_SOBRE VARCHAR2(10), FORMAT_FULLA VARCHAR2(10), CONSTRAINT NOT_DOMICILI_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-18::limit (generated)
CREATE TABLE NOT_FORMATS_FULLA (ID NUMBER(38, 0) NOT NULL, CREATEDDATE TIMESTAMP(6), LASTMODIFIEDDATE TIMESTAMP(6), CODI VARCHAR2(64), CREATEDBY_CODI VARCHAR2(64), LASTMODIFIEDBY_CODI VARCHAR2(64), PAGADOR_CIE_ID NUMBER(38, 0), CONSTRAINT NOT_FORMATS_FULLA_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-19::limit (generated)
CREATE TABLE NOT_FORMATS_SOBRE (ID NUMBER(38, 0) NOT NULL, CREATEDDATE TIMESTAMP(6), LASTMODIFIEDDATE TIMESTAMP(6), CODI VARCHAR2(64), CREATEDBY_CODI VARCHAR2(64), LASTMODIFIEDBY_CODI VARCHAR2(64), PAGADOR_CIE_ID NUMBER(38, 0), CONSTRAINT NOT_FORMATS_SOBRE_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-20::limit (generated)
CREATE TABLE NOT_GRUP (ID NUMBER(38, 0) NOT NULL, CREATEDDATE TIMESTAMP(6), LASTMODIFIEDDATE TIMESTAMP(6), CODI VARCHAR2(64) NOT NULL, NOM VARCHAR2(100), CREATEDBY_CODI VARCHAR2(64), LASTMODIFIEDBY_CODI VARCHAR2(64), ENTITAT NUMBER(38, 0), ORGAN_GESTOR NUMBER(38, 0), CONSTRAINT NOT_GRUP_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-21::limit (generated)
CREATE TABLE NOT_GRUP_AUDIT (ID NUMBER(38, 0) NOT NULL, TIPUSOPERACIO VARCHAR2(20) NOT NULL, JOINPOINT VARCHAR2(256), CREATEDBY_CODI VARCHAR2(64), CREATEDDATE TIMESTAMP(6), LASTMODIFIEDBY_CODI VARCHAR2(64), LASTMODIFIEDDATE TIMESTAMP(6), GRUP_ID NUMBER(38, 0) NOT NULL, CODI VARCHAR2(64) NOT NULL, NOM VARCHAR2(100), ENTITAT_ID NUMBER(38, 0), ORGAN VARCHAR2(64), CONSTRAINT NOT_GRUP_AUDIT_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-22::limit (generated)
CREATE TABLE NOT_HIST_ENVIAMENTS (ID NUMBER(38, 0) NOT NULL, ENTITAT_ID NUMBER(38, 0) NOT NULL, ORGAN_ID NUMBER(38, 0), TIPUS INTEGER NOT NULL, DATA TIMESTAMP(6) NOT NULL, PROCEDIMENT_ID NUMBER(38, 0), COMU NUMBER(1), GRUP_CODI NUMBER(38, 0), USUARI_CODI VARCHAR2(64) NOT NULL, ESTAT INTEGER NOT NULL, ESTAT_NOT INTEGER NOT NULL, ENV_TIPUS INTEGER NOT NULL, N_TOTAL NUMBER(38, 0) NOT NULL, N_CORRECTES NUMBER(38, 0) NOT NULL, N_AMB_ERROR NUMBER(38, 0) NOT NULL, N_ORIGEN_API NUMBER(38, 0) NOT NULL, N_ORIGEN_WEB NUMBER(38, 0) NOT NULL, N_DESTI_ADM NUMBER(38, 0) NOT NULL, N_DESTI_CIUTADA NUMBER(38, 0) NOT NULL, CREATEDBY_CODI VARCHAR2(64), CREATEDDATE TIMESTAMP(6), LASTMODIFIEDBY_CODI VARCHAR2(64), LASTMODIFIEDDATE TIMESTAMP(6), VERSION NUMBER(38, 0) NOT NULL, CONSTRAINT NOT_HIST_ENVI_OID_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-23::limit (generated)
CREATE TABLE NOT_HIST_NOTIF (ID NUMBER(38, 0) NOT NULL, ENTITAT_ID NUMBER(38, 0) NOT NULL, ORGAN_ID NUMBER(38, 0), TIPUS INTEGER NOT NULL, DATA TIMESTAMP(6) NOT NULL, PROCEDIMENT_ID NUMBER(38, 0), COMU NUMBER(1), GRUP_CODI NUMBER(38, 0), USUARI_CODI VARCHAR2(64) NOT NULL, ESTAT INTEGER NOT NULL, N_NOT_TOTAL NUMBER(38, 0) NOT NULL, N_NOT_CORRECTES NUMBER(38, 0) NOT NULL, N_NOT_AMB_ERROR NUMBER(38, 0) NOT NULL, N_NOT_ORIGEN_API NUMBER(38, 0) NOT NULL, N_NOT_ORIGEN_WEB NUMBER(38, 0) NOT NULL, N_NOT_DESTI_ADM NUMBER(38, 0) NOT NULL, N_NOT_DESTI_CIUTADA NUMBER(38, 0) NOT NULL, N_COM_TOTAL NUMBER(38, 0) NOT NULL, N_COM_CORRECTES NUMBER(38, 0) NOT NULL, N_COM_AMB_ERROR NUMBER(38, 0) NOT NULL, N_COM_ORIGEN_API NUMBER(38, 0) NOT NULL, N_COM_ORIGEN_WEB NUMBER(38, 0) NOT NULL, N_COM_DESTI_ADM NUMBER(38, 0) NOT NULL, N_COM_DESTI_CIUTADA NUMBER(38, 0) NOT NULL, CREATEDBY_CODI VARCHAR2(64), CREATEDDATE TIMESTAMP(6), LASTMODIFIEDBY_CODI VARCHAR2(64), LASTMODIFIEDDATE TIMESTAMP(6), VERSION NUMBER(38, 0) NOT NULL, CONSTRAINT NOT_HIST_NOTIF_OID_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-30::limit (generated)
CREATE TABLE NOT_HIST_ORGAN (ID NUMBER(38, 0) NOT NULL, ENTITAT_ID NUMBER(38, 0) NOT NULL, ORGAN_ID NUMBER(38, 0), TIPUS INTEGER NOT NULL, DATA TIMESTAMP(6) NOT NULL, CODI_DIR3 VARCHAR2(64) NOT NULL, NOM VARCHAR2(64) NOT NULL, N_PROCEDIMENTS NUMBER(38, 0) NOT NULL, N_GRUPS NUMBER(38, 0) NOT NULL, N_PERM_CONSULTA NUMBER(38, 0) NOT NULL, N_PERM_NOTIFICACIO NUMBER(38, 0) NOT NULL, N_PERM_GESTIO NUMBER(38, 0) NOT NULL, N_PERM_PROCESSAR NUMBER(38, 0) NOT NULL, N_PERM_ADMINISTRAR NUMBER(38, 0) NOT NULL, CREATEDBY_CODI VARCHAR2(64), CREATEDDATE TIMESTAMP(6), LASTMODIFIEDBY_CODI VARCHAR2(64), LASTMODIFIEDDATE TIMESTAMP(6), VERSION NUMBER(38, 0) NOT NULL, CONSTRAINT NOT_HIST_ORGAN_OID_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-31::limit (generated)
CREATE TABLE NOT_HIST_PROCEDIMENT (ID NUMBER(38, 0) NOT NULL, ENTITAT_ID NUMBER(38, 0) NOT NULL, ORGAN_ID NUMBER(38, 0), TIPUS INTEGER NOT NULL, DATA TIMESTAMP(6) NOT NULL, PROCEDIMENT_ID NUMBER(38, 0) NOT NULL, COMU NUMBER(1) NOT NULL, CODI_SIA VARCHAR2(64) NOT NULL, NOM VARCHAR2(64) NOT NULL, N_GRUPS NUMBER(38, 0) NOT NULL, N_PERM_CONSULTA NUMBER(38, 0) NOT NULL, N_PERM_NOTIFICACIO NUMBER(38, 0) NOT NULL, N_PERM_GESTIO NUMBER(38, 0) NOT NULL, N_PERM_PROCESSAR NUMBER(38, 0) NOT NULL, CREATEDBY_CODI VARCHAR2(64), CREATEDDATE TIMESTAMP(6), LASTMODIFIEDBY_CODI VARCHAR2(64), LASTMODIFIEDDATE TIMESTAMP(6), VERSION NUMBER(38, 0) NOT NULL, CONSTRAINT NOT_HIST_PROC_OID_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-32::limit (generated)
CREATE TABLE NOT_NOTIFICACIO (ID NUMBER(38, 0) NOT NULL, CREATEDDATE TIMESTAMP(6), LASTMODIFIEDDATE TIMESTAMP(6), CADUCITAT date, COM_TIPUS INTEGER NOT NULL, CONCEPTE VARCHAR2(240) NOT NULL, DESCRIPCIO VARCHAR2(1000), EMISOR_DIR3CODI VARCHAR2(9) NOT NULL, ENV_DATA_PROG date, ENV_TIPUS INTEGER NOT NULL, CALLBACK_ERROR NUMBER(1), ESTAT INTEGER NOT NULL, ESTAT_DATE TIMESTAMP(6), GRUP_CODI VARCHAR2(64), MOTIU VARCHAR2(255), NOT_ENV_DATA TIMESTAMP(6), NOT_ENV_INTENT INTEGER, NOT_ERROR_TIPUS INTEGER, REGISTRE_NUM_EXPEDIENT VARCHAR2(80), PROC_CODI_NOTIB VARCHAR2(9), REGISTRE_DATA date, REGISTRE_ENV_INTENT INTEGER, REGISTRE_NUMERO INTEGER, REGISTRE_NUMERO_FORMATAT VARCHAR2(200), RETARD_POSTAL INTEGER, TIPUS_USUARI INTEGER, USUARI_CODI VARCHAR2(64) NOT NULL, CREATEDBY_CODI VARCHAR2(64), LASTMODIFIEDBY_CODI VARCHAR2(64), DOCUMENT_ID NUMBER(38, 0) NOT NULL, ENTITAT_ID NUMBER(38, 0) NOT NULL, PAGADOR_CIE_ID NUMBER(38, 0), PAGADOR_POSTAL_ID NUMBER(38, 0), PROCEDIMENT_ID NUMBER(38, 0), ORGAN_GESTOR VARCHAR2(64), PROCEDIMENT_ORGAN_ID NUMBER(38, 0), NOT_ENV_DATA_NOTIFICA TIMESTAMP(6), IDIOMA INTEGER, DOCUMENT2_ID NUMBER(38, 0), DOCUMENT3_ID NUMBER(38, 0), DOCUMENT4_ID NUMBER(38, 0), DOCUMENT5_ID NUMBER(38, 0), REGISTRE_OFICINA_NOM VARCHAR2(255), REGISTRE_LLIBRE_NOM VARCHAR2(255), IS_ERROR_LAST_EVENT NUMBER(1) DEFAULT 0, NOTIFICACIO_MASSIVA_ID NUMBER(38, 0), CONSTRAINT NOT_NOTIFICACIO_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-33::limit (generated)
CREATE TABLE NOT_NOTIFICACIO_AUDIT (ID NUMBER(38, 0) NOT NULL, TIPUSOPERACIO VARCHAR2(20) NOT NULL, JOINPOINT VARCHAR2(256), CREATEDBY_CODI VARCHAR2(64), CREATEDDATE TIMESTAMP(6), LASTMODIFIEDBY_CODI VARCHAR2(64), LASTMODIFIEDDATE TIMESTAMP(6), NOTIFICACIO_ID NUMBER(38, 0) NOT NULL, SINCRON VARCHAR2(20), TIPUS_USUARI VARCHAR2(20), USUARI VARCHAR2(64), EMISOR VARCHAR2(9) NOT NULL, TIPUS VARCHAR2(20) NOT NULL, ENTITAT_ID NUMBER(38, 0), ORGAN VARCHAR2(64), PROCEDIMENT VARCHAR2(64), GRUP VARCHAR2(64), CONCEPTE VARCHAR2(255), DESCRIPCIO VARCHAR2(1000), NUM_EXPEDIENT VARCHAR2(80), ENV_DATA_PROG date, RETARD_POSTAL INTEGER, CADUCITAT date, DOCUMENT_ID NUMBER(38, 0) NOT NULL, ESTAT VARCHAR2(20) NOT NULL, ESTAT_DATE TIMESTAMP(6), MOTIU VARCHAR2(255), PAGADOR_POSTAL_ID NUMBER(38, 0), PAGADOR_CIE_ID NUMBER(38, 0), REGISTRE_ENV_INTENT INTEGER, REGISTRE_NUMERO INTEGER, REGISTRE_NUMERO_FORMATAT VARCHAR2(200), REGISTRE_DATA date, NOT_ENV_DATA TIMESTAMP(6), NOT_ENV_INTENT INTEGER, NOT_ERROR_TIPUS VARCHAR2(30), CALLBACK_ERROR NUMBER(1), EVENT_ERROR NUMBER(38, 0), CONSTRAINT NOT_NOTIFICACIO_AUDIT_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-34::limit (generated)
CREATE TABLE NOT_NOTIFICACIO_ENV (ID NUMBER(38, 0) NOT NULL, CREATEDDATE TIMESTAMP(6), LASTMODIFIEDDATE TIMESTAMP(6), DEH_NIF VARCHAR2(9), DEH_OBLIGAT NUMBER(1), DEH_PROC_CODI VARCHAR2(64), FORMAT_FULLA VARCHAR2(10), FORMAT_SOBRE VARCHAR2(10), NOTIFICA_ARR_DIR3DESC VARCHAR2(100), NOTIFICA_ARR_DIR3CODI VARCHAR2(9), NOTIFICA_ARR_DIR3NIF VARCHAR2(9), NOTIFICA_CER_ARXIUID VARCHAR2(50), NOTIFICA_CER_ARXTIP INTEGER, NOTIFICA_CER_CSV VARCHAR2(50), NOTIFICA_CER_DATA TIMESTAMP(6), NOTIFICA_CER_HASH VARCHAR2(50), NOTIFICA_CER_METAS VARCHAR2(255), NOTIFICA_CER_MIME VARCHAR2(20), NOTIFICA_CER_NUMSEG VARCHAR2(50), NOTIFICA_CER_ORIGEN VARCHAR2(20), NOTIFICA_CER_TAMANY INTEGER, NOTIFICA_CER_TIPUS INTEGER, NOTIFICA_DATCAD TIMESTAMP(6), NOTIFICA_DATCRE TIMESTAMP(6), NOTIFICA_DATDISP TIMESTAMP(6), NOTIFICA_DATAT_ERRDES VARCHAR2(255), NOTIFICA_DATAT_NUMSEG VARCHAR2(50), NOTIFICA_DATAT_ORIGEN VARCHAR2(20), NOTIFICA_DATAT_RECNIF VARCHAR2(9), NOTIFICA_DATAT_RECNOM VARCHAR2(100), NOTIFICA_EMI_DIR3DESC VARCHAR2(100), NOTIFICA_EMI_DIR3CODI VARCHAR2(9), NOTIFICA_EMI_DIR3NIF VARCHAR2(9), NOTIFICA_ERROR NUMBER(1) NOT NULL, NOTIFICA_ESTAT INTEGER NOT NULL, NOTIFICA_ESTAT_DATA TIMESTAMP(6), NOTIFICA_ESTAT_DATAACT TIMESTAMP(6), NOTIFICA_ESTAT_DESC VARCHAR2(255), NOTIFICA_ESTAT_FINAL NUMBER(1), NOTIFICA_ID VARCHAR2(20), NOTIFICA_INTENT_DATA TIMESTAMP(6), NOTIFICA_INTENT_NUM INTEGER, NOTIFICA_REF VARCHAR2(20), NOTIFICACIO_ID NUMBER(38, 0), REGISTRE_DATA TIMESTAMP(6), ESTAT_REGISTRE INTEGER, REGISTRE_ESTAT_FINAL NUMBER(1), REGISTRE_NUMERO_FORMATAT VARCHAR2(50), SERVEI_TIPUS INTEGER, SIR_CON_DATA TIMESTAMP(6), SIR_CON_INTENT INTEGER, SIR_REC_DATA TIMESTAMP(6), SIR_REG_DESTI_DATA TIMESTAMP(6), CREATEDBY_CODI VARCHAR2(64), LASTMODIFIEDBY_CODI VARCHAR2(64), NOTIFICA_ERROR_EVENT_ID NUMBER(38, 0), TITULAR_ID NUMBER(38, 0) NOT NULL, DEH_CERT_INTENT_NUM INTEGER DEFAULT 0, DEH_CERT_INTENT_DATA TIMESTAMP(6), CIE_CERT_INTENT_NUM INTEGER DEFAULT 0, CIE_CERT_INTENT_DATA TIMESTAMP(6), ENTREGA_POSTAL_ID NUMBER(38, 0), CONSTRAINT NOT_NOTIFICACIO_ENV_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-35::limit (generated)
CREATE TABLE NOT_NOTIFICACIO_ENV_AUDIT (ID NUMBER(38, 0) NOT NULL, TIPUSOPERACIO VARCHAR2(20) NOT NULL, JOINPOINT VARCHAR2(256), CREATEDBY_CODI VARCHAR2(64), CREATEDDATE TIMESTAMP(6), LASTMODIFIEDBY_CODI VARCHAR2(64), LASTMODIFIEDDATE TIMESTAMP(6), ENVIAMENT_ID NUMBER(38, 0) NOT NULL, NOTIFICACIO_ID NUMBER(38, 0) NOT NULL, TITULAR_ID NUMBER(38, 0), DESTINATARIS_ID VARCHAR2(200), DOMICILI_TIPUS VARCHAR2(20), DOMICILI VARCHAR2(500), SERVEI_TIPUS VARCHAR2(20), CIE INTEGER, FORMAT_SOBRE VARCHAR2(10), FORMAT_FULLA VARCHAR2(10), DEH_OBLIGAT NUMBER(1), DEH_NIF VARCHAR2(9), NOTIFICA_REF VARCHAR2(20), NOTIFICA_ID VARCHAR2(20), NOTIFICA_DATCRE TIMESTAMP(6), NOTIFICA_DATDISP TIMESTAMP(6), NOTIFICA_DATCAD TIMESTAMP(6), NOTIFICA_EMI_DIR3CODI VARCHAR2(9), NOTIFICA_ARR_DIR3CODI VARCHAR2(9), NOTIFICA_ESTAT INTEGER, NOTIFICA_ESTAT_DATA TIMESTAMP(6), NOTIFICA_ESTAT_FINAL NUMBER(1), NOTIFICA_DATAT_ORIGEN VARCHAR2(20), NOTIFICA_DATAT_RECNIF VARCHAR2(9), NOTIFICA_DATAT_NUMSEG VARCHAR2(50), NOTIFICA_CER_DATA TIMESTAMP(6), NOTIFICA_CER_ARXIUID VARCHAR2(50), NOTIFICA_CER_ORIGEN VARCHAR2(20), NOTIFICA_CER_TIPUS VARCHAR2(20), NOTIFICA_CER_ARXTIP VARCHAR2(20), NOTIFICA_CER_NUMSEG VARCHAR2(50), REGISTRE_NUMERO_FORMATAT VARCHAR2(50), REGISTRE_DATA TIMESTAMP(6), REGISTRE_ESTAT VARCHAR2(20), REGISTRE_ESTAT_FINAL NUMBER(1), SIR_CON_DATA TIMESTAMP(6), SIR_REC_DATA TIMESTAMP(6), SIR_REG_DESTI_DATA TIMESTAMP(6), NOTIFICA_ERROR_EVENT_ID NUMBER(38, 0), NOTIFICA_ERROR NUMBER(1), NOTIFICA_DATAT_ERRDES VARCHAR2(255), CONSTRAINT NOT_NOTIFICACIO_ENV_AUDIT_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-36::limit (generated)
CREATE TABLE NOT_NOTIFICACIO_ENV_TABLE (ID NUMBER(38, 0) NOT NULL, NOTIFICACIO_ID NUMBER(38, 0) NOT NULL, ENTITAT_ID NUMBER(38, 0) NOT NULL, DESTINATARIS VARCHAR2(4000) DEFAULT '', TIPUS_ENVIAMENT INTEGER NOT NULL, TITULAR_NIF VARCHAR2(9), TITULAR_NOM VARCHAR2(256), TITULAR_EMAIL VARCHAR2(160), TITULAR_LLINATGE1 VARCHAR2(40), TITULAR_LLINATGE2 VARCHAR2(40), TITULAR_RAOSOCIAL VARCHAR2(100), DATA_PROGRAMADA date, PROCEDIMENT_CODI_NOTIB VARCHAR2(9), GRUP_CODI VARCHAR2(64), EMISOR_DIR3 VARCHAR2(9), USUARI_CODI VARCHAR2(64), NOT_ORGAN_CODI VARCHAR2(64), CONCEPTE VARCHAR2(240), DESCRIPCIO VARCHAR2(1000), LLIBRE VARCHAR2(255), NOT_ESTAT INTEGER NOT NULL, CSV_UUID VARCHAR2(256), HAS_ERRORS NUMBER(1) DEFAULT 0 NOT NULL, PROCEDIMENT_IS_COMU NUMBER(1) DEFAULT 0, PROCEDIMENT_PROCORGAN_ID NUMBER(38, 0), REGISTRE_NUMERO INTEGER, REGISTRE_DATA date, REGISTRE_ENVIAMENT_INTENT INTEGER, NOTIFICA_DATA_CADUCITAT TIMESTAMP(6), NOTIFICA_IDENTIFICADOR VARCHAR2(20), NOTIFICA_CERT_NUM_SEGUIMENT VARCHAR2(50), NOTIFICA_ESTAT INTEGER NOT NULL, NOTIFICA_REF VARCHAR2(20), CREATEDDATE TIMESTAMP(6), CREATEDBY_CODI VARCHAR2(64), LASTMODIFIEDBY_CODI VARCHAR2(64), LASTMODIFIEDDATE TIMESTAMP(6), ORGAN_ESTAT INTEGER DEFAULT 0 NOT NULL, PROCEDIMENT_REQUIRE_PERMISSION NUMBER(1) DEFAULT 0 NOT NULL, CONSTRAINT NOT_NOTIFICACIO_ENV_TABLE_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-37::limit (generated)
CREATE TABLE NOT_NOTIFICACIO_EVENT (ID NUMBER(38, 0) NOT NULL, CREATEDDATE TIMESTAMP(6), LASTMODIFIEDDATE TIMESTAMP(6), CALLBACK_DATA TIMESTAMP(6), CALLBACK_ERROR_DESC VARCHAR2(2048), CALLBACK_ESTAT VARCHAR2(10), CALLBACK_INTENTS INTEGER, DATA TIMESTAMP(6) NOT NULL, DESCRIPCIO VARCHAR2(256), ERROR NUMBER(1) NOT NULL, ERROR_DESC VARCHAR2(2048), NOTIFICACIO_ID NUMBER(38, 0), TIPUS INTEGER NOT NULL, CREATEDBY_CODI VARCHAR2(64), LASTMODIFIEDBY_CODI VARCHAR2(64), NOTIFICACIO_ENV_ID NUMBER(38, 0), NOTIFICA_ERROR_TIPUS INTEGER, CONSTRAINT NOT_NOTIFICACIO_EVENT_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-38::limit (generated)
CREATE TABLE NOT_NOTIFICACIO_MASSIVA (ID NUMBER(38, 0) NOT NULL, ENTITAT_ID NUMBER(38, 0) NOT NULL, CSV_GESDOC_ID VARCHAR2(64) NOT NULL, ZIP_GESDOC_ID VARCHAR2(64), CSV_FILENAME VARCHAR2(200) NOT NULL, ZIP_FILENAME VARCHAR2(200), CADUCITAT TIMESTAMP(6) NOT NULL, EMAIL VARCHAR2(64), PAGADOR_POSTAL_ID NUMBER(38, 0), RESUM_GESDOC_ID VARCHAR2(64), ERRORS_GESDOC_ID VARCHAR2(64), PROGRESS NUMBER(3, 0) DEFAULT 0 NOT NULL, CREATEDBY_CODI VARCHAR2(64), CREATEDDATE TIMESTAMP(6), LASTMODIFIEDBY_CODI VARCHAR2(64), LASTMODIFIEDDATE TIMESTAMP(6), CONSTRAINT NOT_NOTIFICACIO_MASSIVA_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-39::limit (generated)
CREATE TABLE NOT_NOTIFICACIO_TABLE (ID NUMBER(38, 0) NOT NULL, ENTITAT_ID NUMBER(38, 0) NOT NULL, ENTITAT_NOM VARCHAR2(256), PROC_CODI_NOTIB VARCHAR2(9), PROCEDIMENT_ORGAN_ID NUMBER(38, 0), GRUP_CODI VARCHAR2(64), USUARI_CODI VARCHAR2(64), TIPUS_USUARI INTEGER, ERROR_LAST_CALLBACK NUMBER(1) DEFAULT 0 NOT NULL, ERROR_LAST_EVENT NUMBER(1) DEFAULT 0 NOT NULL, REGISTRE_ENV_INTENT INTEGER, REGISTRE_NUM_EXPEDIENT VARCHAR2(80), NOTIFICA_ERROR_DATE date, NOTIFICA_ERROR_DESCRIPCIO VARCHAR2(2048), ENV_TIPUS INTEGER NOT NULL, CONCEPTE VARCHAR2(255) NOT NULL, ESTAT INTEGER NOT NULL, ESTAT_DATE TIMESTAMP(6), PROCEDIMENT_CODI VARCHAR2(64), PROCEDIMENT_NOM VARCHAR2(256), PROCEDIMENT_IS_COMU NUMBER(1) DEFAULT 0 NOT NULL, ORGAN_CODI VARCHAR2(64), ORGAN_NOM VARCHAR2(1000), CREATEDDATE TIMESTAMP(6), CREATEDBY_CODI VARCHAR2(64), LASTMODIFIEDBY_CODI VARCHAR2(64), LASTMODIFIEDDATE TIMESTAMP(6), ORGAN_ESTAT INTEGER DEFAULT 0 NOT NULL, NOTIFICACIO_MASSIVA_ID NUMBER(38, 0), PROCEDIMENT_REQUIRE_PERMISSION NUMBER(1) DEFAULT 0 NOT NULL, CONSTRAINT NOT_NOTIFICACIO_TABLE_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-40::limit (generated)
CREATE TABLE NOT_ORGAN_GESTOR (ID NUMBER(38, 0) NOT NULL, CODI VARCHAR2(64) NOT NULL, ENTITAT NUMBER(38, 0), NOM VARCHAR2(1000), LLIBRE VARCHAR2(255), LLIBRE_NOM VARCHAR2(255), OFICINA VARCHAR2(255), OFICINA_NOM VARCHAR2(255), ESTAT INTEGER DEFAULT 0 NOT NULL, ENTREGA_CIE_ID NUMBER(38, 0), CONSTRAINT NOT_ORGAN_GESTOR_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-41::limit (generated)
CREATE TABLE NOT_PAGADOR_CIE (ID NUMBER(38, 0) NOT NULL, CREATEDDATE TIMESTAMP(6), LASTMODIFIEDDATE TIMESTAMP(6), CONTRACTE_DATA_VIG date, DIR3_CODI VARCHAR2(9), CREATEDBY_CODI VARCHAR2(64), LASTMODIFIEDBY_CODI VARCHAR2(64), ENTITAT NUMBER(38, 0), ORGAN_GESTOR NUMBER(38, 0), NOM VARCHAR2(256) NOT NULL, CONSTRAINT NOT_PAGADOR_CIE_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-42::limit (generated)
CREATE TABLE NOT_PAGADOR_POSTAL (ID NUMBER(38, 0) NOT NULL, CREATEDDATE TIMESTAMP(6), LASTMODIFIEDDATE TIMESTAMP(6), CONTRACTE_DATA_VIG date, CONTRACTE_NUM VARCHAR2(20), DIR3_CODI VARCHAR2(9), FACTURACIO_CODI_CLIENT VARCHAR2(20), CREATEDBY_CODI VARCHAR2(64), LASTMODIFIEDBY_CODI VARCHAR2(64), ENTITAT NUMBER(38, 0), ORGAN_GESTOR NUMBER(38, 0), NOM VARCHAR2(256) NOT NULL, CONSTRAINT NOT_PAGADOR_POSTAL_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-43::limit (generated)
CREATE TABLE NOT_PERSONA (ID NUMBER(38, 0) NOT NULL, CREATEDDATE TIMESTAMP(6), LASTMODIFIEDDATE TIMESTAMP(6), COD_ENTITAT_DESTI VARCHAR2(9), EMAIL VARCHAR2(160), INCAPACITAT NUMBER(1), INTERESSATTIPUS VARCHAR2(255) NOT NULL, LLINATGE1 VARCHAR2(40), LLINATGE2 VARCHAR2(40), NIF VARCHAR2(9), NOM VARCHAR2(255), RAO_SOCIAL VARCHAR2(100), TELEFON VARCHAR2(16), CREATEDBY_CODI VARCHAR2(64), LASTMODIFIEDBY_CODI VARCHAR2(64), NOTIFICACIO_ENV_ID NUMBER(38, 0), CONSTRAINT NOT_PERSONA_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-44::limit (generated)
CREATE TABLE NOT_PROCEDIMENT (ID NUMBER(38, 0) NOT NULL, CREATEDDATE TIMESTAMP(6), LASTMODIFIEDDATE TIMESTAMP(6), AGRUPAR NUMBER(1) NOT NULL, CADUCITAT INTEGER, CODI VARCHAR2(64) NOT NULL, CODIASSUMPTE VARCHAR2(255), CODIASSUMPTE_NOM VARCHAR2(255), NOM VARCHAR2(256) NOT NULL, RETARD INTEGER, TIPUSASSUMPTE VARCHAR2(255), TIPUSASSUMPTE_NOM VARCHAR2(255), CREATEDBY_CODI VARCHAR2(64), LASTMODIFIEDBY_CODI VARCHAR2(64), ENTITAT NUMBER(38, 0), ORGAN_GESTOR VARCHAR2(64), COMU NUMBER(1) DEFAULT 0 NOT NULL, ULTIMA_ACT date, DIRECT_PERMISSION_REQUIRED NUMBER(1) DEFAULT 0 NOT NULL, ENTREGA_CIE_ID NUMBER(38, 0), PAGADORPOSTAL NUMBER(38, 0), PAGADORCIE NUMBER(38, 0), CONSTRAINT NOT_PROCEDIMENT_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-45::limit (generated)
CREATE TABLE NOT_PROCEDIMENT_AUDIT (ID NUMBER(38, 0) NOT NULL, TIPUSOPERACIO VARCHAR2(20) NOT NULL, JOINPOINT VARCHAR2(256), CREATEDBY_CODI VARCHAR2(64), CREATEDDATE TIMESTAMP(6), LASTMODIFIEDBY_CODI VARCHAR2(64), LASTMODIFIEDDATE TIMESTAMP(6), PROCEDIMENT_ID NUMBER(38, 0) NOT NULL, ENTITAT_ID NUMBER(38, 0), ORGAN VARCHAR2(64), CODI VARCHAR2(64) NOT NULL, NOM VARCHAR2(256), RETARD INTEGER, CADUCITAT INTEGER, AGRUPAR NUMBER(1), COMU NUMBER(1), PAGADORPOSTAL_ID NUMBER(38, 0), PAGADORCIE_ID NUMBER(38, 0), CONSTRAINT NOT_PROCEDIMENT_AUDIT_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-46::limit (generated)
CREATE TABLE NOT_PRO_GRUP (ID NUMBER(38, 0) NOT NULL, CREATEDDATE TIMESTAMP(6), LASTMODIFIEDDATE TIMESTAMP(6), CREATEDBY_CODI VARCHAR2(64), LASTMODIFIEDBY_CODI VARCHAR2(64), GRUP NUMBER(38, 0), PROCEDIMENT NUMBER(38, 0), CONSTRAINT NOT_PRO_GRUP_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-47::limit (generated)
CREATE TABLE NOT_PRO_GRUP_AUDIT (ID NUMBER(38, 0) NOT NULL, TIPUSOPERACIO VARCHAR2(20) NOT NULL, JOINPOINT VARCHAR2(256), CREATEDBY_CODI VARCHAR2(64), CREATEDDATE TIMESTAMP(6), LASTMODIFIEDBY_CODI VARCHAR2(64), LASTMODIFIEDDATE TIMESTAMP(6), PROGRUP_ID NUMBER(38, 0) NOT NULL, PROCEDIMENT VARCHAR2(64) NOT NULL, GRUP VARCHAR2(64) NOT NULL, CONSTRAINT NOT_PRO_GRUP_AUDIT_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-48::limit (generated)
CREATE TABLE NOT_PRO_ORGAN (ID NUMBER(38, 0) NOT NULL, PROCEDIMENT_ID NUMBER(38, 0), ORGANGESTOR_ID NUMBER(38, 0), CREATEDDATE TIMESTAMP(6), LASTMODIFIEDDATE TIMESTAMP(6), CREATEDBY_CODI VARCHAR2(64), LASTMODIFIEDBY_CODI VARCHAR2(64), CONSTRAINT NOT_PRO_ORGAN_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-49::limit (generated)
CREATE TABLE NOT_USUARI (CODI VARCHAR2(64) NOT NULL, EMAIL VARCHAR2(200), IDIOMA VARCHAR2(2), LLINATGES VARCHAR2(100), NOM VARCHAR2(100), NOM_SENCER VARCHAR2(200), REBRE_EMAILS NUMBER(1), VERSION NUMBER(38, 0) NOT NULL, ULTIM_ROL VARCHAR2(40), ULTIMA_ENTITAT NUMBER(38, 0), REBRE_EMAILS_CREATS NUMBER(1) DEFAULT 0 NOT NULL, CONSTRAINT NOT_USUARI_PK PRIMARY KEY (CODI));

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-1::limit (generated)
ALTER TABLE NOT_ORGAN_GESTOR ADD CONSTRAINT NOT_ORGAN_GESTOR_UK UNIQUE (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-2::limit (generated)
ALTER TABLE NOT_ENTITAT ADD CONSTRAINT NOT_ENTITAT_CODI_UK UNIQUE (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-3::limit (generated)
ALTER TABLE NOT_APLICACIO ADD CONSTRAINT NOT_APLICACIO_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-4::limit (generated)
ALTER TABLE NOT_APLICACIO ADD CONSTRAINT NOT_APLICACIO_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-5::limit (generated)
ALTER TABLE NOT_APLICACIO ADD CONSTRAINT NOT_APLICACIO_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-6::limit (generated)
ALTER TABLE NOT_COLUMNES ADD CONSTRAINT NOT_COLUMNES_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-7::limit (generated)
ALTER TABLE NOT_COLUMNES ADD CONSTRAINT NOT_COLUMNES_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-8::limit (generated)
ALTER TABLE NOT_COLUMNES ADD CONSTRAINT NOT_COLUMNES_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-9::limit (generated)
ALTER TABLE NOT_COLUMNES ADD CONSTRAINT NOT_COLUMNES_USUARI_FK FOREIGN KEY (USUARI_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-10::limit (generated)
ALTER TABLE NOT_CONFIG ADD CONSTRAINT NOT_CONFIG_GROUP_FK FOREIGN KEY (GROUP_CODE) REFERENCES NOT_CONFIG_GROUP (CODE);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-11::limit (generated)
ALTER TABLE NOT_NOTIFICACIO ADD CONSTRAINT NOT_DOCUMENT_NOTIFICACIO_FK FOREIGN KEY (DOCUMENT_ID) REFERENCES NOT_DOCUMENT (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-12::limit (generated)
ALTER TABLE NOT_DOCUMENT ADD CONSTRAINT NOT_DOCUMENT_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-13::limit (generated)
ALTER TABLE NOT_DOCUMENT ADD CONSTRAINT NOT_DOCUMENT_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-14::limit (generated)
ALTER TABLE NOT_ENTITAT ADD CONSTRAINT NOT_ENTITAT_ENTREGA_CIE_FK FOREIGN KEY (ENTREGA_CIE_ID) REFERENCES NOT_ENTREGA_CIE (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-15::limit (generated)
ALTER TABLE NOT_PROCEDIMENT ADD CONSTRAINT NOT_ENTITAT_FK FOREIGN KEY (ENTITAT) REFERENCES NOT_ENTITAT (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-16::limit (generated)
ALTER TABLE NOT_GRUP ADD CONSTRAINT NOT_ENTITAT_GRUP_FK FOREIGN KEY (ENTITAT) REFERENCES NOT_ENTITAT (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-17::limit (generated)
ALTER TABLE NOT_NOTIFICACIO ADD CONSTRAINT NOT_ENTITAT_NOTIFICACIO_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-18::limit (generated)
ALTER TABLE NOT_ENTITAT_TIPUS_DOC ADD CONSTRAINT NOT_ENTITAT_TIPUS_DOC_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-19::limit (generated)
ALTER TABLE NOT_ENTITAT ADD CONSTRAINT NOT_ENTITAT_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-20::limit (generated)
ALTER TABLE NOT_ENTITAT ADD CONSTRAINT NOT_ENTITAT_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-21::limit (generated)
ALTER TABLE NOT_ENTREGA_CIE ADD CONSTRAINT NOT_ENTREGA_CIE_CIE_FK FOREIGN KEY (CIE_ID) REFERENCES NOT_PAGADOR_CIE (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-22::limit (generated)
ALTER TABLE NOT_ENTREGA_CIE ADD CONSTRAINT NOT_ENTREGA_CIE_OPERADOR_FK FOREIGN KEY (OPERADOR_POSTAL_ID) REFERENCES NOT_PAGADOR_POSTAL (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-23::limit (generated)
ALTER TABLE NOT_ENTITAT_TIPUS_DOC ADD CONSTRAINT NOT_ENTTIPDOC_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-24::limit (generated)
ALTER TABLE NOT_ENTITAT_TIPUS_DOC ADD CONSTRAINT NOT_ENTTIPDOC_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-25::limit (generated)
ALTER TABLE NOT_FORMATS_FULLA ADD CONSTRAINT NOT_FORMATFULLA_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-26::limit (generated)
ALTER TABLE NOT_FORMATS_SOBRE ADD CONSTRAINT NOT_FORMATSOBRE_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-27::limit (generated)
ALTER TABLE NOT_FORMATS_FULLA ADD CONSTRAINT NOT_FORMATS_FULLA_FK FOREIGN KEY (PAGADOR_CIE_ID) REFERENCES NOT_PAGADOR_CIE (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-28::limit (generated)
ALTER TABLE NOT_FORMATS_SOBRE ADD CONSTRAINT NOT_FORMATS_SOBRE_FK FOREIGN KEY (PAGADOR_CIE_ID) REFERENCES NOT_PAGADOR_CIE (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-29::limit (generated)
ALTER TABLE NOT_GRUP ADD CONSTRAINT NOT_GRUP_ORGAN_FK FOREIGN KEY (ORGAN_GESTOR) REFERENCES NOT_ORGAN_GESTOR (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-30::limit (generated)
ALTER TABLE NOT_PRO_GRUP ADD CONSTRAINT NOT_GRUP_PRO_FK FOREIGN KEY (GRUP) REFERENCES NOT_GRUP (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-31::limit (generated)
ALTER TABLE NOT_GRUP ADD CONSTRAINT NOT_GRUP_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-32::limit (generated)
ALTER TABLE NOT_GRUP ADD CONSTRAINT NOT_GRUP_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-33::limit (generated)
ALTER TABLE NOT_HIST_ENVIAMENTS ADD CONSTRAINT NOT_HIST_ENVI_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-34::limit (generated)
ALTER TABLE NOT_HIST_ENVIAMENTS ADD CONSTRAINT NOT_HIST_ENVI_ORGAN_FK FOREIGN KEY (ORGAN_ID) REFERENCES NOT_ORGAN_GESTOR (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-35::limit (generated)
ALTER TABLE NOT_HIST_ENVIAMENTS ADD CONSTRAINT NOT_HIST_ENVI_PROCEDIMENT_FK FOREIGN KEY (PROCEDIMENT_ID) REFERENCES NOT_PROCEDIMENT (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-36::limit (generated)
ALTER TABLE NOT_HIST_NOTIF ADD CONSTRAINT NOT_HIST_NOTIF_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-37::limit (generated)
ALTER TABLE NOT_HIST_NOTIF ADD CONSTRAINT NOT_HIST_NOTIF_ORGAN_FK FOREIGN KEY (ORGAN_ID) REFERENCES NOT_ORGAN_GESTOR (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-38::limit (generated)
ALTER TABLE NOT_HIST_NOTIF ADD CONSTRAINT NOT_HIST_NOTIF_PROCEDIMENT_FK FOREIGN KEY (PROCEDIMENT_ID) REFERENCES NOT_PROCEDIMENT (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-39::limit (generated)
ALTER TABLE NOT_HIST_ORGAN ADD CONSTRAINT NOT_HIST_ORGANENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-40::limit (generated)
ALTER TABLE NOT_HIST_ORGAN ADD CONSTRAINT NOT_HIST_ORGAN_ORGAN_FK FOREIGN KEY (ORGAN_ID) REFERENCES NOT_ORGAN_GESTOR (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-41::limit (generated)
ALTER TABLE NOT_HIST_PROCEDIMENT ADD CONSTRAINT NOT_HIST_PROC_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-42::limit (generated)
ALTER TABLE NOT_HIST_PROCEDIMENT ADD CONSTRAINT NOT_HIST_PROC_ORGAN_FK FOREIGN KEY (ORGAN_ID) REFERENCES NOT_ORGAN_GESTOR (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-43::limit (generated)
ALTER TABLE NOT_HIST_PROCEDIMENT ADD CONSTRAINT NOT_HIST_PROC_PROCEDIMENT_FK FOREIGN KEY (PROCEDIMENT_ID) REFERENCES NOT_PROCEDIMENT (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-44::limit (generated)
ALTER TABLE NOT_NOTIFICACIO_MASSIVA ADD CONSTRAINT NOT_MASSIVA_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-45::limit (generated)
ALTER TABLE NOT_NOTIFICACIO_MASSIVA ADD CONSTRAINT NOT_MASSIVA_PAGADOR_POSTAL_FK FOREIGN KEY (PAGADOR_POSTAL_ID) REFERENCES NOT_PAGADOR_POSTAL (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-46::limit (generated)
ALTER TABLE NOT_NOTIFICACIO_EVENT ADD CONSTRAINT NOT_NOTENV_NOTEVE_FK FOREIGN KEY (NOTIFICACIO_ENV_ID) REFERENCES NOT_NOTIFICACIO_ENV (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-47::limit (generated)
ALTER TABLE NOT_NOTIFICACIO_ENV ADD CONSTRAINT NOT_NOTEVE_NOTERR_NOTENV_FK FOREIGN KEY (NOTIFICA_ERROR_EVENT_ID) REFERENCES NOT_NOTIFICACIO_EVENT (ID) ON DELETE SET NULL;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-48::limit (generated)
ALTER TABLE NOT_NOTIFICACIO_ENV ADD CONSTRAINT NOT_NOTIFENV_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-49::limit (generated)
ALTER TABLE NOT_NOTIFICACIO_ENV ADD CONSTRAINT NOT_NOTIFENV_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-50::limit (generated)
ALTER TABLE NOT_NOTIFICACIO_EVENT ADD CONSTRAINT NOT_NOTIFEVENT_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-51::limit (generated)
ALTER TABLE NOT_NOTIFICACIO_EVENT ADD CONSTRAINT NOT_NOTIFEVENT_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-52::limit (generated)
ALTER TABLE NOT_NOTIFICACIO_ENV ADD CONSTRAINT NOT_NOTIFICACIO_NOTENV_FK FOREIGN KEY (NOTIFICACIO_ID) REFERENCES NOT_NOTIFICACIO (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-53::limit (generated)
ALTER TABLE NOT_NOTIFICACIO ADD CONSTRAINT NOT_NOTIFICACIO_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-54::limit (generated)
ALTER TABLE NOT_NOTIFICACIO ADD CONSTRAINT NOT_NOTIFICACIO_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-55::limit (generated)
ALTER TABLE NOT_NOTIFICACIO_EVENT ADD CONSTRAINT NOT_NOTIFI_NOTEVE_FK FOREIGN KEY (NOTIFICACIO_ID) REFERENCES NOT_NOTIFICACIO (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-56::limit (generated)
ALTER TABLE NOT_NOTIFICACIO ADD CONSTRAINT NOT_NOT_ORGAN_FK FOREIGN KEY (ORGAN_GESTOR) REFERENCES NOT_ORGAN_GESTOR (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-57::limit (generated)
ALTER TABLE NOT_ORGAN_GESTOR ADD CONSTRAINT NOT_ORGAN_ENTITAT_FK FOREIGN KEY (ENTITAT) REFERENCES NOT_ENTITAT (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-58::limit (generated)
ALTER TABLE NOT_ORGAN_GESTOR ADD CONSTRAINT NOT_ORGAN_ENTREGA_CIE_FK FOREIGN KEY (ENTREGA_CIE_ID) REFERENCES NOT_ENTREGA_CIE (ID) ON DELETE CASCADE;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-59::limit (generated)
ALTER TABLE NOT_PRO_ORGAN ADD CONSTRAINT NOT_ORGAN_PRO_FK FOREIGN KEY (PROCEDIMENT_ID) REFERENCES NOT_PROCEDIMENT (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-60::limit (generated)
ALTER TABLE NOT_PAGADOR_CIE ADD CONSTRAINT NOT_PAGADORCIE_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-61::limit (generated)
ALTER TABLE NOT_PAGADOR_CIE ADD CONSTRAINT NOT_PAGADOR_CIE_ENTITAT_FK FOREIGN KEY (ENTITAT) REFERENCES NOT_ENTITAT (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-62::limit (generated)
ALTER TABLE NOT_NOTIFICACIO ADD CONSTRAINT NOT_PAGADOR_CIE_NOT_FK FOREIGN KEY (PAGADOR_CIE_ID) REFERENCES NOT_PAGADOR_CIE (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-63::limit (generated)
ALTER TABLE NOT_PAGADOR_CIE ADD CONSTRAINT NOT_PAGADOR_CIE_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-64::limit (generated)
ALTER TABLE NOT_PAGADOR_POSTAL ADD CONSTRAINT NOT_PAGADOR_POSTAL_ENTITAT_FK FOREIGN KEY (ENTITAT) REFERENCES NOT_ENTITAT (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-65::limit (generated)
ALTER TABLE NOT_NOTIFICACIO ADD CONSTRAINT NOT_PAGADOR_POSTAL_NOT_FK FOREIGN KEY (PAGADOR_POSTAL_ID) REFERENCES NOT_PAGADOR_POSTAL (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-66::limit (generated)
ALTER TABLE NOT_PAGADOR_CIE ADD CONSTRAINT NOT_PAGCIE_ORGAN_FK FOREIGN KEY (ORGAN_GESTOR) REFERENCES NOT_ORGAN_GESTOR (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-67::limit (generated)
ALTER TABLE NOT_PAGADOR_POSTAL ADD CONSTRAINT NOT_PAGPOSTAL_ORGAN_FK FOREIGN KEY (ORGAN_GESTOR) REFERENCES NOT_ORGAN_GESTOR (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-68::limit (generated)
ALTER TABLE NOT_PAGADOR_POSTAL ADD CONSTRAINT NOT_PAGPOSTAL_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-69::limit (generated)
ALTER TABLE NOT_PAGADOR_POSTAL ADD CONSTRAINT NOT_PAGPOSTAL_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-70::limit (generated)
ALTER TABLE NOT_NOTIFICACIO_ENV ADD CONSTRAINT NOT_PERSONA_NOTIFICACIO_ENV_FK FOREIGN KEY (TITULAR_ID) REFERENCES NOT_PERSONA (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-71::limit (generated)
ALTER TABLE NOT_PERSONA ADD CONSTRAINT NOT_PERSONA_NOT_FK FOREIGN KEY (NOTIFICACIO_ENV_ID) REFERENCES NOT_NOTIFICACIO_ENV (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-72::limit (generated)
ALTER TABLE NOT_PERSONA ADD CONSTRAINT NOT_PERSONA_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-73::limit (generated)
ALTER TABLE NOT_PERSONA ADD CONSTRAINT NOT_PERSONA_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-74::limit (generated)
ALTER TABLE NOT_PROCEDIMENT ADD CONSTRAINT NOT_PROCEDIMENT_ENTREGA_CIE_FK FOREIGN KEY (ENTREGA_CIE_ID) REFERENCES NOT_ENTREGA_CIE (ID) ON DELETE CASCADE;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-75::limit (generated)
ALTER TABLE NOT_NOTIFICACIO ADD CONSTRAINT NOT_PROCEDIMENT_NOT_FK FOREIGN KEY (PROCEDIMENT_ID) REFERENCES NOT_PROCEDIMENT (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-76::limit (generated)
ALTER TABLE NOT_NOTIFICACIO ADD CONSTRAINT NOT_PROCORGAN_NOT_FK FOREIGN KEY (PROCEDIMENT_ORGAN_ID) REFERENCES NOT_PRO_ORGAN (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-77::limit (generated)
ALTER TABLE NOT_PROCEDIMENT ADD CONSTRAINT NOT_PROC_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-78::limit (generated)
ALTER TABLE NOT_PROCEDIMENT ADD CONSTRAINT NOT_PROC_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-79::limit (generated)
ALTER TABLE NOT_PRO_GRUP ADD CONSTRAINT NOT_PROGRUP_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-80::limit (generated)
ALTER TABLE NOT_PRO_GRUP ADD CONSTRAINT NOT_PROGRUP_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-81::limit (generated)
ALTER TABLE NOT_PRO_GRUP ADD CONSTRAINT NOT_PRO_GRUP_FK FOREIGN KEY (PROCEDIMENT) REFERENCES NOT_PROCEDIMENT (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-82::limit (generated)
ALTER TABLE NOT_PRO_ORGAN ADD CONSTRAINT NOT_PRO_ORGAN_FK FOREIGN KEY (ORGANGESTOR_ID) REFERENCES NOT_ORGAN_GESTOR (ID);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-83::limit (generated)
ALTER TABLE NOT_FORMATS_FULLA ADD CONSTRAINT NOT_FORMATFULLA_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-84::limit (generated)
ALTER TABLE NOT_FORMATS_SOBRE ADD CONSTRAINT NOT_FORMATSOBRE_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-1::limit (generated)
CREATE UNIQUE INDEX NOT_ORGAN_GESTOR_I ON NOT_ORGAN_GESTOR(CODI);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-2::limit (generated)
CREATE UNIQUE INDEX NOT_ENTITAT_UK ON NOT_ENTITAT(CODI);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-3::limit (generated)
CREATE INDEX NOT_APLICACIO_AUDIT_EK ON NOT_APLICACIO_AUDIT(APLICACIO_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-4::limit (generated)
CREATE INDEX NOT_AVIS_DATA_FINAL_I ON NOT_AVIS(DATA_FINAL);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-5::limit (generated)
CREATE INDEX NOT_AVIS_DATA_INICI_I ON NOT_AVIS(DATA_INICI);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-6::limit (generated)
CREATE INDEX NOT_ENTITAT_AUDIT_EK ON NOT_ENTITAT_AUDIT(ENTITAT_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-7::limit (generated)
CREATE INDEX NOT_ENTITAT_EK ON NOT_NOTIFICACIO_MASSIVA(ENTITAT_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-8::limit (generated)
CREATE INDEX NOT_ENTITAT_ENTREGA_CIE_EK ON NOT_ENTITAT(ENTREGA_CIE_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-9::limit (generated)
CREATE INDEX NOT_ENTREGA_CIE_CIE_EK ON NOT_ENTREGA_CIE(CIE_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-10::limit (generated)
CREATE INDEX NOT_ENTREGA_CIE_OPERADOR_EK ON NOT_ENTREGA_CIE(OPERADOR_POSTAL_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-11::limit (generated)
CREATE INDEX NOT_GRUP_AUDIT_EK ON NOT_GRUP_AUDIT(GRUP_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-12::limit (generated)
CREATE INDEX NOT_NOTIFICACIO_AUDIT_EK ON NOT_NOTIFICACIO_AUDIT(NOTIFICACIO_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-13::limit (generated)
CREATE INDEX NOT_NOTIFICACIO_ENV_AUDIT_EK ON NOT_NOTIFICACIO_ENV_AUDIT(ENVIAMENT_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-14::limit (generated)
CREATE INDEX NOT_NOTIFICACIO_ENV_DOM_EK ON NOT_NOTIFICACIO_ENV(ENTREGA_POSTAL_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-15::limit (generated)
CREATE INDEX NOT_NOTIF_ESTAT_I ON NOT_NOTIFICACIO(ESTAT);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-16::limit (generated)
CREATE INDEX NOT_NOTIF_ORGAN_FK_I ON NOT_NOTIFICACIO(ORGAN_GESTOR);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-17::limit (generated)
CREATE INDEX NOT_NOTIF_PROCEDIMENT_FK_I ON NOT_NOTIFICACIO(PROCEDIMENT_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-18::limit (generated)
CREATE INDEX NOT_NOTIF_PROCOD_I ON NOT_NOTIFICACIO(PROC_CODI_NOTIB);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-19::limit (generated)
CREATE INDEX NOT_NOTIF_PROORGAN_FK_I ON NOT_NOTIFICACIO(PROCEDIMENT_ORGAN_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-20::limit (generated)
CREATE INDEX NOT_NOTIF_USUARI_I ON NOT_NOTIFICACIO(USUARI_CODI);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-21::limit (generated)
CREATE INDEX NOT_NOT_TABLE_NOT_MASSIVA_EK ON NOT_NOTIFICACIO_TABLE(NOTIFICACIO_MASSIVA_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-22::limit (generated)
CREATE INDEX NOT_ORGAN_EK ON NOT_PRO_ORGAN(ORGANGESTOR_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-23::limit (generated)
CREATE INDEX NOT_ORGAN_ENTITAT_FK_I ON NOT_ORGAN_GESTOR(ENTITAT);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-24::limit (generated)
CREATE INDEX NOT_ORGAN_ENTREGA_CIE_EK ON NOT_ORGAN_GESTOR(ENTREGA_CIE_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-25::limit (generated)
CREATE INDEX NOT_PAGADOR_EK ON NOT_NOTIFICACIO_MASSIVA(PAGADOR_POSTAL_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-26::limit (generated)
CREATE INDEX NOT_PROCEDIMENT_AUDIT_EK ON NOT_PROCEDIMENT_AUDIT(PROCEDIMENT_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-27::limit (generated)
CREATE INDEX NOT_PROCEDIMENT_EK ON NOT_PRO_ORGAN(PROCEDIMENT_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-28::limit (generated)
CREATE INDEX NOT_PROCEDIMENT_ENTREGA_CIE_EK ON NOT_PROCEDIMENT(ENTREGA_CIE_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-29::limit (generated)
CREATE INDEX NOT_PRO_GRUP_AUDIT_EK ON NOT_PRO_GRUP_AUDIT(PROGRUP_ID);

-- Changeset db/changelog/initial_schema_sequence.yaml::init-sequence-1::limit (generated)
CREATE SEQUENCE NOT_ACL_SID_SEQ START WITH 1;

-- Changeset db/changelog/initial_schema_sequence.yaml::init-sequence-2::limit (generated)
CREATE SEQUENCE NOT_ACL_OBJECT_IDENTITY_SEQ START WITH 1;

-- Changeset db/changelog/initial_schema_sequence.yaml::init-sequence-3::limit (generated)
CREATE SEQUENCE NOT_ACL_ENTRY_SEQ START WITH 1;

-- Changeset db/changelog/initial_schema_sequence.yaml::init-sequence-4::limit (generated)
CREATE SEQUENCE NOT_ACL_CLASS_SEQ START WITH 1;

-- Changeset db/changelog/initial_schema_sequence.yaml::init-sequence-5::limit (generated)
CREATE SEQUENCE EVENT_IDENTIFIERS START WITH 1 MAXVALUE 999999999 NOCACHE;

-- Changeset db/changelog/initial_schema_sequence.yaml::init-sequence-6::limit (generated)
CREATE SEQUENCE NOT_HIBERNATE_SEQ START WITH 1;

-- Changeset db/changelog/initial_schema_sequence.yaml::init-sequence-7::limit (generated)
CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1;

-- Changeset db/changelog/initial_schema_trigger.yaml::init-trigger-1::limit (generated)
create or replace TRIGGER NOT_ACLCLA_IDGEN_TRG BEFORE INSERT ON NOT_ACL_CLASS FOR EACH ROW BEGIN SELECT NOT_ACL_CLASS_SEQ.NEXTVAL INTO :new.id FROM dual;

END;

/ SHOW ERRORS;

create or replace TRIGGER NOT_ACLENT_IDGEN_TRG BEFORE INSERT ON NOT_ACL_ENTRY FOR EACH ROW BEGIN SELECT NOT_ACL_ENTRY_SEQ.NEXTVAL INTO :new.id FROM dual;

END;

/ SHOW ERRORS;

create or replace TRIGGER NOT_ACLOID_IDGEN_TRG BEFORE INSERT ON NOT_ACL_OBJECT_IDENTITY FOR EACH ROW BEGIN SELECT NOT_ACL_OBJECT_IDENTITY_SEQ.NEXTVAL INTO :new.id FROM dual;

END;

/ SHOW ERRORS;

create or replace TRIGGER NOT_ACLSID_IDGEN_TRG BEFORE INSERT ON NOT_ACL_SID FOR EACH ROW BEGIN SELECT NOT_ACL_SID_SEQ.NEXTVAL INTO :new.id FROM dual;

END;

SHOW ERRORS;

-- Changeset db/changelog/initial_schema_lob.yaml::lob-1::limit (generated)
ALTER TABLE NOT_ENTITAT MOVE LOB(LOGO_PEU) STORE AS NOT_ENTITAT_LOGO_PEU_LOB(TABLESPACE notib_lob INDEX NOT_ENTITAT_LOGO_PEU_LOB_I);

-- Changeset db/changelog/initial_schema_lob.yaml::lob-2::limit (generated)
ALTER TABLE NOT_ENTITAT MOVE LOB(LOGO_CAP) STORE AS NOT_ENTITAT_LOGO_CAP_LOB(TABLESPACE notib_lob INDEX NOT_ENTITAT_LOGO_CAP_LOB_I);

-- Changeset db/changelog/initial_schema_grant.yaml::init-grant-1::limit (generated)
GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_USUARI TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_ENTITAT TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_ENTITAT_AUDIT TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_ENTITAT_TIPUS_DOC TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_APLICACIO TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_APLICACIO_AUDIT TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_AVIS TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_COLUMNES TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_CONFIG TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_CONFIG_GROUP TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_CONFIG_TYPE TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_DOCUMENT TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_ENTREGA_CIE TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_ENTREGA_POSTAL TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_FORMATS_FULLA TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_FORMATS_SOBRE TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_GRUP TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_GRUP_AUDIT TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_HIST_ENVIAMENTS TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_HIST_NOTIF TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_HIST_ORGAN TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_HIST_PROCEDIMENT TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_NOTIFICACIO TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_NOTIFICACIO_AUDIT TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_NOTIFICACIO_ENV TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_NOTIFICACIO_ENV_AUDIT TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_NOTIFICACIO_ENV_TABLE TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_NOTIFICACIO_EVENT TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_NOTIFICACIO_MASSIVA TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_NOTIFICACIO_TABLE TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_ORGAN_GESTOR TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_PAGADOR_CIE TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_PAGADOR_POSTAL TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_PERSONA TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_PROCEDIMENT TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_PROCEDIMENT_AUDIT TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_PRO_GRUP TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_PRO_GRUP_AUDIT TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_PRO_ORGAN TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_NOTIFICACIO_EVENT TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_NOTIFICACIO_EVENT TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_ACL_CLASS TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_ACL_ENTRY TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_ACL_OBJECT_IDENTITY TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_ACL_SID TO WWW_NOTIB;

GRANT SELECT ON NOT_ACL_SID_SEQ TO WWW_NOTIB;

GRANT SELECT ON NOT_ACL_CLASS_SEQ TO WWW_NOTIB;

GRANT SELECT ON NOT_ACL_OBJECT_IDENTITY_SEQ TO WWW_NOTIB;

GRANT SELECT ON NOT_ACL_ENTRY_SEQ TO WWW_NOTIB;

GRANT SELECT ON HIBERNATE_SEQUENCE TO WWW_NOTIB;

-- Changeset db/changelog/initial_schema_inserts.yaml::init-inserts-1::limit
INSERT INTO NOT_CONFIG_TYPE (CODE) VALUES ('BOOL');

INSERT INTO NOT_CONFIG_TYPE (CODE) VALUES ('TEXT');

INSERT INTO NOT_CONFIG_TYPE (CODE) VALUES ('INT');

INSERT INTO NOT_CONFIG_TYPE (CODE) VALUES ('FLOAT');

INSERT INTO NOT_CONFIG_TYPE (CODE) VALUES ('CRON');

INSERT INTO NOT_CONFIG_TYPE (CODE) VALUES ('CREDENTIALS');

INSERT INTO NOT_CONFIG_TYPE (CODE, VALUE) VALUES ('TIPUS_COMUNICACIO', 'ASINCRON,SINCRON');

INSERT INTO NOT_CONFIG_TYPE (CODE, VALUE) VALUES ('NOTIFICA_VERSION', '0,1,2');

INSERT INTO NOT_CONFIG_TYPE (CODE, VALUE) VALUES ('API_PROTOCOL', 'REST,SOAP');

INSERT INTO NOT_CONFIG_TYPE (CODE, VALUE) VALUES ('PRIORITAT_ENVIAMENT_MASSIU', 'ALTA,BAIXA');

INSERT INTO NOT_CONFIG_TYPE (CODE, VALUE) VALUES ('REGISTRE_CLASS', 'es.caib.notib.plugin.registre.RegistrePluginRegweb3Impl,es.caib.notib.plugin.registre.RegistrePluginMockImpl');

INSERT INTO NOT_CONFIG_TYPE (CODE, VALUE) VALUES ('FIRMA_CLASS', 'es.caib.notib.plugin.firmaservidor.FirmaServidorPluginPortafib,es.caib.notib.plugin.firmaservidor.FirmaServidorPluginMock');

INSERT INTO NOT_CONFIG_TYPE (CODE, VALUE) VALUES ('USUARIS_CLASS', 'es.caib.notib.plugin.usuari.DadesUsuariPluginJdbc,es.caib.notib.plugin.usuari.DadesUsuariPluginLdap,es.caib.notib.plugin.usuari.DadesUsuariPluginMock');

INSERT INTO NOT_CONFIG_TYPE (CODE, VALUE) VALUES ('TIPUS_DOCUMENT_ENVIAR', 'CSV,BINARI,TOT');

INSERT INTO NOT_CONFIG_TYPE (CODE) VALUES ('PASSWORD');

INSERT INTO NOT_CONFIG_GROUP (POSITION, CODE, DESCRIPTION) VALUES (0, 'GENERAL', 'Configuracions generals' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, CODE, DESCRIPTION) VALUES (1, 'EMAIL', 'Enviament de correus' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, CODE, DESCRIPTION) VALUES (2, 'SCHEDULLED', 'Configuració de les tasques periòdiques' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, CODE, DESCRIPTION) VALUES (3, 'PLUGINS', 'Plugins de l''aplicació' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, CODE, DESCRIPTION) VALUES (4, 'GES_DOC', 'Gestió documental (Sistema de fitxers)' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, CODE, DESCRIPTION) VALUES (5, 'FIRMA', 'Firma' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, CODE, DESCRIPTION) VALUES (5, 'LOGS', 'Logs del servidor' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, CODE, DESCRIPTION) VALUES (6, 'ASPECTE', 'Aspecte per defecte de l''aplicació' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (1, 'GENERAL', 'TAULA_REMESES', 'Configuració de la taula de remeses' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (2, 'GENERAL', 'FORM_REMESES', 'Configuració del formulari de remeses' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (2, 'GENERAL', 'DOCUMENTS', 'Gestió dels documents' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (3, 'GENERAL', 'DEFAULT_VALUES', 'Valors per defecte configurables' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (1, 'ASPECTE', 'ASPECTE_JUSTIFICANT', 'Valors configurables del justificant' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (1, 'PLUGINS', 'REGISTRE', 'Configuració del registre' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (2, 'PLUGINS', 'NOTIFICA', 'Configuració de notific@' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (3, 'PLUGINS', 'DIR3', 'Configuració del plugin de DIR3' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (4, 'PLUGINS', 'ARXIU', 'Configuració de l''arxiu' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (7, 'PLUGINS', 'USUARIS', 'Configuració del plugin d''usuaris' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (9, 'PLUGINS', 'GESCONADM', 'Plugin de gestió documental administratiu (ROLSAC)' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (1, 'SCHEDULLED', 'SCHEDULLED_REGISTRE', 'Tasca periòdica d''enviament al registre' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (2, 'SCHEDULLED', 'SCHEDULLED_NOTIFICA', 'Tasca periòdica d''enviament a notifica' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (3, 'SCHEDULLED', 'SCHEDULLED_UPDATE_STATUS_NOTIFICA', 'Tasca periòdica d''actualització de l''estat dels enviaments amb l''estat de Notific@' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (3, 'SCHEDULLED', 'SCHEDULLED_UPDATE_STATUS_SIR', 'Tasca periòdica d''actualització de l''estat dels enviaments amb l''estat de enviat_sir' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (5, 'SCHEDULLED', 'SCHEDULLED_PROCEDIMENTS', 'Tasca periòdica d''actualització dels procediments' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (6, 'SCHEDULLED', 'SCHEDULLED_CALLBACK', 'Tasca periòdica de processament callback pendents' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.emprar.sir', 'true', 'Activar SIR', 'BOOL', 'GENERAL' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (1, 'es.caib.notib.adviser.actiu', 'true', 'Activar ADVISER', 'BOOL', 'GENERAL' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (2, 'es.caib.notib.comunicacio.tipus.defecte', 'ASINCRON', 'TIPUS DE COMUNICACIÓ DE LA PLATAFORMA (SINCRON/ASINCRON)', 'TIPUS_COMUNICACIO', 'GENERAL' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (3, 'es.caib.notib.default.user.language', 'ca', 'Llenguatge per defecte de l''aplicació', 'TEXT', 'GENERAL' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (4, 'es.caib.notib.metriques.generar', 'true', 'Generar mètriques', 'BOOL', 'GENERAL' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (7, 'es.caib.notib.plugin.registre.generar.justificant', 'false', 'Indica si s''ha de generar el justificant del registre de totes les notificacions. ' || 'Si es false només es generen per a comunicacions a administracions (enviaments SIR)', 'BOOL', 'GENERAL' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (9, 'es.caib.notib.notifica.dir3.entitat.permes', 'false', 'Tractar l''entitat com un organ gestor més', 'BOOL', 'GENERAL' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (9, 'es.caib.notib.plugin.codi.dir3.entitat', 'false', 'Si s''activa l''organisme emissor de les notificacions és la mateixa l''entitat', 'BOOL', 'GENERAL' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (10, 'es.caib.notib.document.consulta.id.csv.mida.min', '16', 'Nombre mínim de caràcters que pot tenir un codi CSV', 'INT', 'GENERAL' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (11, 'es.caib.notib.app.base.url', '', 'Especificar la URL base de l''aplicació', 'TEXT', 'GENERAL' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (11, 'es.caib.notib.enviament.massiu.prioritat', 'BAIXA', 'Indica si l''enviament massiu s''ha de prioritzar per a que s''enviin el més aviat possible, ' || 'o si han de tenir una prioritat inferior que la resta de notificacions.', 'PRIORITAT_ENVIAMENT_MASSIU', 'GENERAL' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (5, 'es.caib.notib.documents.metadades.from.arxiu', 'false', 'Indica si volem consultar les metadades dels documents directament de l''arxiu. ' || 'Si no està marcat les metadades son consultades a ConCSV', 'BOOL', 'DOCUMENTS' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (6, 'es.caib.notib.notificacio.document.size', '10485760', 'Mida máxima permesa per a un document d''una notificació  (bytes)', 'INT', 'DOCUMENTS' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (6, 'es.caib.notib.notificacio.document.total.size', '15728640', 'Mida máxima del conjunt de documents d''una notificació (bytes)', 'INT', 'DOCUMENTS' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (7, 'es.caib.notib.document.metadades.por.defecto', 'true', 'Indica si usar valors per defecte quan el document no té metadades ' || 'o no s''envien metadades en la crida a l''API REST d''alta notificació', 'BOOL', 'DOCUMENTS' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (0, 'es.caib.notib.email.remitent', '', 'Remitent dels correus electrònics (correu electrònic)', 'EMAIL' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (0, 'es.caib.notib.email.footer', ' Notib - Govern de les Illes Balears', 'Text del peu dels correus electrònics', 'EMAIL' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasques.actives', 'true', 'Activa les tasques d''actualitzar estat (SIR i Notific@) i la d''enviament de callbacks de forma conjunta', 'BOOL', 'SCHEDULLED' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (1, 'es.caib.notib.tasca.registre.enviaments.processar.max', '10', 'Nombre màxim d''enviaments que es processaran cada cop que s''executi la tasca', 'INT', 'SCHEDULLED_REGISTRE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.registre.enviaments.reintents.maxim', '3', 'Nombre màxim de vegades que una mateixa notificació s''intentarà registrar abans d''obtenir una resposta satisfactòria', 'INT', 'SCHEDULLED_REGISTRE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.notifica.enviaments.actiu', 'true', 'Indica si la tasca periòdica està activa (true/false)', 'BOOL', 'SCHEDULLED_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.notifica.enviaments.processar.max', '10', 'Nombre màxim d''enviaments que es processaran cada cop que s''executi la tasca', 'INT', 'SCHEDULLED_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.notifica.enviaments.reintents.maxim', '3', 'Nombre màxim de vegades que una mateixa notificació s''intentarà enviar a notifica abans d''obtenir una resposta satisfactòria', 'INT', 'SCHEDULLED_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.enviament.actualitzacio.estat.actiu', 'true', 'Indica si la tasca periòdica està activa (true/false)', 'BOOL', 'SCHEDULLED_UPDATE_STATUS_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.enviament.actualitzacio.estat.processar.max', '10', 'Nombre màxim d''enviaments que es processaran cada cop que s''executi la tasca', 'INT', 'SCHEDULLED_UPDATE_STATUS_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.enviament.actualitzacio.estat.reintents.maxim', '3', 'Nombre màxim de vegades que una mateixa notificació s''intentarà enviar a notifica abans d''obtenir una resposta satisfactòria', 'INT', 'SCHEDULLED_UPDATE_STATUS_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.enviament.actualitzacio.estat.registre.actiu', 'true', 'Indica si la tasca periòdica està activa (true/false)', 'BOOL', 'SCHEDULLED_UPDATE_STATUS_SIR' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.enviament.actualitzacio.estat.registre.processar.max', '10', 'Nombre màxim d''enviaments que es processaran cada cop que s''executi la tasca', 'INT', 'SCHEDULLED_UPDATE_STATUS_SIR' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.enviament.actualitzacio.estat.registre.reintents.maxim', '3', 'Nombre màxim de vegades que una mateixa notificació s''intentarà enviar a notifica abans d''obtenir una resposta satisfactòria', 'INT', 'SCHEDULLED_UPDATE_STATUS_SIR' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.callback.pendents.actiu', 'true', 'Indica si la tasca periòdica està activa (true/false)', 'BOOL', 'SCHEDULLED_CALLBACK' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.callback.pendents.processar.max', '50', 'Nombre màxim d''enviaments que es processaran cada cop que s''executi la tasca', 'INT', 'SCHEDULLED_CALLBACK' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.callback.pendents.notifica.events.intents.max', '10', 'Nombre màxim de vegades que s''intentarà enviar un callback sense obtenir una resposta satisfactòria', 'INT', 'SCHEDULLED_CALLBACK' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.callback.pendents.periode', '30000', 'Iterval de temps entre les execucions de la tasca (ms)', 'INT', 'SCHEDULLED_CALLBACK' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.callback.pendents.retard.inicial', '60000', 'Temps a esperar per a executar la tasca per primera vegada un cop arrancat el servidor (ms)', 'INT', 'SCHEDULLED_CALLBACK' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.actualitzacio.procediments.actiu', 'true', 'Indica si la tasca periòdica està activa (true/false)', 'BOOL', 'SCHEDULLED_PROCEDIMENTS' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.actualitzacio.procediments.modificar', 'true', 'Indica si la tasca periòdica ha d''actualitzar els procediments', 'BOOL', 'SCHEDULLED_PROCEDIMENTS' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.actualitzacio.procediments.eliminar.organs', 'false', 'Indica si la tasca periòdica ha d''eliminar els òrgans gestors que han quedat en desús.', 'BOOL', 'SCHEDULLED_PROCEDIMENTS' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (9, 'es.caib.notib.plugin.arxiu.class', 'es.caib.notib.plugin.arxiu.ArxiuPluginConcsvImpl', 'Classe Arxiu', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (10, 'es.caib.notib.plugin.arxiu.gestionar.expedients', 'true', 'Gestionar expedients', 'BOOL', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (11, 'es.caib.notib.plugin.arxiu.gestionar.documents', 'true', 'Gestionar documents', 'BOOL', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (12, 'es.caib.notib.plugin.arxiu.gestionar.carpetes', 'true', 'Gestionar carpetes', 'BOOL', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (13, 'es.caib.notib.plugin.arxiu.document.versionable', 'true', 'Document versionable', 'BOOL', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (14, 'es.caib.notib.plugin.arxiu.suporta.metadades', 'true', 'Suporta metadades', 'BOOL', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (15, 'es.caib.notib.plugin.arxiu.escriptori.classificacio', '000000', 'Escriptori classificació', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (16, 'es.caib.notib.plugin.arxiu.escriptori.serie.documental', 'S0001', 'Escriptori serie documental', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (17, 'es.caib.notib.plugin.arxiu.caib.aplicacio.codi', 'NOTIB', 'Codi aplicació', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (18, 'es.caib.notib.plugin.arxiu.caib.csv.definicio', 'CSV_DEF', 'CSV definició', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (19, 'es.caib.notib.plugin.arxiu.caib.timeout.connect', '20000', 'Timeout connect', 'INT', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (20, 'es.caib.notib.plugin.arxiu.caib.timeout.read', '20000', 'Timeout read', 'INT', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.plugin.registre.class', 'es.caib.notib.plugin.registre.RegistrePluginRegweb3Impl', 'Classe Registre', 'REGISTRE_CLASS', 'REGISTRE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (4, 'es.caib.notib.plugin.registre.namespaceuri', 'urn:es:caib:regweb:ws:v1:services', 'URI del namespace del registre', 'REGISTRE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (5, 'es.caib.notib.plugin.registre.service.name', 'RegwebFacadeService', 'Nom del servei del registre', 'REGISTRE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (6, 'es.caib.notib.plugin.registre.port.name', 'RegwebFacade', 'Nom del port del registre', 'REGISTRE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (7, 'es.caib.notib.plugin.registre.segons.entre.peticions', '30', 'Especificar el nombre mínim de segons que hi pot haver entre peticions per obtenir justificant al registre', 'INT', 'REGISTRE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (8, 'es.caib.notib.plugin.registre.documents.enviar', 'true', 'Indicar si s''han d''enviar els documents al registre', 'BOOL', 'REGISTRE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (11, 'es.caib.notib.plugin.registre.enviamentSir.tipusDocumentEnviar', 'BINARI', 'Enviar document com binari, CSV o ambdós per a enviaments SIR', 'TIPUS_DOCUMENT_ENVIAR', 'REGISTRE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (6, 'es.caib.notib.notifica.versio', '2', 'Versió de notifica a utilitzar: 0 (Mock), 1 o 2', 'NOTIFICA_VERSION', 'NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (0, 'es.caib.notib.plugin.gesdoc.class', 'es.caib.notib.plugin.gesdoc.GestioDocumentalPluginFilesystem', 'Nom de la classe per a gestionar l''emmagatzament de documents', 'GES_DOC' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (1, 'es.caib.notib.plugin.gesdoc.filesystem.base.dir', '', 'Directori del sistema de fitxers on emmagatzemar els documents', 'GES_DOC' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.plugin.dades.usuari.class', 'es.caib.notib.plugin.usuari.DadesUsuariPluginJdbc', 'Classe per a gestionar l''accés al plugin d''usuaris', 'USUARIS_CLASS', 'USUARIS' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (2, 'es.caib.notib.plugin.dades.usuari.jdbc.query.codi', 'select usu_codi, usu_nom, usu_nif, usu_codi||''@limit.es'' from sc_wl_usuari where usu_codi=:codi', 'Consulta d''usuaris per codi', 'USUARIS' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (3, 'es.caib.notib.plugin.dades.usuari.jdbc.query.nif', 'select usu_codi, usu_nom, usu_nif, usu_codi||''@limit.es'' from sc_wl_usuari where usu_nif=:nif', 'Consulta d''usuaris per nif', 'USUARIS' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (4, 'es.caib.notib.plugin.dades.usuari.jdbc.query.rols', 'select ugr_codgru from sc_wl_usugru where ugr_codusu=:codi', 'Consulta d''usuaris per rols', 'USUARIS' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (5, 'es.caib.notib.plugin.dades.usuari.jdbc.query.grup', 'select usu_codi, usu_nom, usu_nif, ''josepg@limit.es'' from sc_wl_usuari u, sc_wl_usugru g where g.ugr_codgru=:grup and g.ugr_codusu=u.usu_codi', 'Consulta d''usuaris per grup', 'USUARIS' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (0, 'es.caib.notib.capsalera.logo', '', 'Especificar la ruta de la imatge per a usar a la capsalera com a logo de l''aplicació per defecte', 'ASPECTE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (1, 'es.caib.notib.peu.logo', '', 'Especificar la ruta de la imatge per a usar al peu com a logo de l''aplicació per defecte', 'ASPECTE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (2, 'es.caib.notib.capsalera.color.fons', '', 'Especificar el color del fons de l''aplicació a usar per defecte', 'ASPECTE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (3, 'es.caib.notib.capsalera.color.lletra', '', 'Especificar el color de la lletra de l''aplicació a usar per defecte', 'ASPECTE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (0, 'es.caib.notib.justificant.capsalera.direccio', '', 'Especificar la direcció postal a mostrar al justificant', 'ASPECTE_JUSTIFICANT' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (1, 'es.caib.notib.justificant.capsalera.nif', '', 'Especificar el NIF a mostrar al justificant', 'ASPECTE_JUSTIFICANT' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (2, 'es.caib.notib.justificant.capsalera.codi', '', 'Especificar el codi a mostrar al justificant', 'ASPECTE_JUSTIFICANT' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (3, 'es.caib.notib.justificant.capsalera.email', '', 'Especificar el correu electrònic a mostrar al justificant', 'ASPECTE_JUSTIFICANT' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (4, 'es.caib.notib.justificant.peu.titol', 'NOTIB - Justificant d''enviament de notificació electrònica', 'Especificar el text a mostrar al peu del justificant', 'ASPECTE_JUSTIFICANT' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (5, 'es.caib.notib.justificant.peu.logo', '', 'Especificar path del logo a mostrar al peu del justificant', 'ASPECTE_JUSTIFICANT' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (6, 'es.caib.notib.justificant.capsalera.logo', '', 'Especificar path del logo a mostrar a la capçalera del justificant', 'ASPECTE_JUSTIFICANT' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (3, 'es.caib.notib.plugin.unitats.dir3.protocol', 'REST', 'API protocol', 'API_PROTOCOL', 'DIR3' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (4, 'es.caib.notib.plugin.unitats.class', 'es.caib.notib.plugin.unitat.UnitatsOrganitzativesPluginDir3', 'Especificar la classe per a accedir a les unitats organitzatives', 'DIR3' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (5, 'es.caib.notib.plugin.unitats.fitxer', '', 'Path del fitxer on vols guardar l''organigrama DIR3 per evitar consultes innecessaries. ' || 'Si no s''especifica sempre que no estigui a cache es consultarà a la API de DIR3.', 'DIR3' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (3, 'es.caib.notib.plugin.gesconadm.class', 'es.caib.notib.plugin.gesconadm.GestorContingutsAdministratiuPluginRolsac', 'Especificar la classe per a accedir al contingut administratiu', 'GESCONADM' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (4, 'es.caib.notib.plugin.gesconadm.basic.authentication', 'false', 'Indicar si authenticació és basic', 'BOOL', 'GESCONADM' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.procediment.alta.auto.retard', '10', 'Valor per defecte del retard d''un procediment', 'INT', 'DEFAULT_VALUES' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (1, 'es.caib.notib.procediment.alta.auto.caducitat', '15', 'Valor per defecte de la caducitat d''un procediment', 'INT', 'DEFAULT_VALUES' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.columna.entitat', 'false', 'Mostrar columna entitat', 'BOOL', 'TAULA_REMESES' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (1, 'es.caib.notib.columna.num.expedient', 'true', 'Mostrar columna expedient', 'BOOL', 'TAULA_REMESES' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.destinatari.multiple', 'false', 'Permetre múltiples representants', 'BOOL', 'FORM_REMESES' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (1, 'es.caib.notib.titular.incapacitat', 'true', 'Permetre interessat amb discapacitat', 'BOOL', 'FORM_REMESES' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.plugin.firmaservidor.class', 'es.caib.notib.plugin.firmaservidor.FirmaServidorPluginPortafib', 'Especificar la classe per a gestionar la firma del servidor', 'FIRMA_CLASS', 'FIRMA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (0, 'es.caib.notib.plugin.firmaservidor.portafib.username', '', 'Nom usuari firma portafib', 'FIRMA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (0, 'es.caib.notib.plugin.firmaservidor.portafib.location', 'Palma', 'Ubicació de la firma portafib', 'FIRMA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (0, 'es.caib.notib.plugin.firmaservidor.portafib.signerEmail', 'suport@caib.es', 'Correu electrònic del firmant', 'FIRMA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.permisos.organ.logs', 'false', 'Indica si s''han de generar els logs cada vegada que es consulten els permisos dels organs' , 'BOOL', 'LOGS' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES ( 0, 'es.caib.notib.tasca.enviament.actualitzacio.certificacio.finalitzades.actiu', 'true', 'Indica si la tasca periòdica de consulta de certificació per DEH i CIE està activa (true/false)', 'BOOL', 'SCHEDULLED_NOTIFICA' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES ( 7, 'SCHEDULLED', 'SCHEDULLED_UPDATE_CERT_NOTIFICA', 'Tasca periòdica d''actualització de la certificació dels enviaments finalitzats (DEH/CIE) sense certificació' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.enviament.actualitzacio.estat.deh.reintents.maxim', '10', 'Nombre màxim d''enviaments DEH que es processaran cada cop que s''executi la tasca', 'INT', 'SCHEDULLED_UPDATE_CERT_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (1, 'es.caib.notib.tasca.enviament.actualitzacio.estat.cie.reintents.maxim', '10', 'Nombre màxim d''enviaments CIE que es processaran cada cop que s''executi la tasca', 'INT', 'SCHEDULLED_UPDATE_CERT_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (6, 'es.caib.notib.tasca.enviament.deh.actualitzacio.certificacio.processar.max', '10', 'Nombre màxim d''enviaments DEH sense certificació que es processaran cada cop que s''executi la tasca', 'INT', 'SCHEDULLED_UPDATE_CERT_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (7, 'es.caib.notib.tasca.enviament.cie.actualitzacio.certificacio.processar.max', '10', 'Nombre màxim d''enviaments CIE sense certificació que es processaran cada cop que s''executi la tasca', 'INT', 'SCHEDULLED_UPDATE_CERT_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.registre.enviaments.periode', '120000', 'Iterval de temps entre les execucions de la tasca (ms)', 'INT', 'SCHEDULLED_REGISTRE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (2, 'es.caib.notib.tasca.registre.enviaments.retard.inicial', '10000', 'Temps a esperar per a executar la tasca per primera vegada un cop arrancat el servidor (ms)', 'INT', 'SCHEDULLED_REGISTRE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.notifica.enviaments.periode', '120000', 'Iterval de temps entre les execucions de la tasca (ms)', 'INT', 'SCHEDULLED_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.notifica.enviaments.retard.inicial', '10000', 'Temps a esperar per a executar la tasca per primera vegada un cop arrancat el servidor (ms)', 'INT', 'SCHEDULLED_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.enviament.actualitzacio.estat.periode', '300000', 'Iterval de temps entre les execucions de la tasca (ms)', 'INT', 'SCHEDULLED_UPDATE_STATUS_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.enviament.actualitzacio.estat.retard.inicial', '50000', 'Temps a esperar per a executar la tasca per primera vegada un cop arrancat el servidor (ms)', 'INT', 'SCHEDULLED_UPDATE_STATUS_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.enviament.actualitzacio.estat.registre.periode', '600000', 'Iterval de temps entre les execucions de la tasca (ms)', 'INT', 'SCHEDULLED_UPDATE_STATUS_SIR' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.enviament.actualitzacio.estat.registre.retard.inicial', '400000', 'Temps a esperar per a executar la tasca per primera vegada un cop arrancat el servidor (ms)', 'INT', 'SCHEDULLED_UPDATE_STATUS_SIR' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.refrescar.notificacions.expirades.cron', '0 0 0 * * ?', 'Especificar l''expressió ''cron'' indicant l''interval de temps que vols que es refresquin les notificacions expirades', 'CRON', 'SCHEDULLED' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.actualitzacio.procediments.cron', '0 53 16 * * *', 'Especificar l''expressió ''cron'' indicant la freqüencia en que s''han d''actualitzar els procediments', 'CRON', 'SCHEDULLED_PROCEDIMENTS' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE,  DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES ( 2, 'es.caib.notib.tasca.enviament.deh.actualitzacio.certificacio.periode', '300000', 'Iterval de temps entre les execucions de la tasca (ms) d''enviaments DEH', 'INT', 'SCHEDULLED_UPDATE_CERT_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES ( 3, 'es.caib.notib.tasca.enviament.deh.actualitzacio.certificacio.retard.inicial', '300000', 'Temps a esperar per a executar la tasca per primera vegada un cop arrancat el servidor (ms) dels enviaments DEH', 'INT', 'SCHEDULLED_UPDATE_CERT_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES ( 4, 'es.caib.notib.tasca.enviament.cie.actualitzacio.certificacio.periode', '432000000', 'Iterval de temps entre les execucions de la tasca (ms) d''enviaments CIE', 'INT', 'SCHEDULLED_UPDATE_CERT_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES ( 5, 'es.caib.notib.tasca.enviament.cie.actualitzacio.certificacio.retard.inicial', '300000', 'Temps a esperar per a executar la tasca per primera vegada un cop arrancat el servidor (ms) dels enviaments CIE', 'INT', 'SCHEDULLED_UPDATE_CERT_NOTIFICA' );

-- Changeset db/changelog/initial_schema_inserts.yaml::init-inserts-2::limit
INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (0, 'es.caib.notib.email.jndi', 1, 'JNDI email', 'EMAIL' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (0, 'es.caib.notib.plugin.arxiu.caib.base.url', 1, 'Url base ARXIU', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (1, 'es.caib.notib.plugin.arxiu.verificacio.baseurl', 1, 'URL base per a la verificació de firmes', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (2, 'es.caib.notib.plugin.arxiu.caib.usuari', 1, 'Usuari arxiu', 'TEXT', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (3, 'es.caib.notib.plugin.arxiu.caib.contrasenya', 1, 'Password arxiu', 'PASSWORD', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (4, 'es.caib.notib.plugin.arxiu.csv.base.url', 1, 'URL CSV', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (5, 'es.caib.notib.plugin.arxiu.caib.conversio.imprimible.url.uuid', 1, 'Url on generar imprimible per UUID', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (6, 'es.caib.notib.plugin.arxiu.caib.conversio.imprimible.url.csv', 1, 'Url on generar imprimible per CSV', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (7, 'es.caib.notib.plugin.arxiu.caib.conversio.imprimible.usuari', 1, 'Usuari CONCSV', 'TEXT', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (8, 'es.caib.notib.plugin.arxiu.caib.conversio.imprimible.contrasenya', 1, 'Password CONCSV', 'PASSWORD', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (9, 'es.caib.notib.plugin.regweb.mock.sequencia', 1, 'Ruta a un arxiu de text amb la sequencia per al mock del registre', 'REGISTRE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (10, 'es.caib.notib.plugin.regweb.mock.justificant', 1, 'Ruta a un arxiu pdf amb el justificant per al mock del registre', 'REGISTRE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (0, 'es.caib.notib.notifica.url',1, 'Url de notific@', 'NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (1, 'es.caib.notib.notifica.sede.url', 1, 'Url de SEDE de notific@', 'NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (2, 'es.caib.notib.notifica.username', 1, 'Nom de l''usuari per a accedir a Notific@', 'TEXT', 'NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (3, 'es.caib.notib.notifica.password', 1, 'Password per a accedir a Notific@', 'PASSWORD', 'NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (5, 'es.caib.notib.notifica.clau.xifrat.ids', 1, 'Clau per al xifrat dels identificadors de les notificacions', 'NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (1, 'es.caib.notib.plugin.dades.usuari.jdbc.datasource.jndi.name', 1, 'Datasource dels usuaris', 'USUARIS' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (0, 'es.caib.notib.plugin.unitats.dir3.url', 1, 'Url per accedir als organismes', 'DIR3' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (1, 'es.caib.notib.plugin.unitats.dir3.username', 1, 'Nom de l''usuari de DIR3', 'TEXT', 'DIR3' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (2, 'es.caib.notib.plugin.unitats.dir3.password', 1, 'Password de DIR3', 'PASSWORD', 'DIR3' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (0, 'es.caib.notib.plugin.gesconadm.base.url', 1, 'Url per accedir a gestió documental administratiu', 'GESCONADM' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (1, 'es.caib.notib.plugin.gesconadm.username', 1, 'Nom de l''usuari per a accedir a gestió documental administratiu', 'TEXT', 'GESCONADM' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (2, 'es.caib.notib.plugin.gesconadm.password', 1, 'Password per a accedir a gestió documental administratiu', 'PASSWORD', 'GESCONADM' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (1, 'es.caib.notib.plugin.registre.url',1, 'Url de registre', 'REGISTRE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (2, 'es.caib.notib.plugin.registre.usuari', 1, 'Usuari', 'REGISTRE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (3, 'es.caib.notib.plugin.registre.password', 1, 'Contrasenya', 'PASSWORD', 'REGISTRE' );

-- Changeset db/changelog/initial_schema_inserts.yaml::init-inserts-3::limit
