ALTER TABLE NOT_NOTIFICACIO ADD notifica_datenv TIMESTAMP(6);
ALTER TABLE NOT_NOTIFICACIO ADD not_reintents_env NUMBER(10, 0);
ALTER TABLE NOT_NOTIFICACIO ADD SEU_REG_ORGAN VARCHAR2(256);
ALTER TABLE NOT_NOTIFICACIO ADD SEU_PROC_CODI VARCHAR2(256);
ALTER TABLE NOT_NOTIFICACIO_ENV ADD NOTIFICA_INTENT_DATA TIMESTAMP(6);
ALTER TABLE NOT_NOTIFICACIO_ENV ADD INTENT_NUM NUMBER(10, 0);
ALTER TABLE NOT_NOTIFICACIO_ENV RENAME COLUMN SEU_DATA_ENVIAM TO SEU_INTENT_DATA;
ALTER TABLE NOT_NOTIFICACIO_ENV ADD SEU_FITXER_CODI NUMBER(19);
ALTER TABLE NOT_NOTIFICACIO_ENV ADD SEU_FITXER_CLAU VARCHAR2(20);
ALTER TABLE NOT_ENTITAT MODIFY (CIF NULL);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN ERROR_NOT;


UPDATE NOT_NOTIFICACIO SET notifica_datenv = sysdate where notifica_datenv is null;
UPDATE NOT_NOTIFICACIO SET not_reintents_env = 0 where not_reintents_env is null;
UPDATE NOT_NOTIFICACIO_ENV SET SEU_INTENT_DATA = sysdate where SEU_INTENT_DATA is null;
UPDATE NOT_NOTIFICACIO_ENV SET INTENT_NUM = 0 where INTENT_NUM is null;
update not_notificacio_env set notifica_estat_dataact = sysdate where notifica_estat_dataact is null;

