CREATE TABLE NOT_OFICINA (codi VARCHAR(64) NOT NULL, nom VARCHAR(1024), sir BOOLEAN NOT NULL, actiu BOOLEAN NOT NULL, organ_codi VARCHAR(16), entitat_id BIGINT, CONSTRAINT NOT_OFI_PK PRIMARY KEY (codi));

ALTER TABLE NOT_OFICINA ADD CONSTRAINT NOT_OFI_ORGAN_FK FOREIGN KEY (organ_codi) REFERENCES NOT_ORGAN_GESTOR(CODI);

ALTER TABLE NOT_OFICINA ADD CONSTRAINT NOT_OFI_ENTITAT_FK FOREIGN KEY (entitat_id) REFERENCES NOT_ENTITAT(ID);

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_OFICINA TO WWW_NOTIB;

ALTER TABLE not_notificacio_table ADD titular VARCHAR(1024);

ALTER TABLE not_notificacio_table ADD notifica_ids VARCHAR(1024);

ALTER TABLE not_notificacio_table ADD estat_mask INTEGER;

CREATE INDEX not_not_estatrint_idx on NOT_NOTIFICACIO (ESTAT, REGISTRE_ENV_INTENT);

-- NOT_NOTIFICACIO_ENV
CREATE INDEX not_notenv_estat_idx on NOT_NOTIFICACIO_ENV (NOTIFICA_ESTAT);
CREATE INDEX not_notenv_regpen_idx on NOT_NOTIFICACIO_ENV (REGISTRE_ESTAT_FINAL, NOTIFICA_ESTAT, SIR_CON_INTENT);
CREATE INDEX not_notenv_estatsrint_idx on NOT_NOTIFICACIO_ENV (NOTIFICA_ESTAT_FINAL, NOTIFICA_ESTAT, NOTIFICA_INTENT_NUM);

-- NOT_NOTIFICACIO_TABLE
CREATE INDEX not_nottbl_entitat_idx ON NOT_NOTIFICACIO_TABLE(ENTITAT_ID);
CREATE INDEX not_nottbl_entgrup_idx on NOT_NOTIFICACIO_TABLE (ENTITAT_ID, GRUP_CODI);

-- NOT_NOTIFICACIO_ENV_TABLE
CREATE INDEX not_envtbl_entitat_idx ON NOT_NOTIFICACIO_ENV_TABLE(ENTITAT_ID);