ALTER TABLE not_notificacio_table ADD caducitat TIMESTAMP;
ALTER TABLE not_notificacio_env ADD plazo_ampliado NUMBER(1, 0) DEFAULT '0';
ALTER TABLE not_entrega_postal ADD cie_error_desc VARCHAR2(250 CHAR);
ALTER TABLE not_notificacio_table ADD ENTREGA_POSTAL_ERROR NUMBER(1, 0) DEFAULT '0';

ALTER TABLE not_entrega_postal ADD cie_datat_recnif VARCHAR2(9 CHAR);
ALTER TABLE not_entrega_postal ADD cie_datat_recnom VARCHAR2(400 CHAR);
ALTER TABLE not_entrega_postal ADD cie_cer_data TIMESTAMP(6);
ALTER TABLE not_entrega_postal ADD cie_cer_arxiuid VARCHAR2(50 CHAR);
ALTER TABLE not_entrega_postal ADD cie_cer_hash VARCHAR2(50 CHAR);
ALTER TABLE not_entrega_postal ADD cie_cer_origen VARCHAR2(20 CHAR);
ALTER TABLE not_entrega_postal ADD cie_cer_metas VARCHAR2(255 CHAR);
ALTER TABLE not_entrega_postal ADD cie_cer_csv VARCHAR2(50 CHAR);
ALTER TABLE not_entrega_postal ADD cie_cer_mime VARCHAR2(20 CHAR);
ALTER TABLE not_entrega_postal ADD cie_cer_tamany INTEGER;
ALTER TABLE not_entrega_postal ADD cie_cer_tipus VARCHAR2(20 CHAR);
ALTER TABLE not_entrega_postal ADD cie_cer_arxtip VARCHAR2(20 CHAR);
ALTER TABLE not_entrega_postal ADD cie_cer_numseg VARCHAR2(50 CHAR);
ALTER TABLE not_entrega_postal ADD cie_estat_data TIMESTAMP(6);
ALTER TABLE not_entrega_postal ADD cie_estat_desc VARCHAR2(255 CHAR);
ALTER TABLE not_entrega_postal ADD cie_datat_origen VARCHAR2(20 CHAR);
ALTER TABLE not_entrega_postal ADD cie_datat_numseg VARCHAR2(50 CHAR);
ALTER TABLE not_entrega_postal ADD cie_datat_errdes VARCHAR2(255 CHAR);
ALTER TABLE not_entrega_postal ADD cie_estat_dataact TIMESTAMP(6);