-- #190
ALTER TABLE NOT_GRUP ADD ORGAN_GESTOR NUMBER(19);
ALTER TABLE NOT_PAGADOR_CIE ADD ORGAN_GESTOR NUMBER(19);
ALTER TABLE NOT_PAGADOR_POSTAL ADD ORGAN_GESTOR NUMBER(19);

ALTER TABLE NOT_GRUP ADD CONSTRAINT NOT_GRUP_ORGAN_FK FOREIGN KEY (ORGAN_GESTOR) REFERENCES NOT_ORGAN_GESTOR (ID);
ALTER TABLE NOT_PAGADOR_CIE ADD CONSTRAINT NOT_PAGCIE_ORGAN_FK FOREIGN KEY (ORGAN_GESTOR) REFERENCES NOT_ORGAN_GESTOR (ID);
ALTER TABLE NOT_PAGADOR_POSTAL ADD CONSTRAINT NOT_PAGPOSTAL_ORGAN_FK FOREIGN KEY (ORGAN_GESTOR) REFERENCES NOT_ORGAN_GESTOR (ID);

