-- # 198
ALTER TABLE NOT_DOCUMENT ADD MEDIA VARCHAR2(256 CHAR);
ALTER TABLE NOT_DOCUMENT ADD MIDA NUMBER(19, 0);

-- #350
ALTER TABLE NOT_USUARI ADD REBRE_EMAILS_CREATS NUMBER(1) DEFAULT 0 NOT NULL;

-- #361
ALTER TABLE NOT_USUARI ADD ULTIM_ROL VARCHAR2(40 CHAR);
ALTER TABLE NOT_USUARI ADD ULTIMA_ENTITAT NUMBER(19, 0);