
-- Changeset db/changelog/changes/2.0.8/785.yaml::1634114082437-1::limit
ALTER TABLE NOT_PERSONA MODIFY NIF VARCHAR(50);

ALTER TABLE NOT_NOTIFICACIO_ENV_TABLE  MODIFY TITULAR_NIF  VARCHAR(50);

-- Changeset db/changelog/changes/2.0.8/810.yaml::1634114082437-1::limit
ALTER TABLE not_mon_int ADD header_csrf NUMBER(1) DEFAULT '1';

-- Changeset db/changelog/changes/2.0.8/878.yaml::1634114082437-1::limit
ALTER TABLE not_columnes DROP COLUMN llibre_registre;

ALTER TABLE not_columnes DROP COLUMN titular_email;

ALTER TABLE not_columnes DROP COLUMN data_registre;

ALTER TABLE not_columnes DROP COLUMN num_certificacio;

-- Changeset db/changelog/changes/2.0.8/964.yaml::1634114082437-1::limit
ALTER TABLE not_mon_int ADD notificacio_id NUMBER(19, 0);

-- Changeset db/changelog/changes/2.0.8/967.yaml::1634114082437-1::limit
ALTER TABLE not_organ_gestor ADD entrega_cie_desactivada NUMBER(1) DEFAULT '0' NOT NULL;

-- Changeset db/changelog/changes/2.0.8/970.yaml::1634114082437-1::limit
INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (1, 'es.caib.notib.adviser.sir.actiu', 'true', 'Activar adviser SIR', 'BOOL', 'GENERAL' );

-- Changeset db/changelog/changes/2.0.8/974.yaml::1634114082437-1::limit
ALTER TABLE not_organ_gestor ADD sobrescriure_cie_organ_emisor NUMBER(1) DEFAULT '0' NOT NULL;


-- Organ codi en multiples entitats

ALTER TABLE NOT_OFICINA DROP CONSTRAINT NOT_OFI_ORGAN_FK;
ALTER TABLE NOT_OFICINA ADD ORGAN_GESTOR NUMBER(19,0);
UPDATE NOT_OFICINA ofi SET ofi.ORGAN_GESTOR = (SELECT id FROM NOT_ORGAN_GESTOR o WHERE ofi.ORGAN_CODI = o.CODI);
ALTER TABLE NOT_OFICINA DROP COLUMN ORGAN_CODI;
ALTER TABLE NOT_OFICINA ADD CONSTRAINT NOT_OFI_ORGAN_GESTOR_FK FOREIGN KEY (ORGAN_GESTOR) REFERENCES NOT_ORGAN_GESTOR(ID);

ALTER TABLE NOT_NOTIFICACIO DROP CONSTRAINT NOT_NOT_ORGAN_FK;
ALTER TABLE NOT_NOTIFICACIO ADD ORGAN_GESTOR_AUX NUMBER(19,0);
UPDATE NOT_NOTIFICACIO n SET n.ORGAN_GESTOR_AUX = (SELECT id FROM NOT_ORGAN_GESTOR o WHERE n.ORGAN_GESTOR = o.CODI);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN ORGAN_GESTOR;
ALTER TABLE NOT_NOTIFICACIO ADD CONSTRAINT NOT_ORGAN_GESTOR_FK FOREIGN KEY (ORGAN_GESTOR_AUX) REFERENCES NOT_ORGAN_GESTOR(ID);
ALTER TABLE NOT_NOTIFICACIO RENAME COLUMN ORGAN_GESTOR_AUX TO ORGAN_GESTOR;

ALTER TABLE NOT_ORGAN_GESTOR DROP CONSTRAINT NOT_ORGAN_GESTOR_UK;
DROP INDEX NOT_ORGAN_GESTOR_UK;
ALTER TABLE NOT_ORGAN_GESTOR ADD CONSTRAINT NOT_ORGAN_ENTITAT_UNIQUE UNIQUE (CODI,ENTITAT) ENABLE;

ALTER TABLE NOT_PROCEDIMENT ADD ORGAN_GESTOR_AUX NUMBER(19,0);
UPDATE NOT_PROCEDIMENT n SET n.ORGAN_GESTOR_AUX = (SELECT id FROM NOT_ORGAN_GESTOR o WHERE n.ORGAN_GESTOR = o.CODI);
ALTER TABLE NOT_PROCEDIMENT DROP COLUMN ORGAN_GESTOR;
ALTER TABLE NOT_PROCEDIMENT ADD CONSTRAINT NOT_ORGAN_GESTOR_FK FOREIGN KEY (ORGAN_GESTOR_AUX) REFERENCES NOT_ORGAN_GESTOR(ID);
ALTER TABLE NOT_PROCEDIMENT RENAME COLUMN ORGAN_GESTOR_AUX TO ORGAN_GESTOR;


ALTER TABLE NOT_PROCEDIMENT ADD ORGAN_GESTOR_AUX NUMBER(19,0);
UPDATE NOT_PROCEDIMENT n SET n.ORGAN_GESTOR_AUX = (SELECT id FROM NOT_ORGAN_GESTOR o WHERE n.ORGAN_GESTOR = o.CODI AND n.ENTITAT = o.ENTITAT);
ALTER TABLE NOT_PROCEDIMENT DROP COLUMN ORGAN_GESTOR;
ALTER TABLE NOT_PROCEDIMENT ADD CONSTRAINT NOT_PROCSER_ORGAN_FK FOREIGN KEY (ORGAN_GESTOR_AUX) REFERENCES NOT_ORGAN_GESTOR(ID);
ALTER TABLE NOT_PROCEDIMENT RENAME COLUMN ORGAN_GESTOR_AUX TO ORGAN_GESTOR;

ALTER TABLE NOT_PROCEDIMENT ADD ORGAN_GESTOR_AUX VARCHAR2(64);

UPDATE NOT_PROCEDIMENT n SET n.ORGAN_GESTOR_AUX = (SELECT codi FROM NOT_ORGAN_GESTOR o WHERE n.ORGAN_GESTOR = o.id);

ALTER TABLE NOT_PROCEDIMENT RENAME COLUMN ORGAN_GESTOR_AUX TO ORGAN_CODI;

UPDATE NOT_CONFIG_TYPE SET VALUE = 'es.caib.notib.plugin.validatesignature.afirmacxf.AfirmaCxfValidateSignaturePlugin,es.caib.notib.plugin.valsig.ValidacioFirmesPluginMock' WHERE CODE = 'VALSIG_CLASS';


CREATE INDEX NOT_NOTIFICACIO_CREATBY_I ON NOT_NOTIFICACIO (CREATEDBY_CODI);
CREATE INDEX NOT_NOTIFICACIO_MODIFBY_I ON NOT_NOTIFICACIO (LASTMODIFIEDBY_CODI);
CREATE INDEX NOT_NOT_TABLE_CREATBY_I ON NOT_NOTIFICACIO_TABLE (CREATEDBY_CODI);
CREATE INDEX NOT_NOT_TABLE_MODIFBY_I ON NOT_NOTIFICACIO_TABLE (LASTMODIFIEDBY_CODI);
CREATE INDEX NOT_MASSIVA_CREATBY_I ON NOT_NOTIFICACIO_MASSIVA (CREATEDBY_CODI);
CREATE INDEX NOT_MASSIVA_MODIFBY_I ON NOT_NOTIFICACIO_MASSIVA (LASTMODIFIEDBY_CODI);
CREATE INDEX NOT_EVENT_CREATBY_I ON NOT_NOTIFICACIO_EVENT (CREATEDBY_CODI);
CREATE INDEX NOT_EVENT_MODIFBY_I ON NOT_NOTIFICACIO_EVENT (LASTMODIFIEDBY_CODI);
CREATE INDEX NOT_ENVIAMENT_CREATBY_I ON NOT_NOTIFICACIO_ENV (CREATEDBY_CODI);
CREATE INDEX NOT_ENVIAMENT_MODIFBY_I ON NOT_NOTIFICACIO_ENV (LASTMODIFIEDBY_CODI);
CREATE INDEX NOT_ENV_TABLE_CREATBY_I ON NOT_NOTIFICACIO_ENV_TABLE (CREATEDBY_CODI);
CREATE INDEX NOT_ENV_TABLE_MODIFBY_I ON NOT_NOTIFICACIO_ENV_TABLE (LASTMODIFIEDBY_CODI);
