-- #449 Mostrar columna Estat i desactivar Grup per defecte a la consulta d'enviament
UPDATE NOT_COLUMNES SET GRUP_CODI=0,  ESTAT=1;

-- #424
ALTER TABLE NOT_ORGAN_GESTOR ADD OFICINA VARCHAR2(255 CHAR);
ALTER TABLE NOT_ORGAN_GESTOR ADD OFICINA_NOM VARCHAR2(255 CHAR);
ALTER TABLE NOT_ENTITAT ADD OFICINA_ENTITAT NUMBER(1,0) DEFAULT 1;