ALTER TABLE NOT_NOTIFICACIO ADD DOCUMENT2_ID NUMBER(19, 0);
ALTER TABLE NOT_NOTIFICACIO ADD DOCUMENT3_ID NUMBER(19, 0);
ALTER TABLE NOT_NOTIFICACIO ADD DOCUMENT4_ID NUMBER(19, 0);
ALTER TABLE NOT_NOTIFICACIO ADD DOCUMENT5_ID NUMBER(19, 0);

ALTER TABLE NOT_DOCUMENT ADD ORIGEN VARCHAR2(20 CHAR);
ALTER TABLE NOT_DOCUMENT ADD VALIDESA VARCHAR2(20 CHAR);
ALTER TABLE NOT_DOCUMENT ADD TIPUS_DOCUMENTAL VARCHAR2(30 CHAR);
ALTER TABLE NOT_DOCUMENT ADD FIRMAT NUMBER(1);