-- #424
ALTER TABLE NOT_ORGAN_GESTOR ADD OFICINA VARCHAR2(255 CHAR);
ALTER TABLE NOT_ORGAN_GESTOR ADD OFICINA_NOM VARCHAR2(255 CHAR);
ALTER TABLE NOT_ENTITAT ADD OFICINA_ENTITAT NUMBER(1,0) DEFAULT 1;