CREATE INDEX NOT_APLICACIO_AUDIT_EK ON NOT_APLICACIO_AUDIT (APLICACIO_ID);

CREATE INDEX NOT_AVIS_DATA_FINAL_I ON NOT_AVIS (DATA_FINAL);
CREATE INDEX NOT_AVIS_DATA_INICI_I ON NOT_AVIS (DATA_INICI);

CREATE INDEX NOT_ENTITAT_ENTREGA_CIE_EK ON NOT_ENTITAT (ENTREGA_CIE_ID);

CREATE INDEX NOT_ENTITAT_AUDIT_EK ON NOT_ENTITAT_AUDIT (ENTITAT_ID);

CREATE INDEX NOT_ENTREGA_CIE_CIE_EK ON NOT_ENTREGA_CIE (CIE_ID);
CREATE INDEX NOT_ENTREGA_CIE_OPERADOR_EK ON NOT_ENTREGA_CIE (OPERADOR_POSTAL_ID);

CREATE INDEX NOT_GRUP_AUDIT_EK ON NOT_GRUP_AUDIT (GRUP_ID);

CREATE INDEX NOT_NOTIF_ESTAT_I ON NOT_NOTIFICACIO (ESTAT);
CREATE INDEX NOT_NOTIF_ORGAN_FK_I ON NOT_NOTIFICACIO (ORGAN_GESTOR);
CREATE INDEX NOT_NOTIF_PROCEDIMENT_FK_I ON NOT_NOTIFICACIO (PROCEDIMENT_ID);
CREATE INDEX NOT_NOTIF_PROCOD_I ON NOT_NOTIFICACIO (PROC_CODI_NOTIB);
CREATE INDEX NOT_NOTIF_PROORGAN_FK_I ON NOT_NOTIFICACIO (PROCEDIMENT_ORGAN_ID);
CREATE INDEX NOT_NOTIF_USUARI_I ON NOT_NOTIFICACIO (USUARI_CODI);
CREATE INDEX NOT_NOT_ESTATRINT_IDX on NOT_NOTIFICACIO (ESTAT, REGISTRE_ENV_INTENT);

CREATE INDEX NOT_NOTIFICACIO_AUDIT_EK ON NOT_NOTIFICACIO_AUDIT (NOTIFICACIO_ID);

CREATE INDEX NOT_ENV_ENTREGA_POSTAL_EK ON NOT_NOTIFICACIO_ENV (ENTREGA_POSTAL_ID);
CREATE INDEX NOT_NOTENV_ESTAT_IDX on NOT_NOTIFICACIO_ENV (NOTIFICA_ESTAT);
CREATE INDEX NOT_NOTENV_REGPEN_IDX on NOT_NOTIFICACIO_ENV (REGISTRE_ESTAT_FINAL, NOTIFICA_ESTAT, SIR_CON_INTENT);
CREATE INDEX NOT_NOTENV_ESTATSRINT_IDX on NOT_NOTIFICACIO_ENV (NOTIFICA_ESTAT_FINAL, NOTIFICA_ESTAT, NOTIFICA_INTENT_NUM);

CREATE INDEX NOT_NOTIFICACIO_ENV_AUDIT_EK ON NOT_NOTIFICACIO_ENV_AUDIT (ENVIAMENT_ID);

CREATE INDEX NOT_ENVTBL_ENTITAT_IDX ON NOT_NOTIFICACIO_ENV_TABLE(ENTITAT_ID);

CREATE INDEX NOT_NOTEVENT_NOT_IDX ON NOT_NOTIFICACIO_EVENT (NOTIFICACIO_ID);

CREATE INDEX NOT_ENTITAT_EK ON NOT_NOTIFICACIO_MASSIVA (ENTITAT_ID);
CREATE INDEX NOT_PAGADOR_EK ON NOT_NOTIFICACIO_MASSIVA (PAGADOR_POSTAL_ID);

CREATE INDEX NOT_NOT_TABLE_NOT_MASSIVA_EK ON NOT_NOTIFICACIO_TABLE (NOTIFICACIO_MASSIVA_ID);
CREATE INDEX NOT_NOTTBL_ENTITAT_IDX ON NOT_NOTIFICACIO_TABLE(ENTITAT_ID);
CREATE INDEX NOT_NOTTBL_ENTGRUP_IDX ON NOT_NOTIFICACIO_TABLE (ENTITAT_ID, GRUP_CODI);

CREATE INDEX NOT_ORGAN_ENTITAT_FK_I ON NOT_ORGAN_GESTOR (ENTITAT);
CREATE INDEX NOT_ORGAN_ENTREGA_CIE_EK ON NOT_ORGAN_GESTOR (ENTREGA_CIE_ID);

CREATE INDEX NOT_PRO_GRUP_AUDIT_EK ON NOT_PRO_GRUP_AUDIT (PROGRUP_ID);

CREATE INDEX NOT_PROCEDIMENT_EK ON NOT_PRO_ORGAN (PROCEDIMENT_ID);
CREATE INDEX NOT_ORGAN_EK ON NOT_PRO_ORGAN (ORGANGESTOR_ID);

CREATE INDEX NOT_PROCEDIMENT_ENTREGA_CIE_EK ON NOT_PROCEDIMENT (ENTREGA_CIE_ID);

CREATE INDEX NOT_PROCEDIMENT_AUDIT_EK ON NOT_PROCEDIMENT_AUDIT (PROCEDIMENT_ID);
