ALTER TABLE NOT_APLICACIO ADD PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_APLICACIO_AUDIT ADD CONSTRAINT NOT_APLICACIO_AUDIT_PK PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_AVIS ADD CONSTRAINT NOT_AVIS_PK PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_CALLBACK ADD CONSTRAINT NOT_CALLBACK_PK PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_COLUMNES ADD PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_CONFIG ADD CONSTRAINT NOT_CONFIG_PK PRIMARY KEY (KEY) USING INDEX   ENABLE;
ALTER TABLE NOT_CONFIG_GROUP ADD CONSTRAINT NOT_CONFIG_GROUP_PK PRIMARY KEY (CODE) USING INDEX ENABLE;
ALTER TABLE NOT_CONFIG_TYPE ADD CONSTRAINT NOT_CONFIG_TYPE_PK PRIMARY KEY (CODE) USING INDEX ENABLE;
ALTER TABLE NOT_DOCUMENT ADD PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_ENTITAT ADD PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_ENTITAT_AUDIT ADD CONSTRAINT NOT_ENTITAT_AUDIT_PK PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_ENTITAT_TIPUS_DOC ADD PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_ENTREGA_CIE ADD CONSTRAINT NOT_ENTREGA_CIE_PK PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_ENTREGA_POSTAL ADD CONSTRAINT NOT_ENTREGA_POSTAL_PK PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_FORMATS_FULLA ADD PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_FORMATS_SOBRE ADD PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_GRUP ADD PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_GRUP_AUDIT ADD CONSTRAINT NOT_GRUP_AUDIT_PK PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_HIST_ENVIAMENTS ADD CONSTRAINT NOT_HIST_ENVI_OID_PK PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_HIST_NOTIF ADD CONSTRAINT NOT_HIST_NOTIF_OID_PK PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_HIST_ORGAN ADD CONSTRAINT NOT_HIST_ORGAN_OID_PK PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_HIST_PROCEDIMENT ADD CONSTRAINT NOT_HIST_PROC_OID_PK PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_MON_INT ADD CONSTRAINT NOT_MON_INT_PK PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_MON_INT_PARAM ADD CONSTRAINT NOT_MON_INT_PARAM_PK PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_NOTIFICACIO ADD PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_NOTIFICACIO_AUDIT ADD CONSTRAINT NOT_NOTIFICACIO_AUDIT_PK PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_NOTIFICACIO_ENV ADD PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_NOTIFICACIO_ENV_AUDIT ADD CONSTRAINT NOT_NOTIFICACIO_ENV_AUDIT_PK PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOTIB.NOT_NOTIFICACIO_ENV_TABLE ADD CONSTRAINT NOT_NOTIFICACIO_ENV_TABLE_PK PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_NOTIFICACIO_EVENT ADD PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_NOTIFICACIO_MASSIVA ADD CONSTRAINT NOT_NOTIFICACIO_MASSIVA_PK PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_NOTIFICACIO_TABLE ADD CONSTRAINT NOT_NOTIFICACIO_TABLE_PK PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_OFICINA ADD CONSTRAINT NOT_OFI_PK PRIMARY KEY (CODI) USING INDEX ENABLE;
ALTER TABLE NOT_ORGAN_GESTOR ADD CONSTRAINT NOT_ORGAN_GESTOR_PK PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_PAGADOR_CIE ADD PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_PAGADOR_POSTAL ADD PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_PERSONA ADD PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_PROCEDIMENT ADD PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_PROCEDIMENT_AUDIT ADD CONSTRAINT NOT_PROCEDIMENT_AUDIT_PK PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_PROCESSOS_INICIALS ADD CONSTRAINT NOT_PROCESSOS_INICIALS_PK PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_PRO_GRUP ADD PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_PRO_GRUP_AUDIT ADD CONSTRAINT NOT_PRO_GRUP_AUDIT_PK PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_PRO_ORGAN ADD CONSTRAINT NOT_PRO_ORGAN_PK PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE NOT_USUARI ADD PRIMARY KEY (CODI) USING INDEX ENABLE;

ALTER TABLE NOT_ENTITAT ADD UNIQUE (CODI) USING INDEX ENABLE;
ALTER TABLE NOT_NOTIFICACIO ADD CONSTRAINT NOT_NOTIFICACIO_REF_UK UNIQUE (REFERENCIA) USING INDEX ENABLE;
ALTER TABLE NOT_NOTIFICACIO_TABLE ADD CONSTRAINT NOT_NOTIFICACIO_TABLE_REF_UK UNIQUE (REFERENCIA) USING INDEX ENABLE;
ALTER TABLE NOT_OG_SINC_REL ADD CONSTRAINT NOT_UO_SINC_REL_MULT_UK UNIQUE (ANTIC_OG, NOU_OG) USING INDEX ENABLE;
ALTER TABLE NOT_ORGAN_GESTOR ADD CONSTRAINT NOT_ORGAN_GESTOR_UK UNIQUE (CODI) USING INDEX ENABLE;

ALTER TABLE NOT_APLICACIO ADD CONSTRAINT NOT_APLICACIO_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID) ENABLE;
ALTER TABLE NOT_APLICACIO ADD CONSTRAINT NOT_APLICACIO_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;
ALTER TABLE NOT_APLICACIO ADD CONSTRAINT NOT_APLICACIO_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;

ALTER TABLE NOT_COLUMNES ADD CONSTRAINT NOT_COLUMNES_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID) ENABLE;
ALTER TABLE NOT_COLUMNES ADD CONSTRAINT NOT_COLUMNES_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;
ALTER TABLE NOT_COLUMNES ADD CONSTRAINT NOT_COLUMNES_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;
ALTER TABLE NOT_COLUMNES ADD CONSTRAINT NOT_COLUMNES_USUARI_FK FOREIGN KEY (USUARI_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;

ALTER TABLE NOT_CONFIG ADD CONSTRAINT NOT_CONFIG_GROUP_FK FOREIGN KEY (GROUP_CODE) REFERENCES NOT_CONFIG_GROUP (CODE) ENABLE;

ALTER TABLE NOT_DOCUMENT ADD CONSTRAINT NOT_DOCUMENT_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;
ALTER TABLE NOT_DOCUMENT ADD CONSTRAINT NOT_DOCUMENT_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;

ALTER TABLE NOT_ENTITAT ADD CONSTRAINT NOT_ENTITAT_ENTREGA_CIE_FK FOREIGN KEY (ENTREGA_CIE_ID) REFERENCES NOT_ENTREGA_CIE (ID) ON DELETE CASCADE ENABLE;
ALTER TABLE NOT_ENTITAT ADD CONSTRAINT NOT_ENTITAT_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;
ALTER TABLE NOT_ENTITAT ADD CONSTRAINT NOT_ENTITAT_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;

ALTER TABLE NOT_ENTITAT_TIPUS_DOC ADD CONSTRAINT NOT_ENTITAT_TIPUS_DOC_FK FOREIGN KEY (ENTITAT_ID)  REFERENCES NOT_ENTITAT (ID) ENABLE;
ALTER TABLE NOT_ENTITAT_TIPUS_DOC ADD CONSTRAINT NOT_ENTTIPDOC_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;
ALTER TABLE NOT_ENTITAT_TIPUS_DOC ADD CONSTRAINT NOT_ENTTIPDOC_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;

ALTER TABLE NOT_ENTREGA_CIE ADD CONSTRAINT NOT_ENTREGA_CIE_CIE_FK FOREIGN KEY (CIE_ID) REFERENCES NOT_PAGADOR_CIE (ID) ENABLE;
ALTER TABLE NOT_ENTREGA_CIE ADD CONSTRAINT NOT_ENTREGA_CIE_OPERADOR_FK FOREIGN KEY (OPERADOR_POSTAL_ID) REFERENCES NOT_PAGADOR_POSTAL (ID) ENABLE;

ALTER TABLE NOT_FORMATS_FULLA ADD CONSTRAINT NOT_FORMATFULLA_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;
ALTER TABLE NOT_FORMATS_FULLA ADD CONSTRAINT NOT_FORMATFULLA_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;
ALTER TABLE NOT_FORMATS_FULLA ADD CONSTRAINT NOT_FORMATS_FULLA_FK FOREIGN KEY (PAGADOR_CIE_ID) REFERENCES NOT_PAGADOR_CIE (ID) ENABLE;

ALTER TABLE NOT_FORMATS_SOBRE ADD CONSTRAINT NOT_FORMATSOBRE_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;
ALTER TABLE NOT_FORMATS_SOBRE ADD CONSTRAINT NOT_FORMATSOBRE_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;
ALTER TABLE NOT_FORMATS_SOBRE ADD CONSTRAINT NOT_FORMATS_SOBRE_FK FOREIGN KEY (PAGADOR_CIE_ID) REFERENCES NOT_PAGADOR_CIE (ID) ENABLE;

ALTER TABLE NOT_GRUP ADD CONSTRAINT NOT_ENTITAT_GRUP_FK FOREIGN KEY (ENTITAT) REFERENCES NOT_ENTITAT (ID) ENABLE;
ALTER TABLE NOT_GRUP ADD CONSTRAINT NOT_GRUP_ORGAN_FK FOREIGN KEY (ORGAN_GESTOR) REFERENCES NOT_ORGAN_GESTOR (ID) ENABLE;
ALTER TABLE NOT_GRUP ADD CONSTRAINT NOT_GRUP_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;
ALTER TABLE NOT_GRUP ADD CONSTRAINT NOT_GRUP_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;

ALTER TABLE NOT_HIST_ENVIAMENTS ADD CONSTRAINT NOT_HIST_ENVI_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID) ENABLE;
ALTER TABLE NOT_HIST_ENVIAMENTS ADD CONSTRAINT NOT_HIST_ENVI_ORGAN_FK FOREIGN KEY (ORGAN_ID) REFERENCES NOT_ORGAN_GESTOR (ID) ENABLE;
ALTER TABLE NOT_HIST_ENVIAMENTS ADD CONSTRAINT NOT_HIST_ENVI_PROCEDIMENT_FK FOREIGN KEY (PROCEDIMENT_ID) REFERENCES NOT_PROCEDIMENT (ID) ENABLE;

ALTER TABLE NOT_HIST_NOTIF ADD CONSTRAINT NOT_HIST_NOTIF_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID) ENABLE;
ALTER TABLE NOT_HIST_NOTIF ADD CONSTRAINT NOT_HIST_NOTIF_ORGAN_FK FOREIGN KEY (ORGAN_ID) REFERENCES NOT_ORGAN_GESTOR (ID) ENABLE;
ALTER TABLE NOT_HIST_NOTIF ADD CONSTRAINT NOT_HIST_NOTIF_PROCEDIMENT_FK FOREIGN KEY (PROCEDIMENT_ID) REFERENCES NOT_PROCEDIMENT (ID) ENABLE;

ALTER TABLE NOT_HIST_ORGAN ADD CONSTRAINT NOT_HIST_ORGANENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID) ENABLE;
ALTER TABLE NOT_HIST_ORGAN ADD CONSTRAINT NOT_HIST_ORGAN_ORGAN_FK FOREIGN KEY (ORGAN_ID) REFERENCES NOT_ORGAN_GESTOR (ID) ENABLE;

ALTER TABLE NOT_HIST_PROCEDIMENT ADD CONSTRAINT NOT_HIST_PROC_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID) ENABLE;
ALTER TABLE NOT_HIST_PROCEDIMENT ADD CONSTRAINT NOT_HIST_PROC_ORGAN_FK FOREIGN KEY (ORGAN_ID) REFERENCES NOT_ORGAN_GESTOR (ID) ENABLE;
ALTER TABLE NOT_HIST_PROCEDIMENT ADD CONSTRAINT NOT_HIST_PROC_PROCEDIMENT_FK FOREIGN KEY (PROCEDIMENT_ID) REFERENCES NOT_PROCEDIMENT (ID) ENABLE;

ALTER TABLE NOT_MON_INT_PARAM ADD CONSTRAINT NOT_MONINTPARAM_MONINT_FK FOREIGN KEY (MON_INT_ID) REFERENCES NOT_MON_INT(ID);

ALTER TABLE NOT_NOTIFICACIO ADD CONSTRAINT NOT_DOCUMENT_NOTIFICACIO_FK FOREIGN KEY (DOCUMENT_ID) REFERENCES NOT_DOCUMENT (ID) ENABLE;
ALTER TABLE NOT_NOTIFICACIO ADD CONSTRAINT NOT_ENTITAT_NOTIFICACIO_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID) ENABLE;
ALTER TABLE NOT_NOTIFICACIO ADD CONSTRAINT NOT_NOTIFICACIO_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;
ALTER TABLE NOT_NOTIFICACIO ADD CONSTRAINT NOT_NOTIFICACIO_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;
ALTER TABLE NOT_NOTIFICACIO ADD CONSTRAINT NOT_NOTIF_NOTIF_MASSIVA_FK FOREIGN KEY (NOTIFICACIO_MASSIVA_ID) REFERENCES NOT_NOTIFICACIO_MASSIVA (ID) ENABLE;
ALTER TABLE NOT_NOTIFICACIO ADD CONSTRAINT NOT_NOT_ORGAN_FK FOREIGN KEY (ORGAN_GESTOR) REFERENCES NOT_ORGAN_GESTOR (CODI) ENABLE;
ALTER TABLE NOT_NOTIFICACIO ADD CONSTRAINT NOT_PROCEDIMENT_NOT_FK FOREIGN KEY (PROCEDIMENT_ID) REFERENCES NOT_PROCEDIMENT (ID) ENABLE;
ALTER TABLE NOT_NOTIFICACIO ADD CONSTRAINT NOT_PROCORGAN_NOT_FK FOREIGN KEY (PROCEDIMENT_ORGAN_ID) REFERENCES NOT_PRO_ORGAN (ID) ENABLE;

ALTER TABLE NOT_NOTIFICACIO_ENV ADD CONSTRAINT NOT_ENV_ENTREGA_POSTAL_FK FOREIGN KEY (ENTREGA_POSTAL_ID) REFERENCES NOT_ENTREGA_POSTAL (ID) ENABLE;
ALTER TABLE NOT_NOTIFICACIO_ENV ADD CONSTRAINT NOT_NOTENV_NOTEVENT_ERROR_FK FOREIGN KEY (NOTIFICA_ERROR_EVENT_ID) REFERENCES NOT_NOTIFICACIO_EVENT (ID) ON DELETE SET NULL ENABLE;
ALTER TABLE NOT_NOTIFICACIO_ENV ADD CONSTRAINT NOT_NOTIFENV_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;
ALTER TABLE NOT_NOTIFICACIO_ENV ADD CONSTRAINT NOT_NOTIFENV_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;
ALTER TABLE NOT_NOTIFICACIO_ENV ADD CONSTRAINT NOT_NOTIFICACIO_NOTENV_FK FOREIGN KEY (NOTIFICACIO_ID) REFERENCES NOT_NOTIFICACIO (ID) ENABLE;
ALTER TABLE NOT_NOTIFICACIO_ENV ADD CONSTRAINT NOT_PERSONA_NOTIFICACIO_ENV_FK FOREIGN KEY (TITULAR_ID) REFERENCES NOT_PERSONA (ID) ENABLE;

ALTER TABLE NOT_NOTIFICACIO_EVENT ADD CONSTRAINT NOT_NOTENV_NOTEVE_FK FOREIGN KEY (NOTIFICACIO_ENV_ID) REFERENCES NOT_NOTIFICACIO_ENV (ID) ENABLE;
ALTER TABLE NOT_NOTIFICACIO_EVENT ADD CONSTRAINT NOT_NOTIFEVENT_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;
ALTER TABLE NOT_NOTIFICACIO_EVENT ADD CONSTRAINT NOT_NOTIFEVENT_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;
ALTER TABLE NOT_NOTIFICACIO_EVENT ADD CONSTRAINT NOT_NOTIFICACIO_NOTEVENT_FK FOREIGN KEY (NOTIFICACIO_ID) REFERENCES NOT_NOTIFICACIO (ID) ENABLE;

ALTER TABLE NOT_NOTIFICACIO_MASSIVA ADD CONSTRAINT NOT_MASSIVA_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID) ENABLE;
ALTER TABLE NOT_NOTIFICACIO_MASSIVA ADD CONSTRAINT NOT_MASSIVA_PAGADOR_POSTAL_FK FOREIGN KEY (PAGADOR_POSTAL_ID) REFERENCES NOT_PAGADOR_POSTAL (ID) ENABLE;

ALTER TABLE NOT_NOTIFICACIO_TABLE ADD CONSTRAINT NOT_NOT_TABLE_NOT_MASSIVA_FK FOREIGN KEY (NOTIFICACIO_MASSIVA_ID) REFERENCES NOT_NOTIFICACIO_MASSIVA (ID) ENABLE;

ALTER TABLE NOT_OFICINA ADD CONSTRAINT NOT_OFI_ORGAN_FK FOREIGN KEY (ORGAN_CODI) REFERENCES NOT_ORGAN_GESTOR(CODI);
ALTER TABLE NOT_OFICINA ADD CONSTRAINT NOT_OFI_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT(ID);

ALTER TABLE NOT_OG_SINC_REL ADD CONSTRAINT NOT_ORGAN_ANTIC_FK FOREIGN KEY (ANTIC_OG) REFERENCES NOT_ORGAN_GESTOR (id);
ALTER TABLE NOT_OG_SINC_REL ADD CONSTRAINT NOT_ORGAN_NOU_FK FOREIGN KEY (NOU_OG) REFERENCES NOT_ORGAN_GESTOR (id);

ALTER TABLE NOT_ORGAN_GESTOR ADD CONSTRAINT NOT_ORGAN_ENTITAT_FK FOREIGN KEY (ENTITAT) REFERENCES NOT_ENTITAT (ID) ENABLE;
ALTER TABLE NOT_ORGAN_GESTOR ADD CONSTRAINT NOT_ORGAN_ENTREGA_CIE_FK FOREIGN KEY (ENTREGA_CIE_ID) REFERENCES NOT_ENTREGA_CIE (ID) ON DELETE CASCADE ENABLE;

ALTER TABLE NOT_PAGADOR_CIE ADD CONSTRAINT NOT_PAGADORCIE_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;
ALTER TABLE NOT_PAGADOR_CIE ADD CONSTRAINT NOT_PAGADOR_CIE_ENTITAT_FK FOREIGN KEY (ENTITAT) REFERENCES NOT_ENTITAT (ID) ENABLE;
ALTER TABLE NOT_PAGADOR_CIE ADD CONSTRAINT NOT_PAGADOR_CIE_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;
ALTER TABLE NOT_PAGADOR_CIE ADD CONSTRAINT NOT_PAGCIE_ORGAN_FK FOREIGN KEY (ORGAN_GESTOR) REFERENCES NOT_ORGAN_GESTOR (ID) ENABLE;

ALTER TABLE NOT_PAGADOR_POSTAL ADD CONSTRAINT NOT_PAGADOR_POSTAL_ENTITAT_FK FOREIGN KEY (ENTITAT) REFERENCES NOT_ENTITAT (ID) ENABLE;
ALTER TABLE NOT_PAGADOR_POSTAL ADD CONSTRAINT NOT_PAGPOSTAL_ORGAN_FK FOREIGN KEY (ORGAN_GESTOR) REFERENCES NOT_ORGAN_GESTOR (ID) ENABLE;
ALTER TABLE NOT_PAGADOR_POSTAL ADD CONSTRAINT NOT_PAGPOSTAL_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;
ALTER TABLE NOT_PAGADOR_POSTAL ADD CONSTRAINT NOT_PAGPOSTAL_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;

ALTER TABLE NOT_PERSONA ADD CONSTRAINT NOT_PERSONA_NOT_FK FOREIGN KEY (NOTIFICACIO_ENV_ID) REFERENCES NOT_NOTIFICACIO_ENV (ID) ENABLE;
ALTER TABLE NOT_PERSONA ADD CONSTRAINT NOT_PERSONA_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;
ALTER TABLE NOT_PERSONA ADD CONSTRAINT NOT_PERSONA_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;

ALTER TABLE NOT_PROCEDIMENT ADD CONSTRAINT NOT_ENTITAT_FK FOREIGN KEY (ENTITAT) REFERENCES NOT_ENTITAT (ID) ENABLE;
ALTER TABLE NOT_PROCEDIMENT ADD CONSTRAINT NOT_PROCEDIMENT_ENTREGA_CIE_FK FOREIGN KEY (ENTREGA_CIE_ID) REFERENCES NOT_ENTREGA_CIE (ID) ON DELETE CASCADE ENABLE;
ALTER TABLE NOT_PROCEDIMENT ADD CONSTRAINT NOT_PROC_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;
ALTER TABLE NOT_PROCEDIMENT ADD CONSTRAINT NOT_PROC_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;

ALTER TABLE NOT_PRO_GRUP ADD CONSTRAINT NOT_GRUP_PRO_FK FOREIGN KEY (GRUP) REFERENCES NOT_GRUP (ID) ENABLE;
ALTER TABLE NOT_PRO_GRUP ADD CONSTRAINT NOT_PROGRUP_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;
ALTER TABLE NOT_PRO_GRUP ADD CONSTRAINT NOT_PROGRUP_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ENABLE;
ALTER TABLE NOT_PRO_GRUP ADD CONSTRAINT NOT_PRO_GRUP_FK FOREIGN KEY (PROCEDIMENT) REFERENCES NOT_PROCEDIMENT (ID) ENABLE;

ALTER TABLE NOT_PRO_ORGAN ADD CONSTRAINT NOT_ORGAN_PRO_FK FOREIGN KEY (PROCEDIMENT_ID) REFERENCES NOT_PROCEDIMENT (ID) ENABLE;
ALTER TABLE NOT_PRO_ORGAN ADD CONSTRAINT NOT_PRO_ORGAN_FK FOREIGN KEY (ORGANGESTOR_ID) REFERENCES NOT_ORGAN_GESTOR (ID) ENABLE;
