
package es.caib.notib.logic.wsdl.notificaV2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import es.caib.notib.logic.wsdl.notificaV2.altaremesaenvios.AltaRemesaEnvios;
import es.caib.notib.logic.wsdl.notificaV2.altaremesaenvios.ResultadoAltaRemesaEnvios;
import es.caib.notib.logic.wsdl.notificaV2.getcies.GetCies;
import es.caib.notib.logic.wsdl.notificaV2.getcies.ResultadoGetCies;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NotificaWsV2PortType", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    es.caib.notib.logic.wsdl.notificaV2.altaremesaenvios.ObjectFactory.class,
    es.caib.notib.logic.wsdl.notificaV2.getcies.ObjectFactory.class,
})
public interface NotificaWsV2PortType {


    /**
     * 
     * @param altaRemesaEnvios
     * @return
     *     returns es.caib.notib.logic.wsdl.notificaV2.altaremesaenvios.ResultadoAltaRemesaEnvios
     */
    @WebMethod(action = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/altaRemesaEnvios")
    @WebResult(name = "resultadoAltaRemesaEnvios", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/altaRemesaEnvios", partName = "resultadoAltaRemesaEnvios")
    public ResultadoAltaRemesaEnvios altaRemesaEnvios(
        @WebParam(name = "altaRemesaEnvios", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/altaRemesaEnvios", partName = "altaRemesaEnvios")
        AltaRemesaEnvios altaRemesaEnvios);

//    /**
//     *
//     * @param infoEnvioV2
//     * @return
//     *     returns es.caib.notib.logic.wsdl.notificaV2.infoEnvioV2.ResultadoInfoEnvioV2
//     */
//    @WebMethod(action = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/infoEnvioV2")
//    @WebResult(name = "resultadoInfoEnvioV2", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/infoEnvioV2", partName = "resultadoInfoEnvioV2")
//    public ResultadoInfoEnvioV2 infoEnvioV2(
//        @WebParam(name = "infoEnvioV2", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/infoEnvioV2", partName = "infoEnvioV2")
//        InfoEnvioV2 infoEnvioV2);

    /**
     * 
     * @param getCies
     * @return
     *     returns es.caib.notib.logic.wsdl.notificaV2.getcies.ResultadoGetCies
     */
    @WebMethod(action = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/getCies")
    @WebResult(name = "resultadoGetCies", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/getCies", partName = "resultadoGetCies")
    public ResultadoGetCies getCies(
        @WebParam(name = "getCies", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/getCies", partName = "getCies")
        GetCies getCies);

}
