package es.caib.notib.logic.wsdl.notificaV2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "SincronizarEnvioWsService", targetNamespace = "http://administracionelectronica.gob.es/notifica/ws/sincronizarenvio/1.0/", wsdlLocation = "classpath:wsdl/SincronizarEnvio.wsdl")
public class SincronizarEnvioWsService
        extends Service
{

    private final static URL SINCRONIZARENVIOWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SINCRONIZARENVIOWSSERVICE_EXCEPTION;
    private final static QName SINCRONIZARENVIOWSSERVICE_QNAME = new QName("http://administracionelectronica.gob.es/notifica/ws/sincronizarenvio/1.0/", "SincronizarEnvioWsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("classpath:wsdl/SincronizarEnvio.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SINCRONIZARENVIOWSSERVICE_WSDL_LOCATION = url;
        SINCRONIZARENVIOWSSERVICE_EXCEPTION = e;
    }

    public SincronizarEnvioWsService() {
        super(__getWsdlLocation(), SINCRONIZARENVIOWSSERVICE_QNAME);
    }

    public SincronizarEnvioWsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SINCRONIZARENVIOWSSERVICE_QNAME, features);
    }

    public SincronizarEnvioWsService(URL wsdlLocation) {
        super(wsdlLocation, SINCRONIZARENVIOWSSERVICE_QNAME);
    }

    public SincronizarEnvioWsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SINCRONIZARENVIOWSSERVICE_QNAME, features);
    }

    public SincronizarEnvioWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SincronizarEnvioWsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SincronizarEnvioWsPortType
     */
    @WebEndpoint(name = "SincronizarEnvioWsPort")
    public SincronizarEnvioWsPortType getSincronizarEnvioWsPort() {
        return super.getPort(new QName("http://administracionelectronica.gob.es/notifica/ws/sincronizarenvio/1.0/", "SincronizarEnvioWsPort"), SincronizarEnvioWsPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SincronizarEnvioWsPortType
     */
    @WebEndpoint(name = "SincronizarEnvioWsPort")
    public SincronizarEnvioWsPortType getSincronizarEnvioWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://administracionelectronica.gob.es/notifica/ws/sincronizarenvio/1.0/", "SincronizarEnvioWsPort"), SincronizarEnvioWsPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SINCRONIZARENVIOWSSERVICE_EXCEPTION!= null) {
            throw SINCRONIZARENVIOWSSERVICE_EXCEPTION;
        }
        return SINCRONIZARENVIOWSSERVICE_WSDL_LOCATION;
    }

}