-- Actualitzar els estats DESCONEGUT i SENSE_INFORMACIO a estats finals
UPDATE NOT_NOTIFICACIO_ENV
SET NOTIFICA_ESTAT_FINAL = 1
WHERE NOTIFICA_ESTAT IN (4, 21);

COMMIT;

-- Actualitzar els estats de les notificacions
UPDATE NOT_NOTIFICACIO
SET ESTAT = 3
WHERE ID IN (
	SELECT nn.ID
	FROM NOT_NOTIFICACIO nn
	INNER JOIN NOT_NOTIFICACIO_ENV nne ON nn.ID = nne.NOTIFICACIO_ID 
	WHERE nne.NOTIFICACIO_ID NOT IN (
		SELECT NOTIFICACIO_ID
		FROM NOT_NOTIFICACIO_ENV
		WHERE NOTIFICA_ESTAT_FINAL = 0)
	AND nn.ESTAT NOT IN (3, 4)
);

COMMIT;