CREATE TABLE NOT_NOTIFICACIO_TABLE
(
    ID                   		NUMBER(19)			NOT NULL,

    ENTITAT_ID             		NUMBER(19)			NOT NULL,
    ENTITAT_NOM			        VARCHAR2(256 CHAR),

    PROC_CODI_NOTIB		    	VARCHAR2(9),
    PROCEDIMENT_ORGAN_ID        NUMBER(19,0),
    GRUP_CODI                   VARCHAR2(64 CHAR),

    USUARI_CODI                 VARCHAR2(64 CHAR) NOT NULL ENABLE,
    TIPUS_USUARI				NUMBER(10),

    ERROR_LAST_CALLBACK         NUMBER(1) DEFAULT 0 NOT NULL,

    REGISTRE_ENV_INTENT 		NUMBER(10,0),
    REGISTRE_NUM_EXPEDIENT	    VARCHAR2(80 CHAR),

    NOTIFICA_ERROR_DATE         DATE,
    NOTIFICA_ERROR_DESCRIPCIO   VARCHAR2(2048 CHAR),

    ENV_TIPUS            		NUMBER(10)  		NOT NULL,
    CONCEPTE             		VARCHAR2(255 CHAR)	NOT NULL,
    ESTAT                		NUMBER(10)			NOT NULL,
    ESTAT_DATE				    TIMESTAMP(6),

    PROCEDIMENT_CODI			VARCHAR2(64 CHAR),
    PROCEDIMENT_NOM			    VARCHAR2(256 CHAR),
    PROCEDIMENT_IS_COMU		    NUMBER(1) DEFAULT 0 NOT NULL,

    ORGAN_CODI			        VARCHAR2(64),
    ORGAN_NOM			        VARCHAR2(1000),

    CREATEDDATE          		TIMESTAMP(6),
    CREATEDBY_CODI              VARCHAR2(64 CHAR),
    LASTMODIFIEDBY_CODI         VARCHAR2(64 CHAR),
    LASTMODIFIEDDATE            TIMESTAMP (6)
);

-- Primary keys
ALTER TABLE NOT_NOTIFICACIO_TABLE ADD (CONSTRAINT NOT_NOTIFICACIO_TABLE_PK PRIMARY KEY (ID));

INSERT INTO NOT_NOTIFICACIO_TABLE
    (ID,
     ENTITAT_ID, ENTITAT_NOM,

     PROC_CODI_NOTIB,
     PROCEDIMENT_ORGAN_ID,
     GRUP_CODI,

     USUARI_CODI, TIPUS_USUARI,

     ERROR_LAST_CALLBACK,

     REGISTRE_ENV_INTENT, REGISTRE_NUM_EXPEDIENT,

     NOTIFICA_ERROR_DATE, NOTIFICA_ERROR_DESCRIPCIO,

     ENV_TIPUS, CONCEPTE, ESTAT, ESTAT_DATE,

     PROCEDIMENT_CODI, PROCEDIMENT_NOM, PROCEDIMENT_IS_COMU,

     ORGAN_CODI, ORGAN_NOM,

     CREATEDDATE, CREATEDBY_CODI,  LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE)
    SELECT n.ID,
           n.ENTITAT_ID, entitat.NOM,
           n.PROC_CODI_NOTIB, n.PROC_CODI_NOTIB, n.GRUP_CODI,

           n.USUARI_CODI, n.TIPUS_USUARI,
           n.CALLBACK_ERROR,

           n.REGISTRE_ENV_INTENT, n.REGISTRE_NUM_EXPEDIENT,

           event.DATA, event.ERROR_DESC,

           n.ENV_TIPUS, n.CONCEPTE, n.ESTAT, n.ESTAT_DATE,

           pro.CODI, pro.NOM, CASE WHEN pro.COMU is null then 0 else pro.COMU end, organ.CODI, organ.NOM,

           n.CREATEDDATE, n.CREATEDBY_CODI, n.LASTMODIFIEDBY_CODI, n.LASTMODIFIEDDATE
FROM
    NOT_NOTIFICACIO n
        LEFT JOIN NOT_NOTIFICACIO_EVENT event on n.NOT_ERROR_EVENT_ID = event.ID
        LEFT JOIN NOT_PROCEDIMENT pro on n.PROCEDIMENT_ID = pro.ID
        LEFT JOIN NOT_ORGAN_GESTOR organ on n.ORGAN_GESTOR = organ.CODI
        LEFT JOIN NOT_ENTITAT entitat on n.ENTITAT_ID = entitat.ID;

COMMIT;

ALTER TABLE NOT_NOTIFICACIO_EVENT
    ADD NOTIFICA_ERROR_TIPUS NUMBER(10, 0);


GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_NOTIFICACIO_TABLE TO WWW_NOTIB;


DROP TABLE NOT_NOTIFICACIO_TABLE;