CREATE TABLE NOT_NOTIFICACIO_TABLE
(
    ID                   		NUMBER(19)			NOT NULL,

    ENTITAT_ID             		NUMBER(19)			NOT NULL,
    ENTITAT_NOM			        VARCHAR2(256 CHAR),

    PROC_CODI_NOTIB		    	VARCHAR2(9),
    PROCEDIMENT_ORGAN_ID        NUMBER(19,0),
    GRUP_CODI                   VARCHAR2(64 CHAR),

    USUARI_CODI                 VARCHAR2(64 CHAR),
    TIPUS_USUARI				NUMBER(10),

    ERROR_LAST_CALLBACK         NUMBER(1) DEFAULT 0 NOT NULL,
    ERROR_LAST_EVENT            NUMBER(1) DEFAULT 0 NOT NULL,

    REGISTRE_ENV_INTENT 		NUMBER(10,0),
    REGISTRE_NUM_EXPEDIENT	    VARCHAR2(80 CHAR),

    NOTIFICA_ERROR_DATE         DATE,
    NOTIFICA_ERROR_DESCRIPCIO   VARCHAR2(2048 CHAR),

    ENV_TIPUS            		NUMBER(10)  		NOT NULL,
    CONCEPTE             		VARCHAR2(255 CHAR)	NOT NULL,
    ESTAT                		NUMBER(10)			NOT NULL,
    ESTAT_DATE				    TIMESTAMP(6),

    PROCEDIMENT_CODI			VARCHAR2(64 CHAR),
    PROCEDIMENT_NOM			    VARCHAR2(256 CHAR),
    PROCEDIMENT_IS_COMU		    NUMBER(1) DEFAULT 0 NOT NULL,

    ORGAN_CODI			        VARCHAR2(64),
    ORGAN_NOM			        VARCHAR2(1000),

    CREATEDDATE          		TIMESTAMP(6),
    CREATEDBY_CODI              VARCHAR2(64 CHAR),
    LASTMODIFIEDBY_CODI         VARCHAR2(64 CHAR),
    LASTMODIFIEDDATE            TIMESTAMP (6)
);

-- Primary keys
ALTER TABLE NOT_NOTIFICACIO_TABLE ADD (CONSTRAINT NOT_NOTIFICACIO_TABLE_PK PRIMARY KEY (ID));

INSERT INTO NOT_NOTIFICACIO_TABLE
    (ID,
     ENTITAT_ID, ENTITAT_NOM,

     PROC_CODI_NOTIB,
     PROCEDIMENT_ORGAN_ID,
     GRUP_CODI,

     USUARI_CODI, TIPUS_USUARI,

     ERROR_LAST_CALLBACK, ERROR_LAST_EVENT,

     REGISTRE_ENV_INTENT, REGISTRE_NUM_EXPEDIENT,

     NOTIFICA_ERROR_DATE, NOTIFICA_ERROR_DESCRIPCIO,

     ENV_TIPUS, CONCEPTE, ESTAT, ESTAT_DATE,

     PROCEDIMENT_CODI, PROCEDIMENT_NOM, PROCEDIMENT_IS_COMU,

     ORGAN_CODI, ORGAN_NOM,

     CREATEDDATE, CREATEDBY_CODI,  LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE)
    SELECT n.ID,
           n.ENTITAT_ID, entitat.NOM,
           n.PROC_CODI_NOTIB, n.PROCEDIMENT_ORGAN_ID, n.GRUP_CODI,

           n.USUARI_CODI, n.TIPUS_USUARI,
           n.CALLBACK_ERROR,
           CASE WHEN n.IS_ERROR_LAST_EVENT is null THEN 0 ELSE n.IS_ERROR_LAST_EVENT END,

           n.REGISTRE_ENV_INTENT, n.REGISTRE_NUM_EXPEDIENT,

           event.DATA, event.ERROR_DESC,

           n.ENV_TIPUS, n.CONCEPTE, n.ESTAT, n.ESTAT_DATE,

           pro.CODI, pro.NOM, CASE WHEN pro.COMU is null then 0 else pro.COMU end, organ.CODI, organ.NOM,

           n.CREATEDDATE, n.CREATEDBY_CODI, n.LASTMODIFIEDBY_CODI, n.LASTMODIFIEDDATE
FROM
    NOT_NOTIFICACIO n
        LEFT JOIN NOT_NOTIFICACIO_EVENT event on n.NOT_ERROR_EVENT_ID = event.ID
        LEFT JOIN NOT_PROCEDIMENT pro on n.PROCEDIMENT_ID = pro.ID
        LEFT JOIN NOT_ORGAN_GESTOR organ on n.ORGAN_GESTOR = organ.CODI
        LEFT JOIN NOT_ENTITAT entitat on n.ENTITAT_ID = entitat.ID;

COMMIT;

ALTER TABLE NOT_NOTIFICACIO_EVENT
    ADD NOTIFICA_ERROR_TIPUS NUMBER(10, 0);


CREATE TABLE NOT_NOTIFICACIO_ENV_TABLE
(
    ID                   		NUMBER(19)			NOT NULL,
    NOTIFICACIO_ID              NUMBER(19)			NOT NULL,
    ENTITAT_ID             		NUMBER(19)			NOT NULL,
    DESTINATARIS                VARCHAR2(4000 CHAR)	DEFAULT '',

    TIPUS_ENVIAMENT             NUMBER(10,0) NOT NULL,


    -- TITULAR
    TITULAR_NIF                 VARCHAR2(9 CHAR),
    TITULAR_NOM                 VARCHAR2(256 CHAR),
    TITULAR_EMAIL               VARCHAR2(160 CHAR),
    TITULAR_LLINATGE1           VARCHAR2(40 CHAR),
    TITULAR_LLINATGE2           VARCHAR2(40 CHAR),
    TITULAR_RAOSOCIAL           VARCHAR2(100 CHAR),

    -- INFO NOTIFICACIO
    DATA_PROGRAMADA             DATE,
    PROCEDIMENT_CODI_NOTIB      VARCHAR2(9 BYTE),
    GRUP_CODI                   VARCHAR2(64 CHAR),
    EMISOR_DIR3                 VARCHAR2(9 CHAR),
    USUARI_CODI                 VARCHAR2(64 CHAR),
    NOT_ORGAN_CODI			    VARCHAR2(64 BYTE),

    CONCEPTE             		VARCHAR2(240 CHAR),
    DESCRIPCIO             		VARCHAR2(1000 CHAR),
    LLIBRE                      VARCHAR2(255 CHAR),
    NOT_ESTAT      		        NUMBER(10,0)		NOT NULL,

    CSV_UUID                    VARCHAR2(256 CHAR),

    HAS_ERRORS              NUMBER(1) DEFAULT 0 NOT NULL,

    -- INFO PROCEDIMENT
    PROCEDIMENT_IS_COMU		    NUMBER(1) DEFAULT 0,
    PROCEDIMENT_PROCORGAN_ID    NUMBER(19),

    -- REGISTRE
    REGISTRE_NUMERO             NUMBER(10,0),
    REGISTRE_DATA               DATE,
    REGISTRE_ENVIAMENT_INTENT   NUMBER(10,0),

    -- NOTIFICA
    NOTIFICA_DATA_CADUCITAT     TIMESTAMP(6),
    NOTIFICA_IDENTIFICADOR      VARCHAR2(20 CHAR),
    NOTIFICA_CERT_NUM_SEGUIMENT VARCHAR2(50 CHAR),
    NOTIFICA_ESTAT              NUMBER(10,0) NOT NULL,

    CREATEDDATE          		TIMESTAMP(6),
    CREATEDBY_CODI              VARCHAR2(64 CHAR),
    LASTMODIFIEDBY_CODI         VARCHAR2(64 CHAR),
    LASTMODIFIEDDATE            TIMESTAMP (6)
);

INSERT INTO NOT_NOTIFICACIO_ENV_TABLE
(
    ID,
    NOTIFICACIO_ID,
    ENTITAT_ID,
    DESTINATARIS,
    TIPUS_ENVIAMENT,

    -- TITULAR
    TITULAR_NIF, TITULAR_NOM, TITULAR_EMAIL, TITULAR_LLINATGE1, TITULAR_LLINATGE2, TITULAR_RAOSOCIAL,

    -- INFO NOTIFICACIO
    DATA_PROGRAMADA, PROCEDIMENT_CODI_NOTIB, GRUP_CODI, EMISOR_DIR3, USUARI_CODI, NOT_ORGAN_CODI,
    CONCEPTE,
    DESCRIPCIO,
    LLIBRE,
    NOT_ESTAT,
    CSV_UUID,
    HAS_ERRORS,

    -- INFO PROCEDIMENT
    PROCEDIMENT_IS_COMU,
    PROCEDIMENT_PROCORGAN_ID,

    -- REGISTRE
    REGISTRE_NUMERO,
    REGISTRE_DATA,
    REGISTRE_ENVIAMENT_INTENT,

    -- NOTIFICA
    NOTIFICA_DATA_CADUCITAT,
    NOTIFICA_IDENTIFICADOR,
    NOTIFICA_CERT_NUM_SEGUIMENT,
    NOTIFICA_ESTAT,

    CREATEDDATE,
    CREATEDBY_CODI,
    LASTMODIFIEDBY_CODI,
    LASTMODIFIEDDATE
)
SELECT env.ID, n.id, n.ENTITAT_ID,
       (select
            listagg(
                        CASE WHEN dest.nif is null THEN '' ELSE concat(dest.nif, ' - ') END ||
                        CASE WHEN dest.llinatge1 is null AND dest.llinatge2 is null THEN
                                     '[' || dest.nom || ']'
                             ELSE
                                     '[' || dest.llinatge1 || CASE WHEN dest.llinatge2 is null THEN '' ELSE concat(' ', dest.llinatge2) END || ', ' || dest.nom || ']'
                            END
                , '<br> ')
                        within group ( order by dest.nom )
        from
            not_persona dest
        WHERE dest.notificacio_env_id = env.id),
       N.ENV_TIPUS,

       titular.NIF, titular.nom, titular.EMAIL, titular.LLINATGE1, titular.LLINATGE2, titular.RAO_SOCIAL,

       n.ENV_DATA_PROG, n.PROC_CODI_NOTIB, n.GRUP_CODI, n.EMISOR_DIR3CODI, n.USUARI_CODI, n.ORGAN_GESTOR,
       n.CONCEPTE, n.DESCRIPCIO, n.REGISTRE_LLIBRE_NOM, n.ESTAT,
       concat(doc.CSV, doc.UUID),
       CASE WHEN n.NOT_ERROR_EVENT_ID is null THEN 0 ELSE 1 END,
       pro.COMU, n.PROCEDIMENT_ORGAN_ID,
       n.REGISTRE_NUMERO, n.REGISTRE_DATA, n.REGISTRE_ENV_INTENT,

       env.NOTIFICA_DATCAD, env.NOTIFICACIO_ID, env.NOTIFICA_CER_NUMSEG, env.NOTIFICA_ESTAT,

       env.CREATEDDATE, env.CREATEDBY_CODI, env.LASTMODIFIEDBY_CODI, env.LASTMODIFIEDDATE
FROM
    NOT_NOTIFICACIO_ENV env
        INNER JOIN NOT_NOTIFICACIO n on env.NOTIFICACIO_ID = n.ID
        LEFT JOIN NOT_PERSONA titular on env.TITULAR_ID = titular.id
        LEFT JOIN NOT_PROCEDIMENT pro on n.PROCEDIMENT_ID = pro.ID
        LEFT JOIN NOT_DOCUMENT doc on n.DOCUMENT_ID = doc.ID
        LEFT JOIN NOT_ENTITAT entitat on n.ENTITAT_ID = entitat.ID;

COMMIT;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_NOTIFICACIO_TABLE TO WWW_NOTIB;