--#188
ALTER TABLE not_procediment ADD comu BIGSERIAL(1) DEFAULT 0 NOT NULL;

-- #254
ALTER TABLE NOT_APLICACIO ADD ACTIVA BIGSERIAL(1) DEFAULT 1 NOT NULL;
ALTER TABLE NOT_PROCEDIMENT MODIFY NOM character varying(256);

-- #260
ALTER TABLE NOT_PROCEDIMENT ADD LLIBRE_NOM character varying(255);
ALTER TABLE NOT_PROCEDIMENT ADD OFICINA_NOM character varying(255);

-- #190
ALTER TABLE NOT_PROCEDIMENT ADD ULTIMA_ACT DATE;

-- #263
ALTER TABLE NOT_GRUP ADD ORGAN_GESTOR BIGSERIAL(19);
ALTER TABLE NOT_PAGADOR_CIE ADD ORGAN_GESTOR BIGSERIAL(19);
ALTER TABLE NOT_PAGADOR_POSTAL ADD ORGAN_GESTOR BIGSERIAL(19);

ALTER TABLE NOT_GRUP ADD CONSTRAINT NOT_GRUP_ORGAN_FK FOREIGN KEY (ORGAN_GESTOR) REFERENCES NOT_ORGAN_GESTOR (ID);
ALTER TABLE NOT_PAGADOR_CIE ADD CONSTRAINT NOT_PAGCIE_ORGAN_FK FOREIGN KEY (ORGAN_GESTOR) REFERENCES NOT_ORGAN_GESTOR (ID);
ALTER TABLE NOT_PAGADOR_POSTAL ADD CONSTRAINT NOT_PAGPOSTAL_ORGAN_FK FOREIGN KEY (ORGAN_GESTOR) REFERENCES NOT_ORGAN_GESTOR (ID);

-- #297
ALTER TABLE NOT_ENTITAT ADD NOM_OFICINA_VIRTUAL character varying(255);