CREATE TABLE NOT_OFICINA (codi VARCHAR2(64 CHAR) NOT NULL, nom VARCHAR2(1024 CHAR), sir NUMBER(1) NOT NULL, actiu NUMBER(1) NOT NULL, organ_codi VARCHAR2(16 CHAR), entitat_id NUMBER(38, 0), CONSTRAINT NOT_OFI_PK PRIMARY KEY (codi));

ALTER TABLE NOT_OFICINA ADD CONSTRAINT NOT_OFI_ORGAN_FK FOREIGN KEY (organ_codi) REFERENCES NOT_ORGAN_GESTOR(CODI);

ALTER TABLE NOT_OFICINA ADD CONSTRAINT NOT_OFI_ENTITAT_FK FOREIGN KEY (entitat_id) REFERENCES NOT_ENTITAT(ID);

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_OFICINA TO WWW_NOTIB;

ALTER TABLE not_notificacio_table ADD titular VARCHAR2(1024 CHAR);

ALTER TABLE not_notificacio_table ADD notifica_ids VARCHAR2(1024 CHAR);

ALTER TABLE not_notificacio_table ADD estat_mask INTEGER;
