server:
  port: 8080
  servlet:
    context-path: /notibback
  error:
    path: /error

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:49161:xe
    username: notib
    password: notib
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
#        implicit-strategy: es.caib.notib.persist.audit.CustomImplicitNamingStrategy
    properties:
      hibernate:
        dialect: es.caib.notib.persist.dialect.OracleCaibDialect
        format_sql: false
  liquibase:
    enabled: false
  jta:
    atomikos:
      datasource:
        concurrent-connection-validation:
  mail:
    host: correu.limit.es
    username: proves_limit@limit.es
    password: R8lmu-98TRN
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 25
          auth: false
#          starttls:
#            enable:
#            required:
  mvc:
    view:
      prefix: /WEB_INF/jsp/
      suffix: .jsp
  freemarker:
    enabled: false
  messages:
    basename: messages
#  resources:
#    stat...

keycloak:
  auth-server-url: http://localhost:8081/auth/
  ssl-required: external
  realm: GOIB
  resource: goib-default
  use-resource-role-mappings: false
  public-client: true
  principal-attribute: preferred_username
  verify-token-audience: true

logging:
  level:
    root: INFO
    org.springframework: DEBUG
#    org.springframework.jdbc.core: TRACE
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.keycloak: DEBUG
#    org.springframework: DEBUG
#    org.hibernate: DEBUG

es:
  caib:
    notib:
      plugin:
        dades:
          usuari:
            pluginsib:
              userinformation:
                keycloak:
                  serverurl: http://localhost:8081/auth/
                  realm: GOIB
                  client_id: goib-ws
                  client_id_for_user_autentication: goib-ws
                  password_secret: d5c15941-64f1-4097-9da1-3d447fa37ab7