-- #286 Afegir un sistema d'avisos generals
CREATE TABLE NOT_AVIS
(
    ID                   NUMBER(19)               NOT NULL,
    ASSUMPTE             VARCHAR2(256)            NOT NULL,
    MISSATGE             VARCHAR2(2048)           NOT NULL,
    DATA_INICI           TIMESTAMP(6)             NOT NULL,
    DATA_FINAL           TIMESTAMP(6)             NOT NULL,
    ACTIU                NUMBER(1)                NOT NULL,
    AVIS_NIVELL          VARCHAR2(10)             NOT NULL,
    CREATEDBY_CODI       VARCHAR2(64),
    CREATEDDATE          TIMESTAMP(6),
    LASTMODIFIEDBY_CODI  VARCHAR2(64),
    LASTMODIFIEDDATE     TIMESTAMP(6)
);

ALTER TABLE NOT_AVIS ADD (
    CONSTRAINT NOT_AVIS_PK PRIMARY KEY (ID));

CREATE INDEX NOT_AVIS_DATA_INICI_I ON NOT_AVIS(DATA_INICI);
CREATE INDEX NOT_AVIS_DATA_FINAL_I ON NOT_AVIS(DATA_FINAL);


-- #379 Enviament massiu (fitxer CSV)
CREATE TABLE NOT_NOTIFICACIO_MASSIVA
(
    ID                   NUMBER(19)               NOT NULL,
    ENTITAT_ID           NUMBER(19)               NOT NULL,
    CSV_GESDOC_ID        VARCHAR2(64 CHAR)        NOT NULL,
    ZIP_GESDOC_ID        VARCHAR2(64 CHAR),
    CSV_FILENAME         VARCHAR2(200 CHAR)       NOT NULL,
    ZIP_FILENAME         VARCHAR2(200 CHAR),
    CADUCITAT            TIMESTAMP(6)             NOT NULL,
    EMAIL                VARCHAR2(64 CHAR),
    PAGADOR_POSTAL_ID    NUMBER(19, 0),
    RESUM_GESDOC_ID      VARCHAR2(64 CHAR),
    ERRORS_GESDOC_ID     VARCHAR2(64 CHAR),
    PROGRESS             NUMBER(3)                DEFAULT 0 NOT NULL,

    CREATEDBY_CODI       VARCHAR2(64),
    CREATEDDATE          TIMESTAMP(6),
    LASTMODIFIEDBY_CODI  VARCHAR2(64),
    LASTMODIFIEDDATE     TIMESTAMP(6)
);

ALTER TABLE NOT_NOTIFICACIO_MASSIVA ADD (
    CONSTRAINT NOT_NOTIFICACIO_MASSIVA_PK PRIMARY KEY (ID));

CREATE INDEX NOT_PAGADOR_EK ON NOT_NOTIFICACIO_MASSIVA(PAGADOR_POSTAL_ID);
ALTER TABLE NOT_NOTIFICACIO_MASSIVA
    ADD CONSTRAINT NOT_MASSIVA_PAGADOR_POSTAL_FK FOREIGN KEY (PAGADOR_POSTAL_ID) REFERENCES NOT_PAGADOR_POSTAL(ID);

CREATE INDEX NOT_ENTITAT_EK ON NOT_NOTIFICACIO_MASSIVA(ENTITAT_ID);
ALTER TABLE NOT_NOTIFICACIO_MASSIVA
    ADD CONSTRAINT NOT_MASSIVA_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT(ID);

ALTER TABLE NOT_NOTIFICACIO
    ADD NOTIFICACIO_MASSIVA_ID NUMBER(19) DEFAULT NULL;

ALTER TABLE NOT_NOTIFICACIO_TABLE
    ADD NOTIFICACIO_MASSIVA_ID NUMBER(19) DEFAULT NULL;

ALTER TABLE NOT_NOTIFICACIO_TABLE
    ADD CONSTRAINT NOT_NOT_TABLE_NOT_MASSIVA_FK FOREIGN KEY (NOTIFICACIO_MASSIVA_ID) REFERENCES NOT_NOTIFICACIO_MASSIVA(ID);

CREATE INDEX NOT_NOT_TABLE_NOT_MASSIVA_EK ON NOT_NOTIFICACIO_TABLE(NOTIFICACIO_MASSIVA_ID);

ALTER TABLE NOT_NOTIFICACIO
    ADD CONSTRAINT NOT_NOTIF_NOTIF_MASSIVA_FK FOREIGN KEY (NOTIFICACIO_MASSIVA_ID) REFERENCES NOT_NOTIFICACIO_MASSIVA(ID);

-- #536 No permetre realitzar enviaments amb òrgans obsolets
ALTER TABLE NOT_ORGAN_GESTOR
    ADD ESTAT NUMBER(10, 0) DEFAULT 0 NOT NULL;


ALTER TABLE NOT_NOTIFICACIO_TABLE
    ADD ORGAN_ESTAT NUMBER(10, 0) DEFAULT 0 NOT NULL;


ALTER TABLE NOT_NOTIFICACIO_ENV_TABLE
    ADD ORGAN_ESTAT NUMBER(10, 0) DEFAULT 0 NOT NULL;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_AVIS TO WWW_NOTIB;
GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_NOTIFICACIO_MASSIVA TO WWW_NOTIB;