-- #286 Afegir un sistema d'avisos generals
CREATE TABLE NOT_AVIS
(
  ID                   NUMBER(19)               NOT NULL,
  ASSUMPTE             VARCHAR2(256)            NOT NULL,
  MISSATGE             VARCHAR2(2048)           NOT NULL,
  DATA_INICI           TIMESTAMP(6)             NOT NULL,
  DATA_FINAL           TIMESTAMP(6)             NOT NULL,
  ACTIU                NUMBER(1)                NOT NULL,
  AVIS_NIVELL          VARCHAR2(10)             NOT NULL,
  CREATEDBY_CODI       VARCHAR2(64),
  CREATEDDATE          TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  VARCHAR2(64),
  LASTMODIFIEDDATE     TIMESTAMP(6)
);

ALTER TABLE NOT_AVIS ADD (
  CONSTRAINT NOT_AVIS_PK PRIMARY KEY (ID));

CREATE INDEX NOT_AVIS_DATA_INICI_I ON NOT_AVIS(DATA_INICI);
CREATE INDEX NOT_AVIS_DATA_FINAL_I ON NOT_AVIS(DATA_FINAL);

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_AVIS TO WWW_NOTIB;