ALTER TABLE NOT_NOTIFICACIO_ENV
    DROP CONSTRAINT NOT_NOTEVE_NOTERR_NOTENV_FK;

ALTER TABLE NOT_NOTIFICACIO_ENV
ADD CONSTRAINT NOT_NOTENV_NOTEVENT_ERROR_FK
  FOREIGN KEY (NOTIFICA_ERROR_EVENT_ID)
  REFERENCES NOT_NOTIFICACIO_EVENT(ID)
  ON DELETE SET NULL;
  
