ALTER TABLE NOT_PROCEDIMENT ADD (
  CONSTRAINT NOT_PROCEDIMENT_PK PRIMARY KEY (ID));
  
ALTER TABLE NOT_GRUP ADD (
  CONSTRAINT NOT_GRUP_PK PRIMARY KEY (ID));
  
ALTER TABLE NOT_PAGADOR_POSTAL ADD (
  CONSTRAINT NOT_PAGADOR_POSTAL_PK PRIMARY KEY (ID));
  
ALTER TABLE NOT_PAGADOR_CIE ADD (
  CONSTRAINT NOT_PAGADOR_CIE_PK PRIMARY KEY (ID));

ALTER TABLE NOT_DOCUMENT ADD (
  CONSTRAINT NOT_DOCUMENT_PK PRIMARY KEY (ID));
  
ALTER TABLE NOT_PERSONA ADD (
  CONSTRAINT NOT_PERSONA_PK PRIMARY KEY (ID));
  
ALTER TABLE NOT_PROCEDIMENT ADD (
  CONSTRAINT NOT_PAGADOR_POSTAL_FK FOREIGN KEY (PAGADORPOSTAL)
    REFERENCES NOT_PAGADOR_POSTAL (ID));
  
ALTER TABLE NOT_PROCEDIMENT ADD (
  CONSTRAINT NOT_PAGADOR_CIE_FK FOREIGN KEY (PAGADORCIE)
    REFERENCES NOT_PAGADOR_CIE (ID));
    

ALTER TABLE NOT_NOTIFICACIO_ENV ADD (
  CONSTRAINT NOT_PERSONA_NOTIFICACIO_ENV_FK FOREIGN KEY (TITULAR_ID)
    REFERENCES NOT_PERSONA (ID));

ALTER TABLE NOT_NOTIFICACIO ADD (
  CONSTRAINT NOT_DOCUMENT_NOTIFICACIO_FK FOREIGN KEY (DOCUMENT_ID)
    REFERENCES NOT_DOCUMENT (ID));
    
ALTER TABLE NOT_NOTIFICACIO ADD (
  CONSTRAINT NOT_PROCEDIMENT_NOT_FK FOREIGN KEY (PROCEDIMENT_ID)
    REFERENCES NOT_PROCEDIMENT (ID));
    
ALTER TABLE NOT_NOTIFICACIO ADD (
  CONSTRAINT NOT_PAGADOR_POSTAL_NOT_FK FOREIGN KEY (PAGADOR_POSTAL_ID)
    REFERENCES NOT_PAGADOR_POSTAL (ID));
    
ALTER TABLE NOT_NOTIFICACIO ADD (
  CONSTRAINT NOT_PAGADOR_CIE_NOTIFICACIO_FK FOREIGN KEY (PAGADOR_CIE_ID)
    REFERENCES NOT_PAGADOR_CIE (ID));
    
  
ALTER TABLE NOT_PRO_GRUP ADD (
  CONSTRAINT NOT_GRUP_PRO_FK FOREIGN KEY (GRUP)
      REFERENCES NOT_GRUP (ID),
  CONSTRAINT NOT_PRO_GRUP_FK FOREIGN KEY (PROCEDIMENT)
      REFERENCES NOT_PROCEDIMENT (ID));

    
    
ALTER TABLE NOT_USUARI ADD (
  CONSTRAINT NOT_USUARI_PK PRIMARY KEY (CODI));

ALTER TABLE NOT_ENTITAT ADD (
  CONSTRAINT NOT_ENTITAT_PK PRIMARY KEY (ID),
  CONSTRAINT NOT_ENTITAT_CODI_UK UNIQUE (CODI));

ALTER TABLE NOT_APLICACIO ADD (
  CONSTRAINT NOT_APLICACIO_PK PRIMARY KEY (ID));

ALTER TABLE NOT_NOTIFICACIO ADD (
  CONSTRAINT NOT_NOTIFICACIO_PK PRIMARY KEY (ID));

ALTER TABLE NOT_NOTIFICACIO_ENV ADD (
  CONSTRAINT NOT_NOTIFICACIO_ENV_PK PRIMARY KEY (ID));

ALTER TABLE NOT_NOTIFICACIO_EVENT ADD (
  CONSTRAINT NOT_NOTIFICACIO_EVENT_PK PRIMARY KEY (ID));

ALTER TABLE NOT_ENTITAT ADD (
  CONSTRAINT NOT_USUCRE_ENTITAT_FK FOREIGN KEY (CREATEDBY_CODI)
    REFERENCES NOT_USUARI (CODI),
  CONSTRAINT NOT_USUMOD_ENTITAT_FK FOREIGN KEY (LASTMODIFIEDBY_CODI)
    REFERENCES NOT_USUARI (CODI));

ALTER TABLE NOT_APLICACIO ADD (
  CONSTRAINT NOT_USUCRE_APLICACIO_FK FOREIGN KEY (CREATEDBY_CODI)
    REFERENCES NOT_USUARI (CODI),
  CONSTRAINT NOT_USUMOD_APLICACIO_FK FOREIGN KEY (LASTMODIFIEDBY_CODI)
    REFERENCES NOT_USUARI (CODI));

ALTER TABLE NOT_NOTIFICACIO ADD (
  CONSTRAINT NOT_NOTERREVENT_NOTIFICACIO_FK FOREIGN KEY (NOT_ERROR_EVENT_ID)
    REFERENCES NOT_NOTIFICACIO_EVENT (ID),
  CONSTRAINT NOT_ENTITAT_NOTIFICACIO_FK FOREIGN KEY (ENTITAT_ID)
    REFERENCES NOT_ENTITAT (ID),
  CONSTRAINT NOT_USUCRE_NOTIFICACIO_FK FOREIGN KEY (CREATEDBY_CODI)
    REFERENCES NOT_USUARI (CODI),
  CONSTRAINT NOT_USUMOD_NOTIFICACIO_FK FOREIGN KEY (LASTMODIFIEDBY_CODI)
    REFERENCES NOT_USUARI (CODI));

ALTER TABLE NOT_NOTIFICACIO_ENV ADD (
  CONSTRAINT NOT_NOTEVE_NOTERR_NOTENV_FK FOREIGN KEY (NOTIFICA_ERROR_EVENT_ID)
	  REFERENCES NOT_NOTIFICACIO_EVENT (ID),
  CONSTRAINT NOT_NOTEVE_SEUERR_NOTENV_FK FOREIGN KEY (SEU_ERROR_EVENT_ID)
	  REFERENCES NOT_NOTIFICACIO_EVENT (ID),
  CONSTRAINT NOT_NOTIFICACIO_NOTENV_FK FOREIGN KEY (NOTIFICACIO_ID)
	  REFERENCES NOT_NOTIFICACIO (ID),
  CONSTRAINT NOT_USUCRE_NOTENV_FK FOREIGN KEY (CREATEDBY_CODI)
    REFERENCES NOT_USUARI (CODI),
  CONSTRAINT NOT_USUMOD_NOTENV_FK FOREIGN KEY (LASTMODIFIEDBY_CODI)
    REFERENCES NOT_USUARI (CODI));

ALTER TABLE NOT_NOTIFICACIO_EVENT ADD (
  CONSTRAINT NOT_NOTIFICACIO_NOTEVENT_FK FOREIGN KEY (NOTIFICACIO_ID)
	  REFERENCES NOT_NOTIFICACIO (ID),
  CONSTRAINT NOT_NOTENV_NOTEVENT_FK FOREIGN KEY (NOTIFICACIO_ENV_ID)
	  REFERENCES NOT_NOTIFICACIO_ENV (ID),
  CONSTRAINT NOT_USUCRE_NOTEVENT_FK FOREIGN KEY (CREATEDBY_CODI)
    REFERENCES NOT_USUARI (CODI),
  CONSTRAINT NOT_USUMOD_NOTEVENT_FK FOREIGN KEY (LASTMODIFIEDBY_CODI)
    REFERENCES NOT_USUARI (CODI));

ALTER TABLE NOT_ACL_CLASS ADD (
  CONSTRAINT NOT_ACL_CLASS_PK PRIMARY KEY (ID),
  CONSTRAINT NOT_ACL_CLASS_CLASS_UK UNIQUE (CLASS));

ALTER TABLE NOT_ACL_ENTRY ADD (
  CONSTRAINT NOT_ACL_ENTRY_PK PRIMARY KEY (ID),
  CONSTRAINT NOT_ACL_ENTRY_IDENT_ORDER_UK UNIQUE (ACL_OBJECT_IDENTITY, ACE_ORDER));

ALTER TABLE NOT_ACL_OBJECT_IDENTITY ADD (
  CONSTRAINT NOT_ACL_OID_PK PRIMARY KEY (ID),
  CONSTRAINT NOT_ACL_IOD_CLASS_IDENTITY_UK UNIQUE (OBJECT_ID_CLASS, OBJECT_ID_IDENTITY));

ALTER TABLE NOT_ACL_SID ADD (
  CONSTRAINT NOT_ACL_SID_PK PRIMARY KEY (ID),
  CONSTRAINT NOT_ACL_SID_PRINCIPAL_SID_UK UNIQUE (SID, PRINCIPAL));

ALTER TABLE NOT_ACL_ENTRY ADD CONSTRAINT NOT_ACL_ENTRY_GRANTING_CK
  CHECK (GRANTING IN (1,0));

ALTER TABLE NOT_ACL_ENTRY ADD CONSTRAINT NOT_ACL_ENTRY_AUDIT_SUCCESS_CK
  CHECK (AUDIT_SUCCESS IN (1,0));

ALTER TABLE NOT_ACL_ENTRY ADD CONSTRAINT NOT_ACL_ENTRY_AUDIT_FAILURE_CK
  CHECK (AUDIT_FAILURE IN (1,0));

ALTER TABLE NOT_ACL_OBJECT_IDENTITY ADD CONSTRAINT NOT_ACL_OID_ENTRIES_CK
  CHECK (ENTRIES_INHERITING IN (1,0));

ALTER TABLE NOT_ACL_SID ADD CONSTRAINT NOT_ACL_SID_PRINCIPAL_CK
  CHECK (PRINCIPAL IN (1,0));

ALTER TABLE NOT_ACL_ENTRY ADD CONSTRAINT NOT_ACL_OID_ENTRY_FK
  FOREIGN KEY (ACL_OBJECT_IDENTITY)
  REFERENCES NOT_ACL_OBJECT_IDENTITY (ID);

ALTER TABLE NOT_ACL_ENTRY ADD CONSTRAINT NOT_ACL_SID_ENTRY_FK
  FOREIGN KEY (SID)
  REFERENCES NOT_ACL_SID (ID);

ALTER TABLE NOT_ACL_OBJECT_IDENTITY ADD CONSTRAINT NOT_ACL_CLASS_OID_FK
  FOREIGN KEY (OBJECT_ID_CLASS)
  REFERENCES NOT_ACL_CLASS (ID);

ALTER TABLE NOT_ACL_OBJECT_IDENTITY ADD CONSTRAINT NOT_ACL_PARENT_OID_FK
  FOREIGN KEY (PARENT_OBJECT)
  REFERENCES NOT_ACL_OBJECT_IDENTITY (ID);

ALTER TABLE NOT_ACL_OBJECT_IDENTITY ADD CONSTRAINT NOT_ACL_SID_OID_FK
  FOREIGN KEY (OWNER_SID)
  REFERENCES NOT_ACL_SID (ID);
  
  ALTER TABLE NOT_PROCEDIMENT ADD (
  CONSTRAINT NOT_ENTITAT_FK FOREIGN KEY (ENTITAT)
    REFERENCES NOT_ENTITAT (ID));
      
ALTER TABLE NOT_GRUP ADD (
  CONSTRAINT NOT_ENTITAT_GRUP_FK FOREIGN KEY (ENTITAT)
    REFERENCES NOT_ENTITAT (ID));
    
ALTER TABLE NOT_COLUMNES ADD (
  CONSTRAINT NOT_COLUMNES_ENTITAT_FK FOREIGN KEY (ENTITAT_ID)
    REFERENCES NOT_ENTITAT (ID));

ALTER TABLE NOT_COLUMNES ADD (
  CONSTRAINT NOT_COLUMNES_USUARI_FK FOREIGN KEY (USUARI_CODI)
    REFERENCES NOT_USUARI (CODI));
    
ALTER TABLE NOT_PERSONA ADD (
  CONSTRAINT NOT_PERSONA_NOT_FK FOREIGN KEY (NOTIFICACIO_ENV_ID)
    REFERENCES NOT_NOTIFICACIO_ENV (ID));
    
