GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_USUARI TO WWW_NOTIB;
GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_ENTITAT TO WWW_NOTIB;
GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_ENTITAT_USUARI TO WWW_NOTIB;
GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_NOTIFICACIO TO WWW_NOTIB;
GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_NOTIFICACIO_DEST TO WWW_NOTIB;
GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_NOTIFICACIO_EVENT TO WWW_NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_ACL_CLASS TO WWW_NOTIB;
GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_ACL_ENTRY TO WWW_NOTIB;
GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_ACL_OBJECT_IDENTITY TO WWW_NOTIB;
GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_ACL_SID TO WWW_NOTIB;

GRANT SELECT ON NOT_ACL_SID_SEQ TO WWW_NOTIB;
GRANT SELECT ON NOT_ACL_CLASS_SEQ TO WWW_NOTIB;
GRANT SELECT ON NOT_ACL_OBJECT_IDENTITY_SEQ TO WWW_NOTIB;
GRANT SELECT ON NOT_ACL_ENTRY_SEQ TO WWW_NOTIB;

GRANT SELECT ON HIBERNATE_SEQUENCE TO WWW_NOTIB;
