//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.01 at 01:39:07 PM CEST 
//


package es.caib.notib.logic.intf.ws.adviser.common;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.gob.administracionelectronica.notifica.ws.adviserwsv2._1_0.common package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
//@XmlRegistry
public class ObjectFactory {


//    /**
//     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.caib.notib.logic.intf.ws.adviser.common
//     *
//     */
//    public ObjectFactory() {
//    }
//
//    /**
//     * Create an instance of {@link Opcion }
//     *
//     */
//    public Opcion createOpcion() {
//        return new Opcion();
//    }
//
//    /**
//     * Create an instance of {@link Opciones }
//     *
//     */
//    public Opciones createOpciones() {
//        return new Opciones();
//    }

}
