
CREATE OR REPLACE TRIGGER "NOTIB"."NOT_ACLCLA_IDGEN_TRG"
BEFORE INSERT ON NOT_ACL_CLASS
FOR EACH ROW
BEGIN
SELECT NOT_ACL_CLASS_SEQ.NEXTVAL INTO :new.id FROM dual;
END;




/
ALTER TRIGGER "NOTIB"."NOT_ACLCLA_IDGEN_TRG" ENABLE;


  CREATE OR REPLACE TRIGGER "NOTIB"."NOT_ACLENT_IDGEN_TRG"
BEFORE INSERT ON NOT_ACL_ENTRY
FOR EACH ROW
BEGIN
SELECT NOT_ACL_ENTRY_SEQ.NEXTVAL INTO :new.id FROM dual;
END;




/
ALTER TRIGGER "NOTIB"."NOT_ACLENT_IDGEN_TRG" ENABLE;


  CREATE OR REPLACE TRIGGER "NOTIB"."NOT_ACLOID_IDGEN_TRG"
BEFORE INSERT ON NOT_ACL_OBJECT_IDENTITY
FOR EACH ROW
BEGIN
SELECT NOT_ACL_OBJECT_IDENTITY_SEQ.NEXTVAL INTO :new.id FROM dual;
END;




/
ALTER TRIGGER "NOTIB"."NOT_ACLOID_IDGEN_TRG" ENABLE;


  CREATE OR REPLACE TRIGGER "NOTIB"."NOT_ACLSID_IDGEN_TRG"
BEFORE INSERT ON NOT_ACL_SID
FOR EACH ROW
BEGIN
SELECT NOT_ACL_SID_SEQ.NEXTVAL INTO :new.id FROM dual;
END;




/
ALTER TRIGGER "NOTIB"."NOT_ACLSID_IDGEN_TRG" ENABLE;