ALTER TABLE "NOTIB"."NOT_COLUMNES" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_COLUMNES" ADD PRIMARY KEY ("ID");

ALTER TABLE "NOTIB"."NOT_PROCEDIMENT_AUDIT" ADD CONSTRAINT "NOT_PROCEDIMENT_AUDIT_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_PROCEDIMENT_AUDIT" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PROCEDIMENT_AUDIT" MODIFY ("TIPUSOPERACIO" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PROCEDIMENT_AUDIT" MODIFY ("PROCEDIMENT_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PROCEDIMENT_AUDIT" MODIFY ("CODI" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."NOT_MON_INT" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_MON_INT" MODIFY ("CODI" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_MON_INT" ADD CONSTRAINT "NOT_MON_INT_PK" PRIMARY KEY ("ID");

ALTER TABLE "NOTIB"."NOT_HIST_NOTIF" ADD CONSTRAINT "NOT_HIST_NOTIF_OID_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_HIST_NOTIF" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_NOTIF" MODIFY ("ENTITAT_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_NOTIF" MODIFY ("TIPUS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_NOTIF" MODIFY ("DATA" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_NOTIF" MODIFY ("USUARI_CODI" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_NOTIF" MODIFY ("ESTAT" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_NOTIF" MODIFY ("N_NOT_TOTAL" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_NOTIF" MODIFY ("N_NOT_CORRECTES" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_NOTIF" MODIFY ("N_NOT_AMB_ERROR" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_NOTIF" MODIFY ("N_NOT_ORIGEN_API" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_NOTIF" MODIFY ("N_NOT_ORIGEN_WEB" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_NOTIF" MODIFY ("N_NOT_DESTI_ADM" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_NOTIF" MODIFY ("N_NOT_DESTI_CIUTADA" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_NOTIF" MODIFY ("N_COM_TOTAL" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_NOTIF" MODIFY ("N_COM_CORRECTES" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_NOTIF" MODIFY ("N_COM_AMB_ERROR" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_NOTIF" MODIFY ("N_COM_ORIGEN_API" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_NOTIF" MODIFY ("N_COM_ORIGEN_WEB" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_NOTIF" MODIFY ("N_COM_DESTI_ADM" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_NOTIF" MODIFY ("N_COM_DESTI_CIUTADA" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_NOTIF" MODIFY ("VERSION" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."NOT_PROCEDIMENT" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PROCEDIMENT" MODIFY ("AGRUPAR" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PROCEDIMENT" MODIFY ("CODI" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PROCEDIMENT" MODIFY ("NOM" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PROCEDIMENT" ADD PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_PROCEDIMENT" MODIFY ("COMU" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PROCEDIMENT" MODIFY ("DIRECT_PERMISSION_REQUIRED" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."NOT_PRO_GRUP" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PRO_GRUP" ADD PRIMARY KEY ("ID");

ALTER TABLE "NOTIB"."NOT_USUARI" MODIFY ("CODI" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_USUARI" MODIFY ("VERSION" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_USUARI" ADD PRIMARY KEY ("CODI");
ALTER TABLE "NOTIB"."NOT_USUARI" MODIFY ("REBRE_EMAILS_CREATS" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."NOT_OG_SINC_REL" MODIFY ("ANTIC_OG" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_OG_SINC_REL" MODIFY ("NOU_OG" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_OG_SINC_REL" ADD CONSTRAINT "NOT_UO_SINC_REL_MULT_UK" UNIQUE ("ANTIC_OG", "NOU_OG");

ALTER TABLE "NOTIB"."NOT_PERSONA" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PERSONA" MODIFY ("INTERESSATTIPUS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PERSONA" ADD PRIMARY KEY ("ID");

ALTER TABLE "NOTIB"."NOT_ENTITAT_AUDIT" ADD CONSTRAINT "NOT_ENTITAT_AUDIT_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_ENTITAT_AUDIT" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ENTITAT_AUDIT" MODIFY ("TIPUSOPERACIO" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ENTITAT_AUDIT" MODIFY ("ENTITAT_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ENTITAT_AUDIT" MODIFY ("CODI" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ENTITAT_AUDIT" MODIFY ("NOM" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ENTITAT_AUDIT" MODIFY ("DIR3_CODI" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."NOT_PAGADOR_POSTAL" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PAGADOR_POSTAL" ADD PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_PAGADOR_POSTAL" MODIFY ("NOM" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV_TABLE" MODIFY ("CALLBACK_ERROR" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV_TABLE" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV_TABLE" MODIFY ("NOTIFICACIO_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV_TABLE" MODIFY ("ENTITAT_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV_TABLE" MODIFY ("TIPUS_ENVIAMENT" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV_TABLE" MODIFY ("NOT_ESTAT" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV_TABLE" MODIFY ("HAS_ERRORS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV_TABLE" MODIFY ("NOTIFICA_ESTAT" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV_TABLE" MODIFY ("ORGAN_ESTAT" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV_TABLE" MODIFY ("PROCEDIMENT_REQUIRE_PERMISSION" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."NOT_HIST_ENVIAMENTS" ADD CONSTRAINT "NOT_HIST_ENVI_OID_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_HIST_ENVIAMENTS" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_ENVIAMENTS" MODIFY ("ENTITAT_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_ENVIAMENTS" MODIFY ("TIPUS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_ENVIAMENTS" MODIFY ("DATA" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_ENVIAMENTS" MODIFY ("USUARI_CODI" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_ENVIAMENTS" MODIFY ("ESTAT" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_ENVIAMENTS" MODIFY ("ESTAT_NOT" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_ENVIAMENTS" MODIFY ("ENV_TIPUS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_ENVIAMENTS" MODIFY ("N_TOTAL" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_ENVIAMENTS" MODIFY ("N_CORRECTES" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_ENVIAMENTS" MODIFY ("N_AMB_ERROR" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_ENVIAMENTS" MODIFY ("N_ORIGEN_API" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_ENVIAMENTS" MODIFY ("N_ORIGEN_WEB" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_ENVIAMENTS" MODIFY ("N_DESTI_ADM" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_ENVIAMENTS" MODIFY ("N_DESTI_CIUTADA" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_ENVIAMENTS" MODIFY ("VERSION" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."STATE_MACHINE" MODIFY ("MACHINE_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."STATE_MACHINE" ADD PRIMARY KEY ("MACHINE_ID");

ALTER TABLE "NOTIB"."NOT_PRO_GRUP_AUDIT" ADD CONSTRAINT "NOT_PRO_GRUP_AUDIT_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_PRO_GRUP_AUDIT" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PRO_GRUP_AUDIT" MODIFY ("TIPUSOPERACIO" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PRO_GRUP_AUDIT" MODIFY ("PROGRUP_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PRO_GRUP_AUDIT" MODIFY ("PROCEDIMENT" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PRO_GRUP_AUDIT" MODIFY ("GRUP" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."NOT_ACL_ENTRY" ADD CONSTRAINT not_acl_entry_pk PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_ACL_ENTRY" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_ENTRY" MODIFY ("ACL_OBJECT_IDENTITY" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_ENTRY" MODIFY ("ACE_ORDER" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_ENTRY" MODIFY ("SID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_ENTRY" MODIFY ("MASK" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_ENTRY" MODIFY ("GRANTING" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_ENTRY" MODIFY ("AUDIT_SUCCESS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_ENTRY" MODIFY ("AUDIT_FAILURE" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."NOT_GRUP_AUDIT" ADD CONSTRAINT "NOT_GRUP_AUDIT_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_GRUP_AUDIT" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_GRUP_AUDIT" MODIFY ("TIPUSOPERACIO" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_GRUP_AUDIT" MODIFY ("GRUP_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_GRUP_AUDIT" MODIFY ("CODI" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."NOT_PROCESSOS_INICIALS" MODIFY ("CODI" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PROCESSOS_INICIALS" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PROCESSOS_INICIALS" MODIFY ("INIT" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PROCESSOS_INICIALS" ADD CONSTRAINT "NOT_PROCESSOS_INICIALS_PK" PRIMARY KEY ("ID");

ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV" MODIFY ("CALLBACK_ERROR" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV" MODIFY ("NOTIFICA_ERROR" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV" MODIFY ("NOTIFICA_ESTAT" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV" ADD PRIMARY KEY ("ID");

ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" MODIFY ("COM_TIPUS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" MODIFY ("CONCEPTE" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" MODIFY ("EMISOR_DIR3CODI" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" MODIFY ("ENV_TIPUS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" MODIFY ("ESTAT" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" MODIFY ("USUARI_CODI" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" MODIFY ("DOCUMENT_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" MODIFY ("ENTITAT_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" ADD PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" ADD CONSTRAINT "NOT_NOTIFICACIO_UN" UNIQUE ("REFERENCIA");

ALTER TABLE "NOTIB"."NOT_PAGADOR_CIE" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PAGADOR_CIE" ADD PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_PAGADOR_CIE" MODIFY ("NOM" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."NOT_CONFIG_TYPE" ADD CONSTRAINT "NOT_CONFIG_TYPE_PK" PRIMARY KEY ("CODE");
ALTER TABLE "NOTIB"."NOT_CONFIG_TYPE" MODIFY ("CODE" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."NOT_OFICINA" ADD CONSTRAINT "NOT_OFI_PK" PRIMARY KEY ("CODI");
ALTER TABLE "NOTIB"."NOT_OFICINA" MODIFY ("ACTIU" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_OFICINA" MODIFY ("SIR" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_OFICINA" MODIFY ("CODI" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."NOT_GRUP" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_GRUP" MODIFY ("CODI" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_GRUP" ADD PRIMARY KEY ("ID");

ALTER TABLE "NOTIB"."NOT_APLICACIO" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_APLICACIO" MODIFY ("ENTITAT_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_APLICACIO" ADD PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_APLICACIO" MODIFY ("ACTIVA" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."NOT_HIST_ORGAN" ADD CONSTRAINT "NOT_HIST_ORGAN_OID_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_HIST_ORGAN" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_ORGAN" MODIFY ("ENTITAT_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_ORGAN" MODIFY ("TIPUS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_ORGAN" MODIFY ("DATA" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_ORGAN" MODIFY ("CODI_DIR3" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_ORGAN" MODIFY ("NOM" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_ORGAN" MODIFY ("N_PROCEDIMENTS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_ORGAN" MODIFY ("N_GRUPS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_ORGAN" MODIFY ("N_PERM_CONSULTA" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_ORGAN" MODIFY ("N_PERM_NOTIFICACIO" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_ORGAN" MODIFY ("N_PERM_GESTIO" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_ORGAN" MODIFY ("N_PERM_PROCESSAR" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_ORGAN" MODIFY ("N_PERM_ADMINISTRAR" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_ORGAN" MODIFY ("VERSION" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."NOT_HIST_PROCEDIMENT" ADD CONSTRAINT "NOT_HIST_PROC_OID_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_HIST_PROCEDIMENT" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_PROCEDIMENT" MODIFY ("ENTITAT_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_PROCEDIMENT" MODIFY ("TIPUS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_PROCEDIMENT" MODIFY ("DATA" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_PROCEDIMENT" MODIFY ("PROCEDIMENT_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_PROCEDIMENT" MODIFY ("COMU" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_PROCEDIMENT" MODIFY ("CODI_SIA" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_PROCEDIMENT" MODIFY ("NOM" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_PROCEDIMENT" MODIFY ("N_GRUPS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_PROCEDIMENT" MODIFY ("N_PERM_CONSULTA" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_PROCEDIMENT" MODIFY ("N_PERM_NOTIFICACIO" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_PROCEDIMENT" MODIFY ("N_PERM_GESTIO" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_PROCEDIMENT" MODIFY ("N_PERM_PROCESSAR" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_HIST_PROCEDIMENT" MODIFY ("VERSION" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."NOT_ENTREGA_POSTAL" ADD CONSTRAINT "NOT_ENTREGA_POSTAL_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_ENTREGA_POSTAL" MODIFY ("ID" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."NOT_APLICACIO_AUDIT" ADD CONSTRAINT "NOT_APLICACIO_AUDIT_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_APLICACIO_AUDIT" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_APLICACIO_AUDIT" MODIFY ("TIPUSOPERACIO" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_APLICACIO_AUDIT" MODIFY ("APLICACIO_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_APLICACIO_AUDIT" MODIFY ("ENTITAT_ID" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."NOT_ACL_CLASS" ADD CONSTRAINT not_acl_class_pk PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_ACL_CLASS" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_CLASS" MODIFY ("CLASS" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."NOT_PRO_ORGAN" ADD CONSTRAINT "NOT_PRO_ORGAN_PK" PRIMARY KEY ("ID");

ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_AUDIT" ADD CONSTRAINT "NOT_NOTIFICACIO_AUDIT_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_AUDIT" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_AUDIT" MODIFY ("TIPUSOPERACIO" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_AUDIT" MODIFY ("NOTIFICACIO_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_AUDIT" MODIFY ("EMISOR" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_AUDIT" MODIFY ("TIPUS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_AUDIT" MODIFY ("DOCUMENT_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_AUDIT" MODIFY ("ESTAT" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."NOT_DOCUMENT" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_DOCUMENT" ADD PRIMARY KEY ("ID");

ALTER TABLE "NOTIB"."NOT_ENTITAT" MODIFY ("TIPUS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ENTITAT" MODIFY ("VERSION" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ENTITAT" ADD PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_ENTITAT" ADD UNIQUE ("CODI");
ALTER TABLE "NOTIB"."NOT_ENTITAT" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ENTITAT" MODIFY ("ACTIVA" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ENTITAT" MODIFY ("AMB_ENTREGA_DEH" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ENTITAT" MODIFY ("API_KEY" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ENTITAT" MODIFY ("CODI" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ENTITAT" MODIFY ("DIR3_CODI" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ENTITAT" MODIFY ("NOM" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."NOT_ACL_OBJECT_IDENTITY" CONSTRAINT not_acl_object_identity_pk PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_ACL_OBJECT_IDENTITY" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_OBJECT_IDENTITY" MODIFY ("OBJECT_ID_CLASS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_OBJECT_IDENTITY" MODIFY ("OBJECT_ID_IDENTITY" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_OBJECT_IDENTITY" MODIFY ("OWNER_SID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_OBJECT_IDENTITY" MODIFY ("ENTRIES_INHERITING" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_MASSIVA" ADD CONSTRAINT "NOT_NOTIFICACIO_MASSIVA_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_MASSIVA" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_MASSIVA" MODIFY ("ENTITAT_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_MASSIVA" MODIFY ("CSV_GESDOC_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_MASSIVA" MODIFY ("CSV_FILENAME" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_MASSIVA" MODIFY ("CADUCITAT" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_MASSIVA" MODIFY ("PROGRESS" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_TABLE" ADD CONSTRAINT "NOT_NOTIFICACIO_TABLE_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_TABLE" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_TABLE" MODIFY ("ENTITAT_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_TABLE" MODIFY ("ERROR_LAST_CALLBACK" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_TABLE" MODIFY ("ERROR_LAST_EVENT" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_TABLE" MODIFY ("ENV_TIPUS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_TABLE" MODIFY ("CONCEPTE" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_TABLE" MODIFY ("ESTAT" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_TABLE" MODIFY ("PROCEDIMENT_IS_COMU" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_TABLE" MODIFY ("ORGAN_ESTAT" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_TABLE" MODIFY ("PROCEDIMENT_REQUIRE_PERMISSION" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_TABLE" ADD CONSTRAINT "NOT_NOTIFICACIO_TABLE_UN" UNIQUE ("REFERENCIA");

ALTER TABLE "NOTIB"."NOT_ENTREGA_CIE" ADD CONSTRAINT "NOT_ENTREGA_CIE_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_ENTREGA_CIE" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ENTREGA_CIE" MODIFY ("OPERADOR_POSTAL_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ENTREGA_CIE" MODIFY ("CIE_ID" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV_AUDIT" ADD CONSTRAINT "NOT_NOTIFICACIO_ENV_AUDIT_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV_AUDIT" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV_AUDIT" MODIFY ("TIPUSOPERACIO" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV_AUDIT" MODIFY ("ENVIAMENT_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV_AUDIT" MODIFY ("NOTIFICACIO_ID" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."NOT_CONFIG" MODIFY ("KEY" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_CONFIG" MODIFY ("GROUP_CODE" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_CONFIG" MODIFY ("POSITION" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_CONFIG" MODIFY ("JBOSS_PROPERTY" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_CONFIG" ADD CONSTRAINT "NOT_CONFIG_PK" PRIMARY KEY ("KEY");

ALTER TABLE "NOTIB"."NOT_ENTITAT_TIPUS_DOC" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ENTITAT_TIPUS_DOC" ADD PRIMARY KEY ("ID");

ALTER TABLE "NOTIB"."NOT_AVIS" MODIFY ("AVIS_NIVELL" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_AVIS" ADD CONSTRAINT "NOT_AVIS_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_AVIS" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_AVIS" MODIFY ("ASSUMPTE" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_AVIS" MODIFY ("MISSATGE" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_AVIS" MODIFY ("DATA_INICI" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_AVIS" MODIFY ("DATA_FINAL" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_AVIS" MODIFY ("ACTIU" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."NOT_CONFIG_GROUP" ADD CONSTRAINT "NOT_CONFIG_GROUP_PK" PRIMARY KEY ("CODE");
ALTER TABLE "NOTIB"."NOT_CONFIG_GROUP" MODIFY ("CODE" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_CONFIG_GROUP" MODIFY ("POSITION" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_CONFIG_GROUP" MODIFY ("DESCRIPTION" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."NOT_ACL_SID" CONSTRAINT "not_acl_sid_pk" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_ACL_SID" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_SID" MODIFY ("PRINCIPAL" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_SID" MODIFY ("SID" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."NOT_ORGAN_GESTOR" ADD CONSTRAINT "NOT_ORGAN_GESTOR_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_ORGAN_GESTOR" ADD CONSTRAINT "NOT_ORGAN_GESTOR_UK" UNIQUE ("CODI");
ALTER TABLE "NOTIB"."NOT_ORGAN_GESTOR" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ORGAN_GESTOR" MODIFY ("CODI" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_EVENT" MODIFY ("INTENTS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_EVENT" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_EVENT" MODIFY ("DATA" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_EVENT" MODIFY ("ERROR" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_EVENT" MODIFY ("TIPUS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_EVENT" ADD PRIMARY KEY ("ID");

ALTER TABLE "NOTIB"."NOT_FORMATS_FULLA" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_FORMATS_FULLA" ADD PRIMARY KEY ("ID");

ALTER TABLE "NOTIB"."NOT_MON_INT_PARAM" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_MON_INT_PARAM" MODIFY ("MON_INT_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_MON_INT_PARAM" MODIFY ("CODI" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_MON_INT_PARAM" ADD CONSTRAINT "NOT_MON_INT_PARAM_PK" PRIMARY KEY ("ID");

ALTER TABLE "NOTIB"."NOT_FORMATS_SOBRE" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_FORMATS_SOBRE" ADD PRIMARY KEY ("ID");

ALTER TABLE "NOTIB"."NOT_CALLBACK" ADD UNIQUE ("ENVIAMENT_ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
ALTER TABLE "NOTIB"."NOT_CALLBACK" ADD CONSTRAINT "NOT_CALLBACK_PK" PRIMARY KEY ("ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
ALTER TABLE "NOTIB"."NOT_CALLBACK" MODIFY ("INTENTS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_CALLBACK" MODIFY ("ERROR" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_CALLBACK" MODIFY ("ENVIAMENT_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_CALLBACK" MODIFY ("NOTIFICACIO_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_CALLBACK" MODIFY ("USUARI_CODI" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_CALLBACK" MODIFY ("ID" NOT NULL ENABLE);

ALTER TABLE "NOTIB"."NOT_APLICACIO" ADD CONSTRAINT "NOT_APLICACIO_ENTITAT_FK" FOREIGN KEY ("ENTITAT_ID")
    REFERENCES "NOTIB"."NOT_ENTITAT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_APLICACIO" ADD CONSTRAINT "NOT_APLICACIO_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_APLICACIO" ADD CONSTRAINT "NOT_APLICACIO_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;

ALTER TABLE "NOTIB"."NOT_COLUMNES" ADD CONSTRAINT "NOT_COLUMNES_ENTITAT_FK" FOREIGN KEY ("ENTITAT_ID")
    REFERENCES "NOTIB"."NOT_ENTITAT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_COLUMNES" ADD CONSTRAINT "NOT_COLUMNES_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_COLUMNES" ADD CONSTRAINT "NOT_COLUMNES_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_COLUMNES" ADD CONSTRAINT "NOT_COLUMNES_USUARI_FK" FOREIGN KEY ("USUARI_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;

ALTER TABLE "NOTIB"."NOT_CONFIG" ADD CONSTRAINT "NOT_CONFIG_GROUP_FK" FOREIGN KEY ("GROUP_CODE")
    REFERENCES "NOTIB"."NOT_CONFIG_GROUP" ("CODE") ENABLE;

ALTER TABLE "NOTIB"."NOT_DOCUMENT" ADD CONSTRAINT "NOT_DOCUMENT_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_DOCUMENT" ADD CONSTRAINT "NOT_DOCUMENT_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;

ALTER TABLE "NOTIB"."NOT_ENTITAT" ADD CONSTRAINT "NOT_ENTITAT_ENTREGA_CIE_FK" FOREIGN KEY ("ENTREGA_CIE_ID")
    REFERENCES "NOTIB"."NOT_ENTREGA_CIE" ("ID") ON DELETE CASCADE ENABLE;
ALTER TABLE "NOTIB"."NOT_ENTITAT" ADD CONSTRAINT "NOT_ENTITAT_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_ENTITAT" ADD CONSTRAINT "NOT_ENTITAT_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;

ALTER TABLE "NOTIB"."NOT_ENTITAT_TIPUS_DOC" ADD CONSTRAINT "NOT_ENTITAT_TIPUS_DOC_FK" FOREIGN KEY ("ENTITAT_ID")
    REFERENCES "NOTIB"."NOT_ENTITAT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_ENTITAT_TIPUS_DOC" ADD CONSTRAINT "NOT_ENTTIPDOC_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_ENTITAT_TIPUS_DOC" ADD CONSTRAINT "NOT_ENTTIPDOC_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;

ALTER TABLE "NOTIB"."NOT_ENTREGA_CIE" ADD CONSTRAINT "NOT_ENTREGA_CIE_CIE_FK" FOREIGN KEY ("CIE_ID")
    REFERENCES "NOTIB"."NOT_PAGADOR_CIE" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_ENTREGA_CIE" ADD CONSTRAINT "NOT_ENTREGA_CIE_OPERADOR_FK" FOREIGN KEY ("OPERADOR_POSTAL_ID")
    REFERENCES "NOTIB"."NOT_PAGADOR_POSTAL" ("ID") ENABLE;

ALTER TABLE "NOTIB"."NOT_FORMATS_FULLA" ADD CONSTRAINT "NOT_FORMATFULLA_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_FORMATS_FULLA" ADD CONSTRAINT "NOT_FORMATFULLA_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_FORMATS_FULLA" ADD CONSTRAINT "NOT_FORMATS_FULLA_FK" FOREIGN KEY ("PAGADOR_CIE_ID")
    REFERENCES "NOTIB"."NOT_PAGADOR_CIE" ("ID") ENABLE;

ALTER TABLE "NOTIB"."NOT_FORMATS_SOBRE" ADD CONSTRAINT "NOT_FORMATSOBRE_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_FORMATS_SOBRE" ADD CONSTRAINT "NOT_FORMATSOBRE_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_FORMATS_SOBRE" ADD CONSTRAINT "NOT_FORMATS_SOBRE_FK" FOREIGN KEY ("PAGADOR_CIE_ID")
    REFERENCES "NOTIB"."NOT_PAGADOR_CIE" ("ID") ENABLE;

ALTER TABLE "NOTIB"."NOT_GRUP" ADD CONSTRAINT "NOT_ENTITAT_GRUP_FK" FOREIGN KEY ("ENTITAT")
    REFERENCES "NOTIB"."NOT_ENTITAT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_GRUP" ADD CONSTRAINT "NOT_GRUP_ORGAN_FK" FOREIGN KEY ("ORGAN_GESTOR")
    REFERENCES "NOTIB"."NOT_ORGAN_GESTOR" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_GRUP" ADD CONSTRAINT "NOT_GRUP_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_GRUP" ADD CONSTRAINT "NOT_GRUP_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;

ALTER TABLE "NOTIB"."NOT_HIST_ENVIAMENTS" ADD CONSTRAINT "NOT_HIST_ENVI_ENTITAT_FK" FOREIGN KEY ("ENTITAT_ID")
    REFERENCES "NOTIB"."NOT_ENTITAT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_HIST_ENVIAMENTS" ADD CONSTRAINT "NOT_HIST_ENVI_ORGAN_FK" FOREIGN KEY ("ORGAN_ID")
    REFERENCES "NOTIB"."NOT_ORGAN_GESTOR" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_HIST_ENVIAMENTS" ADD CONSTRAINT "NOT_HIST_ENVI_PROCEDIMENT_FK" FOREIGN KEY ("PROCEDIMENT_ID")
    REFERENCES "NOTIB"."NOT_PROCEDIMENT" ("ID") ENABLE;

ALTER TABLE "NOTIB"."NOT_HIST_NOTIF" ADD CONSTRAINT "NOT_HIST_NOTIF_ENTITAT_FK" FOREIGN KEY ("ENTITAT_ID")
    REFERENCES "NOTIB"."NOT_ENTITAT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_HIST_NOTIF" ADD CONSTRAINT "NOT_HIST_NOTIF_ORGAN_FK" FOREIGN KEY ("ORGAN_ID")
    REFERENCES "NOTIB"."NOT_ORGAN_GESTOR" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_HIST_NOTIF" ADD CONSTRAINT "NOT_HIST_NOTIF_PROCEDIMENT_FK" FOREIGN KEY ("PROCEDIMENT_ID")
    REFERENCES "NOTIB"."NOT_PROCEDIMENT" ("ID") ENABLE;

ALTER TABLE "NOTIB"."NOT_HIST_ORGAN" ADD CONSTRAINT "NOT_HIST_ORGANENTITAT_FK" FOREIGN KEY ("ENTITAT_ID")
    REFERENCES "NOTIB"."NOT_ENTITAT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_HIST_ORGAN" ADD CONSTRAINT "NOT_HIST_ORGAN_ORGAN_FK" FOREIGN KEY ("ORGAN_ID")
    REFERENCES "NOTIB"."NOT_ORGAN_GESTOR" ("ID") ENABLE;

ALTER TABLE "NOTIB"."NOT_HIST_PROCEDIMENT" ADD CONSTRAINT "NOT_HIST_PROC_ENTITAT_FK" FOREIGN KEY ("ENTITAT_ID")
    REFERENCES "NOTIB"."NOT_ENTITAT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_HIST_PROCEDIMENT" ADD CONSTRAINT "NOT_HIST_PROC_ORGAN_FK" FOREIGN KEY ("ORGAN_ID")
    REFERENCES "NOTIB"."NOT_ORGAN_GESTOR" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_HIST_PROCEDIMENT" ADD CONSTRAINT "NOT_HIST_PROC_PROCEDIMENT_FK" FOREIGN KEY ("PROCEDIMENT_ID")
    REFERENCES "NOTIB"."NOT_PROCEDIMENT" ("ID") ENABLE;

ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" ADD CONSTRAINT "NOT_DOCUMENT_NOTIFICACIO_FK" FOREIGN KEY ("DOCUMENT_ID")
    REFERENCES "NOTIB"."NOT_DOCUMENT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" ADD CONSTRAINT "NOT_ENTITAT_NOTIFICACIO_FK" FOREIGN KEY ("ENTITAT_ID")
    REFERENCES "NOTIB"."NOT_ENTITAT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" ADD CONSTRAINT "NOT_NOTIFICACIO_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" ADD CONSTRAINT "NOT_NOTIFICACIO_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" ADD CONSTRAINT "NOT_NOTIF_NOTIF_MASSIVA_FK" FOREIGN KEY ("NOTIFICACIO_MASSIVA_ID")
    REFERENCES "NOTIB"."NOT_NOTIFICACIO_MASSIVA" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" ADD CONSTRAINT "NOT_NOT_ORGAN_FK" FOREIGN KEY ("ORGAN_GESTOR")
    REFERENCES "NOTIB"."NOT_ORGAN_GESTOR" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" ADD CONSTRAINT "NOT_PROCEDIMENT_NOT_FK" FOREIGN KEY ("PROCEDIMENT_ID")
    REFERENCES "NOTIB"."NOT_PROCEDIMENT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" ADD CONSTRAINT "NOT_PROCORGAN_NOT_FK" FOREIGN KEY ("PROCEDIMENT_ORGAN_ID")
    REFERENCES "NOTIB"."NOT_PRO_ORGAN" ("ID") ENABLE;

ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV" ADD CONSTRAINT "NOT_ENV_ENTREGA_POSTAL_FK" FOREIGN KEY ("ENTREGA_POSTAL_ID")
    REFERENCES "NOTIB"."NOT_ENTREGA_POSTAL" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV" ADD CONSTRAINT "NOT_NOTENV_NOTEVENT_ERROR_FK" FOREIGN KEY ("NOTIFICA_ERROR_EVENT_ID")
    REFERENCES "NOTIB"."NOT_NOTIFICACIO_EVENT" ("ID") ON DELETE SET NULL ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV" ADD CONSTRAINT "NOT_NOTIFENV_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV" ADD CONSTRAINT "NOT_NOTIFENV_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV" ADD CONSTRAINT "NOT_NOTIFICACIO_NOTENV_FK" FOREIGN KEY ("NOTIFICACIO_ID")
    REFERENCES "NOTIB"."NOT_NOTIFICACIO" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV" ADD CONSTRAINT "NOT_PERSONA_NOTIFICACIO_ENV_FK" FOREIGN KEY ("TITULAR_ID")
    REFERENCES "NOTIB"."NOT_PERSONA" ("ID") ENABLE;

ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_EVENT" ADD CONSTRAINT "NOT_NOTENV_NOTEVE_FK" FOREIGN KEY ("NOTIFICACIO_ENV_ID")
    REFERENCES "NOTIB"."NOT_NOTIFICACIO_ENV" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_EVENT" ADD CONSTRAINT "NOT_NOTIFEVENT_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_EVENT" ADD CONSTRAINT "NOT_NOTIFEVENT_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_EVENT" ADD CONSTRAINT "NOT_NOTIFICACIO_NOTEVENT_FK" FOREIGN KEY ("NOTIFICACIO_ID")
    REFERENCES "NOTIB"."NOT_NOTIFICACIO" ("ID") ENABLE;

ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_MASSIVA" ADD CONSTRAINT "NOT_MASSIVA_ENTITAT_FK" FOREIGN KEY ("ENTITAT_ID")
    REFERENCES "NOTIB"."NOT_ENTITAT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_MASSIVA" ADD CONSTRAINT "NOT_MASSIVA_PAGADOR_POSTAL_FK" FOREIGN KEY ("PAGADOR_POSTAL_ID")
    REFERENCES "NOTIB"."NOT_PAGADOR_POSTAL" ("ID") ENABLE;

ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_TABLE" ADD CONSTRAINT "NOT_NOT_TABLE_NOT_MASSIVA_FK" FOREIGN KEY ("NOTIFICACIO_MASSIVA_ID")
    REFERENCES "NOTIB"."NOT_NOTIFICACIO_MASSIVA" ("ID") ENABLE;

ALTER TABLE "NOTIB"."NOT_OFICINA" ADD CONSTRAINT "NOT_OFI_ENTITAT_FK" FOREIGN KEY ("ENTITAT_ID")
    REFERENCES "NOTIB"."NOT_ENTITAT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_OFICINA" ADD CONSTRAINT "NOT_OFI_ORGAN_FK" FOREIGN KEY ("ORGAN_CODI")
    REFERENCES "NOTIB"."NOT_ORGAN_GESTOR" ("CODI") ENABLE;

ALTER TABLE "NOTIB"."NOT_OG_SINC_REL" ADD CONSTRAINT "NOT_ORGAN_ANTIC_FK" FOREIGN KEY ("ANTIC_OG")
    REFERENCES "NOTIB"."NOT_ORGAN_GESTOR" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_OG_SINC_REL" ADD CONSTRAINT "NOT_ORGAN_NOU_FK" FOREIGN KEY ("NOU_OG")
    REFERENCES "NOTIB"."NOT_ORGAN_GESTOR" ("ID") ENABLE;

ALTER TABLE "NOTIB"."NOT_ORGAN_GESTOR" ADD CONSTRAINT "NOT_ORGAN_ENTITAT_FK" FOREIGN KEY ("ENTITAT")
    REFERENCES "NOTIB"."NOT_ENTITAT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_ORGAN_GESTOR" ADD CONSTRAINT "NOT_ORGAN_ENTREGA_CIE_FK" FOREIGN KEY ("ENTREGA_CIE_ID")
    REFERENCES "NOTIB"."NOT_ENTREGA_CIE" ("ID") ON DELETE CASCADE ENABLE;

ALTER TABLE "NOTIB"."NOT_PAGADOR_CIE" ADD CONSTRAINT "NOT_PAGADORCIE_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_PAGADOR_CIE" ADD CONSTRAINT "NOT_PAGADOR_CIE_ENTITAT_FK" FOREIGN KEY ("ENTITAT")
    REFERENCES "NOTIB"."NOT_ENTITAT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_PAGADOR_CIE" ADD CONSTRAINT "NOT_PAGADOR_CIE_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_PAGADOR_CIE" ADD CONSTRAINT "NOT_PAGCIE_ORGAN_FK" FOREIGN KEY ("ORGAN_GESTOR")
    REFERENCES "NOTIB"."NOT_ORGAN_GESTOR" ("ID") ENABLE;

ALTER TABLE "NOTIB"."NOT_PAGADOR_POSTAL" ADD CONSTRAINT "NOT_PAGADOR_POSTAL_ENTITAT_FK" FOREIGN KEY ("ENTITAT")
    REFERENCES "NOTIB"."NOT_ENTITAT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_PAGADOR_POSTAL" ADD CONSTRAINT "NOT_PAGPOSTAL_ORGAN_FK" FOREIGN KEY ("ORGAN_GESTOR")
    REFERENCES "NOTIB"."NOT_ORGAN_GESTOR" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_PAGADOR_POSTAL" ADD CONSTRAINT "NOT_PAGPOSTAL_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_PAGADOR_POSTAL" ADD CONSTRAINT "NOT_PAGPOSTAL_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;

ALTER TABLE "NOTIB"."NOT_PERSONA" ADD CONSTRAINT "NOT_PERSONA_NOT_FK" FOREIGN KEY ("NOTIFICACIO_ENV_ID")
    REFERENCES "NOTIB"."NOT_NOTIFICACIO_ENV" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_PERSONA" ADD CONSTRAINT "NOT_PERSONA_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_PERSONA" ADD CONSTRAINT "NOT_PERSONA_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;

ALTER TABLE "NOTIB"."NOT_PROCEDIMENT" ADD CONSTRAINT "NOT_ENTITAT_FK" FOREIGN KEY ("ENTITAT")
    REFERENCES "NOTIB"."NOT_ENTITAT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_PROCEDIMENT" ADD CONSTRAINT "NOT_PROCEDIMENT_ENTREGA_CIE_FK" FOREIGN KEY ("ENTREGA_CIE_ID")
    REFERENCES "NOTIB"."NOT_ENTREGA_CIE" ("ID") ON DELETE CASCADE ENABLE;
ALTER TABLE "NOTIB"."NOT_PROCEDIMENT" ADD CONSTRAINT "NOT_PROC_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_PROCEDIMENT" ADD CONSTRAINT "NOT_PROC_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;

ALTER TABLE "NOTIB"."NOT_PRO_GRUP" ADD CONSTRAINT "NOT_GRUP_PRO_FK" FOREIGN KEY ("GRUP")
    REFERENCES "NOTIB"."NOT_GRUP" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_PRO_GRUP" ADD CONSTRAINT "NOT_PROGRUP_USRCREATE_FK" FOREIGN KEY ("CREATEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_PRO_GRUP" ADD CONSTRAINT "NOT_PROGRUP_USRMODIF_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_PRO_GRUP" ADD CONSTRAINT "NOT_PRO_GRUP_FK" FOREIGN KEY ("PROCEDIMENT")
    REFERENCES "NOTIB"."NOT_PROCEDIMENT" ("ID") ENABLE;

ALTER TABLE "NOTIB"."NOT_PRO_ORGAN" ADD CONSTRAINT "NOT_ORGAN_PRO_FK" FOREIGN KEY ("PROCEDIMENT_ID")
    REFERENCES "NOTIB"."NOT_PROCEDIMENT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_PRO_ORGAN" ADD CONSTRAINT "NOT_PRO_ORGAN_FK" FOREIGN KEY ("ORGANGESTOR_ID")
    REFERENCES "NOTIB"."NOT_ORGAN_GESTOR" ("ID") ENABLE;
