-- #131
ALTER TABLE NOT_PERSONA MODIFY (NOM VARCHAR2(255 CHAR));
ALTER TABLE NOT_PERSONA MODIFY (LLINATGE1 VARCHAR2(40 CHAR));
ALTER TABLE NOT_PERSONA MODIFY (LLINATGE2 VARCHAR2(40 CHAR));
ALTER TABLE NOT_PERSONA MODIFY (EMAIL VARCHAR2(255 CHAR));

ALTER TABLE NOT_NOTIFICACIO MODIFY (DESCRIPCIO VARCHAR2(1000 CHAR));

ALTER TABLE NOT_NOTIFICACIO_ENV MODIFY (DOM_VIA_NOM VARCHAR2(50 CHAR));
ALTER TABLE NOT_NOTIFICACIO_ENV MODIFY (DOM_NUM_NUM VARCHAR2(5 CHAR));
ALTER TABLE NOT_NOTIFICACIO_ENV MODIFY (DOM_LINEA1 VARCHAR2(50 CHAR));
ALTER TABLE NOT_NOTIFICACIO_ENV MODIFY (DOM_LINEA2 VARCHAR2(50 CHAR));

ALTER TABLE NOT_GRUP MODIFY (CODI VARCHAR2(255 CHAR));
ALTER TABLE NOT_GRUP MODIFY (NOM VARCHAR2(255 CHAR));