ALTER TABLE not_usuari ADD entitat_defecte NUMBER;
ALTER TABLE not_usuari ADD organ_defecte NUMBER;
ALTER TABLE not_usuari ADD procediment_defecte NUMBER;
ALTER TABLE not_avis MODIFY data_final NULL;
ALTER TABLE not_aplicacio ADD horari_laboral_inici DATE DEFAULT 'TO_DATE(''08:00:00'', ''HH24:MI:SS'')' NOT NULL;
ALTER TABLE not_aplicacio ADD horari_laboral_fi DATE DEFAULT 'TO_DATE(''16:00:00'', ''HH24:MI:SS'')' NOT NULL;
ALTER TABLE not_aplicacio ADD max_env_min_laboral INTEGER DEFAULT '4' NOT NULL;
ALTER TABLE not_aplicacio ADD max_env_min_no_laboral INTEGER DEFAULT '8' NOT NULL;
ALTER TABLE not_aplicacio ADD max_env_dia_laboral INTEGER DEFAULT '8000' NOT NULL;
ALTER TABLE not_aplicacio ADD max_env_dia_no_laboral INTEGER DEFAULT '100000' NOT NULL;
ALTER TABLE not_notificacio_table ADD anulable NUMBER(1) DEFAULT '0';
ALTER TABLE not_notificacio_table ADD last_event_fi_reintents NUMBER(1) DEFAULT '0';
ALTER TABLE not_notificacio_env_table ADD anulable NUMBER(1);
ALTER TABLE not_notificacio_env_table ADD organ_nom VARCHAR2(1000 CHAR);
ALTER TABLE not_notificacio_env_table ADD procediment_nom VARCHAR2(1000 CHAR);
ALTER TABLE not_notificacio_env_table ADD referencia_notificacio VARCHAR2(36 CHAR);
ALTER TABLE not_notificacio_env_table ADD not_id NUMBER(19, 0);
ALTER TABLE not_notificacio_env_table ADD ultim_event_data date;
CREATE INDEX NOT_NOT_ENV_TABLE_USR_CODI_IDX ON NOTIB.NOT_NOTIFICACIO_ENV_TABLE (USUARI_CODI);
CREATE INDEX NOT_ENV_TABLE_CREATEDDATE_IDX ON NOTIB.NOT_NOTIFICACIO_ENV_TABLE (CREATEDDATE);
CREATE INDEX NOT_ENV_TABLE_ORGAN_CODI_IDX ON NOTIB.NOT_NOTIFICACIO_ENV_TABLE (NOT_ORGAN_CODI);
CREATE INDEX NOT_NOT_TABLE_PROCORGAN_ID_IDX ON NOTIB.NOT_NOTIFICACIO_TABLE (PROCEDIMENT_ORGAN_ID);
CREATE INDEX NOT_NOT_TABLE_USUARI_CODI_IDX ON NOTIB.NOT_NOTIFICACIO_TABLE (USUARI_CODI);
ALTER TABLE not_notificacio_env ADD anulat NUMBER(1) DEFAULT '0';
ALTER TABLE not_notificacio_env ADD motiu_anulacio VARCHAR2(250 CHAR);
ALTER TABLE not_notificacio_env_table ADD anulat NUMBER(1) DEFAULT '0';
ALTER TABLE not_notificacio_env_table ADD motiu_anulacio VARCHAR2(250 CHAR);
