-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: db/changelog/db.changelog-master.yaml
-- Ran at: 22/09/21 12:04
-- Against: null@offline:postgresql?changeLogFile=liquibase/databasechangelog.csv
-- Liquibase version: 4.4.3
-- *********************************************************************

-- Changeset db/changelog/initial_schema_table.yaml::init-table-1::limit (generated)
CREATE TABLE NOT_ACL_SID (ID BIGSERIAL NOT NULL, PRINCIPAL BOOLEAN NOT NULL, SID VARCHAR(100) NOT NULL, CONSTRAINT NOT_ACL_SID_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-2::limit (generated)
CREATE TABLE NOT_ACL_OBJECT_IDENTITY (ID BIGSERIAL NOT NULL, OBJECT_ID_CLASS BIGINT NOT NULL, OBJECT_ID_IDENTITY BIGINT NOT NULL, PARENT_OBJECT BIGINT, OWNER_SID BIGINT NOT NULL, ENTRIES_INHERITING BOOLEAN NOT NULL, CONSTRAINT NOT_ACL_OBJECT_IDENTITY_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-3::limit (generated)
CREATE TABLE NOT_ACL_ENTRY (ID BIGSERIAL NOT NULL, ACL_OBJECT_IDENTITY BIGINT NOT NULL, ACE_ORDER BIGINT NOT NULL, SID BIGINT NOT NULL, MASK BIGINT NOT NULL, GRANTING BOOLEAN NOT NULL, AUDIT_SUCCESS BOOLEAN NOT NULL, AUDIT_FAILURE BOOLEAN NOT NULL, CONSTRAINT NOT_ACL_ENTRY_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-4::limit (generated)
CREATE TABLE NOT_ACL_CLASS (ID BIGSERIAL NOT NULL, CLASS VARCHAR(100) NOT NULL, CONSTRAINT NOT_ACL_CLASS_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-5::limit (generated)
CREATE TABLE NOT_APLICACIO (ID BIGINT NOT NULL, CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, CALLBACK_URL VARCHAR(256), USUARI_CODI VARCHAR(64), CREATEDBY_CODI VARCHAR(64), LASTMODIFIEDBY_CODI VARCHAR(64), ENTITAT_ID BIGINT NOT NULL, ACTIVA BOOLEAN DEFAULT TRUE NOT NULL, CONSTRAINT NOT_APLICACIO_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-6::limit (generated)
CREATE TABLE NOT_APLICACIO_AUDIT (ID BIGINT NOT NULL, TIPUSOPERACIO VARCHAR(20) NOT NULL, JOINPOINT VARCHAR(256), CREATEDBY_CODI VARCHAR(64), CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDBY_CODI VARCHAR(64), LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, APLICACIO_ID BIGINT NOT NULL, ENTITAT_ID BIGINT NOT NULL, USUARI_CODI VARCHAR(64), CALLBACK_URL VARCHAR(256), ACTIVA BOOLEAN, CONSTRAINT NOT_APLICACIO_AUDIT_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-7::limit (generated)
CREATE TABLE NOT_AVIS (ID BIGINT NOT NULL, ASSUMPTE VARCHAR(256) NOT NULL, MISSATGE VARCHAR(2048) NOT NULL, DATA_INICI TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, DATA_FINAL TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, ACTIU BOOLEAN NOT NULL, AVIS_NIVELL VARCHAR(10) NOT NULL, CREATEDBY_CODI VARCHAR(64), CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDBY_CODI VARCHAR(64), LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, CONSTRAINT NOT_AVIS_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-8::limit (generated)
CREATE TABLE NOT_COLUMNES (ID BIGINT NOT NULL, CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, CODI_NOTIB_ENV BOOLEAN, CONCEPTE BOOLEAN, CSV_UUID BOOLEAN, DATA_CADUCITAT BOOLEAN, CREATED_DATE BOOLEAN, DATA_PROGRAMADA BOOLEAN, DATA_REGISTRE BOOLEAN, DESCRIPCIO BOOLEAN, DESTINATARIS BOOLEAN, DIR3_CODI BOOLEAN, ENVIAMENT_TIPUS BOOLEAN, ESTAT BOOLEAN, GRUP_CODI BOOLEAN, LLIBRE_REGISTRE BOOLEAN, NOT_IDENTIFICADOR BOOLEAN, NUM_CERTIFICACIO BOOLEAN, NUMERO_REGISTRE BOOLEAN, PRO_CODI BOOLEAN, TITULAR_EMAIL BOOLEAN, TITULAR_NIF BOOLEAN, TITULAR_NOM_LLINATGE BOOLEAN, USUARI BOOLEAN, CREATEDBY_CODI VARCHAR(64), LASTMODIFIEDBY_CODI VARCHAR(64), ENTITAT_ID BIGINT, USUARI_CODI VARCHAR(64), CONSTRAINT NOT_COLUMNES_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-9::limit (generated)
CREATE TABLE NOT_CONFIG (KEY VARCHAR(256) NOT NULL, VALUE VARCHAR(2048), DESCRIPTION VARCHAR(2048), GROUP_CODE VARCHAR(128) NOT NULL, POSITION numeric(3, 0) DEFAULT 0 NOT NULL, JBOSS_PROPERTY BOOLEAN DEFAULT FALSE NOT NULL, TYPE_CODE VARCHAR(128) DEFAULT 'TEXT', LASTMODIFIEDBY_CODI VARCHAR(64), LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, CONSTRAINT NOT_CONFIG_PK PRIMARY KEY (KEY));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-10::limit (generated)
CREATE TABLE NOT_CONFIG_GROUP (CODE VARCHAR(128) NOT NULL, PARENT_CODE VARCHAR(128), POSITION numeric(3, 0) DEFAULT 0 NOT NULL, DESCRIPTION VARCHAR(512) NOT NULL, CONSTRAINT NOT_CONFIG_GROUP_PK PRIMARY KEY (CODE));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-11::limit (generated)
CREATE TABLE NOT_CONFIG_TYPE (CODE VARCHAR(128) NOT NULL, VALUE VARCHAR(2048), CONSTRAINT NOT_CONFIG_TYPE_PK PRIMARY KEY (CODE));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-12::limit (generated)
CREATE TABLE NOT_DOCUMENT (ID BIGINT NOT NULL, CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, ARXIU_GEST_DOC_ID VARCHAR(64), ARXIU_NOM VARCHAR(200), CSV VARCHAR(256), HASH VARCHAR(256), NORMALITZAT BOOLEAN, URL VARCHAR(256), UUID VARCHAR(256), CREATEDBY_CODI VARCHAR(64), LASTMODIFIEDBY_CODI VARCHAR(64), MEDIA VARCHAR(256), MIDA BIGINT, ORIGEN VARCHAR(20), VALIDESA VARCHAR(20), TIPUS_DOCUMENTAL VARCHAR(30), FIRMAT BOOLEAN, CONSTRAINT NOT_DOCUMENT_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-13::limit (generated)
CREATE TABLE NOT_ENTITAT (ID BIGINT NOT NULL, CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, ACTIVA BOOLEAN NOT NULL, AMB_ENTREGA_DEH BOOLEAN NOT NULL, API_KEY VARCHAR(64) NOT NULL, CODI VARCHAR(64) NOT NULL, COLOR_FONS VARCHAR(1024), COLOR_LLETRA VARCHAR(1024), DESCRIPCIO VARCHAR(1024), DIR3_CODI VARCHAR(9) NOT NULL, DIR3_CODI_REG VARCHAR(9), LOGO_CAP BYTEA, LOGO_PEU BYTEA, NOM VARCHAR(256) NOT NULL, TIPUS VARCHAR(32) NOT NULL, TIPUS_DOC_DEFAULT INTEGER, VERSION BIGINT NOT NULL, CREATEDBY_CODI VARCHAR(64), LASTMODIFIEDBY_CODI VARCHAR(64), NOM_OFICINA_VIRTUAL VARCHAR(255), OFICINA VARCHAR(255), LLIBRE VARCHAR(255), LLIBRE_NOM VARCHAR(255), LLIBRE_ENTITAT BOOLEAN, OFICINA_ENTITAT BOOLEAN DEFAULT TRUE, ENTREGA_CIE_ID BIGINT, AMB_ENTREGA_CIE BOOLEAN DEFAULT FALSE, CONSTRAINT NOT_ENTITAT_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-14::limit (generated)
CREATE TABLE NOT_ENTITAT_AUDIT (ID BIGINT NOT NULL, TIPUSOPERACIO VARCHAR(20) NOT NULL, JOINPOINT VARCHAR(256), CREATEDBY_CODI VARCHAR(64), CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDBY_CODI VARCHAR(64), LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, ENTITAT_ID BIGINT NOT NULL, CODI VARCHAR(64) NOT NULL, NOM VARCHAR(256) NOT NULL, TIPUS VARCHAR(32), DIR3_CODI VARCHAR(9) NOT NULL, DIR3_CODI_REG VARCHAR(9), API_KEY VARCHAR(64), AMB_ENTREGA_DEH BOOLEAN, AMB_ENTREGA_CIE BOOLEAN, DESCRIPCIO VARCHAR(1024), ACTIVA BOOLEAN, OFICINA VARCHAR(255), LLIBRE_ENTITAT BOOLEAN, LLIBRE VARCHAR(255), LLIBRE_NOM VARCHAR(255), CONSTRAINT NOT_ENTITAT_AUDIT_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-15::limit (generated)
CREATE TABLE NOT_ENTITAT_TIPUS_DOC (ID BIGINT NOT NULL, CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, TIPUS_DOC INTEGER, CREATEDBY_CODI VARCHAR(64), LASTMODIFIEDBY_CODI VARCHAR(64), ENTITAT_ID BIGINT, CONSTRAINT NOT_ENTITAT_TIPUS_DOC_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-16::limit (generated)
CREATE TABLE NOT_ENTREGA_CIE (ID BIGINT NOT NULL, OPERADOR_POSTAL_ID BIGINT NOT NULL, CIE_ID BIGINT NOT NULL, CREATEDBY_CODI VARCHAR(64), CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDBY_CODI VARCHAR(64), LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, CONSTRAINT NOT_ENTREGA_CIE_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-17::limit (generated)
CREATE TABLE NOT_ENTREGA_POSTAL (ID BIGINT NOT NULL, DOM_TIPUS INTEGER, DOM_CON_TIPUS INTEGER, DOM_VIA_TIPUS INTEGER, DOM_VIA_NOM VARCHAR(50), DOM_NUM_TIPUS INTEGER, DOM_NUM_NUM VARCHAR(5), DOM_NUM_QUALIF VARCHAR(3), DOM_NUM_PUNTKM VARCHAR(10), DOM_APARTAT VARCHAR(10), DOM_BLOC VARCHAR(50), DOM_PORTAL VARCHAR(50), DOM_ESCALA VARCHAR(50), DOM_PLANTA VARCHAR(50), DOM_PORTA VARCHAR(50), DOM_COMPLEM VARCHAR(250), DOM_POBLACIO VARCHAR(30), DOM_MUN_CODINE VARCHAR(6), DOM_MUN_NOM VARCHAR(64), DOM_CODI_POSTAL VARCHAR(10), DOM_PRV_CODI VARCHAR(2), DOM_PRV_NOM VARCHAR(64), DOM_PAI_CODISO VARCHAR(3), DOM_PAI_NOM VARCHAR(64), DOM_LINEA1 VARCHAR(50), DOM_LINEA2 VARCHAR(50), DOM_CIE INTEGER, CREATEDBY_CODI VARCHAR(64), CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDBY_CODI VARCHAR(64), LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, FORMAT_SOBRE VARCHAR(10), FORMAT_FULLA VARCHAR(10), CONSTRAINT NOT_DOMICILI_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-18::limit (generated)
CREATE TABLE NOT_FORMATS_FULLA (ID BIGINT NOT NULL, CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, CODI VARCHAR(64), CREATEDBY_CODI VARCHAR(64), LASTMODIFIEDBY_CODI VARCHAR(64), PAGADOR_CIE_ID BIGINT, CONSTRAINT NOT_FORMATS_FULLA_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-19::limit (generated)
CREATE TABLE NOT_FORMATS_SOBRE (ID BIGINT NOT NULL, CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, CODI VARCHAR(64), CREATEDBY_CODI VARCHAR(64), LASTMODIFIEDBY_CODI VARCHAR(64), PAGADOR_CIE_ID BIGINT, CONSTRAINT NOT_FORMATS_SOBRE_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-20::limit (generated)
CREATE TABLE NOT_GRUP (ID BIGINT NOT NULL, CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, CODI VARCHAR(64) NOT NULL, NOM VARCHAR(100), CREATEDBY_CODI VARCHAR(64), LASTMODIFIEDBY_CODI VARCHAR(64), ENTITAT BIGINT, ORGAN_GESTOR BIGINT, CONSTRAINT NOT_GRUP_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-21::limit (generated)
CREATE TABLE NOT_GRUP_AUDIT (ID BIGINT NOT NULL, TIPUSOPERACIO VARCHAR(20) NOT NULL, JOINPOINT VARCHAR(256), CREATEDBY_CODI VARCHAR(64), CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDBY_CODI VARCHAR(64), LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, GRUP_ID BIGINT NOT NULL, CODI VARCHAR(64) NOT NULL, NOM VARCHAR(100), ENTITAT_ID BIGINT, ORGAN VARCHAR(64), CONSTRAINT NOT_GRUP_AUDIT_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-22::limit (generated)
CREATE TABLE NOT_HIST_ENVIAMENTS (ID BIGINT NOT NULL, ENTITAT_ID BIGINT NOT NULL, ORGAN_ID BIGINT, TIPUS INTEGER NOT NULL, DATA TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, PROCEDIMENT_ID BIGINT, COMU BOOLEAN, GRUP_CODI BIGINT, USUARI_CODI VARCHAR(64) NOT NULL, ESTAT INTEGER NOT NULL, ESTAT_NOT INTEGER NOT NULL, ENV_TIPUS INTEGER NOT NULL, N_TOTAL BIGINT NOT NULL, N_CORRECTES BIGINT NOT NULL, N_AMB_ERROR BIGINT NOT NULL, N_ORIGEN_API BIGINT NOT NULL, N_ORIGEN_WEB BIGINT NOT NULL, N_DESTI_ADM BIGINT NOT NULL, N_DESTI_CIUTADA BIGINT NOT NULL, CREATEDBY_CODI VARCHAR(64), CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDBY_CODI VARCHAR(64), LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, VERSION BIGINT NOT NULL, CONSTRAINT NOT_HIST_ENVI_OID_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-23::limit (generated)
CREATE TABLE NOT_HIST_NOTIF (ID BIGINT NOT NULL, ENTITAT_ID BIGINT NOT NULL, ORGAN_ID BIGINT, TIPUS INTEGER NOT NULL, DATA TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, PROCEDIMENT_ID BIGINT, COMU BOOLEAN, GRUP_CODI BIGINT, USUARI_CODI VARCHAR(64) NOT NULL, ESTAT INTEGER NOT NULL, N_NOT_TOTAL BIGINT NOT NULL, N_NOT_CORRECTES BIGINT NOT NULL, N_NOT_AMB_ERROR BIGINT NOT NULL, N_NOT_ORIGEN_API BIGINT NOT NULL, N_NOT_ORIGEN_WEB BIGINT NOT NULL, N_NOT_DESTI_ADM BIGINT NOT NULL, N_NOT_DESTI_CIUTADA BIGINT NOT NULL, N_COM_TOTAL BIGINT NOT NULL, N_COM_CORRECTES BIGINT NOT NULL, N_COM_AMB_ERROR BIGINT NOT NULL, N_COM_ORIGEN_API BIGINT NOT NULL, N_COM_ORIGEN_WEB BIGINT NOT NULL, N_COM_DESTI_ADM BIGINT NOT NULL, N_COM_DESTI_CIUTADA BIGINT NOT NULL, CREATEDBY_CODI VARCHAR(64), CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDBY_CODI VARCHAR(64), LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, VERSION BIGINT NOT NULL, CONSTRAINT NOT_HIST_NOTIF_OID_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-30::limit (generated)
CREATE TABLE NOT_HIST_ORGAN (ID BIGINT NOT NULL, ENTITAT_ID BIGINT NOT NULL, ORGAN_ID BIGINT, TIPUS INTEGER NOT NULL, DATA TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, CODI_DIR3 VARCHAR(64) NOT NULL, NOM VARCHAR(64) NOT NULL, N_PROCEDIMENTS BIGINT NOT NULL, N_GRUPS BIGINT NOT NULL, N_PERM_CONSULTA BIGINT NOT NULL, N_PERM_NOTIFICACIO BIGINT NOT NULL, N_PERM_GESTIO BIGINT NOT NULL, N_PERM_PROCESSAR BIGINT NOT NULL, N_PERM_ADMINISTRAR BIGINT NOT NULL, CREATEDBY_CODI VARCHAR(64), CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDBY_CODI VARCHAR(64), LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, VERSION BIGINT NOT NULL, CONSTRAINT NOT_HIST_ORGAN_OID_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-31::limit (generated)
CREATE TABLE NOT_HIST_PROCEDIMENT (ID BIGINT NOT NULL, ENTITAT_ID BIGINT NOT NULL, ORGAN_ID BIGINT, TIPUS INTEGER NOT NULL, DATA TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, PROCEDIMENT_ID BIGINT NOT NULL, COMU BOOLEAN NOT NULL, CODI_SIA VARCHAR(64) NOT NULL, NOM VARCHAR(64) NOT NULL, N_GRUPS BIGINT NOT NULL, N_PERM_CONSULTA BIGINT NOT NULL, N_PERM_NOTIFICACIO BIGINT NOT NULL, N_PERM_GESTIO BIGINT NOT NULL, N_PERM_PROCESSAR BIGINT NOT NULL, CREATEDBY_CODI VARCHAR(64), CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDBY_CODI VARCHAR(64), LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, VERSION BIGINT NOT NULL, CONSTRAINT NOT_HIST_PROC_OID_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-32::limit (generated)
CREATE TABLE NOT_NOTIFICACIO (ID BIGINT NOT NULL, CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, CADUCITAT date, COM_TIPUS INTEGER NOT NULL, CONCEPTE VARCHAR(240) NOT NULL, DESCRIPCIO VARCHAR(1000), EMISOR_DIR3CODI VARCHAR(9) NOT NULL, ENV_DATA_PROG date, ENV_TIPUS INTEGER NOT NULL, CALLBACK_ERROR BOOLEAN, ESTAT INTEGER NOT NULL, ESTAT_DATE TIMESTAMP(6) WITHOUT TIME ZONE, GRUP_CODI VARCHAR(64), MOTIU VARCHAR(255), NOT_ENV_DATA TIMESTAMP(6) WITHOUT TIME ZONE, NOT_ENV_INTENT INTEGER, NOT_ERROR_TIPUS INTEGER, REGISTRE_NUM_EXPEDIENT VARCHAR(80), PROC_CODI_NOTIB VARCHAR(9), REGISTRE_DATA date, REGISTRE_ENV_INTENT INTEGER, REGISTRE_NUMERO INTEGER, REGISTRE_NUMERO_FORMATAT VARCHAR(200), RETARD_POSTAL INTEGER, TIPUS_USUARI INTEGER, USUARI_CODI VARCHAR(64) NOT NULL, CREATEDBY_CODI VARCHAR(64), LASTMODIFIEDBY_CODI VARCHAR(64), DOCUMENT_ID BIGINT NOT NULL, ENTITAT_ID BIGINT NOT NULL, PAGADOR_CIE_ID BIGINT, PAGADOR_POSTAL_ID BIGINT, PROCEDIMENT_ID BIGINT, ORGAN_GESTOR VARCHAR(64), PROCEDIMENT_ORGAN_ID BIGINT, NOT_ENV_DATA_NOTIFICA TIMESTAMP(6) WITHOUT TIME ZONE, IDIOMA INTEGER, DOCUMENT2_ID BIGINT, DOCUMENT3_ID BIGINT, DOCUMENT4_ID BIGINT, DOCUMENT5_ID BIGINT, REGISTRE_OFICINA_NOM VARCHAR(255), REGISTRE_LLIBRE_NOM VARCHAR(255), IS_ERROR_LAST_EVENT BOOLEAN DEFAULT FALSE, NOTIFICACIO_MASSIVA_ID BIGINT, CONSTRAINT NOT_NOTIFICACIO_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-33::limit (generated)
CREATE TABLE NOT_NOTIFICACIO_AUDIT (ID BIGINT NOT NULL, TIPUSOPERACIO VARCHAR(20) NOT NULL, JOINPOINT VARCHAR(256), CREATEDBY_CODI VARCHAR(64), CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDBY_CODI VARCHAR(64), LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, NOTIFICACIO_ID BIGINT NOT NULL, SINCRON VARCHAR(20), TIPUS_USUARI VARCHAR(20), USUARI VARCHAR(64), EMISOR VARCHAR(9) NOT NULL, TIPUS VARCHAR(20) NOT NULL, ENTITAT_ID BIGINT, ORGAN VARCHAR(64), PROCEDIMENT VARCHAR(64), GRUP VARCHAR(64), CONCEPTE VARCHAR(255), DESCRIPCIO VARCHAR(1000), NUM_EXPEDIENT VARCHAR(80), ENV_DATA_PROG date, RETARD_POSTAL INTEGER, CADUCITAT date, DOCUMENT_ID BIGINT NOT NULL, ESTAT VARCHAR(20) NOT NULL, ESTAT_DATE TIMESTAMP(6) WITHOUT TIME ZONE, MOTIU VARCHAR(255), PAGADOR_POSTAL_ID BIGINT, PAGADOR_CIE_ID BIGINT, REGISTRE_ENV_INTENT INTEGER, REGISTRE_NUMERO INTEGER, REGISTRE_NUMERO_FORMATAT VARCHAR(200), REGISTRE_DATA date, NOT_ENV_DATA TIMESTAMP(6) WITHOUT TIME ZONE, NOT_ENV_INTENT INTEGER, NOT_ERROR_TIPUS VARCHAR(30), CALLBACK_ERROR BOOLEAN, EVENT_ERROR BIGINT, CONSTRAINT NOT_NOTIFICACIO_AUDIT_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-34::limit (generated)
CREATE TABLE NOT_NOTIFICACIO_ENV (ID BIGINT NOT NULL, CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, DEH_NIF VARCHAR(9), DEH_OBLIGAT BOOLEAN, DEH_PROC_CODI VARCHAR(64), FORMAT_FULLA VARCHAR(10), FORMAT_SOBRE VARCHAR(10), NOTIFICA_ARR_DIR3DESC VARCHAR(100), NOTIFICA_ARR_DIR3CODI VARCHAR(9), NOTIFICA_ARR_DIR3NIF VARCHAR(9), NOTIFICA_CER_ARXIUID VARCHAR(50), NOTIFICA_CER_ARXTIP INTEGER, NOTIFICA_CER_CSV VARCHAR(50), NOTIFICA_CER_DATA TIMESTAMP(6) WITHOUT TIME ZONE, NOTIFICA_CER_HASH VARCHAR(50), NOTIFICA_CER_METAS VARCHAR(255), NOTIFICA_CER_MIME VARCHAR(20), NOTIFICA_CER_NUMSEG VARCHAR(50), NOTIFICA_CER_ORIGEN VARCHAR(20), NOTIFICA_CER_TAMANY INTEGER, NOTIFICA_CER_TIPUS INTEGER, NOTIFICA_DATCAD TIMESTAMP(6) WITHOUT TIME ZONE, NOTIFICA_DATCRE TIMESTAMP(6) WITHOUT TIME ZONE, NOTIFICA_DATDISP TIMESTAMP(6) WITHOUT TIME ZONE, NOTIFICA_DATAT_ERRDES VARCHAR(255), NOTIFICA_DATAT_NUMSEG VARCHAR(50), NOTIFICA_DATAT_ORIGEN VARCHAR(20), NOTIFICA_DATAT_RECNIF VARCHAR(9), NOTIFICA_DATAT_RECNOM VARCHAR(100), NOTIFICA_EMI_DIR3DESC VARCHAR(100), NOTIFICA_EMI_DIR3CODI VARCHAR(9), NOTIFICA_EMI_DIR3NIF VARCHAR(9), NOTIFICA_ERROR BOOLEAN NOT NULL, NOTIFICA_ESTAT INTEGER NOT NULL, NOTIFICA_ESTAT_DATA TIMESTAMP(6) WITHOUT TIME ZONE, NOTIFICA_ESTAT_DATAACT TIMESTAMP(6) WITHOUT TIME ZONE, NOTIFICA_ESTAT_DESC VARCHAR(255), NOTIFICA_ESTAT_FINAL BOOLEAN, NOTIFICA_ID VARCHAR(20), NOTIFICA_INTENT_DATA TIMESTAMP(6) WITHOUT TIME ZONE, NOTIFICA_INTENT_NUM INTEGER, NOTIFICA_REF VARCHAR(20), NOTIFICACIO_ID BIGINT, REGISTRE_DATA TIMESTAMP(6) WITHOUT TIME ZONE, ESTAT_REGISTRE INTEGER, REGISTRE_ESTAT_FINAL BOOLEAN, REGISTRE_NUMERO_FORMATAT VARCHAR(50), SERVEI_TIPUS INTEGER, SIR_CON_DATA TIMESTAMP(6) WITHOUT TIME ZONE, SIR_CON_INTENT INTEGER, SIR_REC_DATA TIMESTAMP(6) WITHOUT TIME ZONE, SIR_REG_DESTI_DATA TIMESTAMP(6) WITHOUT TIME ZONE, CREATEDBY_CODI VARCHAR(64), LASTMODIFIEDBY_CODI VARCHAR(64), NOTIFICA_ERROR_EVENT_ID BIGINT, TITULAR_ID BIGINT NOT NULL, DEH_CERT_INTENT_NUM INTEGER DEFAULT 0, DEH_CERT_INTENT_DATA TIMESTAMP(6) WITHOUT TIME ZONE, CIE_CERT_INTENT_NUM INTEGER DEFAULT 0, CIE_CERT_INTENT_DATA TIMESTAMP(6) WITHOUT TIME ZONE, ENTREGA_POSTAL_ID BIGINT, CONSTRAINT NOT_NOTIFICACIO_ENV_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-35::limit (generated)
CREATE TABLE NOT_NOTIFICACIO_ENV_AUDIT (ID BIGINT NOT NULL, TIPUSOPERACIO VARCHAR(20) NOT NULL, JOINPOINT VARCHAR(256), CREATEDBY_CODI VARCHAR(64), CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDBY_CODI VARCHAR(64), LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, ENVIAMENT_ID BIGINT NOT NULL, NOTIFICACIO_ID BIGINT NOT NULL, TITULAR_ID BIGINT, DESTINATARIS_ID VARCHAR(200), DOMICILI_TIPUS VARCHAR(20), DOMICILI VARCHAR(500), SERVEI_TIPUS VARCHAR(20), CIE INTEGER, FORMAT_SOBRE VARCHAR(10), FORMAT_FULLA VARCHAR(10), DEH_OBLIGAT BOOLEAN, DEH_NIF VARCHAR(9), NOTIFICA_REF VARCHAR(20), NOTIFICA_ID VARCHAR(20), NOTIFICA_DATCRE TIMESTAMP(6) WITHOUT TIME ZONE, NOTIFICA_DATDISP TIMESTAMP(6) WITHOUT TIME ZONE, NOTIFICA_DATCAD TIMESTAMP(6) WITHOUT TIME ZONE, NOTIFICA_EMI_DIR3CODI VARCHAR(9), NOTIFICA_ARR_DIR3CODI VARCHAR(9), NOTIFICA_ESTAT INTEGER, NOTIFICA_ESTAT_DATA TIMESTAMP(6) WITHOUT TIME ZONE, NOTIFICA_ESTAT_FINAL BOOLEAN, NOTIFICA_DATAT_ORIGEN VARCHAR(20), NOTIFICA_DATAT_RECNIF VARCHAR(9), NOTIFICA_DATAT_NUMSEG VARCHAR(50), NOTIFICA_CER_DATA TIMESTAMP(6) WITHOUT TIME ZONE, NOTIFICA_CER_ARXIUID VARCHAR(50), NOTIFICA_CER_ORIGEN VARCHAR(20), NOTIFICA_CER_TIPUS VARCHAR(20), NOTIFICA_CER_ARXTIP VARCHAR(20), NOTIFICA_CER_NUMSEG VARCHAR(50), REGISTRE_NUMERO_FORMATAT VARCHAR(50), REGISTRE_DATA TIMESTAMP(6) WITHOUT TIME ZONE, REGISTRE_ESTAT VARCHAR(20), REGISTRE_ESTAT_FINAL BOOLEAN, SIR_CON_DATA TIMESTAMP(6) WITHOUT TIME ZONE, SIR_REC_DATA TIMESTAMP(6) WITHOUT TIME ZONE, SIR_REG_DESTI_DATA TIMESTAMP(6) WITHOUT TIME ZONE, NOTIFICA_ERROR_EVENT_ID BIGINT, NOTIFICA_ERROR BOOLEAN, NOTIFICA_DATAT_ERRDES VARCHAR(255), CONSTRAINT NOT_NOTIFICACIO_ENV_AUDIT_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-36::limit (generated)
CREATE TABLE NOT_NOTIFICACIO_ENV_TABLE (ID BIGINT NOT NULL, NOTIFICACIO_ID BIGINT NOT NULL, ENTITAT_ID BIGINT NOT NULL, DESTINATARIS VARCHAR(4000) DEFAULT '', TIPUS_ENVIAMENT INTEGER NOT NULL, TITULAR_NIF VARCHAR(9), TITULAR_NOM VARCHAR(256), TITULAR_EMAIL VARCHAR(160), TITULAR_LLINATGE1 VARCHAR(40), TITULAR_LLINATGE2 VARCHAR(40), TITULAR_RAOSOCIAL VARCHAR(100), DATA_PROGRAMADA date, PROCEDIMENT_CODI_NOTIB VARCHAR(9), GRUP_CODI VARCHAR(64), EMISOR_DIR3 VARCHAR(9), USUARI_CODI VARCHAR(64), NOT_ORGAN_CODI VARCHAR(64), CONCEPTE VARCHAR(240), DESCRIPCIO VARCHAR(1000), LLIBRE VARCHAR(255), NOT_ESTAT INTEGER NOT NULL, CSV_UUID VARCHAR(256), HAS_ERRORS BOOLEAN DEFAULT FALSE NOT NULL, PROCEDIMENT_IS_COMU BOOLEAN DEFAULT FALSE, PROCEDIMENT_PROCORGAN_ID BIGINT, REGISTRE_NUMERO INTEGER, REGISTRE_DATA date, REGISTRE_ENVIAMENT_INTENT INTEGER, NOTIFICA_DATA_CADUCITAT TIMESTAMP(6) WITHOUT TIME ZONE, NOTIFICA_IDENTIFICADOR VARCHAR(20), NOTIFICA_CERT_NUM_SEGUIMENT VARCHAR(50), NOTIFICA_ESTAT INTEGER NOT NULL, NOTIFICA_REF VARCHAR(20), CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, CREATEDBY_CODI VARCHAR(64), LASTMODIFIEDBY_CODI VARCHAR(64), LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, ORGAN_ESTAT INTEGER DEFAULT 0 NOT NULL, PROCEDIMENT_REQUIRE_PERMISSION BOOLEAN DEFAULT FALSE NOT NULL, CONSTRAINT NOT_NOTIFICACIO_ENV_TABLE_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-37::limit (generated)
CREATE TABLE NOT_NOTIFICACIO_EVENT (ID BIGINT NOT NULL, CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, CALLBACK_DATA TIMESTAMP(6) WITHOUT TIME ZONE, CALLBACK_ERROR_DESC VARCHAR(2048), CALLBACK_ESTAT VARCHAR(10), CALLBACK_INTENTS INTEGER, DATA TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, DESCRIPCIO VARCHAR(256), ERROR BOOLEAN NOT NULL, ERROR_DESC VARCHAR(2048), NOTIFICACIO_ID BIGINT, TIPUS INTEGER NOT NULL, CREATEDBY_CODI VARCHAR(64), LASTMODIFIEDBY_CODI VARCHAR(64), NOTIFICACIO_ENV_ID BIGINT, NOTIFICA_ERROR_TIPUS INTEGER, CONSTRAINT NOT_NOTIFICACIO_EVENT_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-38::limit (generated)
CREATE TABLE NOT_NOTIFICACIO_MASSIVA (ID BIGINT NOT NULL, ENTITAT_ID BIGINT NOT NULL, CSV_GESDOC_ID VARCHAR(64) NOT NULL, ZIP_GESDOC_ID VARCHAR(64), CSV_FILENAME VARCHAR(200) NOT NULL, ZIP_FILENAME VARCHAR(200), CADUCITAT TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, EMAIL VARCHAR(64), PAGADOR_POSTAL_ID BIGINT, RESUM_GESDOC_ID VARCHAR(64), ERRORS_GESDOC_ID VARCHAR(64), PROGRESS numeric(3, 0) DEFAULT 0 NOT NULL, CREATEDBY_CODI VARCHAR(64), CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDBY_CODI VARCHAR(64), LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, CONSTRAINT NOT_NOTIFICACIO_MASSIVA_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-39::limit (generated)
CREATE TABLE NOT_NOTIFICACIO_TABLE (ID BIGINT NOT NULL, ENTITAT_ID BIGINT NOT NULL, ENTITAT_NOM VARCHAR(256), PROC_CODI_NOTIB VARCHAR(9), PROCEDIMENT_ORGAN_ID BIGINT, GRUP_CODI VARCHAR(64), USUARI_CODI VARCHAR(64), TIPUS_USUARI INTEGER, ERROR_LAST_CALLBACK BOOLEAN DEFAULT FALSE NOT NULL, ERROR_LAST_EVENT BOOLEAN DEFAULT FALSE NOT NULL, REGISTRE_ENV_INTENT INTEGER, REGISTRE_NUM_EXPEDIENT VARCHAR(80), NOTIFICA_ERROR_DATE date, NOTIFICA_ERROR_DESCRIPCIO VARCHAR(2048), ENV_TIPUS INTEGER NOT NULL, CONCEPTE VARCHAR(255) NOT NULL, ESTAT INTEGER NOT NULL, ESTAT_DATE TIMESTAMP(6) WITHOUT TIME ZONE, PROCEDIMENT_CODI VARCHAR(64), PROCEDIMENT_NOM VARCHAR(256), PROCEDIMENT_IS_COMU BOOLEAN DEFAULT FALSE NOT NULL, ORGAN_CODI VARCHAR(64), ORGAN_NOM VARCHAR(1000), CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, CREATEDBY_CODI VARCHAR(64), LASTMODIFIEDBY_CODI VARCHAR(64), LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, ORGAN_ESTAT INTEGER DEFAULT 0 NOT NULL, NOTIFICACIO_MASSIVA_ID BIGINT, PROCEDIMENT_REQUIRE_PERMISSION BOOLEAN DEFAULT FALSE NOT NULL, CONSTRAINT NOT_NOTIFICACIO_TABLE_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-40::limit (generated)
CREATE TABLE NOT_ORGAN_GESTOR (ID BIGINT NOT NULL, CODI VARCHAR(64) NOT NULL, ENTITAT BIGINT, NOM VARCHAR(1000), LLIBRE VARCHAR(255), LLIBRE_NOM VARCHAR(255), OFICINA VARCHAR(255), OFICINA_NOM VARCHAR(255), ESTAT INTEGER DEFAULT 0 NOT NULL, ENTREGA_CIE_ID BIGINT, CONSTRAINT NOT_ORGAN_GESTOR_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-41::limit (generated)
CREATE TABLE NOT_PAGADOR_CIE (ID BIGINT NOT NULL, CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, CONTRACTE_DATA_VIG date, DIR3_CODI VARCHAR(9), CREATEDBY_CODI VARCHAR(64), LASTMODIFIEDBY_CODI VARCHAR(64), ENTITAT BIGINT, ORGAN_GESTOR BIGINT, NOM VARCHAR(256) NOT NULL, CONSTRAINT NOT_PAGADOR_CIE_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-42::limit (generated)
CREATE TABLE NOT_PAGADOR_POSTAL (ID BIGINT NOT NULL, CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, CONTRACTE_DATA_VIG date, CONTRACTE_NUM VARCHAR(20), DIR3_CODI VARCHAR(9), FACTURACIO_CODI_CLIENT VARCHAR(20), CREATEDBY_CODI VARCHAR(64), LASTMODIFIEDBY_CODI VARCHAR(64), ENTITAT BIGINT, ORGAN_GESTOR BIGINT, NOM VARCHAR(256) NOT NULL, CONSTRAINT NOT_PAGADOR_POSTAL_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-43::limit (generated)
CREATE TABLE NOT_PERSONA (ID BIGINT NOT NULL, CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, COD_ENTITAT_DESTI VARCHAR(9), EMAIL VARCHAR(160), INCAPACITAT BOOLEAN, INTERESSATTIPUS VARCHAR(255) NOT NULL, LLINATGE1 VARCHAR(40), LLINATGE2 VARCHAR(40), NIF VARCHAR(9), NOM VARCHAR(255), RAO_SOCIAL VARCHAR(100), TELEFON VARCHAR(16), CREATEDBY_CODI VARCHAR(64), LASTMODIFIEDBY_CODI VARCHAR(64), NOTIFICACIO_ENV_ID BIGINT, CONSTRAINT NOT_PERSONA_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-44::limit (generated)
CREATE TABLE NOT_PROCEDIMENT (ID BIGINT NOT NULL, CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, AGRUPAR BOOLEAN NOT NULL, CADUCITAT INTEGER, CODI VARCHAR(64) NOT NULL, CODIASSUMPTE VARCHAR(255), CODIASSUMPTE_NOM VARCHAR(255), NOM VARCHAR(256) NOT NULL, RETARD INTEGER, TIPUSASSUMPTE VARCHAR(255), TIPUSASSUMPTE_NOM VARCHAR(255), CREATEDBY_CODI VARCHAR(64), LASTMODIFIEDBY_CODI VARCHAR(64), ENTITAT BIGINT, ORGAN_GESTOR VARCHAR(64), COMU BOOLEAN DEFAULT FALSE NOT NULL, ULTIMA_ACT date, DIRECT_PERMISSION_REQUIRED BOOLEAN DEFAULT FALSE NOT NULL, ENTREGA_CIE_ID BIGINT, PAGADORPOSTAL BIGINT, PAGADORCIE BIGINT, CONSTRAINT NOT_PROCEDIMENT_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-45::limit (generated)
CREATE TABLE NOT_PROCEDIMENT_AUDIT (ID BIGINT NOT NULL, TIPUSOPERACIO VARCHAR(20) NOT NULL, JOINPOINT VARCHAR(256), CREATEDBY_CODI VARCHAR(64), CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDBY_CODI VARCHAR(64), LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, PROCEDIMENT_ID BIGINT NOT NULL, ENTITAT_ID BIGINT, ORGAN VARCHAR(64), CODI VARCHAR(64) NOT NULL, NOM VARCHAR(256), RETARD INTEGER, CADUCITAT INTEGER, AGRUPAR BOOLEAN, COMU BOOLEAN, PAGADORPOSTAL_ID BIGINT, PAGADORCIE_ID BIGINT, CONSTRAINT NOT_PROCEDIMENT_AUDIT_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-46::limit (generated)
CREATE TABLE NOT_PRO_GRUP (ID BIGINT NOT NULL, CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, CREATEDBY_CODI VARCHAR(64), LASTMODIFIEDBY_CODI VARCHAR(64), GRUP BIGINT, PROCEDIMENT BIGINT, CONSTRAINT NOT_PRO_GRUP_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-47::limit (generated)
CREATE TABLE NOT_PRO_GRUP_AUDIT (ID BIGINT NOT NULL, TIPUSOPERACIO VARCHAR(20) NOT NULL, JOINPOINT VARCHAR(256), CREATEDBY_CODI VARCHAR(64), CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDBY_CODI VARCHAR(64), LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, PROGRUP_ID BIGINT NOT NULL, PROCEDIMENT VARCHAR(64) NOT NULL, GRUP VARCHAR(64) NOT NULL, CONSTRAINT NOT_PRO_GRUP_AUDIT_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-48::limit (generated)
CREATE TABLE NOT_PRO_ORGAN (ID BIGINT NOT NULL, PROCEDIMENT_ID BIGINT, ORGANGESTOR_ID BIGINT, CREATEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, LASTMODIFIEDDATE TIMESTAMP(6) WITHOUT TIME ZONE, CREATEDBY_CODI VARCHAR(64), LASTMODIFIEDBY_CODI VARCHAR(64), CONSTRAINT NOT_PRO_ORGAN_PK PRIMARY KEY (ID));

-- Changeset db/changelog/initial_schema_table.yaml::init-table-49::limit (generated)
CREATE TABLE NOT_USUARI (CODI VARCHAR(64) NOT NULL, EMAIL VARCHAR(200), IDIOMA VARCHAR(2), LLINATGES VARCHAR(100), NOM VARCHAR(100), NOM_SENCER VARCHAR(200), REBRE_EMAILS BOOLEAN, VERSION BIGINT NOT NULL, ULTIM_ROL VARCHAR(40), ULTIMA_ENTITAT BIGINT, REBRE_EMAILS_CREATS BOOLEAN DEFAULT FALSE NOT NULL, CONSTRAINT NOT_USUARI_PK PRIMARY KEY (CODI));

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-1::limit (generated)
ALTER TABLE NOT_ORGAN_GESTOR ADD CONSTRAINT NOT_ORGAN_GESTOR_UK UNIQUE (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-2::limit (generated)
ALTER TABLE NOT_ENTITAT ADD CONSTRAINT NOT_ENTITAT_CODI_UK UNIQUE (CODI);

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-3::limit (generated)
ALTER TABLE NOT_APLICACIO ADD CONSTRAINT NOT_APLICACIO_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-4::limit (generated)
ALTER TABLE NOT_APLICACIO ADD CONSTRAINT NOT_APLICACIO_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-5::limit (generated)
ALTER TABLE NOT_APLICACIO ADD CONSTRAINT NOT_APLICACIO_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-6::limit (generated)
ALTER TABLE NOT_COLUMNES ADD CONSTRAINT NOT_COLUMNES_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-7::limit (generated)
ALTER TABLE NOT_COLUMNES ADD CONSTRAINT NOT_COLUMNES_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-8::limit (generated)
ALTER TABLE NOT_COLUMNES ADD CONSTRAINT NOT_COLUMNES_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-9::limit (generated)
ALTER TABLE NOT_COLUMNES ADD CONSTRAINT NOT_COLUMNES_USUARI_FK FOREIGN KEY (USUARI_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-10::limit (generated)
ALTER TABLE NOT_CONFIG ADD CONSTRAINT NOT_CONFIG_GROUP_FK FOREIGN KEY (GROUP_CODE) REFERENCES NOT_CONFIG_GROUP (CODE) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-11::limit (generated)
ALTER TABLE NOT_NOTIFICACIO ADD CONSTRAINT NOT_DOCUMENT_NOTIFICACIO_FK FOREIGN KEY (DOCUMENT_ID) REFERENCES NOT_DOCUMENT (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-12::limit (generated)
ALTER TABLE NOT_DOCUMENT ADD CONSTRAINT NOT_DOCUMENT_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-13::limit (generated)
ALTER TABLE NOT_DOCUMENT ADD CONSTRAINT NOT_DOCUMENT_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-14::limit (generated)
ALTER TABLE NOT_ENTITAT ADD CONSTRAINT NOT_ENTITAT_ENTREGA_CIE_FK FOREIGN KEY (ENTREGA_CIE_ID) REFERENCES NOT_ENTREGA_CIE (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-15::limit (generated)
ALTER TABLE NOT_PROCEDIMENT ADD CONSTRAINT NOT_ENTITAT_FK FOREIGN KEY (ENTITAT) REFERENCES NOT_ENTITAT (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-16::limit (generated)
ALTER TABLE NOT_GRUP ADD CONSTRAINT NOT_ENTITAT_GRUP_FK FOREIGN KEY (ENTITAT) REFERENCES NOT_ENTITAT (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-17::limit (generated)
ALTER TABLE NOT_NOTIFICACIO ADD CONSTRAINT NOT_ENTITAT_NOTIFICACIO_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-18::limit (generated)
ALTER TABLE NOT_ENTITAT_TIPUS_DOC ADD CONSTRAINT NOT_ENTITAT_TIPUS_DOC_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-19::limit (generated)
ALTER TABLE NOT_ENTITAT ADD CONSTRAINT NOT_ENTITAT_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-20::limit (generated)
ALTER TABLE NOT_ENTITAT ADD CONSTRAINT NOT_ENTITAT_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-21::limit (generated)
ALTER TABLE NOT_ENTREGA_CIE ADD CONSTRAINT NOT_ENTREGA_CIE_CIE_FK FOREIGN KEY (CIE_ID) REFERENCES NOT_PAGADOR_CIE (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-22::limit (generated)
ALTER TABLE NOT_ENTREGA_CIE ADD CONSTRAINT NOT_ENTREGA_CIE_OPERADOR_FK FOREIGN KEY (OPERADOR_POSTAL_ID) REFERENCES NOT_PAGADOR_POSTAL (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-23::limit (generated)
ALTER TABLE NOT_ENTITAT_TIPUS_DOC ADD CONSTRAINT NOT_ENTTIPDOC_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-24::limit (generated)
ALTER TABLE NOT_ENTITAT_TIPUS_DOC ADD CONSTRAINT NOT_ENTTIPDOC_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-25::limit (generated)
ALTER TABLE NOT_FORMATS_FULLA ADD CONSTRAINT NOT_FORMATFULLA_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-26::limit (generated)
ALTER TABLE NOT_FORMATS_SOBRE ADD CONSTRAINT NOT_FORMATSOBRE_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-27::limit (generated)
ALTER TABLE NOT_FORMATS_FULLA ADD CONSTRAINT NOT_FORMATS_FULLA_FK FOREIGN KEY (PAGADOR_CIE_ID) REFERENCES NOT_PAGADOR_CIE (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-28::limit (generated)
ALTER TABLE NOT_FORMATS_SOBRE ADD CONSTRAINT NOT_FORMATS_SOBRE_FK FOREIGN KEY (PAGADOR_CIE_ID) REFERENCES NOT_PAGADOR_CIE (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-29::limit (generated)
ALTER TABLE NOT_GRUP ADD CONSTRAINT NOT_GRUP_ORGAN_FK FOREIGN KEY (ORGAN_GESTOR) REFERENCES NOT_ORGAN_GESTOR (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-30::limit (generated)
ALTER TABLE NOT_PRO_GRUP ADD CONSTRAINT NOT_GRUP_PRO_FK FOREIGN KEY (GRUP) REFERENCES NOT_GRUP (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-31::limit (generated)
ALTER TABLE NOT_GRUP ADD CONSTRAINT NOT_GRUP_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-32::limit (generated)
ALTER TABLE NOT_GRUP ADD CONSTRAINT NOT_GRUP_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-33::limit (generated)
ALTER TABLE NOT_HIST_ENVIAMENTS ADD CONSTRAINT NOT_HIST_ENVI_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-34::limit (generated)
ALTER TABLE NOT_HIST_ENVIAMENTS ADD CONSTRAINT NOT_HIST_ENVI_ORGAN_FK FOREIGN KEY (ORGAN_ID) REFERENCES NOT_ORGAN_GESTOR (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-35::limit (generated)
ALTER TABLE NOT_HIST_ENVIAMENTS ADD CONSTRAINT NOT_HIST_ENVI_PROCEDIMENT_FK FOREIGN KEY (PROCEDIMENT_ID) REFERENCES NOT_PROCEDIMENT (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-36::limit (generated)
ALTER TABLE NOT_HIST_NOTIF ADD CONSTRAINT NOT_HIST_NOTIF_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-37::limit (generated)
ALTER TABLE NOT_HIST_NOTIF ADD CONSTRAINT NOT_HIST_NOTIF_ORGAN_FK FOREIGN KEY (ORGAN_ID) REFERENCES NOT_ORGAN_GESTOR (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-38::limit (generated)
ALTER TABLE NOT_HIST_NOTIF ADD CONSTRAINT NOT_HIST_NOTIF_PROCEDIMENT_FK FOREIGN KEY (PROCEDIMENT_ID) REFERENCES NOT_PROCEDIMENT (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-39::limit (generated)
ALTER TABLE NOT_HIST_ORGAN ADD CONSTRAINT NOT_HIST_ORGANENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-40::limit (generated)
ALTER TABLE NOT_HIST_ORGAN ADD CONSTRAINT NOT_HIST_ORGAN_ORGAN_FK FOREIGN KEY (ORGAN_ID) REFERENCES NOT_ORGAN_GESTOR (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-41::limit (generated)
ALTER TABLE NOT_HIST_PROCEDIMENT ADD CONSTRAINT NOT_HIST_PROC_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-42::limit (generated)
ALTER TABLE NOT_HIST_PROCEDIMENT ADD CONSTRAINT NOT_HIST_PROC_ORGAN_FK FOREIGN KEY (ORGAN_ID) REFERENCES NOT_ORGAN_GESTOR (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-43::limit (generated)
ALTER TABLE NOT_HIST_PROCEDIMENT ADD CONSTRAINT NOT_HIST_PROC_PROCEDIMENT_FK FOREIGN KEY (PROCEDIMENT_ID) REFERENCES NOT_PROCEDIMENT (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-44::limit (generated)
ALTER TABLE NOT_NOTIFICACIO_MASSIVA ADD CONSTRAINT NOT_MASSIVA_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-45::limit (generated)
ALTER TABLE NOT_NOTIFICACIO_MASSIVA ADD CONSTRAINT NOT_MASSIVA_PAGADOR_POSTAL_FK FOREIGN KEY (PAGADOR_POSTAL_ID) REFERENCES NOT_PAGADOR_POSTAL (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-46::limit (generated)
ALTER TABLE NOT_NOTIFICACIO_EVENT ADD CONSTRAINT NOT_NOTENV_NOTEVE_FK FOREIGN KEY (NOTIFICACIO_ENV_ID) REFERENCES NOT_NOTIFICACIO_ENV (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-47::limit (generated)
ALTER TABLE NOT_NOTIFICACIO_ENV ADD CONSTRAINT NOT_NOTEVE_NOTERR_NOTENV_FK FOREIGN KEY (NOTIFICA_ERROR_EVENT_ID) REFERENCES NOT_NOTIFICACIO_EVENT (ID) ON UPDATE RESTRICT ON DELETE SET NULL;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-48::limit (generated)
ALTER TABLE NOT_NOTIFICACIO_ENV ADD CONSTRAINT NOT_NOTIFENV_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-49::limit (generated)
ALTER TABLE NOT_NOTIFICACIO_ENV ADD CONSTRAINT NOT_NOTIFENV_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-50::limit (generated)
ALTER TABLE NOT_NOTIFICACIO_EVENT ADD CONSTRAINT NOT_NOTIFEVENT_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-51::limit (generated)
ALTER TABLE NOT_NOTIFICACIO_EVENT ADD CONSTRAINT NOT_NOTIFEVENT_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-52::limit (generated)
ALTER TABLE NOT_NOTIFICACIO_ENV ADD CONSTRAINT NOT_NOTIFICACIO_NOTENV_FK FOREIGN KEY (NOTIFICACIO_ID) REFERENCES NOT_NOTIFICACIO (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-53::limit (generated)
ALTER TABLE NOT_NOTIFICACIO ADD CONSTRAINT NOT_NOTIFICACIO_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-54::limit (generated)
ALTER TABLE NOT_NOTIFICACIO ADD CONSTRAINT NOT_NOTIFICACIO_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-55::limit (generated)
ALTER TABLE NOT_NOTIFICACIO_EVENT ADD CONSTRAINT NOT_NOTIFI_NOTEVE_FK FOREIGN KEY (NOTIFICACIO_ID) REFERENCES NOT_NOTIFICACIO (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-56::limit (generated)
ALTER TABLE NOT_NOTIFICACIO ADD CONSTRAINT NOT_NOT_ORGAN_FK FOREIGN KEY (ORGAN_GESTOR) REFERENCES NOT_ORGAN_GESTOR (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-57::limit (generated)
ALTER TABLE NOT_ORGAN_GESTOR ADD CONSTRAINT NOT_ORGAN_ENTITAT_FK FOREIGN KEY (ENTITAT) REFERENCES NOT_ENTITAT (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-58::limit (generated)
ALTER TABLE NOT_ORGAN_GESTOR ADD CONSTRAINT NOT_ORGAN_ENTREGA_CIE_FK FOREIGN KEY (ENTREGA_CIE_ID) REFERENCES NOT_ENTREGA_CIE (ID) ON UPDATE RESTRICT ON DELETE CASCADE;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-59::limit (generated)
ALTER TABLE NOT_PRO_ORGAN ADD CONSTRAINT NOT_ORGAN_PRO_FK FOREIGN KEY (PROCEDIMENT_ID) REFERENCES NOT_PROCEDIMENT (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-60::limit (generated)
ALTER TABLE NOT_PAGADOR_CIE ADD CONSTRAINT NOT_PAGADORCIE_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-61::limit (generated)
ALTER TABLE NOT_PAGADOR_CIE ADD CONSTRAINT NOT_PAGADOR_CIE_ENTITAT_FK FOREIGN KEY (ENTITAT) REFERENCES NOT_ENTITAT (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-62::limit (generated)
ALTER TABLE NOT_NOTIFICACIO ADD CONSTRAINT NOT_PAGADOR_CIE_NOT_FK FOREIGN KEY (PAGADOR_CIE_ID) REFERENCES NOT_PAGADOR_CIE (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-63::limit (generated)
ALTER TABLE NOT_PAGADOR_CIE ADD CONSTRAINT NOT_PAGADOR_CIE_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-64::limit (generated)
ALTER TABLE NOT_PAGADOR_POSTAL ADD CONSTRAINT NOT_PAGADOR_POSTAL_ENTITAT_FK FOREIGN KEY (ENTITAT) REFERENCES NOT_ENTITAT (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-65::limit (generated)
ALTER TABLE NOT_NOTIFICACIO ADD CONSTRAINT NOT_PAGADOR_POSTAL_NOT_FK FOREIGN KEY (PAGADOR_POSTAL_ID) REFERENCES NOT_PAGADOR_POSTAL (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-66::limit (generated)
ALTER TABLE NOT_PAGADOR_CIE ADD CONSTRAINT NOT_PAGCIE_ORGAN_FK FOREIGN KEY (ORGAN_GESTOR) REFERENCES NOT_ORGAN_GESTOR (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-67::limit (generated)
ALTER TABLE NOT_PAGADOR_POSTAL ADD CONSTRAINT NOT_PAGPOSTAL_ORGAN_FK FOREIGN KEY (ORGAN_GESTOR) REFERENCES NOT_ORGAN_GESTOR (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-68::limit (generated)
ALTER TABLE NOT_PAGADOR_POSTAL ADD CONSTRAINT NOT_PAGPOSTAL_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-69::limit (generated)
ALTER TABLE NOT_PAGADOR_POSTAL ADD CONSTRAINT NOT_PAGPOSTAL_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-70::limit (generated)
ALTER TABLE NOT_NOTIFICACIO_ENV ADD CONSTRAINT NOT_PERSONA_NOTIFICACIO_ENV_FK FOREIGN KEY (TITULAR_ID) REFERENCES NOT_PERSONA (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-71::limit (generated)
ALTER TABLE NOT_PERSONA ADD CONSTRAINT NOT_PERSONA_NOT_FK FOREIGN KEY (NOTIFICACIO_ENV_ID) REFERENCES NOT_NOTIFICACIO_ENV (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-72::limit (generated)
ALTER TABLE NOT_PERSONA ADD CONSTRAINT NOT_PERSONA_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-73::limit (generated)
ALTER TABLE NOT_PERSONA ADD CONSTRAINT NOT_PERSONA_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-74::limit (generated)
ALTER TABLE NOT_PROCEDIMENT ADD CONSTRAINT NOT_PROCEDIMENT_ENTREGA_CIE_FK FOREIGN KEY (ENTREGA_CIE_ID) REFERENCES NOT_ENTREGA_CIE (ID) ON UPDATE RESTRICT ON DELETE CASCADE;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-75::limit (generated)
ALTER TABLE NOT_NOTIFICACIO ADD CONSTRAINT NOT_PROCEDIMENT_NOT_FK FOREIGN KEY (PROCEDIMENT_ID) REFERENCES NOT_PROCEDIMENT (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-76::limit (generated)
ALTER TABLE NOT_NOTIFICACIO ADD CONSTRAINT NOT_PROCORGAN_NOT_FK FOREIGN KEY (PROCEDIMENT_ORGAN_ID) REFERENCES NOT_PRO_ORGAN (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-77::limit (generated)
ALTER TABLE NOT_PROCEDIMENT ADD CONSTRAINT NOT_PROC_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-78::limit (generated)
ALTER TABLE NOT_PROCEDIMENT ADD CONSTRAINT NOT_PROC_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-79::limit (generated)
ALTER TABLE NOT_PRO_GRUP ADD CONSTRAINT NOT_PROGRUP_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-80::limit (generated)
ALTER TABLE NOT_PRO_GRUP ADD CONSTRAINT NOT_PROGRUP_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-81::limit (generated)
ALTER TABLE NOT_PRO_GRUP ADD CONSTRAINT NOT_PRO_GRUP_FK FOREIGN KEY (PROCEDIMENT) REFERENCES NOT_PROCEDIMENT (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-82::limit (generated)
ALTER TABLE NOT_PRO_ORGAN ADD CONSTRAINT NOT_PRO_ORGAN_FK FOREIGN KEY (ORGANGESTOR_ID) REFERENCES NOT_ORGAN_GESTOR (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-83::limit (generated)
ALTER TABLE NOT_FORMATS_FULLA ADD CONSTRAINT NOT_FORMATFULLA_USRMODIF_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_constraint.yaml::init-constraint-84::limit (generated)
ALTER TABLE NOT_FORMATS_SOBRE ADD CONSTRAINT NOT_FORMATSOBRE_USRCREATE_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES NOT_USUARI (CODI) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Changeset db/changelog/initial_schema_index.yaml::init-index-1::limit (generated)
CREATE UNIQUE INDEX NOT_ORGAN_GESTOR_I ON NOT_ORGAN_GESTOR(CODI);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-2::limit (generated)
CREATE UNIQUE INDEX NOT_ENTITAT_UK ON NOT_ENTITAT(CODI);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-3::limit (generated)
CREATE INDEX NOT_APLICACIO_AUDIT_EK ON NOT_APLICACIO_AUDIT(APLICACIO_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-4::limit (generated)
CREATE INDEX NOT_AVIS_DATA_FINAL_I ON NOT_AVIS(DATA_FINAL);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-5::limit (generated)
CREATE INDEX NOT_AVIS_DATA_INICI_I ON NOT_AVIS(DATA_INICI);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-6::limit (generated)
CREATE INDEX NOT_ENTITAT_AUDIT_EK ON NOT_ENTITAT_AUDIT(ENTITAT_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-7::limit (generated)
CREATE INDEX NOT_ENTITAT_EK ON NOT_NOTIFICACIO_MASSIVA(ENTITAT_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-8::limit (generated)
CREATE INDEX NOT_ENTITAT_ENTREGA_CIE_EK ON NOT_ENTITAT(ENTREGA_CIE_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-9::limit (generated)
CREATE INDEX NOT_ENTREGA_CIE_CIE_EK ON NOT_ENTREGA_CIE(CIE_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-10::limit (generated)
CREATE INDEX NOT_ENTREGA_CIE_OPERADOR_EK ON NOT_ENTREGA_CIE(OPERADOR_POSTAL_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-11::limit (generated)
CREATE INDEX NOT_GRUP_AUDIT_EK ON NOT_GRUP_AUDIT(GRUP_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-12::limit (generated)
CREATE INDEX NOT_NOTIFICACIO_AUDIT_EK ON NOT_NOTIFICACIO_AUDIT(NOTIFICACIO_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-13::limit (generated)
CREATE INDEX NOT_NOTIFICACIO_ENV_AUDIT_EK ON NOT_NOTIFICACIO_ENV_AUDIT(ENVIAMENT_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-14::limit (generated)
CREATE INDEX NOT_NOTIFICACIO_ENV_DOM_EK ON NOT_NOTIFICACIO_ENV(ENTREGA_POSTAL_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-15::limit (generated)
CREATE INDEX NOT_NOTIF_ESTAT_I ON NOT_NOTIFICACIO(ESTAT);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-16::limit (generated)
CREATE INDEX NOT_NOTIF_ORGAN_FK_I ON NOT_NOTIFICACIO(ORGAN_GESTOR);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-17::limit (generated)
CREATE INDEX NOT_NOTIF_PROCEDIMENT_FK_I ON NOT_NOTIFICACIO(PROCEDIMENT_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-18::limit (generated)
CREATE INDEX NOT_NOTIF_PROCOD_I ON NOT_NOTIFICACIO(PROC_CODI_NOTIB);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-19::limit (generated)
CREATE INDEX NOT_NOTIF_PROORGAN_FK_I ON NOT_NOTIFICACIO(PROCEDIMENT_ORGAN_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-20::limit (generated)
CREATE INDEX NOT_NOTIF_USUARI_I ON NOT_NOTIFICACIO(USUARI_CODI);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-21::limit (generated)
CREATE INDEX NOT_NOT_TABLE_NOT_MASSIVA_EK ON NOT_NOTIFICACIO_TABLE(NOTIFICACIO_MASSIVA_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-22::limit (generated)
CREATE INDEX NOT_ORGAN_EK ON NOT_PRO_ORGAN(ORGANGESTOR_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-23::limit (generated)
CREATE INDEX NOT_ORGAN_ENTITAT_FK_I ON NOT_ORGAN_GESTOR(ENTITAT);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-24::limit (generated)
CREATE INDEX NOT_ORGAN_ENTREGA_CIE_EK ON NOT_ORGAN_GESTOR(ENTREGA_CIE_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-25::limit (generated)
CREATE INDEX NOT_PAGADOR_EK ON NOT_NOTIFICACIO_MASSIVA(PAGADOR_POSTAL_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-26::limit (generated)
CREATE INDEX NOT_PROCEDIMENT_AUDIT_EK ON NOT_PROCEDIMENT_AUDIT(PROCEDIMENT_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-27::limit (generated)
CREATE INDEX NOT_PROCEDIMENT_EK ON NOT_PRO_ORGAN(PROCEDIMENT_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-28::limit (generated)
CREATE INDEX NOT_PROCEDIMENT_ENTREGA_CIE_EK ON NOT_PROCEDIMENT(ENTREGA_CIE_ID);

-- Changeset db/changelog/initial_schema_index.yaml::init-index-29::limit (generated)
CREATE INDEX NOT_PRO_GRUP_AUDIT_EK ON NOT_PRO_GRUP_AUDIT(PROGRUP_ID);

-- Changeset db/changelog/initial_schema_sequence.yaml::init-sequence-1::limit (generated)
CREATE SEQUENCE NOT_ACL_SID_SEQ START WITH 1;

-- Changeset db/changelog/initial_schema_sequence.yaml::init-sequence-2::limit (generated)
CREATE SEQUENCE NOT_ACL_OBJECT_IDENTITY_SEQ START WITH 1;

-- Changeset db/changelog/initial_schema_sequence.yaml::init-sequence-3::limit (generated)
CREATE SEQUENCE NOT_ACL_ENTRY_SEQ START WITH 1;

-- Changeset db/changelog/initial_schema_sequence.yaml::init-sequence-4::limit (generated)
CREATE SEQUENCE NOT_ACL_CLASS_SEQ START WITH 1;

-- Changeset db/changelog/initial_schema_sequence.yaml::init-sequence-5::limit (generated)
CREATE SEQUENCE EVENT_IDENTIFIERS START WITH 1 MAXVALUE 999999999;

-- Changeset db/changelog/initial_schema_sequence.yaml::init-sequence-6::limit (generated)
CREATE SEQUENCE NOT_HIBERNATE_SEQ START WITH 1;

-- Changeset db/changelog/initial_schema_sequence.yaml::init-sequence-7::limit (generated)
CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1;

-- Changeset db/changelog/initial_schema_trigger.yaml::init-trigger-1::limit (generated)
-- Changeset db/changelog/initial_schema_lob.yaml::lob-1::limit (generated)
-- Changeset db/changelog/initial_schema_lob.yaml::lob-2::limit (generated)
-- Changeset db/changelog/initial_schema_grant.yaml::init-grant-1::limit (generated)
-- Changeset db/changelog/initial_schema_inserts.yaml::init-inserts-1::limit
INSERT INTO NOT_CONFIG_TYPE (CODE) VALUES ('BOOL');

INSERT INTO NOT_CONFIG_TYPE (CODE) VALUES ('TEXT');

INSERT INTO NOT_CONFIG_TYPE (CODE) VALUES ('INT');

INSERT INTO NOT_CONFIG_TYPE (CODE) VALUES ('FLOAT');

INSERT INTO NOT_CONFIG_TYPE (CODE) VALUES ('CRON');

INSERT INTO NOT_CONFIG_TYPE (CODE) VALUES ('CREDENTIALS');

INSERT INTO NOT_CONFIG_TYPE (CODE, VALUE) VALUES ('TIPUS_COMUNICACIO', 'ASINCRON,SINCRON');

INSERT INTO NOT_CONFIG_TYPE (CODE, VALUE) VALUES ('NOTIFICA_VERSION', '0,1,2');

INSERT INTO NOT_CONFIG_TYPE (CODE, VALUE) VALUES ('API_PROTOCOL', 'REST,SOAP');

INSERT INTO NOT_CONFIG_TYPE (CODE, VALUE) VALUES ('PRIORITAT_ENVIAMENT_MASSIU', 'ALTA,BAIXA');

INSERT INTO NOT_CONFIG_TYPE (CODE, VALUE) VALUES ('REGISTRE_CLASS', 'es.caib.notib.plugin.registre.RegistrePluginRegweb3Impl,es.caib.notib.plugin.registre.RegistrePluginMockImpl');

INSERT INTO NOT_CONFIG_TYPE (CODE, VALUE) VALUES ('FIRMA_CLASS', 'es.caib.notib.plugin.firmaservidor.FirmaServidorPluginPortafib,es.caib.notib.plugin.firmaservidor.FirmaServidorPluginMock');

INSERT INTO NOT_CONFIG_TYPE (CODE, VALUE) VALUES ('USUARIS_CLASS', 'es.caib.notib.plugin.usuari.DadesUsuariPluginJdbc,es.caib.notib.plugin.usuari.DadesUsuariPluginLdap,es.caib.notib.plugin.usuari.DadesUsuariPluginMock');

INSERT INTO NOT_CONFIG_TYPE (CODE, VALUE) VALUES ('TIPUS_DOCUMENT_ENVIAR', 'CSV,BINARI,TOT');

INSERT INTO NOT_CONFIG_TYPE (CODE) VALUES ('PASSWORD');

INSERT INTO NOT_CONFIG_GROUP (POSITION, CODE, DESCRIPTION) VALUES (0, 'GENERAL', 'Configuracions generals' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, CODE, DESCRIPTION) VALUES (1, 'EMAIL', 'Enviament de correus' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, CODE, DESCRIPTION) VALUES (2, 'SCHEDULLED', 'Configuració de les tasques periòdiques' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, CODE, DESCRIPTION) VALUES (3, 'PLUGINS', 'Plugins de l''aplicació' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, CODE, DESCRIPTION) VALUES (4, 'GES_DOC', 'Gestió documental (Sistema de fitxers)' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, CODE, DESCRIPTION) VALUES (5, 'FIRMA', 'Firma' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, CODE, DESCRIPTION) VALUES (5, 'LOGS', 'Logs del servidor' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, CODE, DESCRIPTION) VALUES (6, 'ASPECTE', 'Aspecte per defecte de l''aplicació' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (1, 'GENERAL', 'TAULA_REMESES', 'Configuració de la taula de remeses' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (2, 'GENERAL', 'FORM_REMESES', 'Configuració del formulari de remeses' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (2, 'GENERAL', 'DOCUMENTS', 'Gestió dels documents' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (3, 'GENERAL', 'DEFAULT_VALUES', 'Valors per defecte configurables' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (1, 'ASPECTE', 'ASPECTE_JUSTIFICANT', 'Valors configurables del justificant' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (1, 'PLUGINS', 'REGISTRE', 'Configuració del registre' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (2, 'PLUGINS', 'NOTIFICA', 'Configuració de notific@' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (3, 'PLUGINS', 'DIR3', 'Configuració del plugin de DIR3' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (4, 'PLUGINS', 'ARXIU', 'Configuració de l''arxiu' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (7, 'PLUGINS', 'USUARIS', 'Configuració del plugin d''usuaris' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (9, 'PLUGINS', 'GESCONADM', 'Plugin de gestió documental administratiu (ROLSAC)' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (1, 'SCHEDULLED', 'SCHEDULLED_REGISTRE', 'Tasca periòdica d''enviament al registre' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (2, 'SCHEDULLED', 'SCHEDULLED_NOTIFICA', 'Tasca periòdica d''enviament a notifica' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (3, 'SCHEDULLED', 'SCHEDULLED_UPDATE_STATUS_NOTIFICA', 'Tasca periòdica d''actualització de l''estat dels enviaments amb l''estat de Notific@' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (3, 'SCHEDULLED', 'SCHEDULLED_UPDATE_STATUS_SIR', 'Tasca periòdica d''actualització de l''estat dels enviaments amb l''estat de enviat_sir' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (5, 'SCHEDULLED', 'SCHEDULLED_PROCEDIMENTS', 'Tasca periòdica d''actualització dels procediments' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES (6, 'SCHEDULLED', 'SCHEDULLED_CALLBACK', 'Tasca periòdica de processament callback pendents' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.emprar.sir', 'true', 'Activar SIR', 'BOOL', 'GENERAL' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (1, 'es.caib.notib.adviser.actiu', 'true', 'Activar ADVISER', 'BOOL', 'GENERAL' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (2, 'es.caib.notib.comunicacio.tipus.defecte', 'ASINCRON', 'TIPUS DE COMUNICACIÓ DE LA PLATAFORMA (SINCRON/ASINCRON)', 'TIPUS_COMUNICACIO', 'GENERAL' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (3, 'es.caib.notib.default.user.language', 'ca', 'Llenguatge per defecte de l''aplicació', 'TEXT', 'GENERAL' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (4, 'es.caib.notib.metriques.generar', 'true', 'Generar mètriques', 'BOOL', 'GENERAL' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (7, 'es.caib.notib.plugin.registre.generar.justificant', 'false', 'Indica si s''ha de generar el justificant del registre de totes les notificacions. ' || 'Si es false només es generen per a comunicacions a administracions (enviaments SIR)', 'BOOL', 'GENERAL' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (9, 'es.caib.notib.notifica.dir3.entitat.permes', 'false', 'Tractar l''entitat com un organ gestor més', 'BOOL', 'GENERAL' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (9, 'es.caib.notib.plugin.codi.dir3.entitat', 'false', 'Si s''activa l''organisme emissor de les notificacions és la mateixa l''entitat', 'BOOL', 'GENERAL' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (10, 'es.caib.notib.document.consulta.id.csv.mida.min', '16', 'Nombre mínim de caràcters que pot tenir un codi CSV', 'INT', 'GENERAL' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (11, 'es.caib.notib.app.base.url', '', 'Especificar la URL base de l''aplicació', 'TEXT', 'GENERAL' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (11, 'es.caib.notib.enviament.massiu.prioritat', 'BAIXA', 'Indica si l''enviament massiu s''ha de prioritzar per a que s''enviin el més aviat possible, ' || 'o si han de tenir una prioritat inferior que la resta de notificacions.', 'PRIORITAT_ENVIAMENT_MASSIU', 'GENERAL' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (5, 'es.caib.notib.documents.metadades.from.arxiu', 'false', 'Indica si volem consultar les metadades dels documents directament de l''arxiu. ' || 'Si no està marcat les metadades son consultades a ConCSV', 'BOOL', 'DOCUMENTS' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (6, 'es.caib.notib.notificacio.document.size', '10485760', 'Mida máxima permesa per a un document d''una notificació  (bytes)', 'INT', 'DOCUMENTS' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (6, 'es.caib.notib.notificacio.document.total.size', '15728640', 'Mida máxima del conjunt de documents d''una notificació (bytes)', 'INT', 'DOCUMENTS' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (7, 'es.caib.notib.document.metadades.por.defecto', 'true', 'Indica si usar valors per defecte quan el document no té metadades ' || 'o no s''envien metadades en la crida a l''API REST d''alta notificació', 'BOOL', 'DOCUMENTS' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (0, 'es.caib.notib.email.remitent', '', 'Remitent dels correus electrònics (correu electrònic)', 'EMAIL' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (0, 'es.caib.notib.email.footer', ' Notib - Govern de les Illes Balears', 'Text del peu dels correus electrònics', 'EMAIL' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasques.actives', 'true', 'Activa les tasques d''actualitzar estat (SIR i Notific@) i la d''enviament de callbacks de forma conjunta', 'BOOL', 'SCHEDULLED' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (1, 'es.caib.notib.tasca.registre.enviaments.processar.max', '10', 'Nombre màxim d''enviaments que es processaran cada cop que s''executi la tasca', 'INT', 'SCHEDULLED_REGISTRE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.registre.enviaments.reintents.maxim', '3', 'Nombre màxim de vegades que una mateixa notificació s''intentarà registrar abans d''obtenir una resposta satisfactòria', 'INT', 'SCHEDULLED_REGISTRE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.notifica.enviaments.actiu', 'true', 'Indica si la tasca periòdica està activa (true/false)', 'BOOL', 'SCHEDULLED_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.notifica.enviaments.processar.max', '10', 'Nombre màxim d''enviaments que es processaran cada cop que s''executi la tasca', 'INT', 'SCHEDULLED_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.notifica.enviaments.reintents.maxim', '3', 'Nombre màxim de vegades que una mateixa notificació s''intentarà enviar a notifica abans d''obtenir una resposta satisfactòria', 'INT', 'SCHEDULLED_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.enviament.actualitzacio.estat.actiu', 'true', 'Indica si la tasca periòdica està activa (true/false)', 'BOOL', 'SCHEDULLED_UPDATE_STATUS_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.enviament.actualitzacio.estat.processar.max', '10', 'Nombre màxim d''enviaments que es processaran cada cop que s''executi la tasca', 'INT', 'SCHEDULLED_UPDATE_STATUS_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.enviament.actualitzacio.estat.reintents.maxim', '3', 'Nombre màxim de vegades que una mateixa notificació s''intentarà enviar a notifica abans d''obtenir una resposta satisfactòria', 'INT', 'SCHEDULLED_UPDATE_STATUS_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.enviament.actualitzacio.estat.registre.actiu', 'true', 'Indica si la tasca periòdica està activa (true/false)', 'BOOL', 'SCHEDULLED_UPDATE_STATUS_SIR' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.enviament.actualitzacio.estat.registre.processar.max', '10', 'Nombre màxim d''enviaments que es processaran cada cop que s''executi la tasca', 'INT', 'SCHEDULLED_UPDATE_STATUS_SIR' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.enviament.actualitzacio.estat.registre.reintents.maxim', '3', 'Nombre màxim de vegades que una mateixa notificació s''intentarà enviar a notifica abans d''obtenir una resposta satisfactòria', 'INT', 'SCHEDULLED_UPDATE_STATUS_SIR' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.callback.pendents.actiu', 'true', 'Indica si la tasca periòdica està activa (true/false)', 'BOOL', 'SCHEDULLED_CALLBACK' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.callback.pendents.processar.max', '50', 'Nombre màxim d''enviaments que es processaran cada cop que s''executi la tasca', 'INT', 'SCHEDULLED_CALLBACK' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.callback.pendents.notifica.events.intents.max', '10', 'Nombre màxim de vegades que s''intentarà enviar un callback sense obtenir una resposta satisfactòria', 'INT', 'SCHEDULLED_CALLBACK' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.callback.pendents.periode', '30000', 'Iterval de temps entre les execucions de la tasca (ms)', 'INT', 'SCHEDULLED_CALLBACK' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.callback.pendents.retard.inicial', '60000', 'Temps a esperar per a executar la tasca per primera vegada un cop arrancat el servidor (ms)', 'INT', 'SCHEDULLED_CALLBACK' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.actualitzacio.procediments.actiu', 'true', 'Indica si la tasca periòdica està activa (true/false)', 'BOOL', 'SCHEDULLED_PROCEDIMENTS' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.actualitzacio.procediments.modificar', 'true', 'Indica si la tasca periòdica ha d''actualitzar els procediments', 'BOOL', 'SCHEDULLED_PROCEDIMENTS' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.actualitzacio.procediments.eliminar.organs', 'false', 'Indica si la tasca periòdica ha d''eliminar els òrgans gestors que han quedat en desús.', 'BOOL', 'SCHEDULLED_PROCEDIMENTS' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (9, 'es.caib.notib.plugin.arxiu.class', 'es.caib.notib.plugin.arxiu.ArxiuPluginConcsvImpl', 'Classe Arxiu', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (10, 'es.caib.notib.plugin.arxiu.gestionar.expedients', 'true', 'Gestionar expedients', 'BOOL', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (11, 'es.caib.notib.plugin.arxiu.gestionar.documents', 'true', 'Gestionar documents', 'BOOL', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (12, 'es.caib.notib.plugin.arxiu.gestionar.carpetes', 'true', 'Gestionar carpetes', 'BOOL', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (13, 'es.caib.notib.plugin.arxiu.document.versionable', 'true', 'Document versionable', 'BOOL', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (14, 'es.caib.notib.plugin.arxiu.suporta.metadades', 'true', 'Suporta metadades', 'BOOL', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (15, 'es.caib.notib.plugin.arxiu.escriptori.classificacio', '000000', 'Escriptori classificació', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (16, 'es.caib.notib.plugin.arxiu.escriptori.serie.documental', 'S0001', 'Escriptori serie documental', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (17, 'es.caib.notib.plugin.arxiu.caib.aplicacio.codi', 'NOTIB', 'Codi aplicació', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (18, 'es.caib.notib.plugin.arxiu.caib.csv.definicio', 'CSV_DEF', 'CSV definició', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (19, 'es.caib.notib.plugin.arxiu.caib.timeout.connect', '20000', 'Timeout connect', 'INT', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (20, 'es.caib.notib.plugin.arxiu.caib.timeout.read', '20000', 'Timeout read', 'INT', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.plugin.registre.class', 'es.caib.notib.plugin.registre.RegistrePluginRegweb3Impl', 'Classe Registre', 'REGISTRE_CLASS', 'REGISTRE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (4, 'es.caib.notib.plugin.registre.namespaceuri', 'urn:es:caib:regweb:ws:v1:services', 'URI del namespace del registre', 'REGISTRE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (5, 'es.caib.notib.plugin.registre.service.name', 'RegwebFacadeService', 'Nom del servei del registre', 'REGISTRE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (6, 'es.caib.notib.plugin.registre.port.name', 'RegwebFacade', 'Nom del port del registre', 'REGISTRE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (7, 'es.caib.notib.plugin.registre.segons.entre.peticions', '30', 'Especificar el nombre mínim de segons que hi pot haver entre peticions per obtenir justificant al registre', 'INT', 'REGISTRE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (8, 'es.caib.notib.plugin.registre.documents.enviar', 'true', 'Indicar si s''han d''enviar els documents al registre', 'BOOL', 'REGISTRE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (11, 'es.caib.notib.plugin.registre.enviamentSir.tipusDocumentEnviar', 'BINARI', 'Enviar document com binari, CSV o ambdós per a enviaments SIR', 'TIPUS_DOCUMENT_ENVIAR', 'REGISTRE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (6, 'es.caib.notib.notifica.versio', '2', 'Versió de notifica a utilitzar: 0 (Mock), 1 o 2', 'NOTIFICA_VERSION', 'NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (0, 'es.caib.notib.plugin.gesdoc.class', 'es.caib.notib.plugin.gesdoc.GestioDocumentalPluginFilesystem', 'Nom de la classe per a gestionar l''emmagatzament de documents', 'GES_DOC' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (1, 'es.caib.notib.plugin.gesdoc.filesystem.base.dir', '', 'Directori del sistema de fitxers on emmagatzemar els documents', 'GES_DOC' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.plugin.dades.usuari.class', 'es.caib.notib.plugin.usuari.DadesUsuariPluginJdbc', 'Classe per a gestionar l''accés al plugin d''usuaris', 'USUARIS_CLASS', 'USUARIS' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (2, 'es.caib.notib.plugin.dades.usuari.jdbc.query.codi', 'select usu_codi, usu_nom, usu_nif, usu_codi||''@limit.es'' from sc_wl_usuari where usu_codi=:codi', 'Consulta d''usuaris per codi', 'USUARIS' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (3, 'es.caib.notib.plugin.dades.usuari.jdbc.query.nif', 'select usu_codi, usu_nom, usu_nif, usu_codi||''@limit.es'' from sc_wl_usuari where usu_nif=:nif', 'Consulta d''usuaris per nif', 'USUARIS' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (4, 'es.caib.notib.plugin.dades.usuari.jdbc.query.rols', 'select ugr_codgru from sc_wl_usugru where ugr_codusu=:codi', 'Consulta d''usuaris per rols', 'USUARIS' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (5, 'es.caib.notib.plugin.dades.usuari.jdbc.query.grup', 'select usu_codi, usu_nom, usu_nif, ''josepg@limit.es'' from sc_wl_usuari u, sc_wl_usugru g where g.ugr_codgru=:grup and g.ugr_codusu=u.usu_codi', 'Consulta d''usuaris per grup', 'USUARIS' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (0, 'es.caib.notib.capsalera.logo', '', 'Especificar la ruta de la imatge per a usar a la capsalera com a logo de l''aplicació per defecte', 'ASPECTE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (1, 'es.caib.notib.peu.logo', '', 'Especificar la ruta de la imatge per a usar al peu com a logo de l''aplicació per defecte', 'ASPECTE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (2, 'es.caib.notib.capsalera.color.fons', '', 'Especificar el color del fons de l''aplicació a usar per defecte', 'ASPECTE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (3, 'es.caib.notib.capsalera.color.lletra', '', 'Especificar el color de la lletra de l''aplicació a usar per defecte', 'ASPECTE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (0, 'es.caib.notib.justificant.capsalera.direccio', '', 'Especificar la direcció postal a mostrar al justificant', 'ASPECTE_JUSTIFICANT' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (1, 'es.caib.notib.justificant.capsalera.nif', '', 'Especificar el NIF a mostrar al justificant', 'ASPECTE_JUSTIFICANT' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (2, 'es.caib.notib.justificant.capsalera.codi', '', 'Especificar el codi a mostrar al justificant', 'ASPECTE_JUSTIFICANT' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (3, 'es.caib.notib.justificant.capsalera.email', '', 'Especificar el correu electrònic a mostrar al justificant', 'ASPECTE_JUSTIFICANT' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (4, 'es.caib.notib.justificant.peu.titol', 'NOTIB - Justificant d''enviament de notificació electrònica', 'Especificar el text a mostrar al peu del justificant', 'ASPECTE_JUSTIFICANT' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (5, 'es.caib.notib.justificant.peu.logo', '', 'Especificar path del logo a mostrar al peu del justificant', 'ASPECTE_JUSTIFICANT' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (6, 'es.caib.notib.justificant.capsalera.logo', '', 'Especificar path del logo a mostrar a la capçalera del justificant', 'ASPECTE_JUSTIFICANT' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (3, 'es.caib.notib.plugin.unitats.dir3.protocol', 'REST', 'API protocol', 'API_PROTOCOL', 'DIR3' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (4, 'es.caib.notib.plugin.unitats.class', 'es.caib.notib.plugin.unitat.UnitatsOrganitzativesPluginDir3', 'Especificar la classe per a accedir a les unitats organitzatives', 'DIR3' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (5, 'es.caib.notib.plugin.unitats.fitxer', '', 'Path del fitxer on vols guardar l''organigrama DIR3 per evitar consultes innecessaries. ' || 'Si no s''especifica sempre que no estigui a cache es consultarà a la API de DIR3.', 'DIR3' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (3, 'es.caib.notib.plugin.gesconadm.class', 'es.caib.notib.plugin.gesconadm.GestorContingutsAdministratiuPluginRolsac', 'Especificar la classe per a accedir al contingut administratiu', 'GESCONADM' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (4, 'es.caib.notib.plugin.gesconadm.basic.authentication', 'false', 'Indicar si authenticació és basic', 'BOOL', 'GESCONADM' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.procediment.alta.auto.retard', '10', 'Valor per defecte del retard d''un procediment', 'INT', 'DEFAULT_VALUES' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (1, 'es.caib.notib.procediment.alta.auto.caducitat', '15', 'Valor per defecte de la caducitat d''un procediment', 'INT', 'DEFAULT_VALUES' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.columna.entitat', 'false', 'Mostrar columna entitat', 'BOOL', 'TAULA_REMESES' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (1, 'es.caib.notib.columna.num.expedient', 'true', 'Mostrar columna expedient', 'BOOL', 'TAULA_REMESES' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.destinatari.multiple', 'false', 'Permetre múltiples representants', 'BOOL', 'FORM_REMESES' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (1, 'es.caib.notib.titular.incapacitat', 'true', 'Permetre interessat amb discapacitat', 'BOOL', 'FORM_REMESES' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.plugin.firmaservidor.class', 'es.caib.notib.plugin.firmaservidor.FirmaServidorPluginPortafib', 'Especificar la classe per a gestionar la firma del servidor', 'FIRMA_CLASS', 'FIRMA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (0, 'es.caib.notib.plugin.firmaservidor.portafib.username', '', 'Nom usuari firma portafib', 'FIRMA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (0, 'es.caib.notib.plugin.firmaservidor.portafib.location', 'Palma', 'Ubicació de la firma portafib', 'FIRMA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, GROUP_CODE) VALUES (0, 'es.caib.notib.plugin.firmaservidor.portafib.signerEmail', 'suport@caib.es', 'Correu electrònic del firmant', 'FIRMA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.permisos.organ.logs', 'false', 'Indica si s''han de generar els logs cada vegada que es consulten els permisos dels organs' , 'BOOL', 'LOGS' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES ( 0, 'es.caib.notib.tasca.enviament.actualitzacio.certificacio.finalitzades.actiu', 'true', 'Indica si la tasca periòdica de consulta de certificació per DEH i CIE està activa (true/false)', 'BOOL', 'SCHEDULLED_NOTIFICA' );

INSERT INTO NOT_CONFIG_GROUP (POSITION, PARENT_CODE, CODE, DESCRIPTION) VALUES ( 7, 'SCHEDULLED', 'SCHEDULLED_UPDATE_CERT_NOTIFICA', 'Tasca periòdica d''actualització de la certificació dels enviaments finalitzats (DEH/CIE) sense certificació' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.enviament.actualitzacio.estat.deh.reintents.maxim', '10', 'Nombre màxim d''enviaments DEH que es processaran cada cop que s''executi la tasca', 'INT', 'SCHEDULLED_UPDATE_CERT_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (1, 'es.caib.notib.tasca.enviament.actualitzacio.estat.cie.reintents.maxim', '10', 'Nombre màxim d''enviaments CIE que es processaran cada cop que s''executi la tasca', 'INT', 'SCHEDULLED_UPDATE_CERT_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (6, 'es.caib.notib.tasca.enviament.deh.actualitzacio.certificacio.processar.max', '10', 'Nombre màxim d''enviaments DEH sense certificació que es processaran cada cop que s''executi la tasca', 'INT', 'SCHEDULLED_UPDATE_CERT_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (7, 'es.caib.notib.tasca.enviament.cie.actualitzacio.certificacio.processar.max', '10', 'Nombre màxim d''enviaments CIE sense certificació que es processaran cada cop que s''executi la tasca', 'INT', 'SCHEDULLED_UPDATE_CERT_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.registre.enviaments.periode', '120000', 'Iterval de temps entre les execucions de la tasca (ms)', 'INT', 'SCHEDULLED_REGISTRE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (2, 'es.caib.notib.tasca.registre.enviaments.retard.inicial', '10000', 'Temps a esperar per a executar la tasca per primera vegada un cop arrancat el servidor (ms)', 'INT', 'SCHEDULLED_REGISTRE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.notifica.enviaments.periode', '120000', 'Iterval de temps entre les execucions de la tasca (ms)', 'INT', 'SCHEDULLED_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.notifica.enviaments.retard.inicial', '10000', 'Temps a esperar per a executar la tasca per primera vegada un cop arrancat el servidor (ms)', 'INT', 'SCHEDULLED_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.enviament.actualitzacio.estat.periode', '300000', 'Iterval de temps entre les execucions de la tasca (ms)', 'INT', 'SCHEDULLED_UPDATE_STATUS_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.enviament.actualitzacio.estat.retard.inicial', '50000', 'Temps a esperar per a executar la tasca per primera vegada un cop arrancat el servidor (ms)', 'INT', 'SCHEDULLED_UPDATE_STATUS_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.enviament.actualitzacio.estat.registre.periode', '600000', 'Iterval de temps entre les execucions de la tasca (ms)', 'INT', 'SCHEDULLED_UPDATE_STATUS_SIR' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.tasca.enviament.actualitzacio.estat.registre.retard.inicial', '400000', 'Temps a esperar per a executar la tasca per primera vegada un cop arrancat el servidor (ms)', 'INT', 'SCHEDULLED_UPDATE_STATUS_SIR' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.refrescar.notificacions.expirades.cron', '0 0 0 * * ?', 'Especificar l''expressió ''cron'' indicant l''interval de temps que vols que es refresquin les notificacions expirades', 'CRON', 'SCHEDULLED' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (0, 'es.caib.notib.actualitzacio.procediments.cron', '0 53 16 * * *', 'Especificar l''expressió ''cron'' indicant la freqüencia en que s''han d''actualitzar els procediments', 'CRON', 'SCHEDULLED_PROCEDIMENTS' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE,  DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES ( 2, 'es.caib.notib.tasca.enviament.deh.actualitzacio.certificacio.periode', '300000', 'Iterval de temps entre les execucions de la tasca (ms) d''enviaments DEH', 'INT', 'SCHEDULLED_UPDATE_CERT_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES ( 3, 'es.caib.notib.tasca.enviament.deh.actualitzacio.certificacio.retard.inicial', '300000', 'Temps a esperar per a executar la tasca per primera vegada un cop arrancat el servidor (ms) dels enviaments DEH', 'INT', 'SCHEDULLED_UPDATE_CERT_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES ( 4, 'es.caib.notib.tasca.enviament.cie.actualitzacio.certificacio.periode', '432000000', 'Iterval de temps entre les execucions de la tasca (ms) d''enviaments CIE', 'INT', 'SCHEDULLED_UPDATE_CERT_NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, VALUE, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES ( 5, 'es.caib.notib.tasca.enviament.cie.actualitzacio.certificacio.retard.inicial', '300000', 'Temps a esperar per a executar la tasca per primera vegada un cop arrancat el servidor (ms) dels enviaments CIE', 'INT', 'SCHEDULLED_UPDATE_CERT_NOTIFICA' );

-- Changeset db/changelog/initial_schema_inserts.yaml::init-inserts-2::limit
-- Changeset db/changelog/initial_schema_inserts.yaml::init-inserts-3::limit
INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (0, 'es.caib.notib.email.jndi', true, 'JNDI email', 'EMAIL' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (0, 'es.caib.notib.plugin.arxiu.caib.base.url', true, 'Url base ARXIU', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (1, 'es.caib.notib.plugin.arxiu.verificacio.baseurl', true, 'URL base per a la verificació de firmes', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (2, 'es.caib.notib.plugin.arxiu.caib.usuari', true, 'Usuari arxiu', 'TEXT', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (3, 'es.caib.notib.plugin.arxiu.caib.contrasenya', true, 'Password arxiu', 'PASSWORD', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (4, 'es.caib.notib.plugin.arxiu.csv.base.url', true, 'URL CSV', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (5, 'es.caib.notib.plugin.arxiu.caib.conversio.imprimible.url.uuid', true, 'Url on generar imprimible per UUID', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (6, 'es.caib.notib.plugin.arxiu.caib.conversio.imprimible.url.csv', true, 'Url on generar imprimible per CSV', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (7, 'es.caib.notib.plugin.arxiu.caib.conversio.imprimible.usuari', true, 'Usuari CONCSV', 'TEXT', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (8, 'es.caib.notib.plugin.arxiu.caib.conversio.imprimible.contrasenya', true, 'Password CONCSV', 'PASSWORD', 'ARXIU' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (9, 'es.caib.notib.plugin.regweb.mock.sequencia', true, 'Ruta a un arxiu de text amb la sequencia per al mock del registre', 'REGISTRE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (10, 'es.caib.notib.plugin.regweb.mock.justificant', true, 'Ruta a un arxiu pdf amb el justificant per al mock del registre', 'REGISTRE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (0, 'es.caib.notib.notifica.url', true, 'Url de notific@', 'NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (1, 'es.caib.notib.notifica.sede.url', true, 'Url de SEDE de notific@', 'NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (2, 'es.caib.notib.notifica.username', true, 'Nom de l''usuari per a accedir a Notific@', 'TEXT', 'NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (3, 'es.caib.notib.notifica.password', true, 'Password per a accedir a Notific@', 'PASSWORD', 'NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (5, 'es.caib.notib.notifica.clau.xifrat.ids', true, 'Clau per al xifrat dels identificadors de les notificacions', 'NOTIFICA' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (1, 'es.caib.notib.plugin.dades.usuari.jdbc.datasource.jndi.name', true, 'Datasource dels usuaris', 'USUARIS' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (0, 'es.caib.notib.plugin.unitats.dir3.url', true, 'Url per accedir als organismes', 'DIR3' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (1, 'es.caib.notib.plugin.unitats.dir3.username', true, 'Nom de l''usuari de DIR3', 'TEXT', 'DIR3' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (2, 'es.caib.notib.plugin.unitats.dir3.password', true, 'Password de DIR3', 'PASSWORD', 'DIR3' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (0, 'es.caib.notib.plugin.gesconadm.base.url', true, 'Url per accedir a gestió documental administratiu', 'GESCONADM' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (1, 'es.caib.notib.plugin.gesconadm.username', true, 'Nom de l''usuari per a accedir a gestió documental administratiu', 'TEXT', 'GESCONADM' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (2, 'es.caib.notib.plugin.gesconadm.password', true, 'Password per a accedir a gestió documental administratiu', 'PASSWORD', 'GESCONADM' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (1, 'es.caib.notib.plugin.registre.url', true, 'Url de registre', 'REGISTRE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, GROUP_CODE) VALUES (2, 'es.caib.notib.plugin.registre.usuari', true, 'Usuari', 'REGISTRE' );

INSERT INTO NOT_CONFIG (POSITION, KEY, JBOSS_PROPERTY, DESCRIPTION, TYPE_CODE, GROUP_CODE) VALUES (3, 'es.caib.notib.plugin.registre.password', true, 'Contrasenya', 'PASSWORD', 'REGISTRE' );

