server:
  servlet:
    context-path: /notibapi/externa

spring:
  mvc:
    view:
      prefix: /WEB_INF/jsp/
      suffix: .jsp

springdoc:
  packages-to-scan: es.caib.notib.api.externa.controller
  api-docs.path: /api-docs
  swagger-ui:
    #    configUrl: /notibapi/interna/api-docs
    path: /rest
    operationsSorter: method
    #    url: /notibapi/interna/
    use-root-path: true