es.caib.notib.fitxers=FILES_PATH

es.caib.notib.plugin.gesdoc.filesystem.base.dir=PLUGIN_GESDOC_BASE_DIR

es.caib.notib.plugin.dades.usuari.pluginsib.userinformation.keycloak.serverurl=https://authdev.limit.es
es.caib.notib.plugin.dades.usuari.pluginsib.userinformation.keycloak.realm=GOIB
es.caib.notib.plugin.dades.usuari.pluginsib.userinformation.keycloak.client_id=goib-ws
es.caib.notib.plugin.dades.usuari.pluginsib.userinformation.keycloak.password_secret=KXbtEBU3kMpiekjvktZSmnpk5cGsnJNY

es.caib.notib.plugin.unitats.dir3.url=PLUGIN_DIR3_URL
es.caib.notib.plugin.unitats.dir3.username=PLUGIN_DIR3_USERNAME
es.caib.notib.plugin.unitats.dir3.password=PLUGIN_DIR3_PASSWORD
es.caib.notib.plugin.unitats.dir3.protocol=PLUGIN_DIR3_PROTOCOL
