-- #189
CREATE TABLE NOT_ORGAN_GESTOR 
(
  ID		NUMBER(19)			NOT NULL,
  CODI		VARCHAR2(64)		NOT NULL,
  ENTITAT	NUMBER(19),				
  NOM		VARCHAR2(1000)
);

ALTER TABLE NOT_ORGAN_GESTOR ADD (CONSTRAINT NOT_ORGAN_GESTOR_PK PRIMARY KEY (ID));
ALTER TABLE NOT_ORGAN_GESTOR ADD (CONSTRAINT NOT_ORGAN_GESTOR_UK UNIQUE (CODI));

-- #215
ALTER TABLE NOT_APLICACIO ADD ENTITAT_ID NUMBER(19);
ALTER TABLE NOT_APLICACIO ADD CONSTRAINT NOT_APLICACIO_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID);

-- #223
ALTER TABLE NOT_NOTIFICACIO ADD CALLBACK_ERROR NUMBER(1) DEFAULT 0 NOT NULL;

-- #230
ALTER TABLE NOT_NOTIFICACIO MODIFY CONCEPTE VARCHAR2(240 CHAR);
ALTER TABLE NOT_PERSONA MODIFY EMAIL VARCHAR2(160 CHAR);
ALTER TABLE NOT_DOCUMENT MODIFY ARXIU_NOM VARCHAR2(200 CHAR);
