-- #223
ALTER TABLE NOT_NOTIFICACIO ADD CALLBACK_ERROR NUMBER(1) DEFAULT 0 NOT NULL;
UPDATE NOT_NOTIFICACIO SET CALLBACK_ERROR = 1 WHERE ID IN (
	SELECT N.ID
	FROM
	    NOT_NOTIFICACIO_EVENT E
	    LEFT OUTER JOIN NOT_NOTIFICACIO N ON E.NOTIFICACIO_ID = N.ID
	WHERE
	    N.TIPUS_USUARI = 0
	    AND E.ERROR = 1
	    AND ( E.TIPUS IN (8, 1, 2, 7, 0) )
	    AND ( E.ID IN (
	        SELECT MAX(E2.ID)
	        FROM NOT_NOTIFICACIO_EVENT E2
	             LEFT OUTER JOIN NOT_NOTIFICACIO N2 ON E2.NOTIFICACIO_ID = N2.ID
	        GROUP BY N2.ID ) 
	    )
);
