-- #189
CREATE TABLE NOT_ORGAN_GESTOR 
(
  ID		NUMBER(19)			NOT NULL,
  CODI		VARCHAR2(64)		NOT NULL,
  ENTITAT	NUMBER(19),				
  NOM		VARCHAR2(1000)
);

ALTER TABLE NOT_ORGAN_GESTOR ADD (CONSTRAINT NOT_ORGAN_GESTOR_PK PRIMARY KEY (ID));
ALTER TABLE NOT_ORGAN_GESTOR ADD (CONSTRAINT NOT_ORGAN_GESTOR_UK UNIQUE (CODI));

INSERT INTO NOT_ORGAN_GESTOR (ID, CODI, ENTITAT)
SELECT NOT_HIBERNATE_SEQ.NEXTVAL, CODI, ENTITAT
FROM (  SELECT DISTINCT PRO.ORGAN_GESTOR AS CODI, PRO.ENTITAT AS ENTITAT
        FROM NOT_PROCEDIMENT PRO
        WHERE PRO.ORGAN_GESTOR IS NOT NULL);

ALTER TABLE NOT_PROCEDIMENT ADD ( CONSTRAINT NOT_PROC_ORGAN_FK FOREIGN KEY (ORGAN_GESTOR) REFERENCES NOT_ORGAN_GESTOR (CODI));
ALTER TABLE NOT_ORGAN_GESTOR ADD ( CONSTRAINT NOT_ORGAN_ENTITAT_FK FOREIGN KEY (ENTITAT) REFERENCES NOT_ENTITAT (ID));
CREATE INDEX NOT_PRO_ORGAN_FK_I ON NOT_PROCEDIMENT(ORGAN_GESTOR);
CREATE INDEX NOT_ORGAN_ENTITAT_FK_I ON NOT_ORGAN_GESTOR(ENTITAT);

-- #215
ALTER TABLE NOT_APLICACIO ADD ENTITAT_ID NUMBER(19);
ALTER TABLE NOT_APLICACIO ADD CONSTRAINT NOT_APLICACIO_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES NOT_ENTITAT (ID);
UPDATE NOT_APLICACIO SET ENTITAT_ID = (SELECT ID FROM NOT_ENTITAT WHERE DIR3_CODI LIKE 'A04003003');
ALTER TABLE NOT_APLICACIO MODIFY ENTITAT_ID NOT NULL;

-- #223
ALTER TABLE NOT_NOTIFICACIO ADD CALLBACK_ERROR NUMBER(1) DEFAULT 0 NOT NULL;
UPDATE NOT_NOTIFICACIO SET CALLBACK_ERROR = 1 WHERE ID IN (
	SELECT N.ID
	FROM
	    NOT_NOTIFICACIO_EVENT E
	    LEFT OUTER JOIN NOT_NOTIFICACIO N ON E.NOTIFICACIO_ID = N.ID
	WHERE
	    N.TIPUS_USUARI = 0
	    AND E.ERROR = 1
	    AND ( E.TIPUS = 8 )
	    AND ( E.ID IN (
	        SELECT MAX(E2.ID)
	        FROM NOT_NOTIFICACIO_EVENT E2
	             LEFT OUTER JOIN NOT_NOTIFICACIO N2 ON E2.NOTIFICACIO_ID = N2.ID
            WHERE E2.TIPUS = 8
	        GROUP BY N2.ID ) 
	    )
);

-- #230
ALTER TABLE NOT_NOTIFICACIO MODIFY CONCEPTE VARCHAR2(240 CHAR);
ALTER TABLE NOT_PERSONA MODIFY EMAIL VARCHAR2(160 CHAR);
ALTER TABLE NOT_DOCUMENT MODIFY ARXIU_NOM VARCHAR2(200 CHAR);