
package es.caib.notib.logic.wsdl.notificaV1;


import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NotificaWsPortType", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NotificaWsPortType {


    /**
     * 
     * @param envioType
     * @return
     *     returns es.caib.notib.logic.wsdl.notificaV1.ResultadoAlta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "altaEnvio", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/", className = "es.caib.notib.logic.wsdl.notificaV1.AltaEnvio")
    @ResponseWrapper(localName = "altaEnvioResponse", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/", className = "es.caib.notib.logic.wsdl.notificaV1.AltaEnvioResponse")
    @Action(input = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/NotificaWs/altaEnvioRequest", output = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/NotificaWs/altaEnvioResponse")
    public ResultadoAlta altaEnvio(
        @WebParam(name = "envio_type", targetNamespace = "")
        TipoEnvio envioType);

    /**
     * 
     * @param identificadorEnvio
     * @return
     *     returns es.caib.notib.logic.wsdl.notificaV1.ResultadoEstado
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaEstado", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/", className = "es.caib.notib.logic.wsdl.notificaV1.ConsultaEstado")
    @ResponseWrapper(localName = "consultaEstadoResponse", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/", className = "es.caib.notib.logic.wsdl.notificaV1.ConsultaEstadoResponse")
    @Action(input = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/NotificaWs/consultaEstadoRequest", output = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/NotificaWs/consultaEstadoResponse")
    public ResultadoEstado consultaEstado(
        @WebParam(name = "identificador_envio", targetNamespace = "")
        String identificadorEnvio);

    /**
     * 
     * @param consultaCies
     * @return
     *     returns es.caib.notib.logic.wsdl.notificaV1.ResultadoGetCies
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaCies", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/", className = "es.caib.notib.logic.wsdl.notificaV1.ConsultaCies")
    @ResponseWrapper(localName = "consultaCiesResponse", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/", className = "es.caib.notib.logic.wsdl.notificaV1.ConsultaCiesResponse")
    @Action(input = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/NotificaWs/consultaCiesRequest", output = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/NotificaWs/consultaCiesResponse")
    public ResultadoGetCies consultaCies(
        @WebParam(name = "consulta_cies", targetNamespace = "")
        ConsultaCie consultaCies);

    /**
     * 
     * @param infoEnvio
     * @return
     *     returns es.caib.notib.logic.wsdl.notificaV1.ResultadoInfoEnvio
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "infoEnvio", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/", className = "es.caib.notib.logic.wsdl.notificaV1.InfoEnvio")
    @ResponseWrapper(localName = "infoEnvioResponse", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/", className = "es.caib.notib.logic.wsdl.notificaV1.InfoEnvioResponse")
    @Action(input = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/NotificaWs/infoEnvioRequest", output = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/NotificaWs/infoEnvioResponse")
    public ResultadoInfoEnvio infoEnvio(
        @WebParam(name = "info_envio", targetNamespace = "")
        InfoEnviament infoEnvio);

    /**
     * 
     * @param identificadorEnvio
     * @return
     *     returns es.caib.notib.logic.wsdl.notificaV1.ResultadoCertificacion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaCertificacionEnvio", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/", className = "es.caib.notib.logic.wsdl.notificaV1.ConsultaCertificacionEnvio")
    @ResponseWrapper(localName = "consultaCertificacionEnvioResponse", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/", className = "es.caib.notib.logic.wsdl.notificaV1.ConsultaCertificacionEnvioResponse")
    @Action(input = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/NotificaWs/consultaCertificacionEnvioRequest", output = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/NotificaWs/consultaCertificacionEnvioResponse")
    public ResultadoCertificacion consultaCertificacionEnvio(
        @WebParam(name = "identificador_envio", targetNamespace = "")
        String identificadorEnvio);

    /**
     * 
     * @param identificadorEnvio
     * @return
     *     returns es.caib.notib.logic.wsdl.notificaV1.ResultadoDatado
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaDatadoEnvio", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/", className = "es.caib.notib.logic.wsdl.notificaV1.ConsultaDatadoEnvio")
    @ResponseWrapper(localName = "consultaDatadoEnvioResponse", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/", className = "es.caib.notib.logic.wsdl.notificaV1.ConsultaDatadoEnvioResponse")
    @Action(input = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/NotificaWs/consultaDatadoEnvioRequest", output = "https://administracionelectronica.gob.es/notifica/ws/notifica/1.0/NotificaWs/consultaDatadoEnvioResponse")
    public ResultadoDatado consultaDatadoEnvio(
        @WebParam(name = "identificador_envio", targetNamespace = "")
        String identificadorEnvio);

}
