CREATE TABLE NOT_PROCEDIMENT 
(
  ID						NUMBER(19)	    NOT NULL,
  CODI          			VARCHAR2(64)		NOT NULL,
  NOM						VARCHAR2(100),
  CODISIA					VARCHAR2(64),
  ENTITAT					NUMBER(19),
  PAGADORPOSTAL				NUMBER(19),
  PAGADORCIE				NUMBER(19),
  AGRUPAR					NUMBER(1) 			NOT NULL,
  DATA_PROGRAMADA			TIMESTAMP(6),
  RETARD					NUMBER(19),
  CREATEDBY_CODI       		VARCHAR2(64),
  CREATEDDATE          		TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  		VARCHAR2(64),
  LASTMODIFIEDDATE     		TIMESTAMP(6)
);

CREATE TABLE NOT_GRUP 
(
  ID						NUMBER(19)	    NOT NULL,
  CODI						VARCHAR2(64)		NOT NULL,
  NOM						VARCHAR2(100),
  CREATEDBY_CODI       		VARCHAR2(64),
  CREATEDDATE          		TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  		VARCHAR2(64),
  LASTMODIFIEDDATE     		TIMESTAMP(6),
  ENTITAT				NUMBER(19)
);

CREATE TABLE NOT_PAGADOR_POSTAL
(
  ID						NUMBER(19)	    NOT NULL,
  DIR3_CODI            		VARCHAR2(9)  		NOT NULL,
  CONTRACTE_NUM		       	VARCHAR2(20),
  CONTRACTE_DATA_VIG      	DATE,
  FACTURACIO_CODI_CLIENT   	VARCHAR2(20),
  CREATEDBY_CODI       		VARCHAR2(64),
  CREATEDDATE          		TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  		VARCHAR2(64),
  LASTMODIFIEDDATE     		TIMESTAMP(6)
);

CREATE TABLE NOT_PAGADOR_CIE
(
  ID						NUMBER(19)	    NOT NULL,
  DIR3_CODI            		VARCHAR2(9)  		NOT NULL,
  CONTRACTE_DATA_VIG      	DATE,
  CREATEDBY_CODI       		VARCHAR2(64),
  CREATEDDATE          		TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  		VARCHAR2(64),
  LASTMODIFIEDDATE     		TIMESTAMP(6)
);

CREATE TABLE NOT_PRO_GRUP 
(
  ID						NUMBER(19)	    	NOT NULL,
  GRUP						NUMBER(19),			
  PROCEDIMENT				NUMBER(19),
  CREATEDBY_CODI       		VARCHAR2(64),
  CREATEDDATE          		TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  		VARCHAR2(64),
  LASTMODIFIEDDATE     		TIMESTAMP(6)
);

ALTER TABLE NOT_PROCEDIMENT ADD (
  CONSTRAINT NOT_PROCEDIMENT_PK PRIMARY KEY (ID));
  
ALTER TABLE NOT_GRUP ADD (
  CONSTRAINT NOT_GRUP_PK PRIMARY KEY (ID));
  
ALTER TABLE NOT_PAGADOR_POSTAL ADD (
  CONSTRAINT NOT_PAGADOR_POSTAL_PK PRIMARY KEY (ID));
  
ALTER TABLE NOT_PAGADOR_CIE ADD (
  CONSTRAINT NOT_PAGADOR_CIE_PK PRIMARY KEY (ID));
  
ALTER TABLE NOT_PROCEDIMENT ADD (
  CONSTRAINT NOT_PAGADOR_POSTAL_FK FOREIGN KEY (PAGADORPOSTAL)
    REFERENCES NOT_PAGADOR_POSTAL (ID));
  
ALTER TABLE NOT_PROCEDIMENT ADD (
  CONSTRAINT NOT_PAGADOR_CIE_FK FOREIGN KEY (PAGADORCIE)
    REFERENCES NOT_PAGADOR_CIE (ID));
    
ALTER TABLE NOT_PROCEDIMENT ADD (
  CONSTRAINT NOT_ENTITAT_FK FOREIGN KEY (ENTITAT)
    REFERENCES NOT_ENTITAT (ID));