-- #84
ALTER TABLE NOT_PROCEDIMENT ADD ORGAN_GESTOR VARCHAR2(19);
ALTER TABLE NOT_PROCEDIMENT ADD ORGAN_GESTOR_NOM VARCHAR2(64);
ALTER TABLE NOT_PROCEDIMENT ADD OFICINA_NOM VARCHAR2(64);
ALTER TABLE NOT_PROCEDIMENT ADD LLIBRE_NOM VARCHAR2(64);
ALTER TABLE NOT_PROCEDIMENT ADD TIPUSASSUMPTE_NOM VARCHAR2(64);
ALTER TABLE NOT_PROCEDIMENT ADD CODIASSUMPTE_NOM VARCHAR2(64);
ALTER TABLE NOT_NOTIFICACIO ADD ORGAN_GESTOR VARCHAR2(19);