-- #92
ALTER TABLE NOT_ENTITAT ADD LOGO_CAP BLOB;
ALTER TABLE NOT_ENTITAT ADD LOGO_PEU BLOB;
ALTER TABLE NOT_ENTITAT ADD COLOR_FONS VARCHAR2(32);
ALTER TABLE NOT_ENTITAT ADD COLOR_LLETRA VARCHAR2(32);

CREATE TABLE NOT_ENTITAT_TIPUS_DOC
(
  ID            			NUMBER(19),
  ENTITAT_ID				NUMBER(19),
  TIPUS_DOC					NUMBER(32),
  TIPUS_DOC_DEFAULT			NUMBER(1),
  CREATEDBY_CODI       		VARCHAR2(64),
  CREATEDDATE          		TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  		VARCHAR2(64),
  LASTMODIFIEDDATE     		TIMESTAMP(6)
)

ALTER TABLE NOT_ENTITAT_TIPUS_DOC ADD (
  CONSTRAINT NOT_ENTITAT_TIPUS_DOC_PK PRIMARY KEY (ID));

ALTER TABLE NOT_ENTITAT_TIPUS_DOC ADD (
  CONSTRAINT NOT_ENTITAT_TIPUS_DOC_FK FOREIGN KEY (ENTITAT_ID)
    REFERENCES NOT_ENTITAT (ID));
	
CREATE INDEX NOT_ENTITAT_TIPUS_DOC_FK_I ON NOT_ENTITAT_TIPUS_DOC(ENTITAT_ID);


