CREATE TABLE NOT_COLUMNES
(
  ID                   		NUMBER(19),
  CREATED_DATE      		NUMBER(1),
  DATA_PROGRAMADA           NUMBER(1),
  NOT_IDENTIFICADOR         NUMBER(1),
  PRO_CODI             		NUMBER(1),
  GRUP_CODI           		NUMBER(1),
  DIR3_CODI					NUMBER(1),
  USUARI					NUMBER(1),
  ENVIAMENT_TIPUS          	NUMBER(1),
  CONCEPTE       			NUMBER(1),
  DESCRIPCIO   				NUMBER(1),
  TITULAR_NIF      			NUMBER(1),
  TITULAR_NOM_LLINATGE      NUMBER(1),
  TITULAR_EMAIL      		NUMBER(1),
  DESTINATARIS        	    NUMBER(1),
  LLIBRE_REGISTRE        	NUMBER(1),
  NUMERO_REGISTRE           NUMBER(1),
  DATA_REGISTRE        		NUMBER(1),
  DATA_CADUCITAT         	NUMBER(1),
  CODI_NOTIB_ENV            NUMBER(1),
  NUM_CERTIFICACIO      	NUMBER(1),
  CSV_UUID          		NUMBER(1),
  ESTAT                		NUMBER(1),
  ENTITAT_ID				NUMBER(19),
  USUARI_CODI				VARCHAR2(64),
  CREATEDBY_CODI       		VARCHAR2(64),
  CREATEDDATE          		TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  		VARCHAR2(64),
  LASTMODIFIEDDATE     		TIMESTAMP(6)
)

ALTER TABLE NOT_COLUMNES ADD (
  CONSTRAINT NOT_COLUMNES_ENTITAT_FK FOREIGN KEY (ENTITAT_ID)
    REFERENCES NOT_ENTITAT (ID));

ALTER TABLE NOT_COLUMNES ADD (
  CONSTRAINT NOT_COLUMNES_USUARI_FK FOREIGN KEY (USUARI_CODI)
    REFERENCES NOT_USUARI (CODI));