
package es.caib.notib.logic.intf.ws.adviser;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.math.BigInteger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AdviserWsV2PortType", targetNamespace = "http://administracionelectronica.gob.es/notifica/ws/adviserwsv2/1.0/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AdviserWsV2PortType {


    /**
     * 
     * @param descripcionRespuesta
     * @param organismoEmisor
     * @param estado
     * @param modoNotificacion
     * @param acusePDF
     * @param tipoEntrega
     * @param fechaEstado
     * @param opcionesResultadoSincronizarEnvio
     * @param opcionesSincronizarEnvio
     * @param receptor
     * @param acuseXML
     * @param codigoRespuesta
     * @param identificador
     */
    @WebMethod(action = "sincronizarEnvio")
    @RequestWrapper(localName = "sincronizarEnvio", targetNamespace = "http://administracionelectronica.gob.es/notifica/ws/adviserwsv2/1.0/sincronizarEnvio", className = "es.caib.notib.logic.wsdl.adviser.SincronizarEnvio")
    @ResponseWrapper(localName = "resultadoSincronizarEnvio", targetNamespace = "http://administracionelectronica.gob.es/notifica/ws/adviserwsv2/1.0/sincronizarEnvio", className = "es.caib.notib.logic.wsdl.adviser.ResultadoSincronizarEnvio")
    public void sincronizarEnvio(
        @WebParam(name = "organismoEmisor", targetNamespace = "http://administracionelectronica.gob.es/notifica/ws/adviserwsv2/1.0/sincronizarEnvio")
        String organismoEmisor,
        @WebParam(name = "identificador", targetNamespace = "http://administracionelectronica.gob.es/notifica/ws/adviserwsv2/1.0/sincronizarEnvio", mode = WebParam.Mode.INOUT)
        Holder<String> identificador,
        @WebParam(name = "tipoEntrega", targetNamespace = "http://administracionelectronica.gob.es/notifica/ws/adviserwsv2/1.0/sincronizarEnvio")
        BigInteger tipoEntrega,
        @WebParam(name = "modoNotificacion", targetNamespace = "http://administracionelectronica.gob.es/notifica/ws/adviserwsv2/1.0/sincronizarEnvio")
        BigInteger modoNotificacion,
        @WebParam(name = "estado", targetNamespace = "http://administracionelectronica.gob.es/notifica/ws/adviserwsv2/1.0/sincronizarEnvio")
        String estado,
        @WebParam(name = "fechaEstado", targetNamespace = "http://administracionelectronica.gob.es/notifica/ws/adviserwsv2/1.0/sincronizarEnvio")
        XMLGregorianCalendar fechaEstado,
        @WebParam(name = "receptor", targetNamespace = "http://administracionelectronica.gob.es/notifica/ws/adviserwsv2/1.0/sincronizarEnvio")
                Receptor receptor,
        @WebParam(name = "acusePDF", targetNamespace = "http://administracionelectronica.gob.es/notifica/ws/adviserwsv2/1.0/sincronizarEnvio")
                Acuse acusePDF,
        @WebParam(name = "acuseXML", targetNamespace = "http://administracionelectronica.gob.es/notifica/ws/adviserwsv2/1.0/sincronizarEnvio")
        Acuse acuseXML,
        @WebParam(name = "opcionesSincronizarEnvio", targetNamespace = "http://administracionelectronica.gob.es/notifica/ws/adviserwsv2/1.0/sincronizarEnvio")
                Opciones opcionesSincronizarEnvio,
        @WebParam(name = "codigoRespuesta", targetNamespace = "http://administracionelectronica.gob.es/notifica/ws/adviserwsv2/1.0/sincronizarEnvio", mode = WebParam.Mode.OUT)
        Holder<String> codigoRespuesta,
        @WebParam(name = "descripcionRespuesta", targetNamespace = "http://administracionelectronica.gob.es/notifica/ws/adviserwsv2/1.0/sincronizarEnvio", mode = WebParam.Mode.OUT)
        Holder<String> descripcionRespuesta,
        @WebParam(name = "opcionesResultadoSincronizarEnvio", targetNamespace = "http://administracionelectronica.gob.es/notifica/ws/adviserwsv2/1.0/sincronizarEnvio", mode = WebParam.Mode.OUT)
        Holder<Opciones> opcionesResultadoSincronizarEnvio);

}
