-- #131
ALTER TABLE NOT_PERSONA MODIFY NOM character varying(255);
ALTER TABLE NOT_PERSONA MODIFY LLINATGE1 character varying(40);
ALTER TABLE NOT_PERSONA MODIFY LLINATGE2 character varying(40);
ALTER TABLE NOT_PERSONA MODIFY EMAIL character varying(255);

ALTER TABLE NOT_NOTIFICACIO MODIFY DESCRIPCIO character varying(1000);

ALTER TABLE NOT_NOTIFICACIO_ENV MODIFY DOM_VIA_NOM character varying(50);
ALTER TABLE NOT_NOTIFICACIO_ENV MODIFY DOM_NUM_NUM character varying(5);
ALTER TABLE NOT_NOTIFICACIO_ENV MODIFY DOM_LINEA1 character varying(50);
ALTER TABLE NOT_NOTIFICACIO_ENV MODIFY DOM_LINEA2 character varying(50);

ALTER TABLE NOT_GRUP MODIFY CODI character varying(255 CHAR);
ALTER TABLE NOT_GRUP MODIFY NOM character varying(255 CHAR);