ALTER TABLE NOT_NOTIFICACIO_ENV MODIFY DOM_POBLACIO VARCHAR2(255 CHAR);
ALTER TABLE NOT_NOTIFICACIO_ENV MODIFY DEH_PROC_CODI VARCHAR2(64 CHAR);
ALTER TABLE NOT_NOTIFICACIO MODIFY REGISTRE_NUM_EXPEDIENT VARCHAR2(80 CHAR);