ALTER TABLE NOT_NOTIFICACIO MODIFY REGISTRE_TIPUS_ASSUMPTE VARCHAR2(255);
ALTER TABLE NOT_NOTIFICACIO MODIFY REGISTRE_CODI_ASSUMPTE	VARCHAR2(255);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN PROC_CODI_SIA;

ALTER TABLE NOT_PROCEDIMENT MODIFY TIPUSASSUMPTE VARCHAR2(255);
ALTER TABLE NOT_PROCEDIMENT ADD CODIASSUMPTE VARCHAR2(255);

ALTER TABLE NOT_NOTIFICACIO MODIFY DOCUMENT_ID NUMBER(19) NULL;

ALTER TABLE NOT_DOCUMENT MODIFY METADADES VARCHAR(3000);