-- Update for version (0.1 -> 1.0)
-- #54
CREATE TABLE NOT_PROCEDIMENT 
(
  ID						NUMBER(19)	    	NOT NULL,
  CODI          			VARCHAR2(64)		NOT NULL,
  NOM						VARCHAR2(100),
  CODISIA					VARCHAR2(64),
  ENTITAT					NUMBER(19),
  PAGADORPOSTAL				NUMBER(19),
  PAGADORCIE				NUMBER(19),
  AGRUPAR					NUMBER(1) 			NOT NULL,
  DATA_PROGRAMADA			TIMESTAMP(6),
  RETARD					NUMBER(19),
  CREATEDBY_CODI       		VARCHAR2(64),
  CREATEDDATE          		TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  		VARCHAR2(64),
  LASTMODIFIEDDATE     		TIMESTAMP(6)
);

CREATE TABLE NOT_GRUP 
(
  ID						NUMBER(19)	    	NOT NULL,
  CODI						VARCHAR2(64)		NOT NULL,
  NOM						VARCHAR2(100),
  CREATEDBY_CODI       		VARCHAR2(64),
  CREATEDDATE          		TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  		VARCHAR2(64),
  LASTMODIFIEDDATE     		TIMESTAMP(6),
  ENTITAT				NUMBER(19)
);

CREATE TABLE NOT_PAGADOR_POSTAL
(
  ID						NUMBER(19)	    	NOT NULL,
  DIR3_CODI            		VARCHAR2(9)  		NOT NULL,
  CONTRACTE_NUM		       	VARCHAR2(20),
  CONTRACTE_DATA_VIG      	DATE,
  FACTURACIO_CODI_CLIENT   	VARCHAR2(20),
  CREATEDBY_CODI       		VARCHAR2(64),
  CREATEDDATE          		TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  		VARCHAR2(64),
  LASTMODIFIEDDATE     		TIMESTAMP(6)
);

CREATE TABLE NOT_PAGADOR_CIE
(
  ID						NUMBER(19)	    	NOT NULL,
  DIR3_CODI            		VARCHAR2(9)  		NOT NULL,
  CONTRACTE_DATA_VIG      	DATE,
  CREATEDBY_CODI       		VARCHAR2(64),
  CREATEDDATE          		TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  		VARCHAR2(64),
  LASTMODIFIEDDATE     		TIMESTAMP(6)
);

CREATE TABLE NOT_PRO_GRUP 
(
  ID						NUMBER(19)	    	NOT NULL,
  GRUP						NUMBER(19),			
  PROCEDIMENT				NUMBER(19),
  CREATEDBY_CODI       		VARCHAR2(64),
  CREATEDDATE          		TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  		VARCHAR2(64),
  LASTMODIFIEDDATE     		TIMESTAMP(6)
);

ALTER TABLE NOT_PROCEDIMENT ADD (
  CONSTRAINT NOT_PROCEDIMENT_PK PRIMARY KEY (ID));
  
ALTER TABLE NOT_GRUP ADD (
  CONSTRAINT NOT_GRUP_PK PRIMARY KEY (ID));
  
ALTER TABLE NOT_PAGADOR_POSTAL ADD (
  CONSTRAINT NOT_PAGADOR_POSTAL_PK PRIMARY KEY (ID));
  
ALTER TABLE NOT_PAGADOR_CIE ADD (
  CONSTRAINT NOT_PAGADOR_CIE_PK PRIMARY KEY (ID));
  
ALTER TABLE NOT_PROCEDIMENT ADD (
  CONSTRAINT NOT_PAGADOR_POSTAL_FK FOREIGN KEY (PAGADORPOSTAL)
    REFERENCES NOT_PAGADOR_POSTAL (ID));
  
ALTER TABLE NOT_PROCEDIMENT ADD (
  CONSTRAINT NOT_PAGADOR_CIE_FK FOREIGN KEY (PAGADORCIE)
    REFERENCES NOT_PAGADOR_CIE (ID));
    
ALTER TABLE NOT_PROCEDIMENT ADD (
  CONSTRAINT NOT_ENTITAT_FK FOREIGN KEY (ENTITAT)
    REFERENCES NOT_ENTITAT (ID));

-- #55

ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_ORGAN varchar2(10);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_OFICINA varchar2(10);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_LLIBRE varchar2(10);

-- #59
CREATE TABLE NOT_COLUMNES
(
  ID                   		NUMBER(19),
  CREATED_DATE      		NUMBER(1),
  DATA_PROGRAMADA           NUMBER(1),
  NOT_IDENTIFICADOR         NUMBER(1),
  PRO_CODI             		NUMBER(1),
  GRUP_CODI           		NUMBER(1),
  DIR3_CODI					NUMBER(1),
  USUARI					NUMBER(1),
  ENVIAMENT_TIPUS          	NUMBER(1),
  CONCEPTE       			NUMBER(1),
  DESCRIPCIO   				NUMBER(1),
  TITULAR_NIF      			NUMBER(1),
  TITULAR_NOM_LLINATGE      NUMBER(1),
  TITULAR_EMAIL      		NUMBER(1),
  DESTINATARIS        	    NUMBER(1),
  LLIBRE_REGISTRE        	NUMBER(1),
  NUMERO_REGISTRE           NUMBER(1),
  DATA_REGISTRE        		NUMBER(1),
  DATA_CADUCITAT         	NUMBER(1),
  CODI_NOTIB_ENV            NUMBER(1),
  NUM_CERTIFICACIO      	NUMBER(1),
  CSV_UUID          		NUMBER(1),
  ESTAT                		NUMBER(1),
  ENTITAT_ID				NUMBER(19),
  USUARI_CODI				VARCHAR2(64),
  CREATEDBY_CODI       		VARCHAR2(64),
  CREATEDDATE          		TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  		VARCHAR2(64),
  LASTMODIFIEDDATE     		TIMESTAMP(6)
);


ALTER TABLE NOT_COLUMNES ADD (
  CONSTRAINT NOT_COLUMNES_ENTITAT_FK FOREIGN KEY (ENTITAT_ID)
    REFERENCES NOT_ENTITAT (ID));

ALTER TABLE NOT_COLUMNES ADD (
  CONSTRAINT NOT_COLUMNES_USUARI_FK FOREIGN KEY (USUARI_CODI)
    REFERENCES NOT_USUARI (CODI));

-- #67
ALTER TABLE NOT_PROCEDIMENT ADD LLIBRE VARCHAR2(64);
ALTER TABLE NOT_PROCEDIMENT ADD OFICINA VARCHAR2(64);
ALTER TABLE NOT_PROCEDIMENT ADD TIPUSASSUMPTE NUMBER(1);

CREATE TABLE NOT_PERSONA
(
  ID					NUMBER(19)			NOT NULL,
  EMAIL					VARCHAR2(100),
  LLINATGE1				VARCHAR2(100)		NOT NULL,
  LLINATGE2				VARCHAR2(100),
  NIF					VARCHAR2(9)			NOT NULL,
  NOM					VARCHAR2(100),
  TELEFON				VARCHAR2(16),
  RAO_SOCIAL			VARCHAR2(100),
  COD_ENTITAT_DESTI		VARCHAR2(9),
  NOTIFICACIO_ENV_ID	NUMBER(19),
  CREATEDBY_CODI       	VARCHAR2(64),
  CREATEDDATE          	TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  	VARCHAR2(64),
  LASTMODIFIEDDATE     	TIMESTAMP(6)
);

ALTER TABLE NOT_PERSONA ADD (
  CONSTRAINT NOT_PERSONA_NOT_FK FOREIGN KEY (NOTIFICACIO_ENV_ID)
    REFERENCES NOT_NOTIFICACIO_ENV(ID));

CREATE TABLE NOT_DOCUMENT
(
  ID					NUMBER(19)			NOT NULL,
  ARXIU_ID				VARCHAR2(64),
  ARXIU_GEST_DOC_ID		VARCHAR2(64),
  ARXIU_NOM				VARCHAR2(100),
  HASH					VARCHAR2(2048),
  URL					VARCHAR2(256),
  TELEFON				VARCHAR2(16),
  METADADES				VARCHAR2(256),
  NORMALITZAT			NUMBER(1, 0),
  GENERAR_CSV			NUMBER(1, 0),
  UUID					VARCHAR2(64),
  CSV					VARCHAR2(256),
  CREATEDBY_CODI       	VARCHAR2(64),
  CREATEDDATE          	TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  	VARCHAR2(64),
  LASTMODIFIEDDATE     	TIMESTAMP(6)
);

ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_EXTRACTE VARCHAR2(64);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_DOC_FISICA VARCHAR2(64);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_IDIOMA VARCHAR2(2);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_TIPUS_ASSUMPTE NUMBER(1);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_NUM_EXPEDIENT VARCHAR2(20);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_REF_EXTERNA VARCHAR2(64);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_CODI_ASSUMPTE VARCHAR2(20);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_OBSERVACIONS VARCHAR2(256);
ALTER TABLE NOT_NOTIFICACIO ADD GRUP_CODI VARCHAR2(64);
ALTER TABLE NOT_NOTIFICACIO MODIFY DOC_ARXIU_NOM VARCHAR2(256);
ALTER TABLE NOT_NOTIFICACIO ADD DOCUMENT_ID	NUMBER(19) NOT NULL;
ALTER TABLE NOT_NOTIFICACIO ADD USUARI_CODI	VARCHAR2(64);
ALTER TABLE NOT_NOTIFICACIO ADD PROCEDIMENT_ID NUMBER(19);
ALTER TABLE NOT_NOTIFICACIO ADD PAGADOR_POSTAL_ID NUMBER(19);
ALTER TABLE NOT_NOTIFICACIO ADD PAGADOR_CIE_ID NUMBER(19);
ALTER TABLE NOT_NOTIFICACIO ADD TITULAR_ID NUMBER(19);
ALTER TABLE NOT_NOTIFICACIO ADD PROC_CODI_NOTIB	VARCHAR2(6);
ALTER TABLE NOT_NOTIFICACIO MODIFY PROC_CODI_SIA VARCHAR2(6);
ALTER TABLE NOT_NOTIFICACIO ADD CSV_UUID VARCHAR2(64);

ALTER TABLE NOT_NOTIFICACIO_ENV ADD TITULAR_ID NUMBER(19);

ALTER TABLE NOT_DOCUMENT ADD (
  CONSTRAINT NOT_DOCUMENT_PK PRIMARY KEY (ID));
  
ALTER TABLE NOT_PERSONA ADD (
  CONSTRAINT NOT_PERSONA_PK PRIMARY KEY (ID));

ALTER TABLE NOT_NOTIFICACIO_ENV ADD (
  CONSTRAINT NOT_PERSONA_NOTIFICACIO_ENV_FK FOREIGN KEY (TITULAR_ID)
    REFERENCES NOT_PERSONA (ID));

ALTER TABLE NOT_NOTIFICACIO ADD (
  CONSTRAINT NOT_DOCUMENT_NOTIFICACIO_FK FOREIGN KEY (DOCUMENT_ID)
    REFERENCES NOT_DOCUMENT (ID));
    
ALTER TABLE NOT_NOTIFICACIO ADD (
  CONSTRAINT NOT_PROCEDIMENT_NOT_FK FOREIGN KEY (PROCEDIMENT_ID)
    REFERENCES NOT_PROCEDIMENT (ID));    
    
ALTER TABLE NOT_NOTIFICACIO ADD (
  CONSTRAINT NOT_PAGADOR_POSTAL_NOT_FK FOREIGN KEY (PAGADOR_POSTAL_ID)
    REFERENCES NOT_PAGADOR_POSTAL (ID));
    
ALTER TABLE NOT_NOTIFICACIO ADD (
  CONSTRAINT NOT_PAGADOR_CIE_NOTIFICACIO_FK FOREIGN KEY (PAGADOR_CIE_ID)
    REFERENCES NOT_PAGADOR_CIE (ID));
      
ALTER TABLE NOT_PRO_GRUP ADD (
  CONSTRAINT NOT_GRUP_PRO_FK FOREIGN KEY (GRUP)
      REFERENCES NOT_GRUP (ID),
  CONSTRAINT NOT_PRO_GRUP_FK FOREIGN KEY (PROCEDIMENT)
      REFERENCES NOT_PROCEDIMENT (ID));

CREATE INDEX NOT_PAGADOR_POSTAL_FK_I ON NOT_PROCEDIMENT(PAGADORPOSTAL);
CREATE INDEX NOT_PAGADOR_CIE_FK_I ON NOT_PROCEDIMENT(PAGADORCIE);
CREATE INDEX NOT_ENTITAT_FK_I ON NOT_PROCEDIMENT(entitat);

ALTER TABLE NOT_NOTIFICACIO DROP COLUMN DOC_ARXIU_NOM;
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN DOC_ARXIU_ID;
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN DOC_GEN_CSV;
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN DOC_HASH;
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN DOC_NORMALITZAT;
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN PROC_CODI_SIA;
ALTER TABLE NOT_NOTIFICACIO ADD PROC_CODI_SIA VARCHAR(6);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_EXP_UNIORG;
ALTER TABLE NOT_NOTIFICACIO ADD SEU_EXP_UNIORG VARCHAR(10);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_EXP_IDENI;
ALTER TABLE NOT_NOTIFICACIO ADD SEU_EXP_IDENI VARCHAR(52);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_EXP_TITOL;
ALTER TABLE NOT_NOTIFICACIO ADD SEU_EXP_TITOL VARCHAR(256);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_EXP_TITOL;
ALTER TABLE NOT_NOTIFICACIO ADD SEU_EXP_TITOL VARCHAR(256);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_REG_OFICINA;
ALTER TABLE NOT_NOTIFICACIO ADD SEU_REG_OFICINA VARCHAR(256);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_REG_LLIBRE;
ALTER TABLE NOT_NOTIFICACIO ADD SEU_REG_LLIBRE VARCHAR(256);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_IDIOMA;
ALTER TABLE NOT_NOTIFICACIO ADD SEU_IDIOMA VARCHAR(256);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_AVIS_TITOL;
ALTER TABLE NOT_NOTIFICACIO ADD SEU_AVIS_TITOL VARCHAR(256);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_AVIS_TEXT;
ALTER TABLE NOT_NOTIFICACIO ADD SEU_AVIS_TEXT VARCHAR(256);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_OFICI_TITOL;
ALTER TABLE NOT_NOTIFICACIO ADD SEU_OFICI_TITOL VARCHAR(256);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN SEU_OFICI_TEXT;
ALTER TABLE NOT_NOTIFICACIO ADD SEU_OFICI_TEXT VARCHAR(256);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_NUMERO VARCHAR(256);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_DATA DATE;

ALTER TABLE NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_NIF;
ALTER TABLE NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_NOM;
ALTER TABLE NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_LLINATGE1;
ALTER TABLE NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_LLINATGE2;
ALTER TABLE NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_RAOSOC;
ALTER TABLE NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_CODDES;
ALTER TABLE NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_TELEFON;
ALTER TABLE NOT_NOTIFICACIO_ENV DROP COLUMN TITULAR_EMAIL;

ALTER TABLE NOT_NOTIFICACIO_ENV DROP COLUMN SEU_ESTAT;
ALTER TABLE NOT_NOTIFICACIO_ENV DROP COLUMN SEU_ERROR;
ALTER TABLE NOT_NOTIFICACIO_ENV ADD SEU_ESTAT NUMBER(19);
ALTER TABLE NOT_NOTIFICACIO_ENV ADD SEU_ERROR NUMBER(19);

-- #72
ALTER TABLE NOT_NOTIFICACIO MODIFY REGISTRE_TIPUS_ASSUMPTE VARCHAR2(255);
ALTER TABLE NOT_NOTIFICACIO MODIFY REGISTRE_CODI_ASSUMPTE VARCHAR2(255);
ALTER TABLE NOT_NOTIFICACIO DROP COLUMN PROC_CODI_SIA;

ALTER TABLE NOT_PROCEDIMENT MODIFY TIPUSASSUMPTE VARCHAR2(255);
ALTER TABLE NOT_PROCEDIMENT ADD CODIASSUMPTE VARCHAR2(255);

ALTER TABLE NOT_NOTIFICACIO MODIFY DOCUMENT_ID NUMBER(19) NULL;

ALTER TABLE NOT_DOCUMENT MODIFY METADADES VARCHAR2(3000);

ALTER TABLE NOT_PERSONA ADD INTERESSATTIPUS VARCHAR2(30);
ALTER TABLE NOT_PERSONA MODIFY LLINATGE1 VARCHAR2(100) NULL;

ALTER TABLE NOT_NOTIFICACIO DROP COLUMN REGISTRE_DOC_FISICA;
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_DOC_FISICA NUMBER(2);
ALTER TABLE NOT_NOTIFICACIO MODIFY REGISTRE_IDIOMA VARCHAR2(10);

ALTER TABLE NOT_NOTIFICACIO MODIFY REGISTRE_NUMERO NUMBER(19);
ALTER TABLE NOT_NOTIFICACIO ADD REGISTRE_NUMERO_FORMATAT VARCHAR2(50);

ALTER TABLE NOT_NOTIFICACIO_ENV ADD REGISTRE_NUMERO_FORMATAT VARCHAR2(50);
ALTER TABLE NOT_NOTIFICACIO_ENV ADD REGISTRE_DATA DATE;
ALTER TABLE NOT_NOTIFICACIO_ENV ADD ESTAT_REGISTRE NUMBER(19);

-- #77
ALTER TABLE NOT_NOTIFICACIO ADD MOTIU VARCHAR2(255);
ALTER TABLE NOT_USUARI ADD REBRE_EMAILS NUMBER(1,0);
UPDATE NOT_USUARI SET REBRE_EMAILS = 1;

-- #83
ALTER TABLE NOT_ENTITAT ADD API_KEY VARCHAR2(64);

-- #84
ALTER TABLE NOT_PROCEDIMENT ADD ORGAN_GESTOR VARCHAR2(19);
ALTER TABLE NOT_PROCEDIMENT ADD ORGAN_GESTOR_NOM VARCHAR2(64);
ALTER TABLE NOT_PROCEDIMENT ADD TIPUSASSUMPTE_NOM VARCHAR2(64);
ALTER TABLE NOT_PROCEDIMENT ADD CODIASSUMPTE_NOM VARCHAR2(64);
ALTER TABLE NOT_NOTIFICACIO ADD ORGAN_GESTOR VARCHAR2(19);



