-- #189
ALTER TABLE NOT_PROCEDIMENT ADD ( CONSTRAINT NOT_PROC_ORGAN_FK FOREIGN KEY (ORGAN_GESTOR) REFERENCES NOT_ORGAN_GESTOR (CODI));
ALTER TABLE NOT_ORGAN_GESTOR ADD ( CONSTRAINT NOT_ORGAN_ENTITAT_FK FOREIGN KEY (ENTITAT) REFERENCES NOT_ENTITAT (ID));
CREATE INDEX NOT_PRO_ORGAN_FK_I ON NOT_PROCEDIMENT(ORGAN_GESTOR);
CREATE INDEX NOT_ORGAN_ENTITAT_FK_I ON NOT_ORGAN_GESTOR(ENTITAT);

-- #215
ALTER TABLE NOT_APLICACIO MODIFY ENTITAT_ID NOT NULL;
