-- #189
CREATE TABLE NOT_ORGAN_GESTOR 
(
  ID		NUMBER(19)			NOT NULL,
  CODI		VARCHAR2(64)		NOT NULL,
  ENTITAT	NUMBER(19),				
  NOM		VARCHAR2(1000)
);

ALTER TABLE NOT_ORGAN_GESTOR ADD (CONSTRAINT NOT_ORGAN_GESTOR_PK PRIMARY KEY (ID));
ALTER TABLE NOT_ORGAN_GESTOR ADD (CONSTRAINT NOT_ORGAN_GESTOR_UK UNIQUE (CODI));

INSERT INTO NOT_ORGAN_GESTOR (ID, CODI, ENTITAT)
SELECT NOT_HIBERNATE_SEQ.NEXTVAL, CODI, ENTITAT
FROM (  SELECT DISTINCT PRO.ORGAN_GESTOR AS CODI, PRO.ENTITAT AS ENTITAT
        FROM NOT_PROCEDIMENT PRO
        WHERE PRO.ORGAN_GESTOR IS NOT NULL);

ALTER TABLE NOT_PROCEDIMENT ADD ( CONSTRAINT NOT_PROC_ORGAN_FK FOREIGN KEY (ORGAN_GESTOR) REFERENCES NOT_ORGAN_GESTOR (CODI));
ALTER TABLE NOT_ORGAN_GESTOR ADD ( CONSTRAINT NOT_ORGAN_ENTITAT_FK FOREIGN KEY (ENTITAT) REFERENCES NOT_ENTITAT (ID));
CREATE INDEX NOT_PRO_ORGAN_FK_I ON NOT_PROCEDIMENT(ORGAN_GESTOR);
CREATE INDEX NOT_ORGAN_ENTITAT_FK_I ON NOT_ORGAN_GESTOR(ENTITAT);

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_ORGAN_GESTOR TO WWW_NOTIB;