import React from 'react';
import { useTheme } from '@mui/material/styles';
import { GridTreeDataGroupingCell } from '@mui/x-data-grid-pro';
import { MuiFilter } from 'reactlib';
import { useNotibContext } from '../components/NotibContext';

export const useDatagridPageSizeOptionsProps = () => {
    const { currentUser, currentUserGridPageSizeOptions } = useNotibContext();
    return {
        defaultPaginationModel: {
            page: 0,
            pageSize: currentUser.numElementsPaginaDefecteAsInt ?? -1,
        },
        pageSizeOptions: currentUserGridPageSizeOptions,
    };
};

export const useDatagridFilterProps = (
    resourceName: string,
    code: string,
    springFilterBuilder: (data: any) => string | undefined,
    content: React.ReactElement,
    minHeight: string = '40px'
) => {
    const [autoFindDisabled, setAutoFindDisabled] = React.useState<boolean>(true);
    const handleSpringFilterChange = (springFilter: string | undefined) => {
        const springFilterEmpty = springFilter == null || springFilter === '';
        autoFindDisabled && setAutoFindDisabled(!springFilterEmpty);
    };
    const filterComponent = (
        <MuiFilter
            resourceName={resourceName}
            code={code}
            persistentStateActive
            springFilterBuilder={springFilterBuilder}
            onSpringFilterChange={handleSpringFilterChange}
            componentProps={{ sx: { mb: 0, mt: 0 } }}
            commonFieldComponentProps={{ size: 'small' }}
        >
            {content}
        </MuiFilter>
    );
    return {
        loading: autoFindDisabled ? autoFindDisabled : undefined,
        autoFindDisabled,
        toolbarHideQuickFilter: true as true,
        toolbarAdditionalRow: filterComponent,
        toolbarAdditionalRowMinHeight: minHeight,
    };
};

export const useDatagridTreeData = (
    active: boolean,
    headerName: string,
    defaultGroupingExpansionDepth?: number,
    groupingColDefProps?: any,
) => {
    const theme = useTheme();
    const getTreeDataPath = (row: any) => {
        return row.path?.map((p: any) => p.description) ?? [row.id];
    };
    return active
        ? {
              perspectives: ['TREE'],
              treeData: true as true,
              getTreeDataPath,
              groupingColDef: {
                  headerName,
                  renderCell: (params: any) => {
                      return (
                          <div
                              style={{
                                  display: 'flex',
                                  color: params.rowNode.isAutoGenerated
                                      ? theme.palette.text.disabled
                                      : undefined,
                              }}
                          >
                              <GridTreeDataGroupingCell {...params} />
                          </div>
                      );
                  },
                  ...groupingColDefProps
              },
              defaultGroupingExpansionDepth,
          }
        : {
              paginationActive: true as true,
              getTreeDataPath
          };
};
