
package es.caib.notib.ws.notificacio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NotificacioServiceV2", targetNamespace = "http://www.caib.es/notib/ws/notificacio")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NotificacioServiceV2 {


    /**
     * 
     * @param arg0
     * @return
     *     returns es.caib.notib.ws.notificacio.RespostaAlta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "alta", targetNamespace = "http://www.caib.es/notib/ws/notificacio", className = "es.caib.notib.ws.notificacio.Alta")
    @ResponseWrapper(localName = "altaResponse", targetNamespace = "http://www.caib.es/notib/ws/notificacio", className = "es.caib.notib.ws.notificacio.AltaResponse")
    public RespostaAlta alta(
        @WebParam(name = "arg0", targetNamespace = "")
        NotificacioV2 arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns es.caib.notib.ws.notificacio.RespostaAltaV2
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "altaV2", targetNamespace = "http://www.caib.es/notib/ws/notificacio", className = "es.caib.notib.ws.notificacio.AltaV2")
    @ResponseWrapper(localName = "altaV2Response", targetNamespace = "http://www.caib.es/notib/ws/notificacio", className = "es.caib.notib.ws.notificacio.AltaV2Response")
    public RespostaAltaV2 altaV2(
        @WebParam(name = "arg0", targetNamespace = "")
        NotificacioV2 arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns es.caib.notib.ws.notificacio.RespostaConsultaDadesRegistre
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaDadesRegistre", targetNamespace = "http://www.caib.es/notib/ws/notificacio", className = "es.caib.notib.ws.notificacio.ConsultaDadesRegistre")
    @ResponseWrapper(localName = "consultaDadesRegistreResponse", targetNamespace = "http://www.caib.es/notib/ws/notificacio", className = "es.caib.notib.ws.notificacio.ConsultaDadesRegistreResponse")
    public RespostaConsultaDadesRegistre consultaDadesRegistre(
        @WebParam(name = "arg0", targetNamespace = "")
        DadesConsulta arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns es.caib.notib.ws.notificacio.RespostaConsultaDadesRegistreV2
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaDadesRegistreV2", targetNamespace = "http://www.caib.es/notib/ws/notificacio", className = "es.caib.notib.ws.notificacio.ConsultaDadesRegistreV2")
    @ResponseWrapper(localName = "consultaDadesRegistreV2Response", targetNamespace = "http://www.caib.es/notib/ws/notificacio", className = "es.caib.notib.ws.notificacio.ConsultaDadesRegistreV2Response")
    public RespostaConsultaDadesRegistreV2 consultaDadesRegistreV2(
        @WebParam(name = "arg0", targetNamespace = "")
        DadesConsulta arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns es.caib.notib.ws.notificacio.RespostaConsultaEstatEnviament
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaEstatEnviament", targetNamespace = "http://www.caib.es/notib/ws/notificacio", className = "es.caib.notib.ws.notificacio.ConsultaEstatEnviament")
    @ResponseWrapper(localName = "consultaEstatEnviamentResponse", targetNamespace = "http://www.caib.es/notib/ws/notificacio", className = "es.caib.notib.ws.notificacio.ConsultaEstatEnviamentResponse")
    public RespostaConsultaEstatEnviament consultaEstatEnviament(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns es.caib.notib.ws.notificacio.RespostaConsultaEstatEnviamentV2
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaEstatEnviamentV2", targetNamespace = "http://www.caib.es/notib/ws/notificacio", className = "es.caib.notib.ws.notificacio.ConsultaEstatEnviamentV2")
    @ResponseWrapper(localName = "consultaEstatEnviamentV2Response", targetNamespace = "http://www.caib.es/notib/ws/notificacio", className = "es.caib.notib.ws.notificacio.ConsultaEstatEnviamentV2Response")
    public RespostaConsultaEstatEnviamentV2 consultaEstatEnviamentV2(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns es.caib.notib.ws.notificacio.RespostaConsultaEstatNotificacio
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaEstatNotificacio", targetNamespace = "http://www.caib.es/notib/ws/notificacio", className = "es.caib.notib.ws.notificacio.ConsultaEstatNotificacio")
    @ResponseWrapper(localName = "consultaEstatNotificacioResponse", targetNamespace = "http://www.caib.es/notib/ws/notificacio", className = "es.caib.notib.ws.notificacio.ConsultaEstatNotificacioResponse")
    public RespostaConsultaEstatNotificacio consultaEstatNotificacio(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns es.caib.notib.ws.notificacio.RespostaConsultaEstatNotificacioV2
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaEstatNotificacioV2", targetNamespace = "http://www.caib.es/notib/ws/notificacio", className = "es.caib.notib.ws.notificacio.ConsultaEstatNotificacioV2")
    @ResponseWrapper(localName = "consultaEstatNotificacioV2Response", targetNamespace = "http://www.caib.es/notib/ws/notificacio", className = "es.caib.notib.ws.notificacio.ConsultaEstatNotificacioV2Response")
    public RespostaConsultaEstatNotificacioV2 consultaEstatNotificacioV2(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param identificador
     * @return
     *     returns es.caib.notib.ws.notificacio.RespostaConsultaJustificantEnviament
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaJustificantEnviament", targetNamespace = "http://www.caib.es/notib/ws/notificacio", className = "es.caib.notib.ws.notificacio.ConsultaJustificantEnviament")
    @ResponseWrapper(localName = "consultaJustificantEnviamentResponse", targetNamespace = "http://www.caib.es/notib/ws/notificacio", className = "es.caib.notib.ws.notificacio.ConsultaJustificantEnviamentResponse")
    public RespostaConsultaJustificantEnviament consultaJustificantEnviament(
        @WebParam(name = "identificador", targetNamespace = "")
        String identificador);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "donarPermisConsulta", targetNamespace = "http://www.caib.es/notib/ws/notificacio", className = "es.caib.notib.ws.notificacio.DonarPermisConsulta")
    @ResponseWrapper(localName = "donarPermisConsultaResponse", targetNamespace = "http://www.caib.es/notib/ws/notificacio", className = "es.caib.notib.ws.notificacio.DonarPermisConsultaResponse")
    public boolean donarPermisConsulta(
        @WebParam(name = "arg0", targetNamespace = "")
        PermisConsulta arg0);

}
