
package es.caib.notib.ws.notificacio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NotificacioServiceV2", targetNamespace = "http://www.caib.es/notib/ws/notificacio", wsdlLocation = "file:/home/siona/git/notib/notib-client/src/main/resources/es/caib/notib/client/wsdl/NotificacioServiceWsV2.wsdl")
public class NotificacioServiceV2_Service
    extends Service
{

    private final static URL NOTIFICACIOSERVICEV2_WSDL_LOCATION;
    private final static WebServiceException NOTIFICACIOSERVICEV2_EXCEPTION;
    private final static QName NOTIFICACIOSERVICEV2_QNAME = new QName("http://www.caib.es/notib/ws/notificacio", "NotificacioServiceV2");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/siona/git/notib/notib-client/src/main/resources/es/caib/notib/client/wsdl/NotificacioServiceWsV2.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NOTIFICACIOSERVICEV2_WSDL_LOCATION = url;
        NOTIFICACIOSERVICEV2_EXCEPTION = e;
    }

    public NotificacioServiceV2_Service() {
        super(__getWsdlLocation(), NOTIFICACIOSERVICEV2_QNAME);
    }

    public NotificacioServiceV2_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), NOTIFICACIOSERVICEV2_QNAME, features);
    }

    public NotificacioServiceV2_Service(URL wsdlLocation) {
        super(wsdlLocation, NOTIFICACIOSERVICEV2_QNAME);
    }

    public NotificacioServiceV2_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NOTIFICACIOSERVICEV2_QNAME, features);
    }

    public NotificacioServiceV2_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotificacioServiceV2_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NotificacioServiceV2
     */
    @WebEndpoint(name = "NotificacioServiceV2Port")
    public NotificacioServiceV2 getNotificacioServiceV2Port() {
        return super.getPort(new QName("http://www.caib.es/notib/ws/notificacio", "NotificacioServiceV2Port"), NotificacioServiceV2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotificacioServiceV2
     */
    @WebEndpoint(name = "NotificacioServiceV2Port")
    public NotificacioServiceV2 getNotificacioServiceV2Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.caib.es/notib/ws/notificacio", "NotificacioServiceV2Port"), NotificacioServiceV2.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NOTIFICACIOSERVICEV2_EXCEPTION!= null) {
            throw NOTIFICACIOSERVICEV2_EXCEPTION;
        }
        return NOTIFICACIOSERVICEV2_WSDL_LOCATION;
    }

}
