
package es.caib.notib.ws.notificacio;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NotificacioServiceWsException", targetNamespace = "http://www.caib.es/notib/ws/notificacio")
public class NotificacioServiceWsException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NotificacioServiceWsException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NotificacioServiceWsException_Exception(String message, NotificacioServiceWsException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public NotificacioServiceWsException_Exception(String message, NotificacioServiceWsException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: es.caib.notib.ws.notificacio.NotificacioServiceWsException
     */
    public NotificacioServiceWsException getFaultInfo() {
        return faultInfo;
    }

}
