UPDATE NOT_NOTIFICACIO_TABLE SET PER_ACTUALITZAR = 1;
UPDATE NOT_NOTIFICACIO_ENV_TABLE t SET REGISTRE_DATA = (SELECT nne.REGISTRE_DATA FROM NOT_NOTIFICACIO_ENV nne WHERE t.id = nne.id);
UPDATE NOT_NOTIFICACIO_TABLE SET REGISTRE_NUMS = (select listagg(E.REGISTRE_NUMERO_FORMATAT , ', ') WITHIN GROUP (ORDER BY E.ID) FROM NOT_NOTIFICACIO_ENV E WHERE E.NOTIFICACIO_ID = NOT_NOTIFICACIO_TABLE.ID);
INSERT INTO NOT_CONFIG (KEY, VALUE, DESCRIPTION, GROUP_CODE, POSITION, JBOSS_PROPERTY, TYPE_CODE, CONFIGURABLE) VALUES ('es.caib.notib.consulta.sir.dies.intents', '7', 'Dies que el pooling seguirà fent la consulta si aquesta no retorna un estat final', 'GENERAL', 0, 0, 'INT', 0);
