GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_USUARI TO NOTIB;
GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_ENTITAT TO NOTIB;
GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_APLICACIO TO NOTIB;
GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_NOTIFICACIO TO NOTIB;
GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_NOTIFICACIO_DEST TO NOTIB;
GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_NOTIFICACIO_EVENT TO NOTIB;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_ACL_CLASS TO NOTIB;
GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_ACL_ENTRY TO NOTIB;
GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_ACL_OBJECT_IDENTITY TO NOTIB;
GRANT SELECT, UPDATE, INSERT, DELETE ON NOT_ACL_SID TO NOTIB;
