ALTER TABLE NOT_PAGADOR_POSTAL
    ADD NOM VARCHAR2(256 CHAR) DEFAULT 'NO ESPECIFICAT' NOT NULL;

ALTER TABLE NOT_PAGADOR_CIE
    ADD NOM VARCHAR2(256 CHAR) DEFAULT 'NO ESPECIFICAT' NOT NULL;

ALTER TABLE NOT_PAGADOR_POSTAL
    MODIFY NOM DEFAULT NULL;

ALTER TABLE NOT_PAGADOR_CIE
    MODIFY NOM DEFAULT NULL;

CREATE TABLE NOT_ENTREGA_CIE
(
    ID                      NUMBER(19) NOT NULL,

    OPERADOR_POSTAL_ID      NUMBER(19) NOT NULL,
    CIE_ID                  NUMBER(19) NOT NULL,

    CREATEDBY_CODI          VARCHAR2(64),
    CREATEDDATE             TIMESTAMP(6),
    LASTMODIFIEDBY_CODI     VARCHAR2(64),
    LASTMODIFIEDDATE        TIMESTAMP(6)
);

ALTER TABLE NOT_ENTREGA_CIE ADD (
    CONSTRAINT NOT_ENTREGA_CIE_PK PRIMARY KEY (ID));

CREATE INDEX NOT_ENTREGA_CIE_CIE_EK ON NOT_ENTREGA_CIE(CIE_ID);
ALTER TABLE NOT_ENTREGA_CIE
    ADD CONSTRAINT NOT_ENTREGA_CIE_CIE_FK FOREIGN KEY (CIE_ID) REFERENCES NOT_PAGADOR_CIE(ID);

CREATE INDEX NOT_ENTREGA_CIE_OPERADOR_EK ON NOT_ENTREGA_CIE(OPERADOR_POSTAL_ID);
ALTER TABLE NOT_ENTREGA_CIE
    ADD CONSTRAINT NOT_ENTREGA_CIE_OPERADOR_FK FOREIGN KEY (OPERADOR_POSTAL_ID) REFERENCES NOT_PAGADOR_POSTAL(ID);

-- ENTITAT
ALTER TABLE NOT_ENTITAT
    DROP COLUMN AMB_ENTREGA_CIE;

ALTER TABLE NOT_ENTITAT
    ADD ENTREGA_CIE_ID NUMBER(19) DEFAULT NULL;

CREATE INDEX NOT_ENTITAT_ENTREGA_CIE_EK ON NOT_ENTITAT(ENTREGA_CIE_ID);
ALTER TABLE NOT_ENTITAT
    ADD CONSTRAINT NOT_ENTITAT_ENTREGA_CIE_FK FOREIGN KEY (ENTREGA_CIE_ID) REFERENCES NOT_ENTREGA_CIE(ID) ON DELETE CASCADE;


-- ORGAN GESTOR

ALTER TABLE NOT_ORGAN_GESTOR
    ADD ENTREGA_CIE_ID NUMBER(19) DEFAULT NULL;

CREATE INDEX NOT_ORGAN_ENTREGA_CIE_EK ON NOT_ORGAN_GESTOR(ENTREGA_CIE_ID);
ALTER TABLE NOT_ORGAN_GESTOR
    ADD CONSTRAINT NOT_ORGAN_ENTREGA_CIE_FK FOREIGN KEY (ENTREGA_CIE_ID) REFERENCES NOT_ENTREGA_CIE(ID) ON DELETE CASCADE;

-- PROCEDIMENT

ALTER TABLE NOT_PROCEDIMENT
    ADD ENTREGA_CIE_ID NUMBER(19) DEFAULT NULL;

CREATE INDEX NOT_PROCEDIMENT_ENTREGA_CIE_EK ON NOT_PROCEDIMENT(ENTREGA_CIE_ID);
ALTER TABLE NOT_PROCEDIMENT
    ADD CONSTRAINT NOT_PROCEDIMENT_ENTREGA_CIE_FK FOREIGN KEY (ENTREGA_CIE_ID) REFERENCES NOT_ENTREGA_CIE(ID) ON DELETE CASCADE;

INSERT INTO NOT_ENTREGA_CIE (ID, CIE_ID, OPERADOR_POSTAL_ID)
(SELECT ID, PAGADORCIE, PAGADORPOSTAL FROM NOT_PROCEDIMENT WHERE PAGADORCIE IS NOT NULL AND PAGADORPOSTAL IS NOT NULL);

SELECT PAGADORCIE, PAGADORPOSTAL FROM NOT_PROCEDIMENT WHERE PAGADORCIE IS NOT NULL AND PAGADORPOSTAL IS NOT NULL;
(SELECT DISTINCT ID FROM NOT_ENTREGA_CIE WHERE OPERADOR_POSTAL_ID = P.PAGADORPOSTAL AND CIE_ID = P.PAGADORCIE);

UPDATE NOT_PROCEDIMENT P
SET ENTREGA_CIE_ID = (SELECT DISTINCT P.ID FROM NOT_ENTREGA_CIE WHERE OPERADOR_POSTAL_ID = P.PAGADORPOSTAL AND CIE_ID = P.PAGADORCIE)
WHERE PAGADORCIE IS NOT NULL AND PAGADORPOSTAL IS NOT NULL;

ALTER TABLE NOT_PROCEDIMENT
    DROP COLUMN PAGADORPOSTAL;
ALTER TABLE NOT_PROCEDIMENT
    DROP COLUMN PAGADORCIE;
