UPDATE NOT_NOTIFICACIO_ENV_TABLE nnet SET nnet.REGISTRE_ENVIAMENT_INTENT = 
	(SELECT nn.REGISTRE_ENV_INTENT 
		FROM NOT_NOTIFICACIO nn 
		WHERE nn.ID = nnet.NOTIFICACIO_ID);

COMMIT;

UPDATE NOT_NOTIFICACIO_TABLE nnt SET nnt.REGISTRE_ENV_INTENT = 
	(SELECT nn.REGISTRE_ENV_INTENT 
		FROM NOT_NOTIFICACIO nn 
		WHERE nn.ID = nnt.ID);

COMMIT;
