CREATE USER notib IDENTIFIED BY notib;
GRANT ALL PRIVILEGES TO notib;


--------------------------------------------------------
--  Sequencies
--------------------------------------------------------

CREATE SEQUENCE  "NOTIB"."NOT_ACL_CLASS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "NOTIB"."NOT_ACL_ENTRY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "NOTIB"."NOT_ACL_OBJECT_IDENTITY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "NOTIB"."NOT_ACL_SID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "NOTIB"."NOT_HIBERNATE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

--------------------------------------------------------
--  Taules
--------------------------------------------------------

CREATE TABLE "NOTIB"."NOT_ACL_CLASS" (
                                         "ID" NUMBER(19,0),
                                         "CLASS" VARCHAR2(100 BYTE)
);

CREATE TABLE "NOTIB"."NOT_ACL_ENTRY"
(	"ID" NUMBER(19,0),
     "ACL_OBJECT_IDENTITY" NUMBER(19,0),
     "ACE_ORDER" NUMBER(19,0),
     "SID" NUMBER(19,0),
     "MASK" NUMBER(19,0),
     "GRANTING" NUMBER(1,0),
     "AUDIT_SUCCESS" NUMBER(1,0),
     "AUDIT_FAILURE" NUMBER(1,0)
);

CREATE TABLE "NOTIB"."NOT_ACL_OBJECT_IDENTITY"
(	"ID" NUMBER(19,0),
     "OBJECT_ID_CLASS" NUMBER(19,0),
     "OBJECT_ID_IDENTITY" NUMBER(19,0),
     "PARENT_OBJECT" NUMBER(19,0),
     "OWNER_SID" NUMBER(19,0),
     "ENTRIES_INHERITING" NUMBER(1,0)
);

CREATE TABLE "NOTIB"."NOT_ACL_SID"
(	"ID" NUMBER(19,0),
     "PRINCIPAL" NUMBER(1,0),
     "SID" VARCHAR2(100 BYTE)
);

CREATE TABLE "NOTIB"."NOT_APLICACIO"
(	"ID" NUMBER(19,0),
     "USUARI_CODI" VARCHAR2(64 BYTE),
     "CALLBACK_URL" VARCHAR2(256 BYTE),
     "CREATEDBY_CODI" VARCHAR2(64 BYTE),
     "CREATEDDATE" TIMESTAMP (6),
     "LASTMODIFIEDBY_CODI" VARCHAR2(64 BYTE),
     "LASTMODIFIEDDATE" TIMESTAMP (6),
     "ENTITAT_ID" NUMBER(19,0),
     "ACTIVA" NUMBER(1,0) DEFAULT 1
);

CREATE TABLE "NOTIB"."NOT_APLICACIO_AUDIT"
(	"ID" NUMBER(19,0),
     "TIPUSOPERACIO" VARCHAR2(20 CHAR),
     "JOINPOINT" VARCHAR2(256 CHAR),
     "CREATEDBY_CODI" VARCHAR2(64 CHAR),
     "CREATEDDATE" TIMESTAMP (6),
     "LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR),
     "LASTMODIFIEDDATE" TIMESTAMP (6),
     "APLICACIO_ID" NUMBER(19,0),
     "ENTITAT_ID" NUMBER(19,0),
     "USUARI_CODI" VARCHAR2(64 CHAR),
     "CALLBACK_URL" VARCHAR2(256 CHAR),
     "ACTIVA" NUMBER(1,0)
);

CREATE TABLE "NOTIB"."NOT_COLUMNES"
(	"ID" NUMBER(19,0),
     "CREATED_DATE" NUMBER(1,0),
     "DATA_PROGRAMADA" NUMBER(1,0),
     "NOT_IDENTIFICADOR" NUMBER(1,0),
     "PRO_CODI" NUMBER(1,0),
     "GRUP_CODI" NUMBER(1,0),
     "DIR3_CODI" NUMBER(1,0),
     "USUARI" NUMBER(1,0),
     "ENVIAMENT_TIPUS" NUMBER(1,0),
     "CONCEPTE" NUMBER(1,0),
     "DESCRIPCIO" NUMBER(1,0),
     "TITULAR_NIF" NUMBER(1,0),
     "TITULAR_NOM_LLINATGE" NUMBER(1,0),
     "TITULAR_EMAIL" NUMBER(1,0),
     "DESTINATARIS" NUMBER(1,0),
     "LLIBRE_REGISTRE" NUMBER(1,0),
     "NUMERO_REGISTRE" NUMBER(1,0),
     "DATA_REGISTRE" NUMBER(1,0),
     "DATA_CADUCITAT" NUMBER(1,0),
     "CODI_NOTIB_ENV" NUMBER(1,0),
     "NUM_CERTIFICACIO" NUMBER(1,0),
     "CSV_UUID" NUMBER(1,0),
     "ESTAT" NUMBER(1,0),
     "ENTITAT_ID" NUMBER(19,0),
     "USUARI_CODI" VARCHAR2(64 BYTE),
     "CREATEDBY_CODI" VARCHAR2(64 BYTE),
     "CREATEDDATE" TIMESTAMP (6),
     "LASTMODIFIEDBY_CODI" VARCHAR2(64 BYTE),
     "LASTMODIFIEDDATE" TIMESTAMP (6)
);

CREATE TABLE "NOTIB"."NOT_DOCUMENT"
(	"ID" NUMBER(19,0),
     "ARXIU_ID" VARCHAR2(100 BYTE),
     "ARXIU_NOM" VARCHAR2(200 CHAR),
     "HASH" VARCHAR2(2048 BYTE),
     "URL" VARCHAR2(256 BYTE),
     "TELEFON" VARCHAR2(16 BYTE),
     "METADADES" VARCHAR2(256 BYTE),
     "NORMALITZAT" NUMBER(1,0),
     "GENERAR_CSV" NUMBER(1,0),
     "UUID" VARCHAR2(64 BYTE),
     "CSV" VARCHAR2(256 BYTE),
     "CREATEDBY_CODI" VARCHAR2(64 BYTE),
     "CREATEDDATE" TIMESTAMP (6),
     "LASTMODIFIEDBY_CODI" VARCHAR2(64 BYTE),
     "LASTMODIFIEDDATE" TIMESTAMP (6),
     "ARXIU_GEST_DOC_ID" VARCHAR2(64 BYTE),
     "CONTINGUT_BASE_64" CLOB,
     "MEDIA" VARCHAR2(256 CHAR),
     "MIDA" NUMBER(19,0),
     "ORIGEN" VARCHAR2(20 CHAR),
     "VALIDESA" VARCHAR2(20 CHAR),
     "TIPUS_DOCUMENTAL" VARCHAR2(30 CHAR),
     "FIRMAT" NUMBER(1,0)
);

CREATE TABLE "NOTIB"."NOT_ENTITAT"
(	"ID" NUMBER(19,0),
     "CODI" VARCHAR2(64 BYTE),
     "NOM" VARCHAR2(256 BYTE),
     "TIPUS" VARCHAR2(32 BYTE),
     "DIR3_CODI" VARCHAR2(9 BYTE),
     "DESCRIPCIO" VARCHAR2(1024 BYTE),
     "ACTIVA" NUMBER(1,0),
     "VERSION" NUMBER(19,0),
     "CREATEDBY_CODI" VARCHAR2(64 BYTE),
     "CREATEDDATE" TIMESTAMP (6),
     "LASTMODIFIEDBY_CODI" VARCHAR2(64 BYTE),
     "LASTMODIFIEDDATE" TIMESTAMP (6),
     "API_KEY" VARCHAR2(64 BYTE),
     "LOGO_CAP" BLOB,
     "LOGO_PEU" BLOB,
     "COLOR_FONS" VARCHAR2(32 BYTE),
     "COLOR_LLETRA" VARCHAR2(32 BYTE),
     "TIPUS_DOC_DEFAULT" NUMBER(32,0),
     "AMB_ENTREGA_DEH" NUMBER(1,0) DEFAULT 0,
     "DIR3_CODI_REG" VARCHAR2(9 BYTE),
     "AMB_ENTREGA_CIE" NUMBER(1,0) DEFAULT 0,
     "NOM_OFICINA_VIRTUAL" VARCHAR2(255 CHAR),
     "OFICINA" VARCHAR2(255 CHAR),
     "LLIBRE" VARCHAR2(255 CHAR),
     "LLIBRE_NOM" VARCHAR2(255 CHAR),
     "LLIBRE_ENTITAT" NUMBER(1,0),
     "OFICINA_ENTITAT" NUMBER(1,0) DEFAULT 1
);

CREATE TABLE "NOTIB"."NOT_ENTITAT_AUDIT"
(	"ID" NUMBER(19,0),
     "TIPUSOPERACIO" VARCHAR2(20 CHAR),
     "JOINPOINT" VARCHAR2(256 CHAR),
     "CREATEDBY_CODI" VARCHAR2(64 CHAR),
     "CREATEDDATE" TIMESTAMP (6),
     "LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR),
     "LASTMODIFIEDDATE" TIMESTAMP (6),
     "ENTITAT_ID" NUMBER(19,0),
     "CODI" VARCHAR2(64 CHAR),
     "NOM" VARCHAR2(256 CHAR),
     "TIPUS" VARCHAR2(32 CHAR),
     "DIR3_CODI" VARCHAR2(9 CHAR),
     "DIR3_CODI_REG" VARCHAR2(9 CHAR),
     "API_KEY" VARCHAR2(64 CHAR),
     "AMB_ENTREGA_DEH" NUMBER(1,0),
     "AMB_ENTREGA_CIE" NUMBER(1,0),
     "DESCRIPCIO" VARCHAR2(1024 CHAR),
     "ACTIVA" NUMBER(1,0),
     "NOM_OFICINA_VIRTUAL" VARCHAR2(255 CHAR),
     "OFICINA" VARCHAR2(255 CHAR),
     "LLIBRE_ENTITAT" NUMBER(1,0),
     "LLIBRE" VARCHAR2(255 CHAR),
     "LLIBRE_NOM" VARCHAR2(255 CHAR)
);

CREATE TABLE "NOTIB"."NOT_ENTITAT_TIPUS_DOC"
(	"ID" NUMBER(19,0),
     "ENTITAT_ID" NUMBER(19,0),
     "CREATEDBY_CODI" VARCHAR2(64 BYTE),
     "CREATEDDATE" TIMESTAMP (6),
     "LASTMODIFIEDBY_CODI" VARCHAR2(64 BYTE),
     "LASTMODIFIEDDATE" TIMESTAMP (6),
     "TIPUS_DOC" NUMBER(32,0)
);

CREATE TABLE "NOTIB"."NOT_FORMATS_FULLA"
(	"ID" NUMBER(19,0),
     "PAGADOR_CIE_ID" NUMBER(19,0),
     "CODI" VARCHAR2(64 BYTE),
     "CREATEDBY_CODI" VARCHAR2(64 BYTE),
     "CREATEDDATE" TIMESTAMP (6),
     "LASTMODIFIEDBY_CODI" VARCHAR2(64 BYTE),
     "LASTMODIFIEDDATE" TIMESTAMP (6)
);

CREATE TABLE "NOTIB"."NOT_FORMATS_SOBRE"
(	"ID" NUMBER(19,0),
     "PAGADOR_CIE_ID" NUMBER(19,0),
     "CODI" VARCHAR2(64 BYTE),
     "CREATEDBY_CODI" VARCHAR2(64 BYTE),
     "CREATEDDATE" TIMESTAMP (6),
     "LASTMODIFIEDBY_CODI" VARCHAR2(64 BYTE),
     "LASTMODIFIEDDATE" TIMESTAMP (6)
);

CREATE TABLE "NOTIB"."NOT_GRUP"
(	"ID" NUMBER(19,0),
     "CODI" VARCHAR2(255 CHAR),
     "NOM" VARCHAR2(255 CHAR),
     "ENTITAT" NUMBER(19,0),
     "CREATEDBY_CODI" VARCHAR2(64 BYTE),
     "CREATEDDATE" TIMESTAMP (6),
     "LASTMODIFIEDBY_CODI" VARCHAR2(64 BYTE),
     "LASTMODIFIEDDATE" TIMESTAMP (6),
     "ORGAN_GESTOR" NUMBER(19,0)
);

CREATE TABLE "NOTIB"."NOT_GRUP_AUDIT"
(	"ID" NUMBER(19,0),
     "TIPUSOPERACIO" VARCHAR2(20 CHAR),
     "JOINPOINT" VARCHAR2(256 CHAR),
     "CREATEDBY_CODI" VARCHAR2(64 CHAR),
     "CREATEDDATE" TIMESTAMP (6),
     "LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR),
     "LASTMODIFIEDDATE" TIMESTAMP (6),
     "GRUP_ID" NUMBER(19,0),
     "CODI" VARCHAR2(64 CHAR),
     "NOM" VARCHAR2(100 CHAR),
     "ENTITAT_ID" NUMBER(19,0),
     "ORGAN" VARCHAR2(64 CHAR)
);

CREATE TABLE "NOTIB"."NOT_NOTIFICACIO"
(	"ID" NUMBER(19,0),
     "EMISOR_DIR3CODI" VARCHAR2(9 BYTE),
     "COM_TIPUS" NUMBER(10,0),
     "ENV_TIPUS" NUMBER(10,0),
     "CONCEPTE" VARCHAR2(240 CHAR),
     "DESCRIPCIO" VARCHAR2(1000 CHAR),
     "PAGCOR_DIR3" VARCHAR2(9 BYTE),
     "PAGCOR_NUMCONT" VARCHAR2(20 BYTE),
     "PAGCOR_CODI_CLIENT" VARCHAR2(20 BYTE),
     "PAGCOR_DATA_VIG" DATE,
     "PAGCIE_DIR3" VARCHAR2(9 BYTE),
     "PAGCIE_DATA_VIG" DATE,
     "PROC_CODI_NOTIB" VARCHAR2(9 BYTE),
     "PROC_DESC_SIA" VARCHAR2(256 BYTE),
     "CADUCITAT" DATE,
     "ESTAT" NUMBER(10,0),
     "NOT_ERROR_TIPUS" NUMBER(10,0),
     "NOT_ENV_DATA" TIMESTAMP (6),
     "NOT_ENV_INTENT" NUMBER(10,0),
     "NOT_REENV_DATA" TIMESTAMP (6),
     "NOT_ERROR_EVENT_ID" NUMBER(19,0),
     "ENTITAT_ID" NUMBER(19,0),
     "CREATEDBY_CODI" VARCHAR2(64 BYTE),
     "CREATEDDATE" TIMESTAMP (6),
     "LASTMODIFIEDBY_CODI" VARCHAR2(64 BYTE),
     "LASTMODIFIEDDATE" TIMESTAMP (6),
     "GRUP_CODI" VARCHAR2(64 BYTE),
     "CSV_UUID" VARCHAR2(64 BYTE),
     "REGISTRE_NUM_EXPEDIENT" VARCHAR2(20 BYTE),
     "RETARD_POSTAL" NUMBER,
     "ENV_DATA_PROG" DATE,
     "USUARI_CODI" VARCHAR2(64 BYTE),
     "DOCUMENT_ID" NUMBER,
     "PAGADOR_POSTAL_ID" NUMBER,
     "PAGADOR_CIE_ID" NUMBER,
     "PROCEDIMENT_ID" NUMBER,
     "REGISTRE_NUMERO" NUMBER(19,0),
     "REGISTRE_DATA" DATE,
     "REGISTRE_NUMERO_FORMATAT" VARCHAR2(200 BYTE),
     "MOTIU" VARCHAR2(255 BYTE),
     "ORGAN_GESTOR" VARCHAR2(19 BYTE),
     "ESTAT_DATE" TIMESTAMP (6),
     "TIPUS_USUARI" NUMBER(1,0),
     "REGISTRE_ENV_INTENT" NUMBER(10,0),
     "CALLBACK_ERROR" NUMBER(1,0) DEFAULT 0,
     "PROCEDIMENT_ORGAN_ID" NUMBER(19,0),
     "NOT_ENV_DATA_NOTIFICA" TIMESTAMP (6),
     "IDIOMA" NUMBER(10,0),
     "DOCUMENT2_ID" NUMBER(19,0),
     "DOCUMENT3_ID" NUMBER(19,0),
     "DOCUMENT4_ID" NUMBER(19,0),
     "DOCUMENT5_ID" NUMBER(19,0),
     "REGISTRE_OFICINA_NOM" VARCHAR2(255 CHAR),
     "REGISTRE_LLIBRE_NOM" VARCHAR2(255 CHAR),
     "IS_ERROR_LAST_EVENT" NUMBER(1,0) DEFAULT 0
);

CREATE TABLE "NOTIB"."NOT_NOTIFICACIO_AUDIT"
(	"ID" NUMBER(19,0),
     "TIPUSOPERACIO" VARCHAR2(20 CHAR),
     "JOINPOINT" VARCHAR2(256 CHAR),
     "CREATEDBY_CODI" VARCHAR2(64 CHAR),
     "CREATEDDATE" TIMESTAMP (6),
     "LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR),
     "LASTMODIFIEDDATE" TIMESTAMP (6),
     "NOTIFICACIO_ID" NUMBER(19,0),
     "SINCRON" VARCHAR2(20 CHAR),
     "TIPUS_USUARI" VARCHAR2(20 CHAR),
     "USUARI" VARCHAR2(64 CHAR),
     "EMISOR" VARCHAR2(9 CHAR),
     "TIPUS" VARCHAR2(20 CHAR),
     "ENTITAT_ID" NUMBER(19,0),
     "ORGAN" VARCHAR2(64 CHAR),
     "PROCEDIMENT" VARCHAR2(64 CHAR),
     "GRUP" VARCHAR2(64 CHAR),
     "CONCEPTE" VARCHAR2(255 CHAR),
     "DESCRIPCIO" VARCHAR2(1000 CHAR),
     "NUM_EXPEDIENT" VARCHAR2(80 CHAR),
     "ENV_DATA_PROG" DATE,
     "RETARD_POSTAL" NUMBER(10,0),
     "CADUCITAT" DATE,
     "DOCUMENT_ID" NUMBER(19,0),
     "ESTAT" VARCHAR2(20 CHAR),
     "ESTAT_DATE" TIMESTAMP (6),
     "MOTIU" VARCHAR2(255 CHAR),
     "PAGADOR_POSTAL_ID" NUMBER(19,0),
     "PAGADOR_CIE_ID" NUMBER(19,0),
     "REGISTRE_ENV_INTENT" NUMBER(10,0),
     "REGISTRE_NUMERO" NUMBER(10,0),
     "REGISTRE_NUMERO_FORMATAT" VARCHAR2(200 CHAR),
     "REGISTRE_DATA" DATE,
     "NOT_ENV_DATA" TIMESTAMP (6),
     "NOT_ENV_INTENT" NUMBER(10,0),
     "NOT_ERROR_TIPUS" VARCHAR2(30 CHAR),
     "CALLBACK_ERROR" NUMBER(1,0),
     "EVENT_ERROR" NUMBER(19,0)
);

CREATE TABLE "NOTIB"."NOT_NOTIFICACIO_ENV"
(	"ID" NUMBER(19,0),
     "DOM_TIPUS" NUMBER(10,0),
     "DOM_CON_TIPUS" NUMBER(10,0),
     "DOM_VIA_TIPUS" NUMBER(10,0),
     "DOM_VIA_NOM" VARCHAR2(50 CHAR),
     "DOM_NUM_TIPUS" NUMBER(10,0),
     "DOM_NUM_NUM" VARCHAR2(10 BYTE),
     "DOM_NUM_QUALIF" VARCHAR2(3 BYTE),
     "DOM_NUM_PUNTKM" VARCHAR2(10 BYTE),
     "DOM_APARTAT" VARCHAR2(10 BYTE),
     "DOM_BLOC" VARCHAR2(50 BYTE),
     "DOM_PORTAL" VARCHAR2(50 BYTE),
     "DOM_ESCALA" VARCHAR2(50 BYTE),
     "DOM_PLANTA" VARCHAR2(50 BYTE),
     "DOM_PORTA" VARCHAR2(50 BYTE),
     "DOM_COMPLEM" VARCHAR2(250 BYTE),
     "DOM_POBLACIO" VARCHAR2(255 CHAR),
     "DOM_MUN_CODINE" VARCHAR2(6 BYTE),
     "DOM_MUN_NOM" VARCHAR2(64 BYTE),
     "DOM_CODI_POSTAL" VARCHAR2(10 BYTE),
     "DOM_PRV_CODI" VARCHAR2(2 BYTE),
     "DOM_PRV_NOM" VARCHAR2(64 BYTE),
     "DOM_PAI_CODISO" VARCHAR2(3 BYTE),
     "DOM_PAI_NOM" VARCHAR2(64 BYTE),
     "DOM_LINEA1" VARCHAR2(50 CHAR),
     "DOM_LINEA2" VARCHAR2(50 CHAR),
     "DOM_CIE" NUMBER(10,0),
     "DEH_OBLIGAT" NUMBER(1,0),
     "DEH_NIF" VARCHAR2(9 BYTE),
     "DEH_PROC_CODI" VARCHAR2(64 CHAR),
     "SERVEI_TIPUS" NUMBER(10,0),
     "FORMAT_SOBRE" VARCHAR2(10 BYTE),
     "FORMAT_FULLA" VARCHAR2(10 BYTE),
     "NOTIFICA_REF" VARCHAR2(20 BYTE),
     "NOTIFICA_ID" VARCHAR2(20 BYTE),
     "NOTIFICA_DATCRE" TIMESTAMP (6),
     "NOTIFICA_DATDISP" TIMESTAMP (6),
     "NOTIFICA_DATCAD" TIMESTAMP (6),
     "NOTIFICA_EMI_DIR3CODI" VARCHAR2(9 BYTE),
     "NOTIFICA_EMI_DIR3DESC" VARCHAR2(256 CHAR),
     "NOTIFICA_EMI_DIR3NIF" VARCHAR2(9 BYTE),
     "NOTIFICA_ARR_DIR3CODI" VARCHAR2(9 BYTE),
     "NOTIFICA_ARR_DIR3DESC" VARCHAR2(256 CHAR),
     "NOTIFICA_ARR_DIR3NIF" VARCHAR2(9 BYTE),
     "NOTIFICA_ESTAT" NUMBER(10,0),
     "NOTIFICA_ESTAT_DATA" TIMESTAMP (6),
     "NOTIFICA_ESTAT_DATAACT" TIMESTAMP (6),
     "NOTIFICA_ESTAT_FINAL" NUMBER(1,0),
     "NOTIFICA_ESTAT_DESC" VARCHAR2(50 BYTE),
     "NOTIFICA_DATAT_ORIGEN" VARCHAR2(20 BYTE),
     "NOTIFICA_DATAT_RECNIF" VARCHAR2(9 BYTE),
     "NOTIFICA_DATAT_RECNOM" VARCHAR2(400 BYTE),
     "NOTIFICA_DATAT_NUMSEG" VARCHAR2(50 BYTE),
     "NOTIFICA_DATAT_ERRDES" VARCHAR2(255 BYTE),
     "NOTIFICA_CER_DATA" TIMESTAMP (6),
     "NOTIFICA_CER_ARXIUID" VARCHAR2(64 BYTE),
     "NOTIFICA_CER_HASH" VARCHAR2(100 BYTE),
     "NOTIFICA_CER_ORIGEN" VARCHAR2(50 BYTE),
     "NOTIFICA_CER_METAS" VARCHAR2(255 BYTE),
     "NOTIFICA_CER_CSV" VARCHAR2(50 BYTE),
     "NOTIFICA_CER_MIME" VARCHAR2(20 BYTE),
     "NOTIFICA_CER_TAMANY" NUMBER(10,0),
     "NOTIFICA_CER_TIPUS" NUMBER(10,0),
     "NOTIFICA_CER_ARXTIP" NUMBER(10,0),
     "NOTIFICA_CER_NUMSEG" VARCHAR2(50 BYTE),
     "NOTIFICA_ERROR" NUMBER(1,0),
     "NOTIFICA_ERROR_EVENT_ID" NUMBER(19,0),
     "NOTIFICA_INTENT_DATA" TIMESTAMP (6),
     "NOTIFICA_INTENT_NUM" NUMBER(10,0),
     "NOTIFICACIO_ID" NUMBER(19,0),
     "CREATEDBY_CODI" VARCHAR2(64 BYTE),
     "CREATEDDATE" TIMESTAMP (6),
     "LASTMODIFIEDBY_CODI" VARCHAR2(64 BYTE),
     "LASTMODIFIEDDATE" TIMESTAMP (6),
     "NOTIFICA_ESTAT_ERROR" VARCHAR2(255 BYTE),
     "TITULAR_ID" NUMBER,
     "REGISTRE_NUMERO_FORMATAT" VARCHAR2(200 BYTE),
     "REGISTRE_DATA" DATE,
     "ESTAT_REGISTRE" NUMBER(19,0),
     "REGISTRE_ESTAT_FINAL" NUMBER(1,0),
     "SIR_CON_DATA" TIMESTAMP (6),
     "SIR_CON_INTENT" NUMBER(10,0) DEFAULT 0,
     "SIR_REC_DATA" TIMESTAMP (6),
     "SIR_REG_DESTI_DATA" TIMESTAMP (6)
);

CREATE TABLE "NOTIB"."NOT_NOTIFICACIO_ENV_AUDIT"
(	"ID" NUMBER(19,0),
     "TIPUSOPERACIO" VARCHAR2(20 CHAR),
     "JOINPOINT" VARCHAR2(256 CHAR),
     "CREATEDBY_CODI" VARCHAR2(64 CHAR),
     "CREATEDDATE" TIMESTAMP (6),
     "LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR),
     "LASTMODIFIEDDATE" TIMESTAMP (6),
     "ENVIAMENT_ID" NUMBER(19,0),
     "NOTIFICACIO_ID" NUMBER(19,0),
     "TITULAR_ID" NUMBER(19,0),
     "DESTINATARIS_ID" VARCHAR2(200 CHAR),
     "DOMICILI_TIPUS" VARCHAR2(20 CHAR),
     "DOMICILI" VARCHAR2(500 CHAR),
     "SERVEI_TIPUS" VARCHAR2(20 CHAR),
     "CIE" NUMBER(10,0),
     "FORMAT_SOBRE" VARCHAR2(10 CHAR),
     "FORMAT_FULLA" VARCHAR2(10 CHAR),
     "DEH_OBLIGAT" NUMBER(1,0),
     "DEH_NIF" VARCHAR2(9 CHAR),
     "NOTIFICA_REF" VARCHAR2(20 CHAR),
     "NOTIFICA_ID" VARCHAR2(20 CHAR),
     "NOTIFICA_DATCRE" TIMESTAMP (6),
     "NOTIFICA_DATDISP" TIMESTAMP (6),
     "NOTIFICA_DATCAD" TIMESTAMP (6),
     "NOTIFICA_EMI_DIR3CODI" VARCHAR2(9 CHAR),
     "NOTIFICA_ARR_DIR3CODI" VARCHAR2(9 CHAR),
     "NOTIFICA_ESTAT" NUMBER(10,0),
     "NOTIFICA_ESTAT_DATA" TIMESTAMP (6),
     "NOTIFICA_ESTAT_FINAL" NUMBER(1,0),
     "NOTIFICA_DATAT_ORIGEN" VARCHAR2(20 CHAR),
     "NOTIFICA_DATAT_RECNIF" VARCHAR2(9 CHAR),
     "NOTIFICA_DATAT_NUMSEG" VARCHAR2(50 CHAR),
     "NOTIFICA_CER_DATA" TIMESTAMP (6),
     "NOTIFICA_CER_ARXIUID" VARCHAR2(50 CHAR),
     "NOTIFICA_CER_ORIGEN" VARCHAR2(20 CHAR),
     "NOTIFICA_CER_TIPUS" VARCHAR2(20 CHAR),
     "NOTIFICA_CER_ARXTIP" VARCHAR2(20 CHAR),
     "NOTIFICA_CER_NUMSEG" VARCHAR2(50 CHAR),
     "REGISTRE_NUMERO_FORMATAT" VARCHAR2(50 CHAR),
     "REGISTRE_DATA" TIMESTAMP (6),
     "REGISTRE_ESTAT" VARCHAR2(20 CHAR),
     "REGISTRE_ESTAT_FINAL" NUMBER(1,0),
     "SIR_CON_DATA" TIMESTAMP (6),
     "SIR_REC_DATA" TIMESTAMP (6),
     "SIR_REG_DESTI_DATA" TIMESTAMP (6),
     "NOTIFICA_ERROR_EVENT_ID" NUMBER(19,0),
     "NOTIFICA_ERROR" NUMBER(1,0),
     "NOTIFICA_DATAT_ERRDES" VARCHAR2(255 CHAR)
);

CREATE TABLE "NOTIB"."NOT_NOTIFICACIO_ENV_TABLE"
(	"ID" NUMBER(19,0),
     "NOTIFICACIO_ID" NUMBER(19,0),
     "ENTITAT_ID" NUMBER(19,0),
     "DESTINATARIS" VARCHAR2(4000 CHAR) DEFAULT '',
     "TIPUS_ENVIAMENT" NUMBER(10,0),
     "TITULAR_NIF" VARCHAR2(9 CHAR),
     "TITULAR_NOM" VARCHAR2(256 CHAR),
     "TITULAR_EMAIL" VARCHAR2(160 CHAR),
     "TITULAR_LLINATGE1" VARCHAR2(40 CHAR),
     "TITULAR_LLINATGE2" VARCHAR2(40 CHAR),
     "TITULAR_RAOSOCIAL" VARCHAR2(100 CHAR),
     "DATA_PROGRAMADA" DATE,
     "PROCEDIMENT_CODI_NOTIB" VARCHAR2(9 BYTE),
     "GRUP_CODI" VARCHAR2(64 CHAR),
     "EMISOR_DIR3" VARCHAR2(9 CHAR),
     "USUARI_CODI" VARCHAR2(64 CHAR),
     "NOT_ORGAN_CODI" VARCHAR2(64 BYTE),
     "CONCEPTE" VARCHAR2(240 CHAR),
     "DESCRIPCIO" VARCHAR2(1000 CHAR),
     "LLIBRE" VARCHAR2(255 CHAR),
     "NOT_ESTAT" NUMBER(10,0),
     "CSV_UUID" VARCHAR2(256 CHAR),
     "HAS_ERRORS" NUMBER(1,0) DEFAULT 0,
     "PROCEDIMENT_IS_COMU" NUMBER(1,0) DEFAULT 0,
     "PROCEDIMENT_PROCORGAN_ID" NUMBER(19,0),
     "REGISTRE_NUMERO" NUMBER(10,0),
     "REGISTRE_DATA" DATE,
     "REGISTRE_ENVIAMENT_INTENT" NUMBER(10,0),
     "NOTIFICA_DATA_CADUCITAT" TIMESTAMP (6),
     "NOTIFICA_IDENTIFICADOR" VARCHAR2(20 CHAR),
     "NOTIFICA_CERT_NUM_SEGUIMENT" VARCHAR2(50 CHAR),
     "NOTIFICA_ESTAT" NUMBER(10,0),
     "NOTIFICA_REF" VARCHAR2(20 CHAR),
     "CREATEDDATE" TIMESTAMP (6),
     "CREATEDBY_CODI" VARCHAR2(64 CHAR),
     "LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR),
     "LASTMODIFIEDDATE" TIMESTAMP (6)
);

CREATE TABLE "NOTIB"."NOT_NOTIFICACIO_EVENT"
(	"ID" NUMBER(19,0),
     "TIPUS" NUMBER(10,0),
     "DATA" TIMESTAMP (6),
     "DESCRIPCIO" VARCHAR2(256 BYTE),
     "ERROR" NUMBER(1,0),
     "ERROR_DESC" VARCHAR2(2048 CHAR),
     "NOTIFICACIO_ID" NUMBER(19,0),
     "NOTIFICACIO_ENV_ID" NUMBER(19,0),
     "CALLBACK_ESTAT" VARCHAR2(10 BYTE),
     "CALLBACK_DATA" TIMESTAMP (6),
     "CALLBACK_INTENTS" NUMBER(10,0),
     "CALLBACK_ERROR_DESC" VARCHAR2(2048 CHAR),
     "CREATEDBY_CODI" VARCHAR2(64 BYTE),
     "CREATEDDATE" TIMESTAMP (6),
     "LASTMODIFIEDBY_CODI" VARCHAR2(64 BYTE),
     "LASTMODIFIEDDATE" TIMESTAMP (6),
     "NOTIFICA_ERROR_TIPUS" NUMBER(10,0)
);

CREATE TABLE "NOTIB"."NOT_NOTIFICACIO_TABLE"
(	"ID" NUMBER(19,0),
     "ENTITAT_ID" NUMBER(19,0),
     "ENTITAT_NOM" VARCHAR2(256 CHAR),
     "PROC_CODI_NOTIB" VARCHAR2(9 BYTE),
     "PROCEDIMENT_ORGAN_ID" NUMBER(19,0),
     "GRUP_CODI" VARCHAR2(64 CHAR),
     "USUARI_CODI" VARCHAR2(64 CHAR),
     "TIPUS_USUARI" NUMBER(10,0),
     "ERROR_LAST_CALLBACK" NUMBER(1,0) DEFAULT 0,
     "ERROR_LAST_EVENT" NUMBER(1,0) DEFAULT 0,
     "REGISTRE_ENV_INTENT" NUMBER(10,0),
     "REGISTRE_NUM_EXPEDIENT" VARCHAR2(80 CHAR),
     "NOTIFICA_ERROR_DATE" DATE,
     "NOTIFICA_ERROR_DESCRIPCIO" VARCHAR2(2048 CHAR),
     "ENV_TIPUS" NUMBER(10,0),
     "CONCEPTE" VARCHAR2(255 CHAR),
     "ESTAT" NUMBER(10,0),
     "ESTAT_DATE" TIMESTAMP (6),
     "PROCEDIMENT_CODI" VARCHAR2(64 CHAR),
     "PROCEDIMENT_NOM" VARCHAR2(256 CHAR),
     "PROCEDIMENT_IS_COMU" NUMBER(1,0) DEFAULT 0,
     "ORGAN_CODI" VARCHAR2(64 BYTE),
     "ORGAN_NOM" VARCHAR2(1000 BYTE),
     "CREATEDDATE" TIMESTAMP (6),
     "CREATEDBY_CODI" VARCHAR2(64 CHAR),
     "LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR),
     "LASTMODIFIEDDATE" TIMESTAMP (6)
);

CREATE TABLE "NOTIB"."NOT_ORGAN_GESTOR"
(	"ID" NUMBER(19,0),
     "CODI" VARCHAR2(64 BYTE),
     "ENTITAT" NUMBER(19,0),
     "NOM" VARCHAR2(1000 BYTE),
     "LLIBRE" VARCHAR2(255 CHAR),
     "LLIBRE_NOM" VARCHAR2(255 CHAR),
     "OFICINA" VARCHAR2(255 CHAR),
     "OFICINA_NOM" VARCHAR2(255 CHAR)
);

CREATE TABLE "NOTIB"."NOT_PAGADOR_CIE"
(	"ID" NUMBER(19,0),
     "DIR3_CODI" VARCHAR2(9 BYTE),
     "CONTRACTE_DATA_VIG" DATE,
     "CREATEDBY_CODI" VARCHAR2(64 BYTE),
     "CREATEDDATE" TIMESTAMP (6),
     "LASTMODIFIEDBY_CODI" VARCHAR2(64 BYTE),
     "LASTMODIFIEDDATE" TIMESTAMP (6),
     "ENTITAT" NUMBER(19,0),
     "ORGAN_GESTOR" NUMBER(19,0)
);

CREATE TABLE "NOTIB"."NOT_PAGADOR_POSTAL"
(	"ID" NUMBER(19,0),
     "DIR3_CODI" VARCHAR2(9 BYTE),
     "CONTRACTE_NUM" VARCHAR2(20 BYTE),
     "CONTRACTE_DATA_VIG" DATE,
     "FACTURACIO_CODI_CLIENT" VARCHAR2(20 BYTE),
     "CREATEDBY_CODI" VARCHAR2(64 BYTE),
     "CREATEDDATE" TIMESTAMP (6),
     "LASTMODIFIEDBY_CODI" VARCHAR2(64 BYTE),
     "LASTMODIFIEDDATE" TIMESTAMP (6),
     "ENTITAT" NUMBER(19,0),
     "ORGAN_GESTOR" NUMBER(19,0)
);

CREATE TABLE "NOTIB"."NOT_PERSONA"
(	"ID" NUMBER(19,0),
     "EMAIL" VARCHAR2(160 CHAR),
     "LLINATGE1" VARCHAR2(40 CHAR),
     "LLINATGE2" VARCHAR2(40 CHAR),
     "NIF" VARCHAR2(9 BYTE),
     "NOM" VARCHAR2(255 CHAR),
     "TELEFON" VARCHAR2(16 BYTE),
     "RAO_SOCIAL" VARCHAR2(100 BYTE),
     "COD_ENTITAT_DESTI" VARCHAR2(9 BYTE),
     "NOTIFICACIO_ENV_ID" NUMBER,
     "LASTMODIFIEDDATE" TIMESTAMP (6),
     "CREATEDBY_CODI" VARCHAR2(64 BYTE),
     "CREATEDDATE" TIMESTAMP (6),
     "LASTMODIFIEDBY_CODI" VARCHAR2(64 BYTE),
     "INTERESSATTIPUS" VARCHAR2(30 BYTE),
     "INCAPACITAT" NUMBER(1,0) DEFAULT 1
);

CREATE TABLE "NOTIB"."NOT_PROCEDIMENT"
(	"ID" NUMBER(19,0),
     "CODI" VARCHAR2(64 BYTE),
     "NOM" VARCHAR2(256 CHAR),
     "CODISIA" VARCHAR2(64 BYTE),
     "ENTITAT" NUMBER(19,0),
     "PAGADORPOSTAL" NUMBER(19,0),
     "PAGADORCIE" NUMBER(19,0),
     "AGRUPAR" NUMBER(1,0),
     "CREATEDBY_CODI" VARCHAR2(64 BYTE),
     "CREATEDDATE" TIMESTAMP (6),
     "LASTMODIFIEDBY_CODI" VARCHAR2(64 BYTE),
     "LASTMODIFIEDDATE" TIMESTAMP (6),
     "RETARD" NUMBER(19,0),
     "DATA_PROGRAMADA" TIMESTAMP (6),
     "CODIASSUMPTE" VARCHAR2(255 BYTE),
     "TIPUSASSUMPTE" VARCHAR2(255 BYTE),
     "ORGAN_GESTOR" VARCHAR2(19 BYTE),
     "ORGAN_GESTOR_NOM" VARCHAR2(64 BYTE),
     "TIPUSASSUMPTE_NOM" VARCHAR2(64 BYTE),
     "CODIASSUMPTE_NOM" VARCHAR2(64 BYTE),
     "CADUCITAT" NUMBER(19,0),
     "COMU" NUMBER(1,0) DEFAULT 0,
     "ULTIMA_ACT" DATE
);

CREATE TABLE "NOTIB"."NOT_PROCEDIMENT_AUDIT"
(	"ID" NUMBER(19,0),
     "TIPUSOPERACIO" VARCHAR2(20 CHAR),
     "JOINPOINT" VARCHAR2(256 CHAR),
     "CREATEDBY_CODI" VARCHAR2(64 CHAR),
     "CREATEDDATE" TIMESTAMP (6),
     "LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR),
     "LASTMODIFIEDDATE" TIMESTAMP (6),
     "PROCEDIMENT_ID" NUMBER(19,0),
     "ENTITAT_ID" NUMBER(19,0),
     "ORGAN" VARCHAR2(64 CHAR),
     "CODI" VARCHAR2(64 CHAR),
     "NOM" VARCHAR2(256 CHAR),
     "RETARD" NUMBER(10,0),
     "CADUCITAT" NUMBER(10,0),
     "AGRUPAR" NUMBER(1,0),
     "COMU" NUMBER(1,0),
     "PAGADORPOSTAL_ID" NUMBER(19,0),
     "PAGADORCIE_ID" NUMBER(19,0)
);

CREATE TABLE "NOTIB"."NOT_PRO_GRUP"
(	"ID" NUMBER(19,0),
     "GRUP" NUMBER(19,0),
     "PROCEDIMENT" NUMBER(19,0),
     "CREATEDBY_CODI" VARCHAR2(64 BYTE),
     "CREATEDDATE" TIMESTAMP (6),
     "LASTMODIFIEDBY_CODI" VARCHAR2(64 BYTE),
     "LASTMODIFIEDDATE" TIMESTAMP (6)
);

CREATE TABLE "NOTIB"."NOT_PRO_GRUP_AUDIT"
(	"ID" NUMBER(19,0),
     "TIPUSOPERACIO" VARCHAR2(20 CHAR),
     "JOINPOINT" VARCHAR2(256 CHAR),
     "CREATEDBY_CODI" VARCHAR2(64 CHAR),
     "CREATEDDATE" TIMESTAMP (6),
     "LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR),
     "LASTMODIFIEDDATE" TIMESTAMP (6),
     "PROGRUP_ID" NUMBER(19,0),
     "PROCEDIMENT" VARCHAR2(64 CHAR),
     "GRUP" VARCHAR2(64 CHAR)
);

CREATE TABLE "NOTIB"."NOT_PRO_ORGAN"
(	"ID" NUMBER(19,0),
     "PROCEDIMENT_ID" NUMBER(19,0),
     "ORGANGESTOR_ID" NUMBER(19,0),
     "CREATEDDATE" TIMESTAMP (6),
     "LASTMODIFIEDDATE" TIMESTAMP (6),
     "CREATEDBY_CODI" VARCHAR2(64 CHAR),
     "LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR)
);

CREATE TABLE "NOTIB"."NOT_USUARI"
(	"CODI" VARCHAR2(64 BYTE),
     "NOM" VARCHAR2(100 BYTE),
     "LLINATGES" VARCHAR2(100 BYTE),
     "NOM_SENCER" VARCHAR2(200 BYTE),
     "EMAIL" VARCHAR2(200 BYTE),
     "VERSION" NUMBER(19,0),
     "REBRE_EMAILS" NUMBER(1,0),
     "IDIOMA" VARCHAR2(2 CHAR),
     "REBRE_EMAILS_CREATS" NUMBER(1,0) DEFAULT 0,
     "ULTIM_ROL" VARCHAR2(40 CHAR),
     "ULTIMA_ENTITAT" NUMBER(19,0)
);

--------------------------------------------------------
--  Indexos
--------------------------------------------------------
CREATE UNIQUE INDEX "NOTIB"."NOT_NOTIFICACIO_PK" ON "NOTIB"."NOT_NOTIFICACIO" ("ID");
CREATE UNIQUE INDEX "NOTIB"."NOT_ENTITAT_AUDIT_PK" ON "NOTIB"."NOT_ENTITAT_AUDIT" ("ID");
CREATE UNIQUE INDEX "NOTIB"."NOT_PRO_ORGAN_PK" ON "NOTIB"."NOT_PRO_ORGAN" ("ID");
CREATE UNIQUE INDEX "NOTIB"."NOT_ENTITAT_PK" ON "NOTIB"."NOT_ENTITAT" ("ID");
CREATE UNIQUE INDEX "NOTIB"."NOT_GRUP_AUDIT_PK" ON "NOTIB"."NOT_GRUP_AUDIT" ("ID");
CREATE UNIQUE INDEX "NOTIB"."NOT_PERSONA_PK" ON "NOTIB"."NOT_PERSONA" ("ID");
CREATE INDEX "NOTIB"."NOT_PAGADOR_POSTAL_FK_I" ON "NOTIB"."NOT_PROCEDIMENT" ("PAGADORPOSTAL");
CREATE UNIQUE INDEX "NOTIB"."NOT_ORGAN_GESTOR_UK" ON "NOTIB"."NOT_ORGAN_GESTOR" ("CODI");
CREATE UNIQUE INDEX "NOTIB"."NOT_ACL_OID_PK" ON "NOTIB"."NOT_ACL_OBJECT_IDENTITY" ("ID");
CREATE UNIQUE INDEX "NOTIB"."NOT_FORMATS_FULLA_PK" ON "NOTIB"."NOT_FORMATS_FULLA" ("ID");
CREATE INDEX "NOTIB"."NOT_NOTENV_TITULAR_ID_INDEX" ON "NOTIB"."NOT_NOTIFICACIO_ENV" ("TITULAR_ID");
CREATE INDEX "NOTIB"."NOT_USUMOD_ENTITAT_FK_I" ON "NOTIB"."NOT_ENTITAT" ("LASTMODIFIEDBY_CODI");
CREATE UNIQUE INDEX "NOTIB"."NOT_PRO_GRUP_AUDIT_PK" ON "NOTIB"."NOT_PRO_GRUP_AUDIT" ("ID");
CREATE INDEX "NOTIB"."NOT_PAGADOR_CIE_FK_I" ON "NOTIB"."NOT_PROCEDIMENT" ("PAGADORCIE");
CREATE INDEX "NOTIB"."NOT_NOTIF_ESTAT_I" ON "NOTIB"."NOT_NOTIFICACIO" ("ESTAT");
CREATE UNIQUE INDEX "NOTIB"."NOT_NOTIFICACIO_AUDIT_PK" ON "NOTIB"."NOT_NOTIFICACIO_AUDIT" ("ID");
CREATE UNIQUE INDEX "NOTIB"."NOT_NOTIFICACIO_ENV_PK" ON "NOTIB"."NOT_NOTIFICACIO_ENV" ("ID");
CREATE UNIQUE INDEX "NOTIB"."NOT_ENTITAT_TIPUS_DOC_PK" ON "NOTIB"."NOT_ENTITAT_TIPUS_DOC" ("ID");
CREATE UNIQUE INDEX "NOTIB"."NOT_ORGAN_GESTOR_PK" ON "NOTIB"."NOT_ORGAN_GESTOR" ("ID");
CREATE INDEX "NOTIB"."NOT_APLICACIO_AUDIT_EK" ON "NOTIB"."NOT_APLICACIO_AUDIT" ("APLICACIO_ID");
CREATE UNIQUE INDEX "NOTIB"."NOT_APLICACIO_AUDIT_PK" ON "NOTIB"."NOT_APLICACIO_AUDIT" ("ID");
CREATE INDEX "NOTIB"."NOT_NOTIFICACIO_NOTDEST_FK_I" ON "NOTIB"."NOT_NOTIFICACIO_ENV" ("NOTIFICACIO_ID");
CREATE INDEX "NOTIB"."NOT_USUMOD_NOTEVENT_FK_I" ON "NOTIB"."NOT_NOTIFICACIO_EVENT" ("LASTMODIFIEDBY_CODI");
CREATE UNIQUE INDEX "NOTIB"."NOT_PAGADOR_POSTAL_PK" ON "NOTIB"."NOT_PAGADOR_POSTAL" ("ID");
CREATE UNIQUE INDEX "NOTIB"."NOT_ACL_IOD_CLASS_IDENTITY_UK" ON "NOTIB"."NOT_ACL_OBJECT_IDENTITY" ("OBJECT_ID_CLASS", "OBJECT_ID_IDENTITY");
CREATE UNIQUE INDEX "NOTIB"."NOT_NOTIFICACIO_TABLE_PK" ON "NOTIB"."NOT_NOTIFICACIO_TABLE" ("ID");
CREATE INDEX "NOTIB"."NOT_ACL_PARENT_OID_FK_I" ON "NOTIB"."NOT_ACL_OBJECT_IDENTITY" ("PARENT_OBJECT");
CREATE INDEX "NOTIB"."NOT_NOTIFICACIO_AUDIT_EK" ON "NOTIB"."NOT_NOTIFICACIO_AUDIT" ("NOTIFICACIO_ID");
CREATE INDEX "NOTIB"."NOT_NOTIF_PROORGAN_FK_I" ON "NOTIB"."NOT_NOTIFICACIO" ("PROCEDIMENT_ORGAN_ID");
CREATE INDEX "NOTIB"."NOT_NOTIF_ORGAN_FK_I" ON "NOTIB"."NOT_NOTIFICACIO" ("ORGAN_GESTOR");
CREATE UNIQUE INDEX "NOTIB"."NOT_DOCUMENT_PK" ON "NOTIB"."NOT_DOCUMENT" ("ID");
CREATE INDEX "NOTIB"."NOT_NOTIF_PROCEDIMENT_FK_I" ON "NOTIB"."NOT_NOTIFICACIO" ("PROCEDIMENT_ID");
CREATE INDEX "NOTIB"."NOT_PROCEDIMENT_EK" ON "NOTIB"."NOT_PRO_ORGAN" ("PROCEDIMENT_ID");
CREATE UNIQUE INDEX "NOTIB"."NOT_PAGADOR_CIE_PK" ON "NOTIB"."NOT_PAGADOR_CIE" ("ID");
CREATE UNIQUE INDEX "NOTIB"."NOT_PROCEDIMENT_AUDIT_PK" ON "NOTIB"."NOT_PROCEDIMENT_AUDIT" ("ID");
CREATE UNIQUE INDEX "NOTIB"."NOT_GRUP_PK" ON "NOTIB"."NOT_GRUP" ("ID");
CREATE INDEX "NOTIB"."NOT_USUCRE_NOTIFICACIO_FK_I" ON "NOTIB"."NOT_NOTIFICACIO" ("CREATEDBY_CODI");
CREATE INDEX "NOTIB"."NOT_ORGAN_ENTITAT_FK_I" ON "NOTIB"."NOT_ORGAN_GESTOR" ("ENTITAT");
CREATE INDEX "NOTIB"."NOT_USUMOD_NOTIFICACIO_FK_I" ON "NOTIB"."NOT_NOTIFICACIO" ("LASTMODIFIEDBY_CODI");
CREATE UNIQUE INDEX "NOTIB"."NOT_APLICACIO_PK" ON "NOTIB"."NOT_APLICACIO" ("ID");
CREATE INDEX "NOTIB"."NOT_USUCRE_NOTEVENT_FK_I" ON "NOTIB"."NOT_NOTIFICACIO_EVENT" ("CREATEDBY_CODI");
CREATE UNIQUE INDEX "NOTIB"."NOT_ACL_CLASS_CLASS_UK" ON "NOTIB"."NOT_ACL_CLASS" ("CLASS");
CREATE INDEX "NOTIB"."NOT_ENTITAT_FK_I" ON "NOTIB"."NOT_PROCEDIMENT" ("ENTITAT");
CREATE INDEX "NOTIB"."NOT_ACL_SID_ENTRY_FK_I" ON "NOTIB"."NOT_ACL_ENTRY" ("SID");
CREATE INDEX "NOTIB"."NOT_NOTIFICACIO_NOTEVENT_FK_I" ON "NOTIB"."NOT_NOTIFICACIO_EVENT" ("NOTIFICACIO_ID");
CREATE INDEX "NOTIB"."NOT_NOTEVE_NOTERR_NOTDEST_FK_I" ON "NOTIB"."NOT_NOTIFICACIO_ENV" ("NOTIFICA_ERROR_EVENT_ID");
CREATE INDEX "NOTIB"."NOT_USUCRE_NOTDEST_FK_I" ON "NOTIB"."NOT_NOTIFICACIO_ENV" ("CREATEDBY_CODI");
CREATE INDEX "NOTIB"."NOT_PERSONA_NOTENV_ID_INDEX" ON "NOTIB"."NOT_PERSONA" ("NOTIFICACIO_ENV_ID");
CREATE INDEX "NOTIB"."NOT_ENTITAT_NOTIFICACIO_FK_I" ON "NOTIB"."NOT_NOTIFICACIO" ("ENTITAT_ID");
CREATE INDEX "NOTIB"."NOT_USUCRE_ENTITAT_FK_I" ON "NOTIB"."NOT_ENTITAT" ("CREATEDBY_CODI");
CREATE UNIQUE INDEX "NOTIB"."NOT_ACL_ENTRY_IDENT_ORDER_UK" ON "NOTIB"."NOT_ACL_ENTRY" ("ACL_OBJECT_IDENTITY", "ACE_ORDER");
CREATE UNIQUE INDEX "NOTIB"."NOT_ENTITAT_CODI_UK" ON "NOTIB"."NOT_ENTITAT" ("CODI");
CREATE UNIQUE INDEX "NOTIB"."NOT_FORMATS_SOBRE_PK" ON "NOTIB"."NOT_FORMATS_SOBRE" ("ID");
CREATE UNIQUE INDEX "NOTIB"."NOT_NOTIFICACIO_EVENT_PK" ON "NOTIB"."NOT_NOTIFICACIO_EVENT" ("ID");
CREATE INDEX "NOTIB"."NOT_USUMOD_NOTDEST_FK_I" ON "NOTIB"."NOT_NOTIFICACIO_ENV" ("LASTMODIFIEDBY_CODI");
CREATE INDEX "NOTIB"."NOT_ACL_OID_ENTRY_FK_I" ON "NOTIB"."NOT_ACL_ENTRY" ("ACL_OBJECT_IDENTITY");
CREATE INDEX "NOTIB"."NOT_PRO_GRUP_AUDIT_EK" ON "NOTIB"."NOT_PRO_GRUP_AUDIT" ("PROGRUP_ID");
CREATE UNIQUE INDEX "NOTIB"."NOT_ACL_SID_PK" ON "NOTIB"."NOT_ACL_SID" ("ID");
CREATE INDEX "NOTIB"."NOT_NOTIFICACIO_ENV_AUDIT_EK" ON "NOTIB"."NOT_NOTIFICACIO_ENV_AUDIT" ("ENVIAMENT_ID");
CREATE UNIQUE INDEX "NOTIB"."NOT_USUARI_PK" ON "NOTIB"."NOT_USUARI" ("CODI");
CREATE INDEX "NOTIB"."NOT_ENTITAT_TIPUS_DOC_FK_I" ON "NOTIB"."NOT_ENTITAT_TIPUS_DOC" ("ENTITAT_ID");
CREATE INDEX "NOTIB"."NOT_PRO_ORGAN_FK_I" ON "NOTIB"."NOT_PROCEDIMENT" ("ORGAN_GESTOR");
CREATE UNIQUE INDEX "NOTIB"."NOT_ACL_ENTRY_PK" ON "NOTIB"."NOT_ACL_ENTRY" ("ID");
CREATE UNIQUE INDEX "NOTIB"."NOT_NOTIFICACIO_ENV_AUDIT_PK" ON "NOTIB"."NOT_NOTIFICACIO_ENV_AUDIT" ("ID");
CREATE INDEX "NOTIB"."NOT_ACL_SID_OID_FK_I" ON "NOTIB"."NOT_ACL_OBJECT_IDENTITY" ("OWNER_SID");
CREATE INDEX "NOTIB"."NOT_NOTIF_DOCUMENT_ID_INDEX" ON "NOTIB"."NOT_NOTIFICACIO" ("DOCUMENT_ID");
CREATE UNIQUE INDEX "NOTIB"."NOT_ACL_CLASS_PK" ON "NOTIB"."NOT_ACL_CLASS" ("ID");
CREATE INDEX "NOTIB"."NOT_NOTDEST_NOTEVENT_FK_I" ON "NOTIB"."NOT_NOTIFICACIO_EVENT" ("NOTIFICACIO_ENV_ID");
CREATE UNIQUE INDEX "NOTIB"."NOT_ACL_SID_PRINCIPAL_SID_UK" ON "NOTIB"."NOT_ACL_SID" ("SID", "PRINCIPAL");
CREATE INDEX "NOTIB"."NOT_PROCEDIMENT_AUDIT_EK" ON "NOTIB"."NOT_PROCEDIMENT_AUDIT" ("PROCEDIMENT_ID");
CREATE INDEX "NOTIB"."NOT_NOTIF_PROCOD_I" ON "NOTIB"."NOT_NOTIFICACIO" ("PROC_CODI_NOTIB");
CREATE INDEX "NOTIB"."NOT_GRUP_AUDIT_EK" ON "NOTIB"."NOT_GRUP_AUDIT" ("GRUP_ID");
CREATE UNIQUE INDEX "NOTIB"."NOT_PROCEDIMENT_PK" ON "NOTIB"."NOT_PROCEDIMENT" ("ID");
CREATE INDEX "NOTIB"."NOT_ORGAN_EK" ON "NOTIB"."NOT_PRO_ORGAN" ("ORGANGESTOR_ID");
CREATE INDEX "NOTIB"."NOT_ENTITAT_AUDIT_EK" ON "NOTIB"."NOT_ENTITAT_AUDIT" ("ENTITAT_ID");
CREATE INDEX "NOTIB"."NOT_NOTIF_USUARI_I" ON "NOTIB"."NOT_NOTIFICACIO" ("USUARI_CODI");
CREATE INDEX "NOTIB"."NOT_ACL_CLASS_OID_FK_I" ON "NOTIB"."NOT_ACL_OBJECT_IDENTITY" ("OBJECT_ID_CLASS");

--------------------------------------------------------
--  Triggers
--------------------------------------------------------

CREATE OR REPLACE TRIGGER "NOTIB"."NOT_ACLCLA_IDGEN_TRG"
    BEFORE INSERT ON NOT_ACL_CLASS
    FOR EACH ROW
BEGIN
    SELECT NOT_ACL_CLASS_SEQ.NEXTVAL INTO :new.id FROM dual;
END;

ALTER TRIGGER "NOTIB"."NOT_ACLCLA_IDGEN_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "NOTIB"."NOT_ACLENT_IDGEN_TRG"
    BEFORE INSERT ON NOT_ACL_ENTRY
    FOR EACH ROW
BEGIN
    SELECT NOT_ACL_ENTRY_SEQ.NEXTVAL INTO :new.id FROM dual;
END;

ALTER TRIGGER "NOTIB"."NOT_ACLENT_IDGEN_TRG" ENABLE;
CREATE OR REPLACE TRIGGER "NOTIB"."NOT_ACLOID_IDGEN_TRG"
    BEFORE INSERT ON NOT_ACL_OBJECT_IDENTITY
    FOR EACH ROW
BEGIN
    SELECT NOT_ACL_OBJECT_IDENTITY_SEQ.NEXTVAL INTO :new.id FROM dual;
END;

ALTER TRIGGER "NOTIB"."NOT_ACLOID_IDGEN_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "NOTIB"."NOT_ACLSID_IDGEN_TRG"
    BEFORE INSERT ON NOT_ACL_SID
    FOR EACH ROW
BEGIN
    SELECT NOT_ACL_SID_SEQ.NEXTVAL INTO :new.id FROM dual;
END;

ALTER TRIGGER "NOTIB"."NOT_ACLSID_IDGEN_TRG" ENABLE;

--------------------------------------------------------
--  Constraints
--------------------------------------------------------

ALTER TABLE "NOTIB"."NOT_PAGADOR_CIE" MODIFY ("DIR3_CODI" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PAGADOR_CIE" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PAGADOR_CIE" ADD CONSTRAINT "NOT_PAGADOR_CIE_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_PROCEDIMENT_AUDIT" ADD CONSTRAINT "NOT_PROCEDIMENT_AUDIT_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_PROCEDIMENT_AUDIT" MODIFY ("CODI" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PROCEDIMENT_AUDIT" MODIFY ("PROCEDIMENT_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PROCEDIMENT_AUDIT" MODIFY ("TIPUSOPERACIO" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PROCEDIMENT_AUDIT" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_GRUP" MODIFY ("CODI" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_GRUP" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_GRUP" ADD CONSTRAINT "NOT_GRUP_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_APLICACIO" MODIFY ("ACTIVA" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_APLICACIO" MODIFY ("ENTITAT_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_APLICACIO" MODIFY ("USUARI_CODI" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_APLICACIO" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_APLICACIO" ADD CONSTRAINT "NOT_APLICACIO_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_PROCEDIMENT" MODIFY ("COMU" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PROCEDIMENT" MODIFY ("AGRUPAR" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PROCEDIMENT" MODIFY ("CODI" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PROCEDIMENT" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PROCEDIMENT" ADD CONSTRAINT "NOT_PROCEDIMENT_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_PRO_GRUP" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_APLICACIO_AUDIT" ADD CONSTRAINT "NOT_APLICACIO_AUDIT_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_APLICACIO_AUDIT" MODIFY ("ENTITAT_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_APLICACIO_AUDIT" MODIFY ("APLICACIO_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_APLICACIO_AUDIT" MODIFY ("TIPUSOPERACIO" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_APLICACIO_AUDIT" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_CLASS" MODIFY ("CLASS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_CLASS" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_CLASS" ADD CONSTRAINT "NOT_ACL_CLASS_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_ACL_CLASS" ADD CONSTRAINT "NOT_ACL_CLASS_CLASS_UK" UNIQUE ("CLASS");
ALTER TABLE "NOTIB"."NOT_PRO_ORGAN" ADD CONSTRAINT "NOT_PRO_ORGAN_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_USUARI" MODIFY ("VERSION" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_USUARI" MODIFY ("CODI" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_USUARI" ADD CONSTRAINT "NOT_USUARI_PK" PRIMARY KEY ("CODI");
ALTER TABLE "NOTIB"."NOT_USUARI" MODIFY ("REBRE_EMAILS_CREATS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_AUDIT" ADD CONSTRAINT "NOT_NOTIFICACIO_AUDIT_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_AUDIT" MODIFY ("ESTAT" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_AUDIT" MODIFY ("DOCUMENT_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_AUDIT" MODIFY ("TIPUS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_AUDIT" MODIFY ("EMISOR" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_AUDIT" MODIFY ("NOTIFICACIO_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_AUDIT" MODIFY ("TIPUSOPERACIO" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_AUDIT" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_DOCUMENT" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_DOCUMENT" ADD CONSTRAINT "NOT_DOCUMENT_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_PERSONA" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PERSONA" ADD CONSTRAINT "NOT_PERSONA_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_ENTITAT" MODIFY ("VERSION" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ENTITAT" MODIFY ("ACTIVA" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ENTITAT" MODIFY ("DIR3_CODI" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ENTITAT" MODIFY ("TIPUS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ENTITAT" MODIFY ("NOM" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ENTITAT" MODIFY ("CODI" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ENTITAT" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ENTITAT" ADD CONSTRAINT "NOT_ENTITAT_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_ENTITAT" ADD CONSTRAINT "NOT_ENTITAT_CODI_UK" UNIQUE ("CODI");
ALTER TABLE "NOTIB"."NOT_ACL_OBJECT_IDENTITY" MODIFY ("ENTRIES_INHERITING" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_OBJECT_IDENTITY" MODIFY ("OWNER_SID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_OBJECT_IDENTITY" MODIFY ("OBJECT_ID_IDENTITY" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_OBJECT_IDENTITY" MODIFY ("OBJECT_ID_CLASS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_OBJECT_IDENTITY" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_OBJECT_IDENTITY" ADD CONSTRAINT "NOT_ACL_OID_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_ACL_OBJECT_IDENTITY" ADD CONSTRAINT "NOT_ACL_OID_ENTRIES_CK" CHECK (ENTRIES_INHERITING IN (1,0)) ENABLE;
ALTER TABLE "NOTIB"."NOT_ACL_OBJECT_IDENTITY" ADD CONSTRAINT "NOT_ACL_IOD_CLASS_IDENTITY_UK" UNIQUE ("OBJECT_ID_CLASS", "OBJECT_ID_IDENTITY");
ALTER TABLE "NOTIB"."NOT_ENTITAT_AUDIT" ADD CONSTRAINT "NOT_ENTITAT_AUDIT_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_ENTITAT_AUDIT" MODIFY ("DIR3_CODI" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ENTITAT_AUDIT" MODIFY ("NOM" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ENTITAT_AUDIT" MODIFY ("CODI" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ENTITAT_AUDIT" MODIFY ("ENTITAT_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ENTITAT_AUDIT" MODIFY ("TIPUSOPERACIO" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ENTITAT_AUDIT" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_TABLE" ADD CONSTRAINT "NOT_NOTIFICACIO_TABLE_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_TABLE" MODIFY ("PROCEDIMENT_IS_COMU" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_TABLE" MODIFY ("ESTAT" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_TABLE" MODIFY ("CONCEPTE" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_TABLE" MODIFY ("ENV_TIPUS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_TABLE" MODIFY ("ERROR_LAST_EVENT" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_TABLE" MODIFY ("ERROR_LAST_CALLBACK" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_TABLE" MODIFY ("ENTITAT_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_TABLE" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PAGADOR_POSTAL" MODIFY ("DIR3_CODI" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PAGADOR_POSTAL" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PAGADOR_POSTAL" ADD CONSTRAINT "NOT_PAGADOR_POSTAL_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV_AUDIT" ADD CONSTRAINT "NOT_NOTIFICACIO_ENV_AUDIT_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV_AUDIT" MODIFY ("NOTIFICACIO_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV_AUDIT" MODIFY ("ENVIAMENT_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV_AUDIT" MODIFY ("TIPUSOPERACIO" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV_AUDIT" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV_TABLE" MODIFY ("NOTIFICA_ESTAT" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV_TABLE" MODIFY ("HAS_ERRORS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV_TABLE" MODIFY ("NOT_ESTAT" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV_TABLE" MODIFY ("TIPUS_ENVIAMENT" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV_TABLE" MODIFY ("ENTITAT_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV_TABLE" MODIFY ("NOTIFICACIO_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV_TABLE" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."HT_NOT_NOTIFICACIO_ENV" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ENTITAT_TIPUS_DOC" ADD CONSTRAINT "NOT_ENTITAT_TIPUS_DOC_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_PRO_GRUP_AUDIT" ADD CONSTRAINT "NOT_PRO_GRUP_AUDIT_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_PRO_GRUP_AUDIT" MODIFY ("GRUP" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PRO_GRUP_AUDIT" MODIFY ("PROCEDIMENT" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PRO_GRUP_AUDIT" MODIFY ("PROGRUP_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PRO_GRUP_AUDIT" MODIFY ("TIPUSOPERACIO" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_PRO_GRUP_AUDIT" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_SID" MODIFY ("SID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_SID" MODIFY ("PRINCIPAL" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_SID" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_SID" ADD CONSTRAINT "NOT_ACL_SID_PRINCIPAL_SID_UK" UNIQUE ("SID", "PRINCIPAL");
ALTER TABLE "NOTIB"."NOT_ACL_SID" ADD CONSTRAINT "NOT_ACL_SID_PRINCIPAL_CK" CHECK (PRINCIPAL IN (1,0)) ENABLE;
ALTER TABLE "NOTIB"."NOT_ACL_SID" ADD CONSTRAINT "NOT_ACL_SID_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_ACL_ENTRY" MODIFY ("AUDIT_FAILURE" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_ENTRY" MODIFY ("AUDIT_SUCCESS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_ENTRY" MODIFY ("GRANTING" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_ENTRY" MODIFY ("MASK" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_ENTRY" MODIFY ("SID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_ENTRY" MODIFY ("ACE_ORDER" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_ENTRY" MODIFY ("ACL_OBJECT_IDENTITY" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_ENTRY" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ACL_ENTRY" ADD CONSTRAINT "NOT_ACL_ENTRY_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_ACL_ENTRY" ADD CONSTRAINT "NOT_ACL_ENTRY_IDENT_ORDER_UK" UNIQUE ("ACL_OBJECT_IDENTITY", "ACE_ORDER");
ALTER TABLE "NOTIB"."NOT_ACL_ENTRY" ADD CONSTRAINT "NOT_ACL_ENTRY_GRANTING_CK" CHECK (GRANTING IN (1,0)) ENABLE;
ALTER TABLE "NOTIB"."NOT_ACL_ENTRY" ADD CONSTRAINT "NOT_ACL_ENTRY_AUDIT_SUCCESS_CK" CHECK (AUDIT_SUCCESS IN (1,0)) ENABLE;
ALTER TABLE "NOTIB"."NOT_ACL_ENTRY" ADD CONSTRAINT "NOT_ACL_ENTRY_AUDIT_FAILURE_CK" CHECK (AUDIT_FAILURE IN (1,0)) ENABLE;
ALTER TABLE "NOTIB"."NOT_ORGAN_GESTOR" ADD CONSTRAINT "NOT_ORGAN_GESTOR_UK" UNIQUE ("CODI");
ALTER TABLE "NOTIB"."NOT_ORGAN_GESTOR" ADD CONSTRAINT "NOT_ORGAN_GESTOR_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_ORGAN_GESTOR" MODIFY ("CODI" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_ORGAN_GESTOR" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_EVENT" MODIFY ("NOTIFICACIO_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_EVENT" MODIFY ("ERROR" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_EVENT" MODIFY ("DATA" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_EVENT" MODIFY ("TIPUS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_EVENT" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_EVENT" ADD CONSTRAINT "NOT_NOTIFICACIO_EVENT_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_FORMATS_FULLA" ADD CONSTRAINT "NOT_FORMATS_FULLA_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_FORMATS_SOBRE" ADD CONSTRAINT "NOT_FORMATS_SOBRE_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_GRUP_AUDIT" ADD CONSTRAINT "NOT_GRUP_AUDIT_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_GRUP_AUDIT" MODIFY ("CODI" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_GRUP_AUDIT" MODIFY ("GRUP_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_GRUP_AUDIT" MODIFY ("TIPUSOPERACIO" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_GRUP_AUDIT" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV" MODIFY ("SIR_CON_INTENT" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV" MODIFY ("NOTIFICACIO_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV" MODIFY ("NOTIFICA_ERROR" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV" ADD CONSTRAINT "NOT_NOTIFICACIO_ENV_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" MODIFY ("CALLBACK_ERROR" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" MODIFY ("COM_TIPUS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" MODIFY ("ENTITAT_ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" MODIFY ("NOT_ENV_INTENT" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" MODIFY ("ESTAT" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" MODIFY ("CONCEPTE" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" MODIFY ("ENV_TIPUS" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" MODIFY ("EMISOR_DIR3CODI" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" ADD CONSTRAINT "NOT_NOTIFICACIO_PK" PRIMARY KEY ("ID");
ALTER TABLE "NOTIB"."NOT_ACL_ENTRY" ADD CONSTRAINT "NOT_ACL_OID_ENTRY_FK" FOREIGN KEY ("ACL_OBJECT_IDENTITY")
    REFERENCES "NOTIB"."NOT_ACL_OBJECT_IDENTITY" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_ACL_ENTRY" ADD CONSTRAINT "NOT_ACL_SID_ENTRY_FK" FOREIGN KEY ("SID")
    REFERENCES "NOTIB"."NOT_ACL_SID" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_ACL_OBJECT_IDENTITY" ADD CONSTRAINT "NOT_ACL_CLASS_OID_FK" FOREIGN KEY ("OBJECT_ID_CLASS")
    REFERENCES "NOTIB"."NOT_ACL_CLASS" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_ACL_OBJECT_IDENTITY" ADD CONSTRAINT "NOT_ACL_PARENT_OID_FK" FOREIGN KEY ("PARENT_OBJECT")
    REFERENCES "NOTIB"."NOT_ACL_OBJECT_IDENTITY" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_ACL_OBJECT_IDENTITY" ADD CONSTRAINT "NOT_ACL_SID_OID_FK" FOREIGN KEY ("OWNER_SID")
    REFERENCES "NOTIB"."NOT_ACL_SID" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_APLICACIO" ADD CONSTRAINT "NOT_APLICACIO_ENTITAT_FK" FOREIGN KEY ("ENTITAT_ID")
    REFERENCES "NOTIB"."NOT_ENTITAT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_APLICACIO" ADD CONSTRAINT "NOT_USUCRE_APLICACIO_FK" FOREIGN KEY ("CREATEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_APLICACIO" ADD CONSTRAINT "NOT_USUMOD_APLICACIO_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_COLUMNES" ADD CONSTRAINT "NOT_COLUMNES_ENTITAT_FK" FOREIGN KEY ("ENTITAT_ID")
    REFERENCES "NOTIB"."NOT_ENTITAT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_COLUMNES" ADD CONSTRAINT "NOT_COLUMNES_USUARI_FK" FOREIGN KEY ("USUARI_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_ENTITAT" ADD CONSTRAINT "NOT_USUCRE_ENTITAT_FK" FOREIGN KEY ("CREATEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_ENTITAT" ADD CONSTRAINT "NOT_USUMOD_ENTITAT_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_ENTITAT_TIPUS_DOC" ADD CONSTRAINT "NOT_ENTITAT_TIPUS_DOC_FK" FOREIGN KEY ("ENTITAT_ID")
    REFERENCES "NOTIB"."NOT_ENTITAT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_FORMATS_FULLA" ADD CONSTRAINT "NOT_FORMATS_FULLA_FK" FOREIGN KEY ("PAGADOR_CIE_ID")
    REFERENCES "NOTIB"."NOT_PAGADOR_CIE" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_FORMATS_SOBRE" ADD CONSTRAINT "NOT_FORMATS_SOBRE_FK" FOREIGN KEY ("PAGADOR_CIE_ID")
    REFERENCES "NOTIB"."NOT_PAGADOR_CIE" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_GRUP" ADD CONSTRAINT "NOT_ENTITAT_GRUP_FK" FOREIGN KEY ("ENTITAT")
    REFERENCES "NOTIB"."NOT_ENTITAT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_GRUP" ADD CONSTRAINT "NOT_GRUP_ORGAN_FK" FOREIGN KEY ("ORGAN_GESTOR")
    REFERENCES "NOTIB"."NOT_ORGAN_GESTOR" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" ADD CONSTRAINT "NOT_DOCUMENT_NOTIFICACIO_FK" FOREIGN KEY ("DOCUMENT_ID")
    REFERENCES "NOTIB"."NOT_DOCUMENT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" ADD CONSTRAINT "NOT_ENTITAT_NOTIFICACIO_FK" FOREIGN KEY ("ENTITAT_ID")
    REFERENCES "NOTIB"."NOT_ENTITAT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" ADD CONSTRAINT "NOT_NOTERREVENT_NOTIFICACIO_FK" FOREIGN KEY ("NOT_ERROR_EVENT_ID")
    REFERENCES "NOTIB"."NOT_NOTIFICACIO_EVENT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" ADD CONSTRAINT "NOT_PAGADOR_CIE_NOTIFICACIO_FK" FOREIGN KEY ("PAGADOR_CIE_ID")
    REFERENCES "NOTIB"."NOT_PAGADOR_CIE" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" ADD CONSTRAINT "NOT_PROCEDIMENT_NOT_FK" FOREIGN KEY ("PROCEDIMENT_ID")
    REFERENCES "NOTIB"."NOT_PROCEDIMENT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" ADD CONSTRAINT "NOT_PROCORGAN_NOT_FK" FOREIGN KEY ("PROCEDIMENT_ORGAN_ID")
    REFERENCES "NOTIB"."NOT_PRO_ORGAN" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" ADD CONSTRAINT "NOT_USUCRE_NOTIFICACIO_FK" FOREIGN KEY ("CREATEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO" ADD CONSTRAINT "NOT_USUMOD_NOTIFICACIO_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV" ADD CONSTRAINT "NOT_NOTEVE_NOTERR_NOTENV_FK" FOREIGN KEY ("NOTIFICA_ERROR_EVENT_ID")
    REFERENCES "NOTIB"."NOT_NOTIFICACIO_EVENT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV" ADD CONSTRAINT "NOT_NOTIFICACIO_NOTENV_FK" FOREIGN KEY ("NOTIFICACIO_ID")
    REFERENCES "NOTIB"."NOT_NOTIFICACIO" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV" ADD CONSTRAINT "NOT_PERSONA_NOTIFICACIO_ENV_FK" FOREIGN KEY ("TITULAR_ID")
    REFERENCES "NOTIB"."NOT_PERSONA" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV" ADD CONSTRAINT "NOT_USUCRE_NOTENV_FK" FOREIGN KEY ("CREATEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_ENV" ADD CONSTRAINT "NOT_USUMOD_NOTENV_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_EVENT" ADD CONSTRAINT "NOT_NOTENV_NOTEVENT_FK" FOREIGN KEY ("NOTIFICACIO_ENV_ID")
    REFERENCES "NOTIB"."NOT_NOTIFICACIO_ENV" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_EVENT" ADD CONSTRAINT "NOT_NOTIFICACIO_NOTEVENT_FK" FOREIGN KEY ("NOTIFICACIO_ID")
    REFERENCES "NOTIB"."NOT_NOTIFICACIO" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_EVENT" ADD CONSTRAINT "NOT_USUCRE_NOTEVENT_FK" FOREIGN KEY ("CREATEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_NOTIFICACIO_EVENT" ADD CONSTRAINT "NOT_USUMOD_NOTEVENT_FK" FOREIGN KEY ("LASTMODIFIEDBY_CODI")
    REFERENCES "NOTIB"."NOT_USUARI" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_ORGAN_GESTOR" ADD CONSTRAINT "NOT_ORGAN_ENTITAT_FK" FOREIGN KEY ("ENTITAT")
    REFERENCES "NOTIB"."NOT_ENTITAT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_PAGADOR_CIE" ADD CONSTRAINT "NOT_PAGADOR_CIE_ENTITAT_FK" FOREIGN KEY ("ENTITAT")
    REFERENCES "NOTIB"."NOT_ENTITAT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_PAGADOR_CIE" ADD CONSTRAINT "NOT_PAGCIE_ORGAN_FK" FOREIGN KEY ("ORGAN_GESTOR")
    REFERENCES "NOTIB"."NOT_ORGAN_GESTOR" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_PAGADOR_POSTAL" ADD CONSTRAINT "NOT_PAGADOR_POSTAL_ENTITAT_FK" FOREIGN KEY ("ENTITAT")
    REFERENCES "NOTIB"."NOT_ENTITAT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_PAGADOR_POSTAL" ADD CONSTRAINT "NOT_PAGPOSTAL_ORGAN_FK" FOREIGN KEY ("ORGAN_GESTOR")
    REFERENCES "NOTIB"."NOT_ORGAN_GESTOR" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_PERSONA" ADD CONSTRAINT "NOT_PERSONA_NOT_FK" FOREIGN KEY ("NOTIFICACIO_ENV_ID")
    REFERENCES "NOTIB"."NOT_NOTIFICACIO_ENV" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_PROCEDIMENT" ADD CONSTRAINT "NOT_ENTITAT_FK" FOREIGN KEY ("ENTITAT")
    REFERENCES "NOTIB"."NOT_ENTITAT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_PROCEDIMENT" ADD CONSTRAINT "NOT_PAGADOR_CIE_FK" FOREIGN KEY ("PAGADORCIE")
    REFERENCES "NOTIB"."NOT_PAGADOR_CIE" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_PROCEDIMENT" ADD CONSTRAINT "NOT_PAGADOR_POSTAL_FK" FOREIGN KEY ("PAGADORPOSTAL")
    REFERENCES "NOTIB"."NOT_PAGADOR_POSTAL" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_PROCEDIMENT" ADD CONSTRAINT "NOT_PROC_ORGAN_FK" FOREIGN KEY ("ORGAN_GESTOR")
    REFERENCES "NOTIB"."NOT_ORGAN_GESTOR" ("CODI") ENABLE;
ALTER TABLE "NOTIB"."NOT_PRO_GRUP" ADD CONSTRAINT "NOT_GRUP_PRO_FK" FOREIGN KEY ("GRUP")
    REFERENCES "NOTIB"."NOT_GRUP" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_PRO_GRUP" ADD CONSTRAINT "NOT_PRO_GRUP_FK" FOREIGN KEY ("PROCEDIMENT")
    REFERENCES "NOTIB"."NOT_PROCEDIMENT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_PRO_ORGAN" ADD CONSTRAINT "NOT_ORGAN_PRO_FK" FOREIGN KEY ("PROCEDIMENT_ID")
    REFERENCES "NOTIB"."NOT_PROCEDIMENT" ("ID") ENABLE;
ALTER TABLE "NOTIB"."NOT_PRO_ORGAN" ADD CONSTRAINT "NOT_PRO_ORGAN_FK" FOREIGN KEY ("ORGANGESTOR_ID")
    REFERENCES "NOTIB"."NOT_ORGAN_GESTOR" ("ID") ENABLE;
