import { Grid, Icon, IconButton, Tooltip } from '@mui/material';
import {
    GridGroupingColDefOverride,
    GridSlots,
    GridTreeDataGroupingCell,
    isAutogeneratedRow,
} from '@mui/x-data-grid-pro';
import React from 'react';
import { useTranslation } from 'react-i18next';
import {
    FormField,
    FormFieldProps,
    GridPage,
    MuiDataGrid,
    MuiDataGridColDef,
    useBaseAppContext,
    useCloseDialogButtons,
    useFormContext,
    useMuiContentDialog,
} from 'reactlib';
import { Cancel, CheckCircle, RemoveCircle } from '@mui/icons-material';
import DataGridNoRowsOverlay from '../../../lib/components/mui/datagrid/DataGridNoRowsOverlay';
type OnRowExpansionChangeFunction = (id: string | number, expanded: boolean) => void;
interface DefaultRowExpansionState {
    [id: string | number]: boolean;
}

enum ParamTipus {
    NUMERIC = 'NUMERIC',
    TEXT = 'TEXT',
    BOOLEAN = 'BOOLEAN',
    PASSWORD = 'PASSWORD',
    CRON = 'CRON',
    SELECT = 'SELECT',
}

const getFormFieldPropsForTipus = (tipus?: ParamTipus): FormFieldProps => {
    if (!tipus) {
        return { name: 'valor' };
    }

    switch (tipus) {
        case ParamTipus.NUMERIC:
            return { type: 'number', name: 'valor' };

        case ParamTipus.BOOLEAN:
            return { name: 'valorBoolean' };

        case ParamTipus.PASSWORD:
            return { name: 'valor', overrideTextFieldProps: { type: 'password' } };

        case ParamTipus.TEXT:
        case ParamTipus.CRON:
        case ParamTipus.SELECT:
            return { name: 'valor' };

        default:
            console.warn('ParamTipus no mapeado:', tipus);
            return { name: 'valor' };
    }
};

const ExpandCollapseButtons: React.FC<{
    onExpandAll: () => void;
    onCollapseAll: () => void;
}> = ({ onExpandAll, onCollapseAll }) => (
    <>
        <IconButton onClick={onExpandAll}>
            <Icon>unfold_more</Icon>
        </IconButton>
        <IconButton onClick={onCollapseAll}>
            <Icon>unfold_less</Icon>
        </IconButton>
    </>
);

const PropietatsConfigurablesForm: React.FC = () => {
    const { data } = useFormContext();

    return (
        <Grid container spacing={2}>
            <Grid size={4}>
                <FormField name="codi" readOnly disabled />
            </Grid>
            <Grid size={8}>
                <FormField name="nom" />
            </Grid>
            <Grid size={12}>
                <FormField name="descripcio" />
            </Grid>
            <Grid size={4}>
                <FormField name="tipus" readOnly disabled />
            </Grid>
            <Grid size={8}>
                <FormField {...getFormFieldPropsForTipus(data?.tipus)} />
            </Grid>
        </Grid>
    );
};

const PropietatsConfigurablesValue = ({ tipus, valor }: { tipus: ParamTipus; valor: any }) => {
    const { t } = useTranslation();
    if (valor === null || valor === undefined) {
        return (
            <Tooltip title={t('page.parametres.detail.valuesTootip.null')}>
                <RemoveCircle color="disabled" />
            </Tooltip>
        );
    }

    if (tipus === ParamTipus.BOOLEAN) {
        if (valor === true) {
            return (
                <Tooltip title={t('page.parametres.detail.valuesTootip.true')}>
                    <CheckCircle color="success" />
                </Tooltip>
            );
        } else {
            return (
                <Tooltip title={t('page.parametres.detail.valuesTootip.false')}>
                    <Cancel color="error" />
                </Tooltip>
            );
        }
    }

    return valor;
};

const PropietatsConfigurablesDetall: React.FC<any> = props => {
    const { data } = props;
    // const { t } = useTranslation();
    // const elementsDetail = [
    //     { label: t('page.parametres.detail.grup'), value: data?.grup },
    //     { label: t('page.parametres.detail.subGrup'), value: data?.subGrup },
    //     { label: t('page.parametres.detail.tipus'), value: data?.tipus },
    //     { label: t('page.parametres.detail.codi'), value: data?.codi },
    //     { label: t('page.parametres.detail.nom'), value: data?.nom },
    //     { label: t('page.parametres.detail.descripcio'), value: data?.descripcio },
    //     {
    //         label: t('page.parametres.detail.valor'),
    //         contentValue: (
    //             <PropietatsConfigurablesValue
    //                 tipus={data?.tipus}
    //                 valor={data?.valorBoolean ?? data?.valor}
    //             />
    //         ),
    //     },
    // ];
    // return <ContentDetail title={''} elements={elementsDetail} />;
    return <p>Hola-- {data?.codi}</p>;
};

const PropietatsConfigurables: React.FC<any> = () => {
    const { t } = useTranslation();
    const { t: tLib } = useBaseAppContext();
    const [expand, setExpand] = React.useState<boolean>(true);
    const closeDialogButton = useCloseDialogButtons();
    const [detailDialogShow, detailDialogComponent] = useMuiContentDialog(closeDialogButton);
    const [expansionState, setExpansionState] = React.useState<DefaultRowExpansionState>({});
    const onRowExpansionChange: OnRowExpansionChangeFunction = (id, expanded) => {
        if (id === '__reset__') {
            setExpansionState({});
            return;
        }
        setExpansionState(prev => ({
            ...prev,
            [id]: expanded,
        }));
    };

    const showDetail = (_id: any, row: any) => {
        detailDialogShow(
            t('page.parametres.detail.title'),
            <PropietatsConfigurablesDetall data={row} />,
            closeDialogButton,
            { maxWidth: 'lg', fullWidth: true }
        );
    };
    const columns: MuiDataGridColDef[] = React.useMemo(() => {
        return [
            { field: 'nom', flex: 1 },
            { field: 'descripcio', flex: 2.5 },
            {
                field: 'valor',
                flex: 1.5,
                renderCell: ({ row }) => (
                    <PropietatsConfigurablesValue
                        tipus={row?.tipus}
                        valor={row?.valorBoolean ?? row?.valor}
                    />
                ),
            },
            { field: 'tipus', flex: 1 },
        ];
    }, [t]);

    const groupingColDef: GridGroupingColDefOverride = React.useMemo(
        () => ({
            flex: 2,
            minWidth: 135,
            renderHeader: (params: any) => (
                <Grid
                    container
                    display="flex"
                    flexDirection="row"
                    alignItems="center"
                    justifyContent="space-between"
                    width="100%"
                >
                    <Grid size={6}>{params?.colDef?.headerName}</Grid>
                    <Grid size={6}>
                        <ExpandCollapseButtons
                            onExpandAll={() => {
                                setExpand(true);
                                onRowExpansionChange?.('__reset__', true);
                            }}
                            onCollapseAll={() => {
                                setExpand(false);
                                onRowExpansionChange?.('__reset__', false);
                            }}
                        />
                    </Grid>
                </Grid>
            ),
            renderCell: (params: any) => <GridTreeDataGroupingCell {...params} />,
            colSpan: (_value: any, row: any) => {
                if (isAutogeneratedRow(row)) return columns.length + 1;
            },
        }),
        [onRowExpansionChange]
    );

    return (
        <GridPage disableMargins={false}>
            <MuiDataGrid
                title={t('page.propietatsConfiguracio.grid.title')}
                resourceName="configGroupResource"
                columns={columns}
                paginationActive
                toolbarCreateLink="form"
                rowLink="form/{{id}}"
                rowUpdateLink="form/{{id}}"
            />
            {/* <MuiDataGrid
                title={t('page.entitats.grid.title')} // TODO
                resourceName="configResource"
                columns={columns} // TODO
                toolbarType="upper"
                paginationActive
                toolbarHideCreate
                rowHideDeleteButton
                rowHideUpdateButton
                popupEditActive
                popupEditFormContent={<PropietatsConfigurablesForm />}
                rowAdditionalActions={[
                    {
                        label: tLib('datacommon.update.label'),
                        icon: 'edit',
                        clickShowUpdateDialog: true,
                        hidden: row => !row?.id || !row?.editable,
                    },
                    {
                        label: tLib('datacommon.details.label'),
                        icon: 'info',
                        onClick: showDetail,
                        hidden: row => !row?.id || row?.editable,
                    },
                ]}
                treeData
                getTreeDataPath={row => [row.grup, row.subGrup, row.codi]}
                groupingColDef={groupingColDef}
                isGroupExpandedByDefault={node => {
                    if (expansionState[node.id] != null) {
                        return expansionState[node.id];
                    }
                    return expand;
                }}
                hideFooter
                slots={{ noRowsOverlay: DataGridNoRowsOverlay as GridSlots['noRowsOverlay'] }}
            /> */}
            {detailDialogComponent}
        </GridPage>
    );
};
export default PropietatsConfigurables;
